### ISSUE TITLE
cannot see graph or backlinks with steps in documentation

### ISSUE THREAD

**Issue by jawaharvignesh** [foambubble/foam#1]
I have cloned a repo from the template and installed all the recommended extensions.

But I am not seeing the `show graph` or `show backlinks` options with the steps described in the recipes documentation

**Comment by jawaharvignesh** [comment]
I assume this is because the extension `tchayen.markdown-links` is not in the recommendations. I installed this extension by myself and got the `show graph` command

**Comment by jevakallio** [comment]
Ah! I forgot I had not added the extension to the recommended list in the template until https://github.com/tchayen/markdown-links/pull/13 was fixed. It's been merged and should be released shortly, will fix and close this now.

I'll ping you in this issue so you can upgrade your version of the plugin!

**Comment by jevakallio** [comment]
@jawaharvignesh Markdown Links 0.6.0 is now available and included in recommend plugins
