### ISSUE TITLE
Color Graph by type

### ISSUE THREAD

**Issue by Casyfill** [foambubble/foam#1001]
### Is your feature request related to a problem? Please describe.

The Graph view is both useful and hard to navigate. It would be great to be able to distinct different parts of the graph (e.g personal notes vs work notes vs tech info vs friends). It seems like an ~easy push, given we already have "filter by type" functionality

### Describe the solution you'd like

As a user, I'd like to be able to have a graph colored by type, similar to how it can be filtered by type right now.
I assume that also would require using / picking / setting color maps via config. 
Perhaps [that](https://jiffyclub.github.io/palettable/wesanderson/) could be a good start :-P

### Describe alternatives you've considered

a potential alternative is, of course, to pre-generate styles using some script, but that seems to be a worse solution.

### Screenshots or Videos

Random example from the internet:

![example](http://3f6iwu1mrif02clvg22bwb9j-wpengine.netdna-ssl.com/wp-content/uploads/sites/9/2018/11/network-Graphs-300x274.png)

**Comment by riccardoferretti** [comment]
This can be achieved by setting a color property in the configuration.
See https://github.com/foambubble/foam/blob/master/docs/features/graph-visualisation.md#style-nodes-by-type
