### ISSUE TITLE
Foam removes autogenerated link references on save

### ISSUE THREAD

**Issue by kevlened** [foambubble/foam#1002]
### Describe the bug

I wanted to test foam using the foam-template and github pages. The basic template worked without any changes. If I save a file with foam enabled, then push to github, links no longer resolve.

<img width="181" alt="Screen Shot 2022-05-31 at 10 44 34 PM" src="https://user-images.githubusercontent.com/955312/171318230-260a1409-c6db-4e69-88fe-c5d14b8c14c9.png">

### Steps to Reproduce the Bug or Issue

1. Clone the foam-template
2. Enable github pages on the repo
3. Clone the repo locally and open VS Code
4. Open `readme.md` and click save
5. The following links are removed:
```
[//begin]: # "Autogenerated link references for markdown compatibility"
[getting-started]: getting-started.md "Getting Started"
[inbox]: inbox.md "Inbox"
[todo]: todo.md "Todo"
[//end]: # "Autogenerated link references"
```
6. Commit and push the change

### Expected behavior

The homepage in github pages should resolve the links, but the links do not resolve.

### Operating System Version

macOS

### Visual Studio Code Version

1.67.2

**Comment by kevlened** [comment]
Ah, the issue is the docs say `linkReferenceDefinitions` are `withoutExtensions` by default, but the default in the extension is `off`. Setting `linkReferenceDefinitions` to `withoutExtensions` fixed the issue.

<img width="622" alt="Screen Shot 2022-05-31 at 11 11 28 PM" src="https://user-images.githubusercontent.com/955312/171320294-ac22c92a-e442-45ed-88b1-6ad4cb2eefcf.png">

<img width="363" alt="Screen Shot 2022-05-31 at 11 12 05 PM" src="https://user-images.githubusercontent.com/955312/171320388-15f6f53d-fd67-405d-9987-60778509d915.png">

**Comment by kevlened** [comment]
This is confusing, because the code agrees with the docs:

https://github.com/foambubble/foam/blob/d222cfbbec342475cc1bd270565baea72f40bc1d/packages/foam-vscode/src/settings.ts#L10-L17

**Comment by riccardoferretti** [comment]
Most people don't use reference definitions so we turn them off by default. The reason for the default setting, which I agree should be changed at this point, was backwards compatibility when we introduced the change. 

There are 3 sources of the setting, in order of priority:
- the setting in the workspace/user setting
- what the code actually uses (the line you pointed at)
- what's defined in the package.json

To ensure backward compatibility while also moving people off that default unless they needed it, we went for that approach. Given it's been some time now, I'd be happy to consolidate to OFF in the extension. 
For the template, I would keep it ON so it can be navigated in GitHub. 

I see the source of confusion, maybe we can clarify that in the template, and I am open to other ideas as well. 

Thanks for reporting the odd behavior!

**Comment by kevlened** [comment]
Appreciate the detail. It seems the line I pointed at above was overridden by the default workspace setting [in the template](https://github.com/foambubble/foam-template/blob/master/.vscode/settings.json#L16).

Changing the default in the template or simply documenting the behavior both make sense!

Thanks for maintaining this project 🙌🏻

**Comment by riccardoferretti** [comment]
We kept them in the readme so that the navigation on github would have worked.
We removed it elsewhere to not pollute the files.

Mmmm.. I see how this is pretty confusing. Here is what makes sense to me:
- we remove link definitions everywhere, including the readme
- in the readme, we remove "links" to other files, which would break on github
- change the default to `off`

This way the behavior is consistent, there is already the documentation to enable definitions, and hopefully there are no surprises for people getting started with the template.
Will do it later, thx!

**Comment by t2hv33** [comment]
Setting `linkReferenceDefinitions` to `withoutExtensions` fixed the issue.

But do not generate the backlink for `journal` `dddd-mm-dd`
Foam can't find the note [[2022-01-01]] inside the `journal` folder.

Operating System Version
macOS
Foam: v0.18.4

**Comment by riccardoferretti** [comment]
This seems to be a different issue to me, so I will close this in the meantime.

To help you debug your problem, I suggest looking at the Foam logs (we have a doc that explains how if you struggle with that) to check if the files in the `journal` folders are being processed.
You can also check whether they are present in the graph, and whether the navigation to those files works.
If the issue persist feel free to open a new issue to track that problem.
