### ISSUE TITLE
Automatic Indexing

### ISSUE THREAD

**Issue by dakenblack** [foambubble/foam#1007]
### Is your feature request related to a problem? Please describe.

Not a problem just an inconvenience.

My foam repo has gotten quite big and there are some topics which are repeated in multiple files. I was about to start making a manual index file where I could list various topics and place references to these multiple files. I was wondering if an automatic solution for this already exists?

### Describe the solution you'd like

As a user I would like to specify for a single .md file or a reference within a .md file (a ## or ### heading for example) one or more tags. Each tag could be a word or a phrase. An index file would be automatically generated and updated listing all user-specified tags with references as links.

### Describe alternatives you've considered

The only alternative I've considered is maintaining the index file manually.

**Comment by riccardoferretti** [comment]
I consider that to be more in the scope of another extension built on top of Foam (once we publish an API) rather that core Foam itself.
Will still keep this open for a bit to see if it gets upvotes

**Comment by dakenblack** [comment]
Hi riccardo, sorry I forgot about this issue. 

I agree with you, I didn't think it should be a core feature of foam but I didn't know where else to post this.

Is there an issue that keeps track of the api development or some other way to keep up to date on the progress (apart from subscribing to releases which I've done already)

Thanks,
Jabez

**Comment by montharon** [comment]
Hi to all of you.

I had exactly the same wish/issue and did a powershell script that automatically creates index files for all my notes.
It is not the way it's mean to be but it works - at least for me ;)

![image](https://user-images.githubusercontent.com/21140797/175940613-37a61339-a0d0-4d46-8786-38499ea53c0a.png)

Each note that is created based on a template automatically sets the backlinks to the TOC as well

![image](https://user-images.githubusercontent.com/21140797/175940884-92eac406-3a48-40ce-95fe-a4a53cadc5e9.png)

If you are interested in my solution - maybe we can find a proper way in sharing our knowledge?
Maybe there could be a specific forum group for such things?

Many greetings,
montharon
