### ISSUE TITLE
Missing Information: Command in foam-templates/inbox.md is platform specific

### ISSUE THREAD

**Issue by CatChenal** [foambubble/foam#1012]
### Describe the bug

Thanks for Foam:sweat_drops:! I've just started my discovery...  

One of the bullet points in `form-template/inbox.md` gives the following command:
```markdown
- For example, you can `Cmd`+`Click` this: [[todo]]
```
On my Windows 10 system, there are no 'Cmd' or 'Click' buttons, so without an explanation of what the above command combination is supposed to do, I cannot find the equivalent.

Also, when `inbox.md` is open in VS code & the cursor is over the `todo` tag, the _on_hover_ text is a little bit odd:
```
You can create todos in Foam.

  This is an example of a todo list item that's complete 
  This one is not completed yet                                     
```
I am assuming that  "This" in the above two lines is a missing example.

PS: :bubbles: not yet available...

### Steps to Reproduce the Bug or Issue

1. Open `form-template/inbox.md` 

### Expected behavior

Expected info in `inbox.md`:  

```markdown
- For example, to [edit? follow?] a todo item, you can place your cursor in the `todo` tag ([[todo]]) and  
  -  `Cmd`+`Click` in Apple OS,
  -  or [X+Y?] in [Windows, NIX...] 
```

Expected info in the `todo` tag _on_over_ text:   
The actual examples that show "a todo list item that's complete" and "one that is not completed yet".
  

### Operating System Version

Windows 10

### Visual Studio Code Version

Version: 1.68.0

### Additional context

Version: 1.68.0 (system setup)
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:44:16.822Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by riccardoferretti** [comment]
Hi @CatChenal , thanks for reporting the issue.

Regarding the `cmd+click`, yup, I can see how that's very mac specific 😅 - I am not sure what the key is for Windows, but it's basically the way links are navigated in VS Code. Any Win user can confirm the key combo so we can update the docs?

Regarding the todo items, you should see this in the file

```
- [x] This is an example of a todo list item that's complete
- [ ] This one is not completed yet
```

Regarding the preview not properly showing the todo items, that's a good point, I never noticed it. Can you create a separate issue for that so we track the two indipendently?

thanks

**Comment by CatChenal** [comment]
Will do!

**Comment by HippieRocket** [comment]
`Cmd` or `Command` on macOS is equivalent to `Ctrl` on Windows. By the way, `Option` plays the same role as `Alt`.
And `Click` means that the user clicks the link with a mouse (or trackpad).
So this operation indicates that you should click the link with your `Ctrl` key pressed as you copy using a `Ctrl`+`C` combination and replace the `C` key with your mouse click.
Hope it helps! 💪

**Comment by riccardoferretti** [comment]
Thanks, I have updated the file (https://github.com/foambubble/foam-template/blob/master/inbox.md)
