### ISSUE TITLE
Allow lowercasing link references

### ISSUE THREAD

**Issue by lauraseidler** [foambubble/foam#1020]
### Is your feature request related to a problem? Please describe.

The auto-generated link references at the end of the file, are super useful for keeping Markdown compatibility, but unfortunately they can conflict with auto-formatters (in my case: prettier).

For example, this is the section generated by Foam:
```md
[//begin]: # "Autogenerated link references for markdown compatibility"
[GitLab]: GitLab.md "GitLab"
[SonarQube]: SonarQube.md "SonarQube"
[//end]: # "Autogenerated link references"
```

This is what prettier expects:
```md
[//begin]: # "Autogenerated link references for markdown compatibility"
[gitlab]: GitLab.md "GitLab"
[sonarqube]: SonarQube.md "SonarQube"
[//end]: # "Autogenerated link references"
```
While prettier will re-format the file automatically for me on commit, this still means it has to happen again every time after a file is saved, always causing a diff, etc.

As far as I can see, the lowercasing does not break Markdown compatibility, the links still work.

### Describe the solution you'd like

It would be great to have an option for Foam to select whether references follow the style of the link (like now) or are lowercased. It could also be an option to detect the current format and follow it automatically, though that's probably more difficult. 

### Describe alternatives you've considered

Living with it :) It's not a huge issue, but would still be great to be able to have a formatting option. I'm also happy to contribute if this feature is welcome.

**Comment by riccardoferretti** [comment]
Can this be disabled in prettier? which rule is causing this behavior?

**Comment by lauraseidler** [comment]
Doesn't look like - but there's an open issue here: https://github.com/prettier/prettier/issues/7118 

I'm not sure why it's being changed tbh, it seems counter productive - I've just never minded, as there was never any conflicts for me.
