### ISSUE TITLE
automatic link creation from [[link with space]] creates 2 files (with and without dashes)

### ISSUE THREAD

**Issue by ultrasaurus** [foambubble/foam#1023]
### Describe the bug

I'm new to Foam, just cloned the template and tried it today.  This bug may be related to https://github.com/foambubble/foam/issues/494 but has very simple, easy to repro steps (at least for me).

### Small Reproducible Example

https://github.com/ultrasaurus/foam-experiment/tree/twofiles

### Steps to Reproduce the Bug or Issue

1. Make a new file `index.md` with this content:
```
# Index

- [[new prototype]]
- 
```

2. Roll over the link, press `command` and click.

### Expected behavior

a single file is created with whatever default naming conventions y'all use

### Screenshots or Videos

Foam creates two files:
- roll over and press `command` => creates `new-prototype.md`
- clicking on it => creates and opens `new prototype.md`

I end up with two files
<img width="469" alt="image" src="https://user-images.githubusercontent.com/41906/176798595-6233dded-0c2d-4d19-b171-c4c255a41c57.png">

### Operating System Version

macOS

### Visual Studio Code Version

1.68.1

**Comment by riccardoferretti** [comment]
Do you have markdown-notes installed? usually this has been the cause of this double note creation in the past

**Comment by ultrasaurus** [comment]
I don't have "markdown-notes" installed.  Do I need it?

**Comment by riccardoferretti** [comment]
Nope, you don't need it. 
Can you try disabling all extensions except foam and check if the issue persists?

**Comment by ultrasaurus** [comment]
well, works fine with just Foam. Sadly I don't have a record of what extensions were installed when I filed this bug.  You might consider an issue template that asks that question.  I didn't think of it, and did some experimentation with other extensions after trying foam, so may have disabled whatever it was that was causing the problem.

Thanks so much for your help!

**Comment by zomars** [comment]
I'm having the same issue and uninstalling markdown notes didn't work for me.

**Comment by riccardoferretti** [comment]
Can you check if it happens when only Foam is enabled?

**Comment by zomars** [comment]
@riccardoferretti yes, disabling foam prevents the double file creating.

**Comment by riccardoferretti** [comment]
Ok, that confirms Foam creates at least one of the files. Can you try disabling all other extensions except Foam and check if the double file creation still occurs?
