### ISSUE TITLE
`Option + click` ignores "slugified" note and instead creates a new "unslugified" one:

### ISSUE THREAD

**Issue by zomars** [foambubble/foam#1035]
### Describe the bug

Having this wiki link:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/3504472/179445443-838a8bad-e5bd-4a7b-aef0-0f0b2121b554.png">

The file does exist:

<img width="201" alt="image" src="https://user-images.githubusercontent.com/3504472/179445583-571762f6-3364-4f5e-9f8c-eb54e59a41ff.png">

But when clicking it created a new "unslugified" one:

<img width="217" alt="image" src="https://user-images.githubusercontent.com/3504472/179445555-a60ba7f5-0837-46d9-9ca8-b7291f0313ad.png">

### Steps to Reproduce the Bug or Issue

- On any note type: `[[This is a new link]]`
- option + click to create a new note
- See `This is a new link.md` instead.

### Expected behavior

Expected a `this-is-a-new-link.md`

### Operating System Version

macOS 12.4

### Visual Studio Code Version

Version: 1.69.1

**Comment by riccardoferretti** [comment]
The expected behavior in your example is `This is a new link.md`

**Comment by zomars** [comment]
@riccardoferretti this was not the case before? Why the change? I remember seeing a slugify option before. This is necessary for publishing notes as website URLs.
