### ISSUE TITLE
Embedding images only works on files in root directory

### ISSUE THREAD

**Issue by XobSod** [foambubble/foam#1036]
### Describe the bug

`![[image.png]]` links show in Markdown preview only when are added to the files placed in the project root directory. Adding the same line to file in different location makes image not showing in the preview.

Reproduction steps:
Add given lines to some `Foam-Template` files.
``` md
Test image link: [[foam-icon.png]]
Test embedded image: ![[foam-icon.png]]
Test note link: [[graph-visualization]]
Test embedded note: ![[graph-visualization]]
```

Here is how it looks, when adding to `getting-started.md` located in root directory:
![image](https://user-images.githubusercontent.com/3855655/179470177-9fe941b2-09de-48d3-9170-626c509344fb.png)

Here is how it looks, when adding to `wikilinks.md` located in docs/features directory:
![image](https://user-images.githubusercontent.com/3855655/179470688-75944169-f8ac-4ec0-b960-c1899bf00355.png)

As you can see, in second example, the image is not rendered in the preview.

### Steps to Reproduce the Bug or Issue

Add linse:
```md
Test image link: [[foam-icon.png]]
Test embedded image: ![[foam-icon.png]]
Test note link: [[graph-visualization]]
Test embedded note: ![[graph-visualization]]
```
to files of `Foam-template` repository located in different directories, and check Markdown Preview.

### Expected behavior

Expected:
Image shown in the Markdown Preview in each file, no matter the location.

Actual:
Images are not shown in Markdown Preview when file is not in the root directory.

### Operating System Version

Windows

### Visual Studio Code Version

1.69.1

### Additional context

Foam version: 0.19.1

**Comment by riccardoferretti** [comment]
Thanks for reporting this, yup definitely not the expected behavior

**Comment by riccardoferretti** [comment]
Upon some investigation the issue seems to be due to the image path needing to be relative to the file source file, whereas now it's computed relative to the repo root
