### ISSUE TITLE
Duplicate files created when name contains underscore and file does not exist yet

### ISSUE THREAD

**Issue by lucidBrot** [foambubble/foam#1037]
### Describe the bug

Control+Click on a `[[file_name]]` that does not yet have a corresponding md file and contains an underscore will create *two* files.

### Small Reproducible Example

https://github.com/lucidBrot/mcve-foam1

### Steps to Reproduce the Bug or Issue

I cloned the template repo today ([this commit is the latest from master](220ce915b673e99caa53cbd7d46e9dd16f8fdc4a)) to create a new project. I deleted a few files that I believe I don't need and then created some files - both creating and deletion of files was done from the vscode file explorer sidebar. This part works correctly:

```
 git diff --name-status 220ce915b673e99caa53cbd7d46e9dd16f8fdc4a HEAD
A       _overview.md
D       attachments/foam-icon.png
D       docs/features/daily-notes.md
D       docs/features/graph-visualization.md
D       docs/features/link-reference-definitions.md
D       docs/features/note-properties.md
D       docs/features/note-templates.md
D       docs/features/spell-checking.md
D       docs/features/tags-and-tag-explorer.md
D       docs/features/wikilinks.md
D       docs/how-to/get-started-with-vscode.md
D       docs/how-to/paste-images-from-clipboard.md
D       docs/how-to/shortcut-list.md
D       docs/how-to/use-keyboard-shortcuts-for-editing.md
D       docs/how-to/write-notes-in-foam.md
D       getting-started.md
D       inbox.md
D       readme.md
D       todo.md

```

Notice that I even created a file called `_overview.md` that contains an underscore. Linking to it as `[[_overview]]` from another file (and saving, and ctrl+clicking it) does not create a duplicate file. All this works as expected.

When I now write some filename that does not yet exist in `overview.md` and ctrl+click it - e.g. `[[timeline]]` - then `timeline.md` is created. As expected.

When I instead write a filename with underscores and ctrl-click that, *two* files are created. E.g. `[[test-name]]` behaves as expected but `[[test_name]]` creates both a `test_name.md` and a `test-name.md` when it is ctrl+clicked. The file that opens then is the correct one (`test_name.md`).

The usecase where this is relevant for me is that I like to name my meeting notes in the format `YYYY-MM-DD_meeting_description.md` for easy finding of files even without foam (on some devices). The additional files don't seem to be disruptive other than that they needlessly exist, and also show up as unconnected dots in the graph view.

Now that I mention this, it reminds me of [this issue](https://github.com/foambubble/foam/issues/494#issuecomment-922339451) that I barely recall but apparently the workaround for duplicate graph entries was to use lowercase letters and dashes only in the filenames. If this is simply a hard constraint set by foam then I can decide to live with it (but clear documentation about that would be important!).

I am using Windows 10, have not (yet?) tried to reproduce on ubuntu.
Foam Extension is `v0.19.1` and vscode is version `1.69.1`.

### Expected behavior

I would expect to only get the file that I specified. I.e. it should retain the underscores and capitalization.

### Operating System Version

Windows

### Visual Studio Code Version

1.69.1

### Additional context

Foam Log output:
```
Foam Logging: info
[info - 13:27:42] Starting Foam
[info - 13:27:42] Workspace folders: 
[
  "N:/Files/Schule/studium/22HS_Research/22hs-foam"
]
[info - 13:27:42] Glob patterns
{
  "includeGlobs": [
    "N:/Files/Schule/studium/22HS_Research/22hs-foam/**/*"
  ],
  "ignoreGlobs": [
    "N:/Files/Schule/studium/22HS_Research/22hs-foam/**/.vscode/**/*",
    "N:/Files/Schule/studium/22HS_Research/22hs-foam/**/_layouts/**/*",
    "N:/Files/Schule/studium/22HS_Research/22hs-foam/**/_site/**/*",
    "N:/Files/Schule/studium/22HS_Research/22hs-foam/**/node_modules/**/*",
    "N:/Files/Schule/studium/22HS_Research/22hs-foam/**/.git",
    "N:/Files/Schule/studium/22HS_Research/22hs-foam/**/.svn",
    "N:/Files/Schule/studium/22HS_Research/22hs-foam/**/.hg",
    "N:/Files/Schule/studium/22HS_Research/22hs-foam/**/CVS",
    "N:/Files/Schule/studium/22HS_Research/22hs-foam/**/.DS_Store",
    "N:/Files/Schule/studium/22HS_Research/22hs-foam/**/Thumbs.db",
    "N:/Files/Schule/studium/22HS_Research/22hs-foam/**/node_modules"
  ]
}
[info - 13:27:42] Workspace loaded in 173ms
[info - 13:27:42] Graph loaded in 2ms
[info - 13:27:42] Tags loaded in 1ms
[info - 13:27:42] Loaded 18 resources
[info - 13:29:05] Updated links in the following files:
"readme.md"
[error - 13:36:21] FileDataStore: error while reading uri: /N:/Files/Schule/studium/22HS_Research/22hs-foam/docs/features/tags-and-tag-explorer.md - EntryNotFound (FileSystemError): Unable to read file 'n:\Files\Schule\studium\22HS_Research\22hs-foam\docs\features\tags-and-tag-explorer.md' (Error: Unable to resolve nonexistent file 'n:\Files\Schule\studium\22HS_Research\22hs-foam\docs\features\tags-and-tag-explorer.md')
[error - 13:36:21] FileDataStore: error while reading uri: /N:/Files/Schule/studium/22HS_Research/22hs-foam/docs/features/note-templates.md - EntryNotFound (FileSystemError): Unable to read file 'n:\Files\Schule\studium\22HS_Research\22hs-foam\docs\features\note-templates.md' (Error: Unable to resolve nonexistent file 'n:\Files\Schule\studium\22HS_Research\22hs-foam\docs\features\note-templates.md')
```

### Workarounds

* Create the file first, using the sidebar, instead of ctrl+clicking the `[[file_name]]`
* Avoid underscores in filenames

**Comment by riccardoferretti** [comment]
Can you check the behavior occurs when only Foam is running? 
If you have Markdown Notes the issue is due to its slugification function (Foam and Markdown Notes conflict on how they handle wikilinks, you need to use one or the other)

**Comment by lucidBrot** [comment]
Fascinating. Incredible divination skills you have there.

Yes, I had Markdown Notes installed and enabled and Yes, after disabling it, the issue is gone.
I can not recall ever installing it, and I have never consciously used it, so I will just leave it disabled and see whether I would even miss it.

Thanks a lot for that help!
