### ISSUE TITLE
links with angles don't navigate

### ISSUE THREAD

**Issue by gmccullo** [foambubble/foam#1039]
Markdown links in this format:

```md
[foobar](<foobar.md>)
```

do not navigate when clicked.

**Comment by riccardoferretti** [comment]
I don't believe those are valid markdown links? why the angles?

**Comment by gmccullo** [comment]
It's valid. Just try it.

[See release notes here](https://code.visualstudio.com/updates/v1_69): "Support for angle bracket links in Markdown"
