### ISSUE TITLE
Page not found: Daily Notes

### ISSUE THREAD

**Issue by Querela** [foambubble/foam#1046]
### Describe the bug

The webpage https://foambubble.github.io/foam/features/daily-notes linked from the VSCode extension overview page does not work.

### Steps to Reproduce the Bug or Issue

1. Go to vscode extensions
2. Search for **foam**
3. View page for **foam**
4. Scroll down to **daily notes**
5. and then click the link.

### Expected behavior

See working help page about daily notes?

### Screenshots or Videos

Link here: ![grafik](https://user-images.githubusercontent.com/1648294/182844924-db723fc1-a2a4-4ebb-89a0-002c17a497ec.png)

### Operating System Version

Windows, WSL

### Visual Studio Code Version

1.69.2

### Additional context

**VSCode:**
Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

**foam** version: v0.19.1

**Comment by riccardoferretti** [comment]
Thanks for reporting this @Querela - I have found a few links that were pointing to the old documentation, I have updated all of them now and used the chance to do a release (will take a few mins to show up in the marketplace). Let me know if you find anything amiss now
