### ISSUE TITLE
Allow "daily note" file template to have `ww`, to allow for weekly notes

### ISSUE THREAD

**Issue by dmurph** [foambubble/foam#1048]
### Is your feature request related to a problem? Please describe.

It isn't possible to have a weekly journal note instead of a daily one.

### Describe the solution you'd like

Right now daily notes can have their filename customized like so:

```
  "foam.openDailyNote.filenameFormat": "'daily-note'-yyyy-mm-dd",
```

This can be edited to, say, have a monthly note:

```
  "foam.openDailyNote.filenameFormat": "'daily-note'-yyyy-mm",
```

I would love to add the `ww` template value in there so I can have a weekly note:

```
  "foam.openDailyNote.filenameFormat": "'daily-note'-yyyy-ww",
```

This would be filled in by the week # of the year.

### Describe alternatives you've considered

Making a whole new feature for weekly notes with a different command. That could be necessary if you want BOTH weekly & daily notes. I, however, don't.

Implementing the way above doesnt block making a weekly feature later.

**Comment by riccardoferretti** [comment]
Hi @dmurph, thanks for reporting this and for the pull request (https://github.com/foambubble/foam/pull/1049).
I like the idea of adding the week number (in my workflow I actually ended up using more weekly notes than daily notes).
Will take my comments related to `FOAM_DATE_WEEK` to the PR.

Are there other week related features that you would find useful? I want to collect some data around that

**Comment by dmurph** [comment]
Looking at the code, I figured out that I could use "W" as a week signifier, as under the hood this uses dateFormat. So no feature request necessary for this part!

Use-case-wise, I keep track of things weekly for compiling summaries of status progress etc, and these get shared around. I like putting common sections / titles in the template for the note, so I can save common links etc.

My team also specifically has biweekly sprints / demo / review days that I try to compile info for, but I currently do that outside of this tool

**Comment by riccardoferretti** [comment]
Yeah I like the approach you took in the PR.
Considering that my goal is to get rid of `dailyNote` settings and manage everything via the template, this fits right in.

Thanks for the info re your workflow. Sounds like nothing else is really needed to support it.
(as a reference my workflow is similar and similarly fully addressed by the `FOAM_DATE_WEEK` variable)

Happy to move forward with the PR as soon as the minor comments are addressed, thanks!

**Comment by dmurph** [comment]
Unfortunately my available cycles have shot through the ground :( so I won't have time for a month or so. If anyone else wants to pick up this pull request and address the comments, feel free :)d
