### ISSUE TITLE
Embed notes not working since v0.19.2

### ISSUE THREAD

**Issue by lyaaz** [foambubble/foam#1052]
### Describe the bug

After upgrading to v0.19.2 (also with v0.19.3), the embed notes not working correctly in the preview.

### Steps to Reproduce the Bug or Issue

1. upgrade to v0.19.2 or v0.19.3
2. open a note contains embed note
3. open preivew

### Expected behavior

The embed notes are displayed correctly.

### Screenshots or Videos

![Screenshot_20220806-183845_Code](https://user-images.githubusercontent.com/45838887/183245601-357c9c86-22d4-4baa-a52e-7dd1e3ba4428.png)

### Operating System Version

Windows 10

### Visual Studio Code Version

1.70.0

**Comment by sleepymalc** [comment]
Yup, this is not working currently.

**Comment by riccardoferretti** [comment]
thanks for reporting this, it's now fixed in 0.19.4

**Comment by skipleam** [comment]
This appears to still be broken (or broke again) in v0.19.5 (VSCode v1.71.2):
![image](https://user-images.githubusercontent.com/15656654/192057016-2d324dfe-e4a5-42c6-a15d-c11bc4104d2a.png)
Happy to provide other info.

**Comment by skipleam** [comment]
I've been using this for a long time it seems; I need to prune my extensions 😄 

I traced this to extension conflicts that you've addressed - no real issue, sorry! These each broke functionality in different ways, so I originally dismissed them as the root cause:
- I had Markdown Notes included from when I originally started my repo. Removed from the template in foambubble/foam-template/pull/25
- Markdown Extended has the note about `kbd`, which I've missed entirely.

**Comment by gilite** [comment]
Me too - I had the same problem but removing the extension [Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) made it work.

**Comment by tensor-tian** [comment]
Removing the extension [markdown-notes](https://marketplace.visualstudio.com/items?itemName=kortina.vscode-markdown-notes) makes it work.

**Comment by hiddengarden** [comment]
> ### Describe the bug
> After upgrading to v0.19.2 (also with v0.19.3), the embed notes not working correctly in the preview.
> 
> ### Small Reproducible Example
> _No response_
> 
> ### Steps to Reproduce the Bug or Issue
> 1. upgrade to v0.19.2 or v0.19.3
> 2. open a note contains embed note
> 3. open preivew
> 
> ### Expected behavior
> The embed notes are displayed correctly.
> 
> ### Screenshots or Videos
> ![Screenshot_20220806-183845_Code](https://user-images.githubusercontent.com/45838887/183245601-357c9c86-22d4-4baa-a52e-7dd1e3ba4428.png)
> 
> ### Operating System Version
> Windows 10
> 
> ### Visual Studio Code Version
> 1.70.0
> 
> ### Additional context
> _No response_

Exactly the same issue. Seems recurring.

**Comment by riccardoferretti** [comment]
@hiddengarden are you using Foam as a web extension? embeds don't work in that case.
Otherwise can you please create a new task with all the information required to reproduce the issue (even if they match, it makes it easier for me to track the issue)

**Comment by hiddengarden** [comment]
Sorry for the delay. I am using Foam as VSCode extension. I was transcluding from a subfolder. It works if I transclude within the same folder.
