### ISSUE TITLE
Consider not showing images/attachments in the graph view by default

### ISSUE THREAD

**Issue by LaurensBosscher** [foambubble/foam#1056]
### Is your feature request related to a problem? Please describe.

I use the recommended [markdown paste image](https://marketplace.visualstudio.com/items?itemName=telesoho.vscode-markdown-paste-image) extension to include illustrations from books that I've added to Foam. 

These images are linked and are then added to the graph, this creates a very messy graph:
![image](https://user-images.githubusercontent.com/13363196/185379088-e452c1e5-4553-4b7f-b95b-9f051991fd63.png)

### Describe the solution you'd like

Consider disabling "attachment" and "image" by default or allow this to be configurable by the user, this results in a far cleaner and more use able graph for my use-case:

![image](https://user-images.githubusercontent.com/13363196/185379516-4c4a1bf3-513c-42c2-990d-acedcd6b5a88.png)

### Describe alternatives you've considered

I've considered using "foam.files.ignore" in the settings but when I add the attachments folder to this settings images are no longer displayed in the markdown preview.

**Comment by riccardoferretti** [comment]
Thanks for the suggestion, I am happy to try it out
