### ISSUE TITLE
Foam should work when notes are in a workspace subdirectory

### ISSUE THREAD

**Issue by jevakallio** [foambubble/foam#106]
## Known issues

- [ ] Markdown links indexes files it shouldn't @tchayen
- [ ] Markdown notes always creates new files in workspace root @kortina

## Potential solutions

- Have all extensions share a configuration key
- Find a way to inject configuration into extensions (@riccardoferretti mentioned this might be possible?)
- Duplicate configuration keys for all projects

## FYI

Foam VSCode doesn't auto trigger commands unless there's a `.vscode/foam.json`. This is to be expected.

**Comment by tchayen** [comment]
Oops, what files are indexed that shouldn't be?

**Comment by riccardoferretti** [comment]
What I was referring to is for an extension to expose its API by returning an object in its `activate` function, but this needs to be done by the "target" (e.g. Markdown links, Markdown notes), not Foam in our case.

See https://code.visualstudio.com/api/references/vscode-api#extensions

Of course with a starter template or CLI we could configure the extension directly, which might be fine at the beginning, but it comes with trade offs too.

**Comment by riccardoferretti** [comment]
@tchayen The extension currently scans all the files under the project root, I think it would be helpful to provide some inclusion or exclusion patterns.

In my specific case, I have 
```
/
  .vscode/
  content/    << the md files
  site/       << for custom site generation
```

As the extension also scans `site` and it's `node_modules` dir,  a few million files get checked :)

Does that make sense?

**Comment by tchayen** [comment]
@riccardoferretti Absolutely. I will for sure add an option to ignore given files or directories. I had it on the roadmap for some time.

**Comment by jevakallio** [comment]
@tchayen did a bit more research on how this works. I think you could get away with simply using `workspace.findFiles` instead of `workspace.fs`. See this issue:

https://github.com/foambubble/foam/issues/130

**Comment by tchayen** [comment]
Oh, wow, that sounds cool! I will try switching to that one.

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
