### ISSUE TITLE
Exclude whole repo/Folder when using foam in a multi-root workspace

### ISSUE THREAD

**Issue by asg0451** [foambubble/foam#1063]
### Is your feature request related to a problem? Please describe.

i want to have my notes repo and my work repo open simultaneously, but i dont want foam to index my work repo's docs (random jpgs, docs, etc)

### Describe the solution you'd like

notes-and-work.code-workspace:
```json
{
	"folders": [
		{
			"name": "notes",
			"path": ".."
		},
		{
			"name": "WORK",
			"path": "../../WORK"
		}
	],
	"settings": {
           "foam.files.ignore": [
             "WORK/**/*"
            ]
        }
```

or some such

### Describe alternatives you've considered

my current workaround is to manually exclude every top-level folder in the work repo, and make sure my notes folder doesnt have any folders with the same name, which sucks

**Comment by riccardoferretti** [comment]
Yup, we had another issue related to this behavior in VS Code when there is more than one workspace folder.
Foam would need to take that into account and change the paths accordingly.

Directionally I completely agree with your proposed solution.
Your current work-around is the only one I can think of, and I agree it's far from ideal.

If someone wants to help on this issue, I will be happy to provide support

**Comment by asg0451** [comment]
@riccardoferretti took a crack at it: https://github.com/foambubble/foam/pull/1065
