### ISSUE TITLE
Transfer References from Tags of Keywords to External Note on Creation of Definition for Concept/Idea: Moving from Keywords to Concepts

### ISSUE THREAD

**Issue by jmanthony3** [foambubble/foam#1064]
### Is your feature request related to a problem? Please describe.

Unless I am missing something, there is no distinct significance between populating a note with `#tag`s to link keywords together across notes and referencing that keyword with a `[[wikilink]]`. This lack of understanding makes it confusing whether marking a keyword with a `#tag` or as a `[[wikilink]]` would prove more effective for linking/navigating future files that also use this same keyword.

To outline my habit so far:
* Tag keywords
* Wikilink to definitions or concepts

Eventually, I will stumble across a formal definition of the concept: e.g. stating an equation and defining what each part of that equation means. If I were to generate an external note of this equation with its definition and description of each term, then I would have to go through and manually change from previously tagged references to this named equation to wikilink the external note containing the definition and concept of the equation.

### Describe the solution you'd like

It would be nice if, as I am creating new notes and tagging keywords, there was an option to move all references from a tagged keyword to a wikilink of the note containing the definition of that keyword. In a way, this would transition from keywords to concepts wherein keywords would serve as an initial way to link content together, and then, once enough content has been generated that a definition has been written or can be made, those keywords instead link to the definition of that keyword instead of simply linking files together. This describes another, formal layer of abstraction to further discretize knowledge as it is collected/stored/navigated/browsed as knowledge transcends keywords into mature definitions and concepts.

### Describe alternatives you've considered

I have tried no alternative solution beyond manually searching and adjusting the tags myself. I have considered writing a script to do this for me, but I have yet to actualize this desire with any work effort out of not wanting to overcome the learning curve of the Foam environment just yet.

**Comment by riccardoferretti** [comment]
Hi @jmanthony3 and thanks for the note. Feels like a pretty advanced use case, and although I can see what you mean, I wouldn't consider it core to Foam's goals and a high priority. Will keep the use case in mind though, should in the future inform some decisions
