### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by carlosblanc0** [foambubble/foam#1067]
### Describe the bug

What: Broken embedded link https://foambubble.github.io/foam/recipes/recipes

Where: README.md
Reference: "_To learn more about how to use Foam, read the [Recipes](https://foambubble.github.io/foam/recipes/recipes) bubbles of the Foam documentation workspace._"

### Small Reproducible Example

https://foambubble.github.io/foam/recipes/recipes

### Steps to Reproduce the Bug or Issue

1. Open **README.md**.
2. Navigate to the third paragraph after bullet points.
3. Click on [Recipes](https://foambubble.github.io/foam/recipes/recipes).

### Expected behavior

Unsure. Couldn't find what the author was referencing to.

### Operating System Version

Web

### Visual Studio Code Version

N/A

**Comment by riccardoferretti** [comment]
can you add a link to the README.md? it seems fine to me
