### ISSUE TITLE
foam.openDailyNote.directory does not create daily notes in the correct location with multiple workspace folders

### ISSUE THREAD

**Issue by geekscrapy** [foambubble/foam#1073]
### Describe the bug

Daily note does not create the note in the correct location if more than one `path` exists in the `folders` attribute in `.code-workspace` file.

### Steps to Reproduce the Bug or Issue

Taking the following `.code-workspace` file:
```
{
    "folders": [
        {"path": "local"},
        {"path": "remote"}
    ],
	"settings": {
            "foam.openDailyNote.directory": "notes"
	}

}
```

File structure:

```
├── .foam
│   └── templates
│       └── example.md
├── local
│   ├── analysis
│   ├── notes
│   └── tools
├── template.code-workspace
└── remote
```

I want to create all notes in the existing `local/notes` directory (as above)

If I set `foam.openDailyNote.directory": "notes",` foam creates a new file in `local/local/notes`
If I set `foam.openDailyNote.directory": "local/notes",` foam creates a new file in `local/local/local/notes`
If I set `foam.openDailyNote.directory": "../local/notes",` foam creates a new file in `local/local/notes`

However, this only appears to be the case if I have two `folders` defined in the workspace. If I only have one (`local`):
```
{
    "folders": [
        {"path": "local"},
       // {"path": "remote"}
    ],
```
If I set `foam.openDailyNote.directory": "notes",` foam creates a new file in `local/notes`, which is as expected.

### Expected behavior

I should be able to use:

```
{
    "folders": [
        {"path": "local"},
        {"path": "remote"}
    ],
	"settings": {
            "foam.openDailyNote.directory": "local/notes"
	}

}
```
To create a new file in the workspace root `/local/notes` directory

### Operating System Version

macOS

### Visual Studio Code Version

1.71.1

**Comment by geekscrapy** [comment]
Also, when using the `.foam` directory, this appears to have to be in the first `path` defined in `folders`. I would like this to not appear in the workspace and have it at the same level as the `.code-workspace` file. Is this possible using relative paths and a setting?

FWIW are these potential issues maybe jointly due to foam only expecting one workspace path?

**Comment by riccardoferretti** [comment]
Thanks for reporting the issue @geekscrapy.
Yup, Foam was born for simple workspaces, it can support multiple folders, but there are a few gotchas, and you have spotted 2 of them (and another one is #1063). (I actually don't think there are many more than these, good job guys ;) )

For what regards the daily note folder setting, I agree that behavior is inconsistent and surprising to say the least, I would recommend as a workaround using an absolute path, which at some point in the future will be a requirement by Foam to avoid disambiguation (see https://github.com/foambubble/foam/pull/683#issuecomment-1205018474 for context).

For what regards the `.foam` folder, you are correct that it takes the one from the first folder, I see why it can be a nuisance but I wouldn't consider it a high priority to change that atm.

**Comment by geekscrapy** [comment]
Thanks for the reply. Unfortunately I'm in a state where I need relative paths due to programmatically creating the workspace itself. I then have the workspace contained in a mountable drive which could be mounted wherever 😬 consider this a usecase where relative paths are required 🙃

Re .foam: yup np 👍

Thanks again

**Comment by geekscrapy** [comment]
Nice! Looking forward to the release!
Will this affect the location of `.foam` too? As I think that is still the first directory?

**Comment by riccardoferretti** [comment]
It doesn't affect the .foam directory, I don't consider it a top priority but it might in the future get addressed depending on complexity/opportunity

**Comment by geekscrapy** [comment]
Awesome, thanks

**Comment by djagoo** [comment]
Still happens for me when I change the "name" value of a workspace folder e.g. to "my notes" instead of "notes" like in the path value it creates a "my notes/journal/" subfolder in notes.

**Comment by riccardoferretti** [comment]
Thanks for opening a new issue for that @djagoo - will continue the conversation there
