### ISSUE TITLE
Reference link double with "foam.edit.linkReferenceDefinitions": "with(out)Extensions"

### ISSUE THREAD

**Issue by MalcolmMielle** [foambubble/foam#1074]
### Describe the bug

On 2 or more save of a file two list of referecnes are generated. One outside off the begin/end tag and one in. I get really inconsistent results with setting in and out of the workspace but never one where it works.

### Steps to Reproduce the Bug or Issue

1. create a file with a wikilink to an exisiting file like:

```
# Python style guide

We use the [[Guidelines/Python-style-guide]] with some modifications.
```

2. Change the setting to  "foam.edit.linkReferenceDefinitions": "with(out)Extensions"
3. Pres Ctrl+S once
4. Link appears correctly
```
[//begin]: # "Autogenerated link references for markdown compatibility"
[Guidelines/Python-style-guide]: ../../Guidelines/Python-style-guide "Python language rules"
[//end]: # "Autogenerated link references"
```
5. Press control S again and you get
```
# Python style guide

We use the [[Guidelines/Python-style-guide]] with some modifications.

[Guidelines/Python-style-guide]: ../../Guidelines/Python-style-guide "Python language rules"

[//begin]: # "Autogenerated link references for markdown compatibility"
[Guidelines/Python-style-guide]: ../../Guidelines/Python-style-guide "Python language rules"
[//end]: # "Autogenerated link references"
```

### Expected behavior

You should get 

```
# Python style guide

We use the [[Guidelines/Python-style-guide]] with some modifications.

[//begin]: # "Autogenerated link references for markdown compatibility"
[Guidelines/Python-style-guide]: ../../Guidelines/Python-style-guide "Python language rules"
[//end]: # "Autogenerated link references"
```

### Operating System Version

Windows 10

### Visual Studio Code Version

1.72.0-insider

**Comment by JakeGinnivan** [comment]
I hit this, but I had an extension formatting my markdown on save.

**Comment by JakeGinnivan** [comment]
```
{
  "singleQuote": true,
  "semi": false,
  "overrides": [
    {
      "files": "*.md",
      "options": {
        "singleQuote": false
      }
    }
  ]
}
```

This fixed the issue for me

**Comment by MalcolmMielle** [comment]
I also have an extension formatting my markdown. I'll have a look!

**Comment by MalcolmMielle** [comment]
It is indeed gone if I remove the markdownlinter

**Comment by serranomorante** [comment]
Hello!
But what if I don't want to remove the format on save of markdownlinter?

**Comment by serranomorante** [comment]
> See [this issue](https://github.com/DavidAnson/markdownlint/issues/634#issuecomment-1315145713) for the solution on this topic.

Thank you! [That config](https://github.com/DavidAnson/markdownlint/issues/634#issuecomment-1314824542) worked!
