### ISSUE TITLE
Section auto-complete

### ISSUE THREAD

**Issue by SunNanbo** [foambubble/foam#1075]
### Is your feature request related to a problem? Please describe.

The external md file can be auto-completed by using `[[xxx]]`
However, the section under the md file can not be auto-completed by using `[[xxx#xxx]]` or `[[#xxx]]`

### Describe the solution you'd like

As a user, I expected that
The `[[xxx#xxx]]` should also auto-complete based on my typing

### Describe alternatives you've considered

Not yet.

**Comment by riccardoferretti** [comment]
I can't reproduce it, can you share a small repo where the issue occurs?
