### ISSUE TITLE
Public examples of Foam second-brains

### ISSUE THREAD

**Issue by elgirafo** [foambubble/foam#1080]
### Is your feature request related to a problem? Please describe.

Not being able to see a variety of different examples of how Foam is being used.

### Describe the solution you'd like

Section or repo showing public examples of people using Foam for a variety of purposes, linking to the source code (if it is shared), enabling people to get inspired and give feedback.

### Describe alternatives you've considered

Creating a repository with these examples.

**Comment by riccardoferretti** [comment]
I have written some notes here:
https://github.com/foambubble/foam/discussions/1081

And I have invite people in the community to share their thoughts there as well to help "less experienced note-takers"

**Comment by elgirafo** [comment]
great initiative, if anyone has a public example of how they use foam, maybe something different that the template would be great to gather these examples somewhere.
