### ISSUE TITLE
Executing inline date command returns Wikilink to Daily Note of that date

### ISSUE THREAD

**Issue by theAkito** [foambubble/foam#1085]
### Describe the bug

When entering a date command, like e.g. `/+1d`, a Wikilink to a daily note gets inserted.

## Example

When entering `/+1d`, I get the following Wikilink: `[[journal_2022-10-16]]`, since my journal's filename format is `'journal'_yyyy-mm-dd`.

### Steps to Reproduce the Bug or Issue

1.  Set the `Open Daily Note: Filename Format` setting to `'journal'_yyyy-mm-dd`.
2. Open any note.
3. Execute the inline command `/+1d`.
4. Get this Wikilink: `[[journal_2022-10-16]]`

### Expected behavior

I just want a date. I just want `2022-10-16`. That's it. Ideally, it should be configurable via a pattern, just like with `Open Daily Note: Filename Format`.

### Operating System Version

Windows

### Visual Studio Code Version

Version: 1.72.2 (user setup) Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075 Date: 2022-10-12T22:15:18.074Z Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10 Sandboxed: No

### Additional context

https://github.com/foambubble/foam/issues/735#issuecomment-888158299

It seems like having a Wikilink extended date insertion was perhaps intended, however, it still does not make sense, if the name creation pattern for the daily note is adjusted. Additionally, the user perhaps does not want to create a daily note, if he is pasting the date of a year from now.

**Comment by riccardoferretti** [comment]
Hi @theAkito, what you are describing is the feature :)

The goal of the date snippets is to quickly create wikilinks to daily notes, therefore they follow the daily note name format. It is not to create a wikilink with an arbitrary date.

I don't know if there are snippets in VS Code that do what you need (it's not Foam specific what you are asking, you need a date formatter with a shortcut) maybe it's worth looking for that.
