### ISSUE TITLE
"Foam: Create Note" command does not use .foam/templates/new-note.md

### ISSUE THREAD

**Issue by tv42** [foambubble/foam#1094]
### Describe the bug

All code paths creating new notes should respect `.foam/templates/new-note.md` (or another more specific template, like `daily-note.md`). "Create Note" does not.

### Steps to Reproduce the Bug or Issue

- Clone https://github.com/foambubble/foam-template/
- `cp .foam/templates/your-first-template.md .foam/templates/new-note.md`
- control-shift-P "Foam: Create Note"
- observe the created note does not contain the template contents

The only non-deprecated use of `getDefaultTemplateUri` is in `createForPlaceholderWikilink`:
 https://github.com/foambubble/foam/blob/8fe869223d6d4b31e81447ed103f1445d6aa4352/packages/foam-vscode/src/services/templates.ts#L358

- in the new note, type `[[This is a placeholder]]` and control-click it
- observe the template contents get used now

### Expected behavior

Consistent behavior, `new-note.md` being the default template for all new notes, no matter how they are created.

### Operating System Version

Linux

### Visual Studio Code Version

1.70.0

**Comment by chrisUsick** [comment]
I can confirm I see this behaviour too.

**Comment by riccardoferretti** [comment]
Thanks for reporting this, will look into it
