### ISSUE TITLE
adding non .md files to a [[note link]]

### ISSUE THREAD

**Issue by elgirafo** [foambubble/foam#1097]
### Is your feature request related to a problem? Please describe.

Currently, I am not able to link a .sol file to an .md note using "[[]]"

### Describe the solution you'd like

Ability to link to non .md notes adding it to the graph view.

### Describe alternatives you've considered

Making it a hyperlink.

**Comment by riccardoferretti** [comment]
Non-md files are considered attachments.
You need to include the `sol` extension in the configuration for the attachment provider.
`foam.files.attachmentExtensions`

**Comment by elgirafo** [comment]
> 

amazing thanks!
