### ISSUE TITLE
Document how to get a rendered version

### ISSUE THREAD

**Issue by DanielMSchmidt** [foambubble/foam#11]
First of all: I love it 😍 

My current problem I solve through foam is organising my dancing journal.
I need to be able to access it and quickly navigate it from my phone and the rendered version you have as a Github page here seems to do just that.

I could not find the instructions to set this up (or to even render it)

**Comment by jevakallio** [comment]
If you created your workspace as a GitHub repository, you should be able to just turn on the GH pages in your repo settings.

There's a stub recipe here:
https://foambubble.github.io/foam/github-pages

Let me know if it doesn't work for you and I can amend to it. If you get it working and something wasn't obvious, I would love a PR to improve the recipe!

**Comment by DanielMSchmidt** [comment]
Yes, that was helpful, thank you 👍
