### ISSUE TITLE
Comparison to memo

### ISSUE THREAD

**Issue by floAr** [foambubble/foam#110]
There also is https://github.com/svsool/vscode-memo which seems to do something similar. Is there anything particular to diversify foam from memo?

**Comment by floAr** [comment]
https://github.com/svsool/vscode-memo/issues/9

**Comment by jevakallio** [comment]
@floAr good question. 

I've seen the vscode-memo repo before but haven't tried it myself. It seems to do a lot of similar things as [VSCode Markdown Notes], which is one of the underlying libraries in Foam.

Foam's scope is slightly larger. With Foam, we're looking to not only improve the editing of networked notes, but also the storage, syncing and collaboration (GitHub), publishing, etc.

Right now the projects are probably quite similar in terms of what you can do with them, but I'd expect them to diverge over time. 

If you want wikilinks with good autocompletion experience, vscode-memo (or just using vscode markdown notes) seems like a good choice. If you want to explore what we can do in the broader note taking space inside VS Code, the community aspect of Foam could be of interest to you.
