### ISSUE TITLE
Nested Daily Notes

### ISSUE THREAD

**Issue by CodingFan72** [foambubble/foam#1101]
### Is your feature request related to a problem? Please describe.

As time goes on my journal folder gets fuller and fuller as all the daily notes are on one level. That kills you.

I wanted to sort the notes into subfolders:

````
- 2022
     - 10
         - 2022-10-09.md
         - ...
    - 11
         - ...
````

This is (as far as I can see so far) only manually.
I tried using a similar "setting" as Obsidian use, but when I enter a path in the form `Journal/yyyy/mm`,
I get

````
- Journal
     - yyyy
         - mm
````

### Describe the solution you'd like

As I said, I could think of a solution similar to Obsidian with a "dynamic" path:

Path: `daily notes/yyyy/mm`

becomes

````
- daily notes
     - 2021
         - 01
         - ...
     - 2022
         - 10
             - 2022-10-23
             - ...
````

### Describe alternatives you've considered

-

**Comment by riccardoferretti** [comment]
You can easily achieve that using the `daily-note.md` template and the `filepath` property within it.
More info here: https://github.com/foambubble/foam/blob/master/docs/user/features/note-templates.md#default-daily-note-template

Will close the issue, but feel free to reply if something is not clear.
Also feel free to update the documentation and submit it as a PR if something might be clearer there :)
