### ISSUE TITLE
Recipes bubbles are missing

### ISSUE THREAD

**Issue by by-cloud** [foambubble/foam#1110]
### Describe the bug

In readme.md file of the repository https://github.com/foambubble/foam-template, in the sentence "To learn more about how to use Foam, read the [Recipes](https://foambubble.github.io/foam/recipes/recipes) bubbles of the Foam documentation workspace.", the hyperlink redirected to an empty page, which shows "Page not found!". Recipes are missing.

### Steps to Reproduce the Bug or Issue

1. Go to https://github.com/foambubble/foam-template
2. Click on [Recipes](https://foambubble.github.io/foam/recipes/recipes)

### Expected behavior

The content of [Recipes](https://foambubble.github.io/foam/recipes/recipes) should appear.

### Operating System Version

Windows10

### Visual Studio Code Version

1.73.1

**Comment by riccardoferretti** [comment]
Thanks, I fixed the link
