### ISSUE TITLE
Reference-style links do not link nodes nor generate backlinks

### ISSUE THREAD

**Issue by thiskurt** [foambubble/foam#1112]
### Describe the bug

When using a reference-style link in a markdown document to link two files Foam does not correctly create a link between the two nodes in the graph nor does it create a backlink for it.

For example:

If I use a `[[wikilink]]` there is clearly a connection between the nodes in the graph and I can see backlink in the linked document back to the source:

![wikilink](https://user-images.githubusercontent.com/15367288/204288092-03df347e-623a-4aa1-8c93-02b4ba4315ab.png)

If I use a classic `[text](url.md)` style link the nodes are also correctly linked and a backlink also appears in the linked document:

![classiclink](https://user-images.githubusercontent.com/15367288/204288423-b1c63a3b-018d-4e07-b3b3-6765d8eab35f.png)

However when I use a reference-style link `[text] followed later by [text]: url.md` there is no connection created between the two nodes nor does a backlink show up in the backlink pane:
 
![referencelink](https://user-images.githubusercontent.com/15367288/204288973-e4c59909-8980-4cb9-8edb-c5952d245143.png)

### Steps to Reproduce the Bug or Issue

1. Create two files.
2. Link to 'file 2' from 'file 2' using a reference-style link
3. Check the graph and/or backlinks panel to see that no link is recognized by Foam.

### Expected behavior

The expected behaviour would be for all three of these links to act in the same way and create a connection between the nodes every time.

### Operating System Version

Windows

### Visual Studio Code Version

1.73.1

**Comment by riccardoferretti** [comment]
in your last example you should have `[[Page]]`, not `[Page]`

try
```
link to [[Page]]

[Page]: Page2.md

```

**Comment by thiskurt** [comment]
Ooh, I see, interesting. Thanks.

**Comment by thiskurt** [comment]
It does have an additional issue that the link is not clickable in preview mode, however.

**Comment by riccardoferretti** [comment]
Yup, that's a good point, can you create an issue for that?
