### ISSUE TITLE
Hierarchical tag explorer only goes one level down.

### ISSUE THREAD

**Issue by dstengle** [foambubble/foam#1134]
### Describe the bug

The tag explorer does not properly handle tags more than two levels. For instance #bydate/2022/11/30, #bydate/2022/12/11, #bydate/2022/12/12 should nest properly like the filesystem view but don't. All of the tags after the first slash are just treated as a single node so the tag hiearchy looks like "bydate > 2022/12/12" instead of "bydate > 2022 > 12 > 12".

### Steps to Reproduce the Bug or Issue

Create tags in a node or nodes:
#bydate/2022/11/30 #bydate/2022/12/11 #bydate/2022/12/12

### Expected behavior

As a user, I expect the tag explorer to present a hierarchical filesystem view of tags that treats each tag separated by slashes as an expandable node in a hierarchy.

### Screenshots or Videos

![Screenshot_20230108_103136](https://user-images.githubusercontent.com/862098/211205123-8dfb71a2-fde5-4be3-8941-2e57336c5897.png)

### Operating System Version

Windows

### Visual Studio Code Version

1.74.2

**Comment by RicSanOP** [comment]
I am having an issue that may be related to this. When I imported my Obsidian vault into VSCode, Foam was only able to identify single level tags in the tag explorer. However, when typing `#` and getting the autocomplete, the autocomplete shows all of my hierarchical tags. Here is an image showcasing the issue. In my case, I don't even get second level (1st generation child) tags in the tag explorer which may have to do with my use of emojis for tags. I hope you can fix this at your earliest convenience.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/123998320/221993377-ec0c718c-153d-4da8-88b2-f9ae2002fc09.png">

**Comment by dstengle** [comment]
BTW, thanks for fixing this! I didn't get the alert for this and I just tried it, works perfectly!
