### ISSUE TITLE
Backlinks are case-sensitive only on Windows

### ISSUE THREAD

**Issue by yoctozepto** [foambubble/foam#1148]
### Describe the bug

The backlinks on Windows include only links using the same-cased file name of the note.

### Steps to Reproduce the Bug or Issue

1. Create a note with title `A` in a file named `a.md`.
2. Create a note with title `B` in a file named `b.md`.
3. Add a wikilink to `B` in `A` (using `[[B]]`).
4. Verify that the backlinks of `B` show `A` -> they do not.

### Expected behavior

As a user, I expected to see the `A` in the backlinks of `B`.

### Operating System Version

Windows

### Visual Studio Code Version

1.74.3

**Comment by badsketch** [comment]
Hey @yoctozepto it's been a while, and I think this may have been fixed? Tried this on windows using your steps
![backlinks-case-sensitive](https://github.com/foambubble/foam/assets/8953212/10cd1de5-aa75-4d9d-a28d-dc18c5b3862e)

Are you still able to reproduce?

**Comment by yoctozepto** [comment]
Must have been fixed then! Thanks for confirming. In the meantime, I have switched to TiddlyWiki because I like it more. :-)
