### ISSUE TITLE
Support displaying wikilinks using target's note metadata like "link_label" instead of name if alias not present

### ISSUE THREAD

**Issue by yoctozepto** [foambubble/foam#1149]
### Is your feature request related to a problem? Please describe.

Currently, wikilinks render as their names unless an alias is given. The target's title is used only as the link title and not as the label. To be able to present the same link canonically in all places, one has to either keep the canonical representation in the filename or keep aliasing everywhere (and break the DRY principle).

### Describe the solution you'd like

As a user, I would like to make wikilink render using target note's metadata like ``link_label`` instead of the name if no alias is given.

### Describe alternatives you've considered

I considered aliasing everywhere, but it violates the DRY principle.

**Comment by riccardoferretti** [comment]
Wikilinks in Foam use the filename (which might or not match the title of the note).
If you want a different text in the source document you can either use an ``[[link|alias]]` or a [reference definition](https://github.com/foambubble/foam/blob/master/docs/user/features/link-reference-definitions.md).

We have an [`alias` property](https://github.com/foambubble/foam/pull/1014) in the note that can be used to help with autocompletion (I admit this could do with some documentation), but there are [no plans](https://github.com/foambubble/foam/pull/1014#discussion_r902525686) to change the principle of having the wikilink to be a standard one (that is, one that matches the name of the file).

**Comment by yoctozepto** [comment]
Dear @riccardoferretti, I think I was misunderstood. My proposal is nothing like the quoted one. I mean to add additional capabilities to the rendering side of things, not how the wikilinks are built and what reference system they use.

**Comment by yoctozepto** [comment]
I proposed an early pull request showing what I mean to achieve. It works for me already. :-)
