### ISSUE TITLE
High download size and disk usage

### ISSUE THREAD

**Issue by piousdeer** [foambubble/foam#1152]
Foam 0.20.6's compressed vsix is 46.7 MB compressed and 223.4 MB uncompressed, resulting in a long download time (notably, VS Code does not have any download progress indicator) and high disk space usage.

From a quick look at the uncompressed package, 99% of that is occupied by /web, which I'm guessing contains transpiled JS files, each separately bundled by webpack and containing a copy of its dependencies. Tests are also redundantly included.

By downloading previous versions of Foam on open-vsx I've determined this regression was introduced in 0.20.4, but I couldn't find a relevant commit nor any mention of /web or webpack in package.json.

**Comment by riccardoferretti** [comment]
Thanks for reporting this, I will release a new version between today and tomorrow to fix the issue

**Comment by riccardoferretti** [comment]
Issue fixed in v0.20.7

Thanks again for reporting it!
