### ISSUE TITLE
Create a new file from the [[XX]] link and get the extension ".com" unexpectedly.

### ISSUE THREAD

**Issue by jqknono** [foambubble/foam#1154]
### Describe the bug

Create a new file from the [[XX]] link and get the extension ".com" unexpectedly.
The `.com` is the tail part of the folder name.

### Steps to Reproduce the Bug or Issue

1. create a folder with the name `abc.com`
2. new a file named `a.md`
3. append content `[[def]]`
4. ctrl+click on `[[def]]`
5. a new file generated as `def.com`, should be `def.md`

### Expected behavior

The new file generated as `def.com`, should be `def.md`

### Operating System Version

Windows

### Visual Studio Code Version

Version: 1.75.0 (system setup) Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164 Date: 2023-02-01T15:23:45.584Z Electron: 19.1.9 Chromium: 102.0.5005.194 Node.js: 16.14.2 V8: 10.2.154.23-electron.0 OS: Windows_NT x64 10.0.19045 Sandboxed: No

![BasbBPAXlJ](https://user-images.githubusercontent.com/12892734/216569869-ea33779a-8fad-47ec-899e-ea155c54c36b.gif)

**Comment by riccardoferretti** [comment]
I have not been able to reproduce this, maybe there is something I am missing from your settings.
Both with the new note dir set to `root` and `current` I couldn't reproduce following the steps above.
Also, this might have been related to #1171 - which is being fixed right now.

Can you please let me know if the issue still occurs with 0.21.1? I will release it later today

**Comment by jqknono** [comment]
@riccardoferretti I just checked, and this issue did not occur now.
