### ISSUE TITLE
If I update foam from 0.20.2 open link command stops working  

### ISSUE THREAD

**Issue by alexfrostdev** [foambubble/foam#1159]
### Describe the bug

vs code extensions allows me to check foam versions 0.20.2 and 0.20.5 - 0.20.7

Version 0.20.2 works fine but  0.20.5 - 0.20.7 stop open wiki links

### Steps to Reproduce the Bug or Issue

1. Install foam 0.20.5 - 0.20.7 
2. Ctrl+click on any [[wiki link]] 
3. or Cttrl+Shift+P and `open link` command

### Expected behavior

Expected behavior: 
open wiki link

Actual behavior: 
show definition pop up after ctrl+click
or nothing happen after `open link` command

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1081686/218176987-0b449717-3d84-4287-affd-422a96709529.png)

### Operating System Version

Windows 10

### Visual Studio Code Version

1.75.1

### Additional context

>The Foam log output for VSCode can be found here: https://github.com/foambubble/foam/blob/master/docs/features/foam-logging-in-vscode.md

this link returns 404

**Comment by riccardoferretti** [comment]
Use the command `Go to definition`

**Comment by alexfrostdev** [comment]
But this broke all flow. I don't need foam to open popup with definitions. I need foam to open wiki article to edit it, like it did before.

**Comment by riccardoferretti** [comment]
The command for me opens the file, not the popup, is it different for you?

**Comment by alexfrostdev** [comment]
Yes.

I use `  "foam.edit.linkReferenceDefinitions": "withExtensions",` settings

I've updated to latest foam plugin. Created fresh new repo to recheck . Added`  "foam.edit.linkReferenceDefinitions": "withExtensions",` settings and  than reopen vscode

and looks like ctrl+click work somehow, but I can't understand difference. And now foam create new  files without .md extension. It can't detect that file already created and show as it will need to create new one. And it is not generate "link references" for those links

![image](https://user-images.githubusercontent.com/1081686/220875570-448ec12f-8cd8-4635-a8af-44a1cffe702c.png)

F12 / Go to definition works differently for different links. It can open [[todo]] link from template. It show definition popup for [[Test Test]]. And it show "no definition found" for [[test test test]] and [[test1]] but all those files exist

![image](https://user-images.githubusercontent.com/1081686/220878058-c8f884f9-7354-4e44-bc0c-923944f43d95.png)

**Comment by riccardoferretti** [comment]
I know it's a bit confusing, but:
- placeholders are links, so you need to open the link to follow them
- wikilinks to existing resources need to be opened with the "Go to definition" command

It's due to how VS Code manages the two, I haven't found a perfect solution and landed on this compromise in the end.

There is a lot going on in the description above, here I am interested in knowing if using the `Go to definition` command opens the file or just the popup.

I just noticed the bug about the missing extension in the created file, please create a separate issue for that.
If there are additional issues due to `foam.edit.linkReferenceDefinitions` please create another issue.

I am not trying to be complicated, it's simply that if issues are not managed atomically it becomes really hard both to understand what's going on and keep track of the fixes.

**Comment by riccardoferretti** [comment]
I created the issue for the missing extension: https://github.com/foambubble/foam/issues/1171

**Comment by alexfrostdev** [comment]
>If there are additional issues due to foam.edit.linkReferenceDefinitions please create another issue.

Unfortunately I don't know what is related to this issue.

I've update foam to 0.21.1. Now wikilinks created with extensions and can provide additional info. Looks like `foam.edit.linkReferenceDefinitions` is unrelated to this issue and works fine for 0.21.1.

```
## [[Test Test]] <- I get definitions popup if use wikilinks as header

[[test test test]] <- this wikilink is opened as expected
```

so looks like it somehow related to markdown headers

**Comment by riccardoferretti** [comment]
Can you please attach a zip file with the smallest repo to allow me to reproduce the issue?

**Comment by alexfrostdev** [comment]
[foam-template-master.zip](https://github.com/foambubble/foam/files/10848608/foam-template-master.zip)

**Comment by riccardoferretti** [comment]
Sorry I can't reproduce the issue. Will keep this open for some time in case other people report similar issues

**Comment by alexfrostdev** [comment]
I don't know how to help to reproduce it.

I change os(to Linux to check if it windows specific) and install vscode from scratch without any settings or settings sync - defaults install. Than I open foam-template-master.zip that I attached and I get same issue when ctrl+click on markdown header link

![image](https://user-images.githubusercontent.com/1081686/224418347-25b44274-7ac3-44a9-9b5e-da3d6b522eb9.png)
