### ISSUE TITLE
Consumes massive CPU when editing non-foam md file

### ISSUE THREAD

**Issue by dsaff** [foambubble/foam#1163]
Type: <b>Bug</b>

- Have foam extension enabled.
- Edit a Markdown file outside of foam

Hypothesis: it's scanning my whole huge workspace for backlinks?

Extension version: 0.20.8
VS Code version: Code 1.75.1 (Universal) (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|11, 124, 109|
|Memory (System)|32.00GB (10.58GB free)|
|Process Argv|--crash-reporter-id c209f967-c684-4080-a846-ee70bf738c13|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30660299
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
f6dab269:30613381
pythonsymbol12cf:30657549
vsccsb:30662443

```

</details>

**Comment by riccardoferretti** [comment]
Sorry @dsaff but from this I can't really reproduce the issue.
There have been similar reports in the past, have you checked those as a first step?

Will close this and focus on others like #1167 #1096 #1062 #739
