### ISSUE TITLE
journal organisation

### ISSUE THREAD

**Issue by Net-Mist** [foambubble/foam#1164]
### Is your feature request related to a problem? Please describe.

When creating a new page in the journal, it creates a new file in the `journal` folder. This folder can grow very big after some time.

### Describe the solution you'd like

As a user, I would like to have an non-flat structure for the journal. For instance organizing files in sub-folder for years and months, like this:

```
journal
├── 2022
│   ├── 01
│   │   ├── 2022-01-03.md
│   │   ├── 2022-01-04.md
│   │   ├── 2022-01-05.md
├── 2023
│   ├── 01
│   │   ├── 2023-01-03.md
│   │   ├── 2023-01-04.md
│   │   ├── 2023-01-05.md

```

If possible, the configuration to achieve this should be simple and allow other kinds of structures. One way to achieve it could be to write something like:
```json
"foam.openDailyNote.directory": "journal/yyyy/mm",
```

### Describe alternatives you've considered

NA

**Comment by hall** [comment]
`filenameFormat` supports subdirectories so the following should match your example.

```json
{
    "foam.openDailyNote.directory": "journal",
    "foam.openDailyNote.filenameFormat": "yyyy/mm/yyyy-mm-dd",
}
```

**Comment by Net-Mist** [comment]
Indeed, I didn't think about it. Thanks a lot !

**Comment by riccardoferretti** [comment]
What I would also recommend is to use the `daily-note.md` template:

https://github.com/foambubble/foam/blob/master/docs/user/features/note-templates.md#default-daily-note-template
