### ISSUE TITLE
The content of the relative path in embed note is not displayed.

### ISSUE THREAD

**Issue by MasouShizuka** [foambubble/foam#1168]
If a note references another note that is not in the same folder, and the latter has content with a relative path, then the note cannot display the content with the relative path in the latter.

For example, this is note2:
![image](https://user-images.githubusercontent.com/44764707/220224450-0409ba77-4282-464f-9e40-3eb39bf8eb8f.png)

And this is note 1 which contains embed note 2:
![image](https://user-images.githubusercontent.com/44764707/220224622-aacb3c6d-1371-4425-a7f3-f7328b54ac26.png)

Can the note display the content of the relative path of other embed notes?

**Comment by riccardoferretti** [comment]
Thanks for reporting this, anyone wanna help with a PR?

**Comment by riccardoferretti** [comment]
This has been fixed on master and will be out with the next release
