### ISSUE TITLE
newNotePath = currentDir does not work

### ISSUE THREAD

**Issue by tv42** [foambubble/foam#1170]
### Describe the bug

Using foam v0.21.0. Settings has

```json
"foam.files.newNotePath": "currentDir"
```

### Steps to Reproduce the Bug or Issue

- create a note foo/bar.md
- in it, write `[[quux]]`
- control-click `[[quux]]`
- observe file `quux.md` was created in root, not in `foo/`

### Expected behavior

`foo/quux.md`

### Operating System Version

Linux

### Visual Studio Code Version

1.73.1

**Comment by riccardoferretti** [comment]
I just tried to reproduce the issue but I seem unable to, can you share your test repo?
Is anyone else experiencing the same problem?

**Comment by tv42** [comment]
Alright, I managed to narrow this down.

The problem manifests if `.foam/templates/new-note.md` sets `filepath`; that filepath is interpreted relative to the root, not relative to the intended destination.

I set `filepath` in an attempt to get foam's "Create New Note" to use `title-of-my-new-note.md`, not spaces and upper case, in the filename.

While this seems to match what's documented (https://foambubble.github.io/foam/user/features/note-templates#metadata), I would argue that the filepath should be relative to what the filename was going to be without filepath set.

```
---
foam_template:
  name: Default
  description: Simple note
  filepath: $FOAM_SLUG.md
---
# $FOAM_TITLE

$FOAM_SELECTED_TEXT
```

**Comment by riccardoferretti** [comment]
Ok I got it now. I see the issue.

Short of implementing variable substitution, and having thought about the problem, this is what I am thinking about:
- `$FOAM_SLUG.md` will resolve to the workspace root
- `./$FOAM_SLUG.md` will resolve to the current dir

Basically starting the `filepath` with a `./` will mean: use the current file as source (if possible)

Happy to hear thoughts

**Comment by tv42** [comment]
Love it!

**Comment by riccardoferretti** [comment]
Thanks for the comments, I tend to agree with them (see https://github.com/foambubble/foam/pull/683). 

Some other considerations:
- I don't love the idea of reimplementing snippet substitution, see  https://github.com/microsoft/vscode/issues/155868 - this is the reason why I didn't go with #683 in the end
- I agree that the subtle difference between `./note.md` and `note.md` might be confusing at first. At the same time I believe that it's pretty easy to understand once discovered as a behavior

Thought?

**Comment by dstengle** [comment]
Based on the thread here, was ./$FOAM_SLUG.md intended to work after the commit that closed this? That didn't work, but I tried the original setting mentioned "newNotePath = currentDir" and that did work as expected.

**Comment by riccardoferretti** [comment]
I tested the following and it worked:

```
---
foam_template:
  filepath: ./$FOAM_SLUG.md
---

content
```

what's the problem you are experiencing? can you share a small reproducible example?

**Comment by Grant-vB** [comment]
Just an FYI for future readers, I also encountered the issue where CTRL+Clicking didn't create a new note when `newNotePath = currentDir`. However, I managed to resolve it by following these steps:

1. Set `newNotePath = root`.
2. Create a note by CTRL+Clicking.
3. Finally, revert `newNotePath` back to `currentDir`.

After making these adjustments, the issue was resolved successfully.

**Comment by karstengresch** [comment]
Seems not to work for me: This is the content of my `.foam/templates/new-note.md:`

```yaml
---
foam_template:
  filepath: ./$FOAM_SLUG.md
---
---
id: $UUID
title: "$FOAM_TITLE"
type: foam-note
desc: ""
created: $FOAM_DATE_SECONDS_UNIX ($FOAM_DATE_YEAR-$FOAM_DATE_MONTH-$FOAM_DATE_DATE $FOAM_DATE_HOUR:$FOAM_DATE_MINUTE:$FOAM_DATE_SECOND)
tags: $FOAM_DATE_YEAR
---
# $FOAM_TITLE

$FOAM_SELECTED_TEXT
```

In settings.json I've set

```json
"foam.files.newNotePath": "currentDir",
```

When I create a new note via "Foam: Create New Note", the note is created in the root directory.

I'd expected the note to be created with a sluggish filename and placed in the current dir.

If I remove 

```yaml
  filepath: ./$FOAM_SLUG.md
```
It's actually created in the current dir, but of course the slug name is gone.

I experience the same behavior for Ctrl+click creation, no matter the above mentioned workaround. Any idea?
