### ISSUE TITLE
link to sections creates new file in addition to the linked section

### ISSUE THREAD

**Issue by shelper** [foambubble/foam#1176]
### Describe the bug

I have two subfolders in my foam repo. one is called `pages`, the other is called `office`.
I create a note in `pages`, e.g., `foo.md`, where i added a link which links to a section of a note in `office`. e.g., `[[office_note#section1]]`, 
now when i try to click the link, i got two options, one is to `[[office_note#section1]]`, the other links to a new note `office_note_section1.md` in the `pages` folder. and this new note is automatically created. 
I tried to constrain the link by adding `[[office/office_note#section1]]`, but then when i click the link, it creates a new note `office_office_note_section1.md` in the `pages` folder. 

### Steps to Reproduce the Bug or Issue

just as i described above
1. create two folders, `pages`, `office`
2. add note to `pages` and add link to the note, and the link links to a section of a note in `office`
3. click the link, got two links, one creates a new note for it.

### Expected behavior

it should not create new note

### Operating System Version

- OS: windows

### Visual Studio Code Version

1.75.1

**Comment by riccardoferretti** [comment]
Thanks for reporting the issue, I can't replicate it, can you please attach a zip with the minimum repo to reproduce the issue?

**Comment by shelper** [comment]
see the enclosed zip, and click the link in `foo.md` 
[foam_broken_section_link.zip](https://github.com/foambubble/foam/files/10854460/foam_broken_section_link.zip)

**Comment by riccardoferretti** [comment]
Am I missing something?

![foam-1176](https://user-images.githubusercontent.com/457005/221974355-36eb3d43-a8b0-40ea-9048-13de1c676e2d.gif)

**Comment by shelper** [comment]
it could be some plugin causing this? 
what happens to me is if i hold ctrl and move mouse to the link, it immediately creates a file called "office-notes-section1.md" in folder `pages`, and if i click it, two results shows up
see enclosed images. 
![image](https://user-images.githubusercontent.com/546163/221980789-1e83c324-4545-468b-b60a-a04a4276d87c.png)

![image](https://user-images.githubusercontent.com/546163/221980855-1e4d5aaf-c0c4-49ec-b784-ca85cae86054.png)

**Comment by shelper** [comment]
well, i tried to disable extension https://marketplace.visualstudio.com/items?itemName=kortina.vscode-markdown-notes and seems the issue is gone, i guess maybe foam should recommend not use this plugin. i am closing this as disabling the extension solves the problem

**Comment by shelper** [comment]
i have this configured for the extension above and problem solved:
`"vscodeMarkdownNotes.createNoteOnGoToDefinitionWhenMissing": false`
