### ISSUE TITLE
Syncing `foam-template/docs` with `foam/docs/user`

### ISSUE THREAD

**Issue by infogulch** [foambubble/foam#1177]
As discussed in https://github.com/foambubble/foam/issues/1025#issuecomment-1178679473 , it would be nice if `foam-template/docs` had a complete copy of the user docs in the `foam/docs/user` directory. It would be even nicer if syncing was automatic.

There I suggested using the git subtree command. The nice thing about this feature is that the files are actually present in the template repo as a regular file. All of the "syncing" is done out of band using the subtree subcommand, and the process for cloning/downloading the template repo is exactly the same as before. The main difference is that you couldn't accept direct contributions to `foam-template/docs` anymore.

Here's a basic strategy for updating `foam-template/docs` dir with the contents of `foam/docs/user` using git subtree:

1. Clone & cd:
    ```
    git clone https://github.com/foambubble/foam-template.git
    cd foam-template
    ```
2. Remove the docs dir (once):
    ```
    git rm -r docs
    git commit -am "Clear old docs once"
    ```
3. Fetch the main foam repo as a different remote, split `docs/user` dir into a separate branch, and add that branch as a subtree at `foam-template/docs`:
    ```
    git remote add upstream-docs https://github.com/foambubble/foam.git
    git fetch -n upstream-docs/master
    git checkout upstream-docs/master
    git subtree split -q --squash --prefix=docs/user --annotate="[docs] " --rejoin -b upstream-docs/
    docs
    git checkout master
    git subtree add --prefix=docs --squash upstream-docs/docs
    ```
4. For maintenance, change the last line from `git subtree add` to `git subtree merge`

Considerations:
* Could omit `--squash` to preserve history. (Is preserving docs commit history in the template repo desired?)
* For simplicity, I think this should be a pull-only strategy. I.e. only pull from `foam/docs/user` into `foam-template/docs`, never push from the latter to the former
* Could create a github action to watch `foam/docs/user` for changes and open a PR on `foam-template` to keep them in sync automatically, see: https://github.com/marketplace/actions/create-pull-request

References:
* :star: https://gist.github.com/tswaters/542ba147a07904b1f3f5
* https://gist.github.com/SKempin/b7857a6ff6bddb05717cc17a44091202
* https://www.atlassian.com/git/tutorials/git-subtree
* https://manpages.debian.org/testing/git-man/git-subtree.1.en.html

---

Thoughts?

**Comment by riccardoferretti** [comment]
I love the idea of the github action, could we do that without introducing git subtree?

**Comment by riccardoferretti** [comment]
Taking a step back, the goal here IMO is to have a single source of truth for the documentation, within the main Foam repo.  

I would choose the simplest solution that can achieve that, for maintenance and for clarity.
My only concern is the extra complexity introduced by using a lesser known git feature. I admit I haven't looked into it deeply, but at the same time I'd rather not if the same can be achieved "as is" with reasonable compromises. 

For the history I would be ok with keeping it only in the main repo, in your opinion are there other pros/cons of one approach vs the other?

**Comment by infogulch** [comment]
I think that's a reasonable approach.

I have implemented this as an action on my fork of the foam repos:

* Example run: https://github.com/infogulch/foam/actions/runs/4464059117/jobs/7839852705
* Action definition: https://github.com/foambubble/foam/compare/master...infogulch:foam:master
* Example resulting PR: https://github.com/infogulch/foam-template/pull/2

I can open a pr from infogulch/foam:master to this repo if you like it.

Note, to get it working you will need to:

1. Create a new Personal Access Token (PAT) that has `PR` and `content` permissions on the `foam-template` repo: https://github.com/settings/personal-access-tokens/new
2. Add it as a new repository secret in your foam repo: https://github.com/foambubble/foam/settings/secrets/actions
3. Make sure the name matches the secret name referenced in the Action yaml definition

**Comment by riccardoferretti** [comment]
Thanks for this, it looks amazing!

It also made me notice something I had missed before, the fact that our docs do have wikilink definitions (which we need to make it navigable within github), whereas `foam-template` does not (because it feels like a "niche" feature that most people are not interested in, and I don't want it to be the default).

Are you willing to conjure a script to process the files after they have been copied to remove the wikilink definitions?

**Comment by riccardoferretti** [comment]
Here is a shell command that can quickly do that:

```
cat input_file.md | awk '/\[\/\/begin\]/ {delete_line=1} !delete_line; /\[\/\/end\]/ {delete_line=0}' > output_file.md
```

**Comment by infogulch** [comment]
That's a good idea.

I put it into a one liner and added it to the script:

* The line: `(cd foam-template/docs; sed -i '/\[\/\/begin\]/,/\[\/\/end\]/d' $(find . -type f -name \*.md))`
* Run where it worked: https://github.com/infogulch/foam/actions/runs/4486390564/jobs/7888835195
* Notably, the difference between runs is visible in the 'bot' PR
  * The (same) PR: https://github.com/infogulch/foam-template/pull/2
  * If a rerun causes the docs to change, the bot will just force push to the same branch, and you have the opportunity to merge the latest version and compare it to previous versions.
  * diff between the previous run and this one: https://github.com/infogulch/foam-template/compare/f017d604a4ad24dc835ed94fa35fda6981c4481b..27cfeaf53d0f237de1a65ade0e98745a4f832d30
