### ISSUE TITLE
Tag expansion fires inside Markdown headings

### ISSUE THREAD

**Issue by jimgraham** [foambubble/foam#1182]
### Describe the bug

When writing a markdown heading prefixed with `#`, the tag expansion bubble opens up

### Steps to Reproduce the Bug or Issue

1. create a tag such as `decision-log`
2. in a separate file, type a markdown header like `## Must DO`
3. the tag-expansion bubble will appear with the `decision-log` tag

### Expected behavior

I expect that tag expansion is ignored in headings

### Screenshots or Videos

<img width="734" alt="tag-expansion" src="https://user-images.githubusercontent.com/430293/230211642-42f20477-c271-4366-82be-1810dd32de02.png">

### Operating System Version

OSX 13.4

### Visual Studio Code Version

1.77

### Additional context

my suspicion is that it occurs because the `TAG_REGEX` https://github.com/foambubble/foam/blob/d0ee71be1b95935fee6987b8f737d0c06a380f3c/packages/foam-vscode/src/features/tag-completion.ts#L8

is far too generous. Something that excludes `# text`. I assume tags can't have spaces, so `\S+` should work
```
TAG_REGEX = /#(\S+)/
```

I could add a test similar to https://github.com/foambubble/foam/blob/122db206956a36d145bea54041559a3b53e067a7/packages/foam-vscode/src/features/tag-completion.spec.ts#L83

**Comment by jimgraham** [comment]
Possible fix in #1183

**Comment by riccardoferretti** [comment]
Fixed in 0.21.2
