### ISSUE TITLE
Discussion: Create place to share Foam workspace Templates

### ISSUE THREAD

**Issue by jsjoeio** [foambubble/foam#119]
After my conversation with @jevakallio today, I thought it would be a good idea to create a place to share Foam workspaces setups. Ideally, it would include:
- `.vscode/settings.json`
- `.vscode/extensions.json`

This will give people inspiration for setting up their Foam workspace to optimize the environment for writing.

Discussion: where should this live in the project?

Ideas:
- Create a Recipe called ~~Workspaces~~ Templates which is it's own page, and people can create sub pages with links to their templates 

Future:
- I don't think those need to be kept under the `foambubble` org, but we should have a place to showcase them

**Comment by riccardoferretti** [comment]
I like the idea, I have a slightly different setup and @jevakallio was asking me to share it, this would be a great place to do that.
I'd suggest calling the recipe `Templates`.

Maybe in the future templates could also be used by the CLI to create a foam project:

```
foam create --template <template-id>
```

e.g. `npx foam create my-foam --template foam-template-gatsby`

(somewhat similar to what https://create-react-app.dev/docs/custom-templates/ does)

**Comment by juanfrank77** [comment]
> Maybe in the future templates could also be used by the CLI to create a foam project:
> 
> ```
> foam create --template <template-id>
> ```

I like this idea! it would be really cool for folks to be able to create a workspace that already has a set of configured options. and it would work with Mathieu's template and mine (and any other template that gets created in the future.)

People could have different foams optimized for different needs 😀

**Comment by jsjoeio** [comment]
> I'd suggest calling the recipe Templates

Good call! I think that word suits the idea better. 

> People could have different foams optimized for different needs

Exactly! 😄

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
