### ISSUE TITLE
"Create New Note From Template" doesn't respect the "New Note Path" currentDir setting

### ISSUE THREAD

**Issue by svko** [foambubble/foam#1193]
### Describe the bug

I created a `selection.md` template containing just ` ${FOAM_SELECTED_TEXT}` , to create new note from selected text. Creating node using this template works, however the resulting file is placed in a workplace root, not in the directory of a file being edited (as "currentDir" setting suggests). Usual "create new note" respects the setting.

### Steps to Reproduce the Bug or Issue

1. Create template `selection.md` containing just `${FOAM_SELECTED_TEXT}` (in .foam/templates )
2. Create subdirectory `somedir` and file `somefile.md` there.
3. Type some text, select part of it, perform "Create new note from template" command.

### Expected behavior

Expected behavior: file is created in `somedir`
Observed behavior: file is created in the root.

### Operating System Version

Windows 11

### Visual Studio Code Version

Version: 1.77.3 (user setup) Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710 Date: 2023-04-12T09:16:02.548Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Windows_NT x64 10.0.22621 Sandboxed: Yes

**Comment by riccardoferretti** [comment]
Thanks for reporting this, the fix will be released in 0.22.0
