### ISSUE TITLE
Feature Request: export to pdf/epub format of my foam workspace

### ISSUE THREAD

**Issue by technolaaji** [foambubble/foam#120]
According to the recipes section on Foam's website [recipes link](https://foambubble.github.io/foam/recipes) if I want to publish my foam workspace, I can publish it as a page on Github pages and Netlify.

What if I want to write a book in Foam and export it as a pdf or epub format? a good tool like Pandoc [pandoc's site](https://pandoc.org/) transforms your existing markdown files to pdf and epub format.

## Why this would be a useful feature in the future 

a good example is writing your university project/thesis or writing a book that has a good amount of links in it. The reason why I am suggesting this feature is that I have written my entire thesis in markdown and compiled it to pdf format. Since Foam already utilizes markdown then it would be great to have a feature to compile your workspace to a pdf or epub format.

## How would the user use this feature

if implemented, there should be a command in the command palette like 'compile to pdf' and 'compile to epub', it would convert your markdown files from the workspace and output them inside of your workspace inside a folder called "outputs" which contains the recently compiled document.

**Comment by jevakallio** [comment]
@technolaaji I like this! I don't think it'll be a priority for Foam to build this into "core", but we should definitely enable this workflow for people who want it.

Have you checked existing epub publishing tools for VS Code like https://marketplace.visualstudio.com/items?itemName=gdrtf.md2reader?

If any of the Foam-specific functionality (like wiki-links) don't work with those tools, we are planning on an optional build step that can output your notes as vanilla markdown (see: https://foambubble.github.io/foam/link-reference-definition-improvements#improvement-proposal)

Let's keep this open, I think it should be a recipe once we figure out what goes into doing this!

**Comment by technolaaji** [comment]
@jevakallio Thank you for the update! I have tried the existing epub publishing tools and they work as expected, I think the biggest issue is with wiki-links since they don't get identified by those interpreters but if there is a build step that can output my foam notes to vanilla markdown then that can help a lot!

as a technical person, it makes perfect sense to output my foam notes to regular markdown then compile them to epub/pdf/mobi but what if the user is not a technical person? tools like Roam Research, Obsidian, and Notion let the user export their notes to variety of options like pdf or plain markdown in a click of a button which is more user friendly 

I think this might be a further step in the future, my suggestion is that if Foam will ever have a plugin system then this feature can be introduced as a plugin or it can be developed as an external extension that takes your notes then parses them to markdown then to the extension of choice under the hood in a click of a button

it wouldn't make sense to have this feature in the core as you said but the use of a plugin system or a section on Foam's site that shows a list of community-made extensions for Foam would be ideal and sufficient enough

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
