### ISSUE TITLE
Foam Treating Links to Images as Nonexistent Notes

### ISSUE THREAD

**Issue by micharris42** [foambubble/foam#1200]
### Describe the bug

I updated a note with a link to an image today, and after saving the file, the link to the image turned yellow (to signify a nonexistent note) and hovering over it brought up the popup to create a new note. Likewise, clicking on the link now creates a new note, rather then taking me to the image file. The file name will show up in the Placeholders section of the sidebar.

The image is still showing up in the preview, so the image link is recognized by VSCodium, just not Foam.

This is new behavior, so it seems most likely to be a bug introduced with the latest version of Foam. 

Thank you.

### Steps to Reproduce the Bug or Issue

1. Create a link to an image file.
2. Save the document.
3. Foam will treat the link as a nonexistent note.

### Expected behavior

That upon creating a link to an image file, Foam does not treat it as a nonexistent note.

### Screenshots or Videos

The link to the image file, colored yellow:

![Capture1](https://user-images.githubusercontent.com/76890677/233497967-3a8b557e-7b4d-4aaa-9b79-8fc72e836fd6.PNG)

The image file listed in the Placeholders section of the sidebar:

![Capture2](https://user-images.githubusercontent.com/76890677/233498058-bab0f0e1-b040-473b-928c-ab72a9025597.PNG)

The image displayed in the preview:

![Capture3](https://user-images.githubusercontent.com/76890677/233498079-97bd9a2f-74cb-4b2b-b162-31186ce5fe26.PNG)

### Operating System Version

Windows 10

### Visual Studio Code Version

VSCodium 1.77.3

**Comment by riccardoferretti** [comment]
Hi @micharris42 - I tried to reproduce it, but without success. I notice the file is in a `.foam` dir?
I literally today pushed a commit to explicitly ignore anything under `.foam`.
1. could this be the cause of your issue?
2. is it on purpose that you are using that folder?
3. if so, why?

**Comment by micharris42** [comment]
@riccardoferretti, sorry for the re-open, close, re-open, but I think I have found an additional issue.

I do not like to include my image files in my graph, so for both `.foam` and `assets`, I added the folders to the `"foam.files.ignore"` setting. 

After doing so, my image file links are back to being treated as nonexistent notes:

![Capture](https://user-images.githubusercontent.com/76890677/233522867-db948e9c-5039-4905-b047-500615320888.PNG)

Is this a bug, or is this the intended behavior?

Thank you.

**Comment by riccardoferretti** [comment]
That setting will completely hide a file from Foam, so from its point of view the file doesn't exist. 
What you want should be achievable with Note Filters, but it has not been integrated in the graph command yet

**Comment by riccardoferretti** [comment]
Also, by default attachments, including images are not shown in the graph, isn't that right?

**Comment by micharris42** [comment]
@riccardoferretti, thank you for the clarification, as well as your patience with me in getting this sorted out.

Removing the folder(s) from the Foam ignore list has resolved the issue. I do apologize; I had misread the directions and thought the setting only ignored files for the purpose of the Graph view. A second reading proved that this was not the case. 

This has been a good push to do a clean up of the non-Markdown assets in my Foam workspace. 

Putting this issue down as Closed. Thank you again.

Best.

**Comment by junfx** [comment]
I have the same issue, with different cause.

```markdown
![](/attachments/2021/2021-03-26-19-01-16.png)      show as a placeholder
![](a/b/c.jpg)                                      no such image, show as a placeholder
![](../../a/b/c.jpg)                                no such image, show as a placeholder
![](/attachments/foam-icon.png)                     show as a placeholder
![](../../attachments/2021/2021-03-26-19-01-16.png)   ok
![](../../attachments/foam-icon.png)                ok
```

I guess we cant use absolute style path for  images.

My pasteImage settings:
```json
  "pasteImage.path": "${projectRoot}/attachments/2023",
  "pasteImage.insertPattern": "${imageSyntaxPrefix}/${imageFilePath}${imageSyntaxSuffix}",
  "pasteImage.basePath": "${projectRoot}",
```
