### ISSUE TITLE
Customised link indicators

### ISSUE THREAD

**Issue by GrimPixel** [foambubble/foam#1211]
### Is your feature request related to a problem? Please describe.

It recognises one type of link indicator only.

### Describe the solution you'd like

I would like to use customisable link indecators, e.g. (()), {{}}, and select which ones to be used to generate a graph.

### Describe alternatives you've considered

None

**Comment by riccardoferretti** [comment]
Foam is based on the markdown standard, and we use `[[wikilinks]]` because they are the standard in this format.
I am not planning on supporting other link indicators atm, whats the use case specifically?

**Comment by GrimPixel** [comment]
By using different link indicators, different graphs can be generated from the same files. It is in different dimensions. In one dimension, the relation can be from A to B; in another, the relation can be from B to A; in another, A and B can be unrelated.

**Comment by riccardoferretti** [comment]
Closing as this doesn't feel like it belongs in Foam core
