### ISSUE TITLE
$FOAM_DATE_TIMEZONE_OFFSET

### ISSUE THREAD

**Issue by redactedscribe** [foambubble/foam#1214]
### Describe the bug

[$CURRENT_TIMEZONE_OFFSET](https://github.com/microsoft/vscode/pull/170518) will be [introduced in VS Code 1.78](https://github.com/microsoft/vscode/issues/151220#issuecomment-1519874738).

I'm not sure for what purposes Foam's `$FOAM_DATE_*` variants exist, but I wanted to bring attention to this new date variable in case Foam should also handle it.

Thanks.

### Steps to Reproduce the Bug or Issue

\-

### Expected behavior

\-

### Operating System Version

Windows 11

### Visual Studio Code Version

VSCodium 1.77.3

**Comment by riccardoferretti** [comment]
Thanks for reporting this. Foam has access to all VS Code variables, and it won't need a custom version of this one, so I consider this issue resolved
