### ISSUE TITLE
Allow replacement of invalid characters in file names instead of them being stripped

### ISSUE THREAD

**Issue by redactedscribe** [foambubble/foam#1217]
### Is your feature request related to a problem? Please describe.

As noted in #1215, a title given for `$FOAM_TITLE` which contains invalid Windows file name characters has them automatically stripped to result in a valid file name, e.g.: `Invalid "Characters"` -> `Invalid Characters`.

### Describe the solution you'd like

In my case, I'd like to use `_` as a replacement character rather than having invalid characters entirely stripped. Others may prefer `-`, so stripping vs replacement (and with what) would ideally be configurable.

### Describe alternatives you've considered

Rename all my note file names to conform with what Foam produces. Preferably not.

**Comment by riccardoferretti** [comment]
I consider this a bit of an edge case, and generally speaking I want to limit the amount of configuration exposed in Foam (80/20). Will keep this open for now to see if there is more interest in the feature

**Comment by riccardoferretti** [comment]
> I've found replacement of invalid characters with _ or - to be more common by software than to strip them completely.

I agree, I might go for -

> People use various styles for Markdown file names:

Foam made the choice of using filenames for wikilinks - we provide the `FOAM_SLUG` variable for those who want to slugify their file names but wikilinks always use the filename, so in that case you'd have the slugified link in your text

Foam aims at being highly customizable, but I don't want to pollute the configuration itself, so except for core configuration I believe the best way for more advanced use cases will be achieved with hooks/plugins

**Comment by redactedscribe** [comment]
> we provide the `FOAM_SLUG` variable for those who want to slugify their file names

Is there documentation on how to use this variable? I'd like to test it to see how it works in practice.

**Comment by riccardoferretti** [comment]
You can find more info here: https://github.com/foambubble/foam/blob/master/docs/user/features/note-templates.md

**Comment by riccardoferretti** [comment]
Fixed in #1232
