### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by dandersonlittle** [foambubble/foam#1225]
### Describe the bug

Broken Link

### Steps to Reproduce the Bug or Issue

I came from docs/features/link-reference-definitions.md

I clicked on (https://foambubble.github.io/foam/features/link-reference-definitions.md)

I landed on page not found, and I have submitted the issue, as requested. 

Thank you. 

### Expected behavior

The linked page was not found

### Operating System Version

mac

### Visual Studio Code Version

1.78

**Comment by riccardoferretti** [comment]
Thanks for reporting, issue fixed
