### ISSUE TITLE
No gifs in foam-templates

### ISSUE THREAD

**Issue by henry-js** [foambubble/foam#1231]
### Describe the bug

In the foam-templates repository, the images subfolder is not included in the assets folder, resulting in notes such as note-templates.md not showing any of the instructional gifs.

### Small Reproducible Example

https://github.com/foambubble/foam-template

### Steps to Reproduce the Bug or Issue

1. Go to template repo
2. Open assets folder
3. Compare to foambubble\foam\docs\assets folder

### Expected behavior

There should be an images folder inside the assets folder for foam-template

### Operating System Version

Windows

### Visual Studio Code Version

1.78.2

**Comment by riccardoferretti** [comment]
Hi @infogulch - could you please take a look at this?

**Comment by infogulch** [comment]
I opened a PR to fix this if there is any interest.

**Comment by riccardoferretti** [comment]
Thanks @infogulch - I didn't get around testing it yet, leaving a comment there right now

**Comment by meow-d** [comment]
so this issue can be closed, right?

**Comment by riccardoferretti** [comment]
yup, thanks for pointing it out
