### ISSUE TITLE
"Create note from template for ..." tooltip option text cuts off 2nd extension for double extension files

### ISSUE THREAD

**Issue by redactedscribe** [foambubble/foam#1236]
### Describe the bug

Minor bug: The second extension in a link to a double-extension file is stripped from the "Create note from template for ..." tooltip option's text. Both tooltip options in the attached screenshot correctly create the note with the double-extension present, it's just the rendered text that appears to be the issue. Bug presented itself when trying to link to a `.tar.gz` file.

### Steps to Reproduce the Bug or Issue

1. `[Link to file](file.double.extension)`
2. Hover over the link, see the bug.

### Expected behavior

Tooltip should read "Create note from template for 'file.double.extension'".

### Screenshots or Videos

![VSCodium_2023-05-23_21-02-02](https://github.com/foambubble/foam/assets/25013746/a2265a43-a651-4170-8388-d06e9b8be31d)

### Operating System Version

- OS: Windows

### Visual Studio Code Version

VSCodium 1.78.2

**Comment by riccardoferretti** [comment]
Thanks for reporting this 👍
