### ISSUE TITLE
Some links are broken in foam-template

### ISSUE THREAD

**Issue by remiposo** [foambubble/foam#1245]
### Describe the bug

In the foam-template repo, some pages don't exist and links broken.
One of the reason is the same as #1231 , the content in `dev` is not being copied, hence the page does not exist.

Also, the content of `getting-started.md` might simply be outdated, causing broken links.
While this is not directly related to this Issue, it is written `You can create [[note-templates]] for things like book reviews, people, daily notes (coming soon), and more!`, but the functionality to create templates for daily notes already exists, doesn't it?

### Steps to Reproduce the Bug or Issue

Go to foam-template repo

### Expected behavior

It would be desirable to have the contents of `getting-started.md` correctly updated.
Also, it may be better to either use external link instead of wikilink when linking to `dev`, or ensure that any documents linked from `user` are copied along with it.

### Operating System Version

macOS

### Visual Studio Code Version

1.79.1

**Comment by riccardoferretti** [comment]
Thanks, yes the template docs need to be updated

**Comment by netpappy** [comment]
I started looking at this... I did the updates to the links in my version of getting-started.md, and it now works within VS Code, and from the GitHub documentation. Does this method seem acceptable? If so, I will continue updating accordingly... https://github.com/netpappy/foam-template/blob/master/getting-started.md

**Comment by riccardoferretti** [comment]
That's correct. to keep the docs in sync between the website/repo and the template we use Foam as the source of truth and copy the `docs/user` folder. See https://github.com/foambubble/foam/pull/1180

Thanks for looking into this, it's important but I haven't paid much attention to the docs lately. Very appreciated!
