### ISSUE TITLE
Resource filters ignore the `path` parameter

### ISSUE THREAD

**Issue by andreavaccari** [foambubble/foam#1246]
### Describe the bug

[Resource filters](https://github.com/foambubble/foam/blob/master/docs/user/features/resource-filters.md) take a `path` parameter that is documented as a regex to filter resources based on their path.

The [current implementation](https://github.com/foambubble/foam/blob/master/packages/foam-vscode/src/core/services/resource-filter.ts) and [unit tests](https://github.com/foambubble/foam/blob/master/packages/foam-vscode/src/core/services/resource-filter.test.ts), however, ignore the parameter.

### Small Reproducible Example

N/A

### Steps to Reproduce the Bug or Issue

Issue is self evident.

### Expected behavior

Feature should be implemented, or documentation should be updated.

### Operating System Version

Not relevant

### Visual Studio Code Version

Not relevant

**Comment by riccardoferretti** [comment]
Thanks for reporting the issue - must have totally missed it 😅

**Comment by riccardoferretti** [comment]
Fixed by https://github.com/foambubble/foam/pull/1250 - will come out in next release
