### ISSUE TITLE
Foam Janitor ran into an error

### ISSUE THREAD

**Issue by BramBonne** [foambubble/foam#1254]
### Describe the bug

When running Foam Janitor, I get the following error:

> Foam Janitor attempted to clean your workspace but ran into an error. Please check that we didn't break anything before committing any changes to version control, and pass the following error message to the Foam team on GitHub issues: Expected a string TypeError: Expected a string at bw (/home/brambonne/.vscode/extensions/foam.foam-vscode-0.25.0/out/extension.js:60:12355) at /home/brambonne/.vscode/extensions/foam.foam-vscode-0.25.0/out/extension.js:277:405 at async Promise.all (index 1) at async AU (/home/brambonne/.vscode/extensions/foam.foam-vscode-0.25.0/out/extension.js:277:661)

### Steps to Reproduce the Bug or Issue

Run the "Run Janitor" command

### Expected behavior

Foam Janitor runs

### Operating System Version

Linux

### Visual Studio Code Version

1.78.0

**Comment by riccardoferretti** [comment]
I can't seem to reproduce it, can you create a small repo I can use to see the error?

**Comment by BramBonne** [comment]
I can't seem to reproduce it anymore on my end either. My guess is that it had something to do with my Foam directory being backed by a virtual filesystem that was suffering intermittent connectivity issues, putting it in a weird state. Apologies for the noise.
