### ISSUE TITLE
add something like supertag from Tana with Template

### ISSUE THREAD

**Issue by shelper** [foambubble/foam#1255]
### Is your feature request related to a problem? Please describe.

Tana note taking tool from https://help.tana.inc/supertags.html supports something that is called `supertag`.
I wonder if a similar feature can be added to foam, this can be done by importing a template in the yaml header of the note.
for instance, if i want to add a supertag called #meeting_note, i create a template called meeting_note.yml, and in the yml header of the note, i can import this meeting_note.yml, thus i have:
```
---
supertag: meeting_note
---
```
And once the supertag is imported, the supertag can be expanded/foldered to show the field of that yaml for you to fill in for this note
```
---
supertag: meeting_note 
  ↳  date:
  ↳  time:
  ↳  attendee:
  ↳  topic:
---
```
then we can organize the note with such info 

### Describe the solution you'd like

as described above

### Describe alternatives you've considered

no alternative

**Comment by shelper** [comment]
it would be even better if this supertag thing can be assigned to each subtitle within a note

**Comment by riccardoferretti** [comment]
This seems pretty similar to our template functionality, am I missing something?

**Comment by shelper** [comment]
does foam supports template importing as i descripted above? if so, i could've overlooked, but didnt find such feature in the docs.
it would also make this supertag thing more useful if there are ways to organize based on thiss supertags.
e.g.. all meeting_notes that have certain attendees , or all meeting_notes within certain date range, etc. or maybe APIs to access these supertags so  people can write script to orgnize the notes based on this supertag thing. .

**Comment by riccardoferretti** [comment]
The feature seems pretty advanced, I feel it is outside of Foam core's goal/scope.
Before considering a PR for it I would want to be fully on board with the use case and IIUC 90% of it can be implemented with a combination of templates and hierarchical tags, so I wouldn't consider it a priority. 
Maybe it's similar to Dendron's schemas (which Foam purposely didn't implement for the same reasons above) so maybe that can do the trick for you?
