### ISSUE TITLE
Wrap link suggestions to files with spaces in the name in angle brackets `<>`

### ISSUE THREAD

**Issue by redactedscribe** [foambubble/foam#1260]
### Is your feature request related to a problem? Please describe.

`[Link](|)`: When an autosuggestion is provided to a file, e.g. `My File.md`, `My%20File.md` will be inserted. This isn't very readable in the Markdown source.

### Describe the solution you'd like

If there was an option to wrap autosuggestions of files with spaces in their name in angle brackets instead, we'd end up with `[Link](<My File.md>` which is easier to read. This would bring standard Markdown links more in line with the readability of wikilinks `[[My File]]`.

### Describe alternatives you've considered

Manually edit out the `%20`s and wrap the filename in angle brackets every time.

**Comment by riccardoferretti** [comment]
This is managed directly by VS Code and not Foam
