### ISSUE TITLE
Option to automatically rename new note to kebab-case

### ISSUE THREAD

**Issue by limbonaut** [foambubble/foam#1263]
### Is your feature request related to a problem? Please describe.

Would be nice to have an option to name the file in kebab-case when running Create New Note.

Found an issue #544 that was closed due to it being not possible to implement.
However, Markdown Notes extension has similar feature implemented. Perhaps, it could be given another look?

### Describe the solution you'd like

When running "Create New Note" with a tile "My New Note" I would like a file to be named my-new-note.md.

### Describe alternatives you've considered

Renaming the file manually - but it could be automated.

**Comment by riccardoferretti** [comment]
Have you looked into using `FOAM_SLUG`?

https://github.com/foambubble/foam/blob/06a5988a52176bacb532372171d88400a871df5a/docs/user/features/note-templates.md

**Comment by limbonaut** [comment]
Thanks! Made a template like this:
```markdown
---
foam_template:
  filepath: $FOAM_SLUG.md
---
# $FOAM_TITLE

```
