### ISSUE TITLE
Discord invitation link is invalid

### ISSUE THREAD

**Issue by thara** [foambubble/foam#1269]
### Describe the bug

I clink discord invitation link in [readme](https://github.com/foambubble/foam/blob/master/readme.md) and `Accept Invite' button on redirection destination, but I can not join the Discord server with a error message as `Unable to accept invite`.

<img width="561" alt="Screen Shot 2023-08-05 at 17 01 03" src="https://github.com/foambubble/foam/assets/1532891/7d671341-9cf0-4697-8012-dc669dc5fedd">

### Steps to Reproduce the Bug or Issue

1. Visit https://github.com/foambubble/foam/blob/master/readme.md
2. On a Discord user not invited the server yet, Click discord invitation link such as:

<img width="406" alt="Screen Shot 2023-08-05 at 17 06 19" src="https://github.com/foambubble/foam/assets/1532891/cd5597ba-796b-4217-9a20-367f0082c319">

3. You should confirm a error mssage as `Unable to accept invite` by Discord.

### Expected behavior

We should be able to join the official Discord server by Discord invitation on README.

### Operating System Version

macOS

### Visual Studio Code Version

1.75.1

### Additional context

I think OS and VSCode aren't matter on this problem.

**Comment by riccardoferretti** [comment]
I can't reproduce it, can you please try again? maybe on a fresh session?

**Comment by thara** [comment]
Oh, I forgot to write the most important infomation...I used Firefox...
I click the invitation link on Safari, I could join the Discord server.

I apologize for wasting your precious time.
