### ISSUE TITLE
Tag Explorer - Show tags in current file

### ISSUE THREAD

**Issue by alexandrupetrini** [foambubble/foam#1270]
### Is your feature request related to a problem? Please describe.

I don't think so.

### Describe the solution you'd like

As a user, I would like to have an option "Show tags in current file" in the Tag Explorer, similar to "Show placeholders in current file".

### Describe alternatives you've considered

#893 may be a feasible solution.

### Screenshots or Videos

![image](https://github.com/foambubble/foam/assets/44755709/faf3129e-4934-4016-8b68-b2cd5837bc1e)

**Comment by riccardoferretti** [comment]
Thanks for the suggestion, this has been released today
