### ISSUE TITLE
foam-template bot sync not replicating .vscode directory

### ISSUE THREAD

**Issue by dcarosone** [foambubble/foam#1299]
### Describe the bug

The foam-template repo is out of date for the .vscode directory (noticed because of the recommended `extensions.json`, but probably also other settings changes, and should be included in the bot sync GHA

### Steps to Reproduce the Bug or Issue

clone the template, compare to source in foam repo `docs/.vscode`

### Expected behavior

up to date template

### Operating System Version

n/a

### Visual Studio Code Version

n/a

**Comment by MakaryGo** [comment]
Hi.
Now when using the template it puts the necessary files in `.vscode/.vscode`, so it doesn't initialize properly, seems related to this fix?

**Comment by riccardoferretti** [comment]
You are right.
I am looking at the script, and tried it locally, and it copies the files in the right location - am I missing something?
https://github.com/foambubble/foam/blob/master/.github/workflows/update-docs.yml

I guess I can just work around the issue by using `*`, but I am trying to understand what's happening

**Comment by riccardoferretti** [comment]
@MakaryGo this is now fixed. Thanks for reporting it
