### ISSUE TITLE
use org file format instead of markdown ?

### ISSUE THREAD

**Issue by jkanche** [foambubble/foam#13]
as the title says, can I switch out markdown with org-mode ? This allows me to use this with emacs org-mode as well.

**Comment by jevakallio** [comment]
Have you seen org-roam? It might be a better fit for your needs

https://github.com/org-roam/org-roam

If org-roam doesn't work for you, I'm curious to hear what you wanted Foam to do for you!

**Comment by jevakallio** [comment]
Closing, please open new issues if you have more specific questions or ideas

**Comment by gamebox** [comment]
I don't want to speak for the creator of this issue, but I think some things that come to mind:

- States for headers (TODO, INPROGRESS, DONE, WAITING, etc).  They can be toggled between with a click or keyboard shortcut(and have different styles applied)
- Deadlines / timestamps
- Agenda feature(collate items based on the above into a daily and/or weekly view, with navigation and state changes possible inline)

Though I think some of this could be done in a separate plugin, I think this would be a real differentiator for Foam - which is already excellent(new user).  I'm already sort of oversubscribed on work to implement these features, but I could give a bit of an overview of how I'd approach these items if requested.

**Comment by ChronosXYZ** [comment]
> Have you seen org-roam? It might be a better fit for your needs
> 
> https://github.com/org-roam/org-roam
> 
> If org-roam doesn't work for you, I'm curious to hear what you wanted Foam to do for you!

This is not valid answer imo. We are talking about VSCode extension and not Emacs package. It can be seen as enhancement.
