### ISSUE TITLE
[Proposal] Folders for tags 

### ISSUE THREAD

**Issue by owl-from-hogvarts** [foambubble/foam#1304]
### Is your feature request related to a problem? Please describe.

Amount of tags grows fast and it becomes hard to memorize them. Some tags are closely related to each other. So it hard to put only one from several related tags. That's because, for me, tags act like associations and nobody knows which association will come up first, when I would try to find a note :) So I want to keep them all to find information faster.

Tags represents topics. Topics are short and easily related to each other. Meanwhile single note may touch several, not such well related, topics. So it is desirable to tag single note with several tags (which is already possible), but keep tags structured

### Describe the solution you'd like

Just allow to group tags into something like folders with multiple levels of nesting. 

This can be done with vscode's tree view. Information about tag groups can be stored as json

While implementing this feature, flat view of all tags should be preserved to allow some _kind of overview_

### Store notes in hierarchical structure. 

When storing *notes* in directory tree, we need to group based on some principle. The one that comes to mind first is _topic_. But grouping by topic is not always possible since one note may touch several quite unrelated topics.

Thus it is desirable to keep notes as flat list, tag each note with indefinite amount of tags, while leaving tags structured

**Comment by riccardoferretti** [comment]
Tags can already be grouped into "folders", in the sense that they are hierarchical (e.g. `#people/friends` and `#people/foes` will show up under the `#friends` tag "folder" in the tags explorer treeview.
My understanding is that you would like to have folder support that is arbitrary. This is currently not planned.
