### ISSUE TITLE
Disable Journal Title

### ISSUE THREAD

**Issue by slashtechno** [foambubble/foam#1308]
### Is your feature request related to a problem? Please describe.

New daily notes are created with a heading. This can be problematic when using Foam with Logseq as it creates inconsistency as Logseq does not. Moreover, the creation of the heading cannot be disabled.

### Describe the solution you'd like

I expected `foam.openDailyNote.titleFormat` being set to an empty string (`""`) to disable the heading from being created. Instead, it creates a heading with a timestamp such as `Tue Nov 21 2023 01:39:32`.

### Describe alternatives you've considered

Unsure what alternatives, besides manually removing the heading, would be viable here.

**Comment by riccardoferretti** [comment]
You can achieve that using the `daily-note.md` template - https://github.com/foambubble/foam/blob/master/docs/user/features/note-templates.md

**Comment by slashtechno** [comment]
Ah, okay - makes sense.
I do think that if `foam.openDailyNote.titleFormat` is set to an empty string, the title should be omitted. That way this behavior can be changed without using templates, if the user prefers.

**Comment by riccardoferretti** [comment]
Your point makes sense, but the `foam.openDailyNote.*` settings will be sunset in favour of the `daily-note.md` template in the future, so given also the easy workaround, I am not sure it's worth making that change at this point.
