### ISSUE TITLE
Wikilink does not display H1 or title: of linked note in rendered markdown

### ISSUE THREAD

**Issue by mburleigh** [foambubble/foam#1320]
### Describe the bug

Wikilinks are not displaying the H1 or frontmatter title: attribute in the rendered markdown. Linking to a note `foo.md` that has an H1 `Foo Title` (ex. [[foo]]) displays `foo` in the markdown preview, not `Foo Title`.

### Small Reproducible Example

https://github.com/mburleigh/foam-wikilinks-titles

### Steps to Reproduce the Bug or Issue

Preview the sample project

### Expected behavior

I would expect the rendered markdown to show the H1 or the frontmatter title attribute.

### Screenshots or Videos

<img width="1072" alt="image" src="https://github.com/foambubble/foam/assets/5316446/48429ac4-2fbb-458c-ab68-426f9c0e03ed">

### Operating System Version

Windows 11

### Visual Studio Code Version

1.85.1

**Comment by mburleigh** [comment]
@riccardoferretti - I have done some work on VS Code extensions in the past. If you can give me an idea of where in the codebase this bug might be I can take a look.

**Comment by riccardoferretti** [comment]
Thanks for looking into it, the code you are looking for is in `wikilink-navigation.ts`. Looking at the code it seems like it should already be doing the substitution, so likely there is some issue I am missing atm.

Let me know if you need additional pointers.

**Comment by mburleigh** [comment]
Looks like it's a problem with the Markdown Preview Enhanced extension; this screenshot shows the source file, Markdown Preview Enhanced rendered version, and the regular Markdown Preview rendered version:

<img width="1083" alt="image" src="https://github.com/foambubble/foam/assets/5316446/6ef6fa0f-759c-487a-b7a6-a3f962edbe90">

**Comment by riccardoferretti** [comment]
That sounds about right, we don't support Markdown Preview Enhanced. Foam supports the built-in md preview
