### ISSUE TITLE
Update dateformat requirement to latest (5.0.3)

### ISSUE THREAD

**Issue by rcyeh** [foambubble/foam#1324]
### Describe the bug

Installed foam 0.25.6 on VS Code 1.85.1. Set preference to make weekly notes with:

```
"foam.openDailyNote.filenameFormat": "yyyy/yy-WW"
```

(yyyy subdirectory, filename 2-digit year, hyphen, padded week number, based on the documentation at https://www.npmjs.com/package/dateformat for version 5.0.3, published two years ago)

Today is Monday, 15 January, the third week of the year. On opening the daily (weekly) note, the created filename is: `2024/24-33.md`. I expected `2024/24-03.md`. Thought, this is probably a regular expression problem in dateformat.

But looking in my ~/.vscode/extensions/foam.foam-vscode-0.25.6/package.json, there is a line:

```
"dependencies": {
  "dateformat": "^3.0.3",
```

and indeed, in that version of dateformat https://www.npmjs.com/package/dateformat/v/3.0.3 (six years ago), there is only support for the single `W`, not padded `WW` format.

Can we update the required dateformat version to 5.0.3?

### Steps to Reproduce the Bug or Issue

1. Make the setting: `"foam.openDailyNote.filenameFormat": "yyyy-WW",`
2. Open a daily note.

### Expected behavior

I expected to be able to use any of the date formats specified in https://www.npmjs.com/package/dateformat, linked from the settings, but because the required dateformat version is 3.0.3, which does not support { `DDD`, `DDDD`, `p`, or `WW`}, when I use those formats in the "foam.openDailyNote.filenameFormat" setting, I get unexpected results.

In particular, in January, `WW` should return 03, but I get 33 instead. 

### Operating System Version

ChromeOS

### Visual Studio Code Version

1.85.1

**Comment by rcyeh** [comment]
I wonder how that version specification gets produced? In this repository's package.json file, the dependencies section is empty. But I see the `"dateformat": "^3.0.3",` specification at  https://github.com/foambubble/foam/blob/cdbb9656612d65cf15b911934e4808a63093168b/packages/foam-vscode/package.json#L565

**Comment by riccardoferretti** [comment]
The dependency is defined in `foam/packages/foam-vscode/package.json`, and yes, it's completely fine to do the upgrade - happy to take it on?

**Comment by rcyeh** [comment]
Thanks! Attached my first pull request ever for your review.

**Comment by rcyeh** [comment]
Since 4.5.1 supports the appropriate padded week codes and compiles with foam, we'll go to 4.5.1 instead of any higher ECMAscript version.
