### ISSUE TITLE
Wikilink are not working in preview mode when using workspace

### ISSUE THREAD

**Issue by chaleaoch** [foambubble/foam#1332]
### Describe the bug

Wikilink are not working in preview mode when using workspace. and this issue cannot be reproduced when open folder directly. and cannot be reproduced in source editor mode.

hope my description is clear, sorry for my English.

### Small Reproducible Example

https://github.com/chaleaoch/template_foam

### Steps to Reproduce the Bug or Issue

Attached a .gif for your information.
![gif](https://github.com/foambubble/foam/assets/11831441/dcf5bf0f-956a-43b2-b39a-520189cac990)

### Expected behavior

could jump to correct path.

### Operating System Version

windows

### Visual Studio Code Version

1.86.1

**Comment by chaleaoch** [comment]
https://github.com/foambubble/foam/issues/1277
this is very similar with above issue. but in preview mode.

**Comment by 2438mc** [comment]
Also getting this issue on VSCode v1.88.1 and Foam v0.25.11, any update?

**Comment by riccardoferretti** [comment]
No updates, it would be great if someone could look into it as well :)

**Comment by surajsharma** [comment]
any idea when this can be fixed? i am facing similar issue
