### ISSUE TITLE
Link to a section does not reflect in linked note's backlinks 

### ISSUE THREAD

**Issue by shelper** [foambubble/foam#1340]
### Describe the bug

when add a link to a section of a note, this link is not shown in backlink list of the linked file, similar to #895, which says it is fixed but seems the bug is still there

### Steps to Reproduce the Bug or Issue

Extract this uploaded zip file and open the bar.md, and you can see it only show the backlink to zar.md, not the foo.md, where the bar#section1 is linked.
[foam_broken_section_backlink.zip](https://github.com/foambubble/foam/files/14484976/foam_broken_section_backlink.zip)

### Expected behavior

the backlink of bar.md should show backlink to both foo.md and zar.md

### Operating System Version

windows 10

### Visual Studio Code Version

1.87.0

### Additional context

with foam v0.25.8

**Comment by riccardoferretti** [comment]
I just tried to reproduce it and it works fine for me with the given repo

<img width="910" alt="image" src="https://github.com/foambubble/foam/assets/457005/5917d0e4-37d2-4020-a090-6703204cf5fe">
