### ISSUE TITLE
[doc] documentation additions and broken link 

### ISSUE THREAD

**Issue by Walshkev** [foambubble/foam#1357]
I noticed that the readme of this project does not contain the contribution guide or community guidelines. I have found the contribution guide deeper with in the repository. I have also found the original code of conduct https://foambubble.github.io/foam/dev/code-of-conduct and the contribution guide https://foambubble.github.io/foam/dev/contribution-guide.html for foam bubble which can be easily linked within the read me. Also, the link on the discord page for the community guidelines is currently broken. 

![foam broken link ](https://github.com/foambubble/foam/assets/77123083/e2365a5e-568a-4374-9687-a34cf6b88e4b)

**Comment by riccardoferretti** [comment]
Thanks for reporting this @Walshkev! are you happy to do a PR and fix the issue?

**Comment by Walshkev** [comment]
i finished the this issue the pull request is [doc] documentation additions #1358

**Comment by riccardoferretti** [comment]
Great, thanks! I have merged it

**Comment by Walshkev** [comment]
i found the broken link on the discord channel https://discord.com/channels/729975036148056075/729976283613626408  
![image](https://github.com/foambubble/foam/assets/77123083/1208e4df-fde7-40c6-8a02-e8e3a59330b1)
All of the other links are working properly.

**Comment by riccardoferretti** [comment]
Thanks for that, I will fix it
