### ISSUE TITLE
"ALL LINKS" pane don't update after renaming a file

### ISSUE THREAD

**Issue by shuyuxie** [foambubble/foam#1371]
### Describe the bug

"ALL LINKS" pane don't update after renaming a file

### Steps to Reproduce the Bug or Issue

1. Go to Explorer side pane
2. Click on foam or whatever foam notes folder called
3. Rename a note Markdown file
4. See links in "ALL LINKS" are gone

### Expected behavior

All the links should remain intact after renaming a file

### Operating System Version

macOs

### Visual Studio Code Version

1.91.1 (Universal)

**Comment by pderaaij** [comment]
Hi, 

I've looked into this, but am unable to replicate this. After renaming, the panel updates correctly for me. Could you eleborate a bit more on your renaming action?

**Comment by shuyuxie** [comment]
Hi. Thanks for looking into it. You can replicate this by renaming a file, say `JavaScript.md`, to `javascript.md`

**Comment by pderaaij** [comment]
Yeah, in my case that works. So, a bit hard to replicate it... If you can share a little test repo that would be great.

**Comment by shuyuxie** [comment]
I've created a demo here: https://github.com/shuyuxie/foam-issue. Hope it helps explain the issue.

**Comment by pderaaij** [comment]
I've done a test with this repo, but I can't replicate the issue. Can you check if you have the latest version of Foam? Or else, check if another extension is causing the issue?

**Comment by shuyuxie** [comment]
I tested it with all other extensions disabled and I've installed the latest version of foam, but the issue was still there. It's not a big issue anyway. But since you can't replicate it, I'm gonna close this issue.
