### ISSUE TITLE
Sets the specified template for a specific empty link

### ISSUE THREAD

**Issue by red-co** [foambubble/foam#1381]
### Is your feature request related to a problem? Please describe.

Diary page. The same seven links are created every day.
- [[daily checklist]],
- work checklist
- common note,
- ....
And similar cases of reusing templates,
If you can specify a template for an empty link, you can save the two template selections for each link **(time/effort complexity O(n)=>O(1) )**

### Describe the solution you'd like

none

### Describe alternatives you've considered

Try editing at the source code and doing an ugly parsing rule and code injection. If the difficulty is not too high.

**Comment by red-co** [comment]
I thought of two syntax,
1. [[boo|Template(src)]]
2. `$foam.function.note.createByTemplate(src, dst)`
- Execute simple text code in place. I have wanted this for a long time.

roadmap
1. Parsing
2. Syntax highlighting
3. Clickable area
    - Call function
- others
    - Function snippet auto-completion. // may be use vscode/textmate text snippets instead of writing code in foam.

**Comment by riccardoferretti** [comment]
Hi @red-co - thanks for submitting the request. I am not sure I fully understand the use case you are trying to implement, can you clarify?
Have you seen https://github.com/foambubble/foam/issues/1218 ? Would this also satisfy what you are describing?

**Comment by red-co** [comment]
1. #1218, somewhat related, but not the same.
  - If I understand correctly. #1218 matches templates by prefix name. Its OP's idea seems to conflict with the use of general paths in wikilink? Or its "/" is based on the folder environment variable, which works when the file under the folder is created?
  - The current solution seems to be hover show msgbox and askUserForTemplate(),
  - In my case,
    - The program automatically creates a diary based on the template,
    - The diary file created by the diary template has multiple empty links under the diary path, for example, there are seven. And these seven files correspond to the corresponding templates used. This is not a choice, and can be achieved by directly commenting the command around the "placeholder & empty link" of the original template, and then automatically executing the template.
2.  I proposed,
  - Create an empty link, placeholder, such as [[boo/foo]] path "boo/foo.md", which does not currently exist.
  - Comment in place, [[boo/foo|template(src)]] The pipeline command is followed by the original comment for the link command. It can be read as using the template() function, calling the src file, creating the file "boo/foo.md", writing the template src.md to "boo/foo.md",
- I tried,
  1. Modify the foam code,
  - foam\foam-master\packages\foam-vscode\src\core\services\markdown-link.ts
  - \foam\foam-master\packages\foam-vscode\src\features\commands\create-note.ts
  - Roughly, I know that I should modify "create-note" and "markdown-link", I feel that modifying here may be the easiest, but this is my first time to check the structure of vscode-extension, I don't know where to start,
  - For example, how to insert a new function near "MarkdownLink.createUpdateLinkEdit",
  - src: `type?: "wikilink" | "link"` => dst: `type?: "wikilink" | "link"| wikilink_rich `;
  - implement wikilink_rich,
  - But I didn't finish it, I feel like I need to spend some time starting with a simpler vscode-extension,
- Thanks for your work,

**Comment by red-co** [comment]
I hope this makes it clear.

**Comment by red-co** [comment]
I found a way to run code snippets in vscode markdown. It is more powerful. It can call functions from local environment to generate files or query.

**Comment by icytree** [comment]
> I found a way to run code snippets in vscode markdown. It is more powerful. It can call functions from local environment to generate files or query.

Hi @red-co could you share more info about how you proceeded? I would be interested.
