### ISSUE TITLE
keyboard shortcut: follow-link

### ISSUE THREAD

**Issue by dcsan** [foambubble/foam#139]
do you rely on other plugins for in-place markdown editing?
it would be nice to have a keyboard shortcut to follow a link, not to have to use the mouse.

some other messengers do this with command-enter when a link is selected.

**Comment by dan-iel-lee** [comment]
I believe the link functionality is all through [markdown notes](https://marketplace.visualstudio.com/items?itemName=kortina.vscode-markdown-notes&ssr=false#overview)

For me, `F12` was already assigned to `editor.action.revealDefinition`, but if it isn't, you can assign your own keyboard shortcut it (on mac: Code-> Preferences -> Keyboard Shortcuts).

**Comment by dcsan** [comment]
found it! also saw someone mention that in discord. its vanilla as F12, same as code navigation but I made it alt-enter now.

**Comment by synesthesia** [comment]
And the default binding of Ctrl-K, F12 will open the new page alongside - really useful if you are breaking down a page into smaller concepts...

**Comment by dcsan** [comment]
i've found these shortcuts don't work a lot of the time. I think for any relative links `folder/doc` they don't work
and also get confused when you have names like `some-link`

oddly, just using the mouse and `folllow link` often *will* work. I haven't completely figured out the pattern yet.

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
