### ISSUE TITLE
Add aliases support to Jekyll

### ISSUE THREAD

**Issue by BravishkaSkytano** [foambubble/foam#1405]
### Is your feature request related to a problem? Please describe.

I publish my wiki/garden to Jekyll and I have the habit of using aliases, but they don't render on Jekyll. The error occurs because Kramdown (the Markdown processor Jekyll uses by default) interprets "|" as a column separator for tables, and even if only one shows up it still thinks I'm creating a table.

### Describe the solution you'd like

I would love it if it was possible to add wikilink aliases support to Jekyll using either a gem plugin or a custom plugin. I'm not sure how else this would work, but I'm willing to test if needed.

### Describe alternatives you've considered

For alternatives, I've tried [jekyll-wikirefs plugin](https://github.com/wikibonsai/jekyll-wikirefs) and switching to the CommonMark markdown processor using the [jekyll-commonmark](https://github.com/jekyll/jekyll-commonmark) plugin.

Jekyll-wikirefs conflicts a little with the way Foam handles file linking, especially if the actual filename is `index.md` but the file title is something else. It will throw errors at me for using relative filepaths instead of absolute ones.

Jekyll-commonmark doesn't work at all for some reason, I don't know why, but I'm assuming it's the developers issue and not mine (the plugin hasn't been updated in 4+ years).

**Comment by BravishkaSkytano** [comment]
I was reading the Kramdown docs and I came across [reference links](https://kramdown.gettalong.org/syntax.html#reference-links). Perhaps there's a way to get Foam to use those for Jekyll sites?

**Comment by riccardoferretti** [comment]
Hi @BravishkaSkytano - this feels something that should be raised up with Jenkins, not Foam, for 2 reasons:

1. Foam is agnostic to whatever publishing framework you use. We don't do anything that is specific to Jekyll, nor Gatsby, Astro, or the many other frameworks out there. Basically it's out of scope
2. In this specific instance, given that the `|` is a standard wikilink feature (see [here](https://en.wikipedia.org/wiki/Help:Link#Piped_link)), it really feels like jekyll should add proper support for that. In fact, after a quick search, I found https://github.com/wikibonsai/jekyll-wikirefs which might be what you are looking for.

Regarding reference links, Foam supports them, see [here](https://github.com/foambubble/foam/blob/d7c92f82847462d15c102f9dcb0f8c8485b78419/docs/user/features/link-reference-definitions.md#L4)
