### ISSUE TITLE
0.26.2 hanging on link completion

### ISSUE THREAD

**Issue by dstengle** [foambubble/foam#1410]
### Describe the bug

My keyboard input hangs badly inside wikilinks and suggestions take forever to show up if they ever do.

### Steps to Reproduce the Bug or Issue

Start a wikilink by typing [[ and keyboard input hangs.

### Expected behavior

Keyboard input with link suggestions without delays.

### Operating System Version

Ubuntu 24.04

### Visual Studio Code Version

1.95.2

**Comment by riccardoferretti** [comment]
Thanks for reporting this, can you confirm that it doesn't happen in the previous version?
Would you be able to provide a reproducible example?

**Comment by mburleigh** [comment]
I've been seeing the same slowness since the last release (0.26.2) across multiple computers running Windows 11.

**Comment by riccardoferretti** [comment]
@mburleigh thanks for reporting - same request, can you please give us more detail? What is slow? Do you have a reproducible example?
I am not experiencing the problem, it would be great to have some instructions on how to see the problem

**Comment by mburleigh** [comment]
I'm seeing the same behavior as the OP. Typing in a note and hit "[[<some text>" to insert a wikilink and the input just hangs before the search text even renders.. Previously the <some text> would be used as a search string against the notes in my vault with very little delay and I could choose the note to link from the intellisense.

I just timed it and it took 9 seconds for the intellisense to appear.

**Comment by pderaaij** [comment]
Some questions:

- How large is your note collection?
- Any resources other than markdown files? For example, PDFs?
- Is there any message in the logs? See command: Developer: show logs.

**Comment by mburleigh** [comment]
6633 files in 388 folders
yes - PDFs, various image files, drawio files, even a couple of Polyglot notebooks, a geojson, probably a few others
nothing in the logs that I can see

**Comment by mburleigh** [comment]
tonight I'll clone the repo and see what I can see debugging
it felt like a regression bug to me but could definitely be related to my vault composistion

**Comment by dstengle** [comment]
BTW, if I revert to the previous release the problem goes away.

**Comment by pderaaij** [comment]
Yes. There is something off in the change I made. However, with the current information I can't understand what the problem is. Especially as I can't reproduce the problem.  So, we need a lot of info to research

**Comment by dstengle** [comment]
The TrieMap is variable time based on size for lookup vs hashmap which should be fixed, so probably related to size of knowledge base?

**Comment by dstengle** [comment]
I have ~2500 notes spread across ~600 directories (1 per day).

**Comment by jhhoward481** [comment]
I'm having the same problem described above. 

System:
- Foam: 26.2 (bug does not happen on 26.1)
- macOS Sequoia 15.0.1
- 1700 files across 13 directories (about half are in the same directory as my VSCode workspace; the other half are in a single folder. The rest of the folders have very few notes). Mostly `.md` files, maybe 10 `.jpeg` and 10 `.py` files.
- Notes open in split view, about 50 currently open

Problem:
- Same as above as far as I know. Typing `[[` and then a name of a note does not show possible auto-complete wiki link options. If I start typing a file name (e.g. "abcd"), then backspace, it freezes and I'm unable to edit the wiki link. I can move my cursor, but my keystrokes take a delay of many seconds before registering, sometimes even in another note if I move my cursor to another note before they register. I'm wondering if there's something wrong in how the search is performed or how the files are indexed.

**Comment by pderaaij** [comment]
I've located the source of the problems. (cc @riccardoferretti)

In `link-completion.provideCompletionItems` we iterate over all resources. However, for each resource, we want to retrieve the identifier. We use `FoamWorkspace.getIdentifier()` for this. In this method, we also iterate over each resource to get the identifier. So, in larger collections of notes, this multiplies to a large set of iterations. This causes a delay in operations. This connects with the investigation I did for #1375 yesterday.

Will work on finding a solution for this.

**Comment by mburleigh** [comment]
Cartesian product strikes again! Thanks for proving we're not crazy @pderaaij !

**Comment by pderaaij** [comment]
Sorry about the regression. It was definitely an unexpected side-event. Although it helped me find a more general performance issue which I couldn't find up to now.

**Comment by mburleigh** [comment]
Tricky kind of bug to test for. Says a lot how quickly you were able to track down the root cause though - thanks!
