### ISSUE TITLE
Integrate with neuron

### ISSUE THREAD

**Issue by srid** [foambubble/foam#15]
Have you considered shifting much of the responsibility to [neuron](https://neuron.zettel.page/), and integrate vscode (and other editors) via [LSP](https://github.com/srid/neuron/issues/213)?

**Comment by jevakallio** [comment]
I have not but I will take a look!

**Comment by jcmkk3** [comment]
The first thing that I thought when seeing foam is “I wonder if they’re familiar with Neuron”. It seems like it would be the perfect backend. Neuron has had very active development.

**Comment by RoyiAvital** [comment]
What would Windows users do?
They won't be able to use Foam if it integrates Neuron.

If it will support Windows, it will be great thing to have.

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
