### ISSUE TITLE
Images outside of workspace folder not detected

### ISSUE THREAD

**Issue by hmuny99** [foambubble/foam#153]
If i try to insert an image in a .md file, unless is present in the workspace folder, vscode can't find.
In my case if i write
`![image](/home/hmuny99/Pictures/image.png)`
the editor won't find it, but, if i take the same image and copy it in the workspace folder, even if it's in a subfolder, so 
`image.png`
or
`Pictures/image.png`
the editor seems to recognize it.

![1595580495_grim](https://user-images.githubusercontent.com/28223818/88375138-50f3c780-cd9b-11ea-9c6b-276e7cf27264.png)

![1595580443_grim](https://user-images.githubusercontent.com/28223818/88375115-476a5f80-cd9b-11ea-9983-e27bf7398f85.png)

As you can see the image is present in the "incrimated folder"

**Comment by vitaly-pevgonen** [comment]
There's issue in markdown-all-in-one: https://github.com/yzhang-gh/vscode-markdown/issues/118 , that points to decision of VSCode team:

> Root cause: We now restrict the markdown preview to only loading resources inside the current workspace for security reasons.

https://github.com/microsoft/vscode/issues/45260#issuecomment-371428889
