### ISSUE TITLE
Improve `graph-visualisation`

### ISSUE THREAD

**Issue by MrHeer** [foambubble/foam#154]
see https://github.com/tchayen/markdown-links/issues/36

**Comment by jevakallio** [comment]
Agreed with Tomasz over at https://github.com/tchayen/markdown-links/issues/36 -- we'll be working on improving visualisations over time. Proposals welcome at https://github.com/tchayen/markdown-links/issues/36

Closing this issue for time being, as we're not likely to going to be working on this specific approach.
