### ISSUE TITLE
Graph visualitazion not updated when creating a new file or link

### ISSUE THREAD

**Issue by hmuny99** [foambubble/foam#158]
Unless i refresh the graph visualization by manually closing and reopening it, the graph visualization is not updated when i create a new link or a new file

**Comment by brtbt** [comment]
for me even after manually closing it soesnt work with vague artefact graphs

![image](https://user-images.githubusercontent.com/4089964/88459137-ab327c80-ceb0-11ea-8eb0-cc02f6b13303.png)

**Comment by jevakallio** [comment]
@hmuny99 I've submitted a fix to this in markdown-links (https://github.com/tchayen/markdown-links/pull/34)  and it should be released in Markdown Links 0.7.0 as per their [changelog](https://marketplace.visualstudio.com/items/tchayen.markdown-links/changelog).

Can you ensure you're running Foam for VSCode 0.3.0+ and Markdown Links 0.7.0+ and let us know if the issue persists.

**Comment by jevakallio** [comment]
@brtbt that doesn't seem to be the same issue. If you have a problem with the visualisation, please open a separate issue in [markdown-links](https://github.com/tchayen/markdown-links) -- though we are already working with the author to improve it.

**Comment by hmuny99** [comment]
> @hmuny99 I've submitted a fix to this in markdown-links ([tchayen/markdown-links#34](https://github.com/tchayen/markdown-links/pull/34)) and it should be released in Markdown Links 0.7.0 as per their [changelog](https://marketplace.visualstudio.com/items/tchayen.markdown-links/changelog).
> 
> Can you ensure you're running Foam for VSCode 0.3.0+ and Markdown Links 0.7.0+ and let us know if the issue persists.

Visualization now is fixed.
