### ISSUE TITLE
I created a Foam Menu Bar with buttons that map to various Foam Commands

### ISSUE THREAD

**Issue by nixsee** [foambubble/foam#161]
I used this [existing extension](https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar) that allows you to add commands to the menu bar above the editor window, and mapped with with commands from the Recommended Extensions like New Note, Daily Note, Janitor, and Open Graph, as well as commands like Back, Forward and Zen Mode. I also mapped it to a couple other extensions - one for [Favorites](https://marketplace.visualstudio.com/items?itemName=howardzuo.vscode-favorites), one for [expanding links]( https://marketplace.visualstudio.com/items?itemName=skn0tt.markdown-link-expander).

Here's a gif of me quickly going through it. I didn't demonstrate the Graph, because it doesn't work with my 1200 notes, but it opens. 

![kENkxD3yIY](https://user-images.githubusercontent.com/24255237/88472327-c4e2bc80-cece-11ea-85f4-0655dd4e96b0.gif)

I forked the original extension and added my tweaks and the custom icons to it as well. https://github.com/nixsee/Shortcut-Menu-Bar-VSCode-Extension

If this is something you guys want to incorporate somehow, let me know the best way to do so that will respect/work with the original author (while using my config) as well as be seamless with Foam! It would also be ideal to get rid of the duplicated Preview Button (I use Markdown Preview Enhanced, which I've found to be better than whatever is built into one of the recommended extensions.

**Comment by nixsee** [comment]
I now notice that Markdown Preview Enhanced doesn't allow you to navigate links to other markdown files while in preview mode. So I've disabled it and there's no longer a double icon for previews

**Comment by Travis42** [comment]
Wow.  This is good--I think it goes a long way toward adding polish to the experience by not forcing people to use shortcuts/hotkeys.  With such steps, its more conceivable that a person who doesn't code would use Foam.

**Comment by nixsee** [comment]
Thanks! This kind of thing is getting towards the limits of my coding skills - literally just adding some entries to the json and .js file and a few hours looking for and testing icons (the toolbar is so narrow that the really neat ones don't work at all) - so I sort of straddle the line between the general person (who tend to view me as a wizard) and you actual wizards. 

As such, hopefully someone can explain what needs to be done to get this better integrated with Foam! It makes sense to use the existing extension (presumably the developer will keep improving it) but be able to install the modifications that I have made to it. If it could also automatically install the "recommended extensions" for favorites and link expansion (and any others that might be added), that would be great.

**Comment by nixsee** [comment]
After more thought, I would very much prefer seeing a full-fledged markdown editor (with its own toolbar) be integrated into Foam. I have opened an issue regarding this [here](https://github.com/foambubble/foam/issues/169). 

Still, this is an option that should be relatively quick and easy to integrate as a recipe

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
