### ISSUE TITLE
Error message while creating a new Daily Note

### ISSUE THREAD

**Issue by d2s** [foambubble/foam#164]
When running command `Foam: Open Daily Note` via VS Code command palette (on a Windows 10 machine), getting an error message with the following text:

```txt
Command 'Foam: Open Daily Note' resulted in an error (cannot open c:%5CUsers%5Cusername%5CDocuments%5Cnotes%5C2020-07-26.md. Detail: Unable to resolve resource c:%5CUsers%5Cusername%5CDocuments%5Cnotes%5C2020-07-26.md)
```

Issue seems to be that for some reason, the file path handling isn't working properly on a Windows machine. It is taking `\` character and replacing it with `%5C` urlencoded character code.

File path urlencoded:

```txt
c:%5CUsers%5Cusername%5CDocuments%5Cnotes%5C2020-07-26.md
```

Working path would be (in this example):

```txt
c:\Users\username\Documents\notes\2020-07-26.md
```

Haven't looked at the Foam code to figure out what could be done to fix this. If someone who has a Windows machine could check if they get the same error message while trying to use the feature, it could help to verify if this is happening on a multiple computers.

**Edit:** File `2020-07-26.md` got created, but it couldn't get opened automatically. So part of the code works.

_Related to:_

- [Add 'Open Daily Note' Command · Issue #54 · foambubble/foam](https://github.com/foambubble/foam/issues/54)
- [Add open daily note base feature by francishamel · Pull Request #79 · foambubble/foam](https://github.com/foambubble/foam/pull/79)

**Comment by jevakallio** [comment]
@d2s thanks for reporting this! It's already been reported as https://github.com/foambubble/foam/issues/160, so I'm going to close this as a duplicate and track the issue there.

Looks like a potential Windows issue. I don't have a Windows box available right now, but let me look through the source code and see if I can see anything suspicious!
