### ISSUE TITLE
Recipe - install without git / github

### ISSUE THREAD

**Issue by synesthesia** [foambubble/foam#165]
At least one contact has said to me they were deterred from trying foam because of git / github.

Proposing a simple recipe that covers 

* download and unpack template as zip
* optionally use cloud sync such as dropbox to backup notes

Will open a PR with a roadmap stub linked back here for any discussion

**Comment by jevakallio** [comment]
IMO the first part is already covered in Getting Started, but if you want to write a recipe for this, I'm happy to have one! 

Right now as project maintainer I want to focus on Foam-specific improvements, and not on telling people how to unzip a file or -- I figure a user at that level might not have a good time with Foam at this early stage, and would likely to have a better experience as a later adopter.

**Comment by jevakallio** [comment]
Update: I added the "Download as zip" link to the Getting Started guide:
https://github.com/foambubble/foam/commit/16a0e94d3f2e2edd80004491781e5130339cd269

**Comment by synesthesia** [comment]
Ok
