### ISSUE TITLE
Setting for Link Reference Definitions doesn't seem to do anything. Also, various other issues with links and previews

### ISSUE THREAD

**Issue by nixsee** [foambubble/foam#166]
Heres a couple videos I made with using the with and without extensions setting - it doesn't seem to do anything. I tested with every way of entering a link and it does the same thing, always creating a .md extension. 

With both, when I use [[ ]] to create a link, whether I press enter or click on the autocompleted result, it creates a link with *.md. And when there is .md, the link definitions don't work. The links still work to Ctrl+Click, but they don't work with Markdown Preview Enhanced (no links work with this). Conversely, in the other preview tool, only extension-free links work. Also, there's an issue when you create a new in-line link with [[pagename.md]], when you hover click it creates a page but the link can't be followed.

Hopefully this is clear in these gifs. I'm happy to try to better explain if theres any questions. (if you're seeing some weird grid pattern on the gifs, zoom in - no idea why that's happening on Github).

Note that this is with a completely fresh workspace that was copied from the Foam Template.

without .md Extensions:
![noext](https://user-images.githubusercontent.com/24255237/88485935-656cc700-cf37-11ea-9774-168f211ab0ee.gif)

with .md extensions:
![withext](https://user-images.githubusercontent.com/24255237/88485885-e37c9e00-cf36-11ea-8aef-1b8d365e414c.gif)

**Comment by nixsee** [comment]
Ok, I'm stupid. The purpose of that setting is to add .md to the Link Reference Definitions at the bottom, not the links in the body of the note. 

As an end-user, whether or not you need to have the link definitions at the bottom, and how they're formatted is not particularly important to me. What is important to me is that the in-line links have the same formatting, whether they're generated by autocompletion, ctrl+hover, or ctrl+click. 

But as it stands, as can be seen in the gifs, autocompleted links with .md are clickable but don't generate Link Definitions. They also don't work in Preview Mode. And links to uncreated pages that have .md at the end get created, but the link doesn't work at all. 

In an ideal world, there would be no Link Definitions at the bottom, Markdown Preview Enhanced become the main Previewer, and there would be a standard in-line link format that is compatible with web publishing. I know you guys are in deep thought and conversation about how to handle links (I assume this is the most fundamental feature of Foam), so I'll just leave this for you to consider if you weren't already aware of any of this yet!

**Comment by nixsee** [comment]
Part of this issue is now resolved by changing the setting "Vscode Markdown Notes: Note Completion Convention" to "noExtension". Now autocompleted links do not have the troublesome ".md" within the brackets, which allows Link Reference Definitions to be created

Until this setting can be set to "noExtension" by default, I'll leave this issue open for other to find.

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
