### ISSUE TITLE
Consider integrating Toast UI Editor (WYSIWYG and MUCH more) into Foam 

### ISSUE THREAD

**Issue by nixsee** [foambubble/foam#169]
[UNotes](https://marketplace.visualstudio.com/items?itemName=ryanmcalister.Unotes) and [Markdown Live](https://marketplace.visualstudio.com/items?itemName=keshan.markdown-live) VS Code Extensions are built off of this heavily developed tool - [Toast UI Editor](https://ui.toast.com/tui-editor/) (which is a part of its own broader suite of tools). 

It has WYSIWYG, a toolbar that sits below the titlebar (so it doesn't rob the precious real estate for file tabs), various plugins, etc...

It has fantastic [documentation](https://nhn.github.io/tui.editor/latest/ToastUIEditor) and it seems like it would perfectly fit Foam's ethos of gluing together best-in-class tools. All that would be needed is to port some of the linking, TOC, etc... functionality from Markdown All in One, which it seems like you guys are already overhauling anyway. 

I shared on Discord, but wanted to make sure it didn't get missed and lost forever there so created this issue.

Here's their Github page as well, which seems like a more detailed overview of the features. https://github.com/nhn/tui.editor

**Comment by VKondakoff** [comment]
To be honest, I really want to see WYSIWYM (Typora-like) editor in Foam, not WYSIWYG-one.

**Comment by nixsee** [comment]
@VKondakoff If you're referring to how Typora allows you to enter markdown syntax and then it automatically converts to a formatted version in real-time, so that there's only one "view", yes that is fantastic. But I see two problems with it:

1. Unless you know of an open-source tool for it, I suspect it is a very large job to build and using Toast would be a way to get similar functionality while saving developer time for other "core" features
1. Toast seems to more closely align with Foam's principles of people a tool that is inclusive of all sorts of people. Given that you can edit in both markdown or WYSIWYG mode, it satisfies all people. 

Here's a gif from their documentation showing how it works (which is basically a considerably slicker version of what Foam already has)

![image](https://user-images.githubusercontent.com/24255237/88539861-343fd580-cfcf-11ea-97f1-efd12262cd25.png)

**Comment by nixsee** [comment]
Here's one open-source WYSIWYM editor https://prosemirror.net/

And a couple other WYSIWYG ones for reference.
https://pandao.github.io/editor.md/en.html
https://github.com/tylingsoft/markdown-plus

I still prefer Toast for all the reasons I shared above and in the [discord](https://discordapp.com/channels/729975036148056075/729978910363746315/737134108760866847)

**Comment by VKondakoff** [comment]
This is an interesting plugin: [Crossnote](https://marketplace.visualstudio.com/items?itemName=shd101wyy.crossnote).
WYSIWYM markdown editing in VSCode. Never thought it was possible:

![](https://i.loli.net/2020/04/12/lTMIFCuUcyeSGjV.gif)

> editor [0xGG/VickyMD](https://github.com/0xGG/VickyMD) was built on top of [laobubu/HyperMD](https://github.com/laobubu/HyperMD/)

**Comment by SanketDG** [comment]
I am sort of looking for feedback here, I would like to know what advantages are to be gained on implementing something like this on top of Foam. I absolutely understand that they make Foam more accessible to a larger audience, but other than that, this is all I could figure out:

WYSIWYG - More control and options for styling 
WYSIWYM - Aesthetics and accessibility (without the preview)

I am sort of on the train that a standard (to be taken loosely) like Markdown is the whole reason why note-taking becomes relatively easy, compared to integrating HTML which takes away the simplicity and uniformity. Also, the Markdown all-in-one provides a whole range of shortcuts for operations where adding/removing/updating text would be too tedious.

I would really love to see WYSIWYM in VSCode, but sadly it's not possible, and implementing something like CrossNote takes away all the flexibility of using my editor for note taking.

**Comment by VKondakoff** [comment]
@SanketDG: not sure I understand you correctly.

> WYSIWYG - More control and options for styling
> WYSIWYM - Aesthetics and accessibility (without the preview)

Both system offers the same set of options for styling. The difference is that WYSIWYG completely hides markdown tags and you style your note using keyboard hotkeys and available buttons/menu items. WYSIWYM, on the other hand, act exactly as an ordinary markdown editor when you edit text, but hides markdown tags when you exit the current line or markdown code block.

Both of them has advantage of making the preview pane/window redundant. 

So, for me personally, WYSIWYM is preferred system, because it acts like a standard markdown editor when editing text, but still does not require the preview window.

Are my explanations helpful somehow?

**Comment by SanketDG** [comment]
> Both system offers the same set of options for styling. The difference is that WYSIWYG completely hides markdown tags and you style your note using keyboard hotkeys and available buttons/menu items. WYSIWYM, on the other hand, act exactly as an ordinary markdown editor when you edit text, but hides markdown tags when you exit the current line or markdown code block.

Right, in retrospect, I see that I could I have used more words to explain what I wanted to convey.

> So, for me personally, WYSIWYM is preferred system, because it acts like a standard markdown editor when editing text, but still does not require the preview window.

I would want something like this too, it just seems not possible right now natively within VSCode.

**Comment by nixsee** [comment]
@VKondakoff Crossnote seems pretty neat from my quick test-drive. I'm not sure how I feel about it fully taking over the folder panel etc.., but I like the WYSIWYM features and it seems to play nicely with the existing links, graph etc..., the links work (which doesn't current apply to Markdown Preview Enhanced, which I vastly prefer over the built-in Previewer). 

As I mentioned in the [#markdown-all-in-one channel](https://discordapp.com/channels/729975036148056075/730181839263629343/737396189347053678), it seems to me that the solution here is not to favor one editor over another, but to make the linking capabilities compatible with whichever editor someone wants. If they want Crossnote or Unotes or Toast or Markdown All in One, go for it - Foam will handle the links in the background so that they talk to the graph, backlinks pane/functionality, etc.. I have no thoughts on how that could be done though.

What do you think?

**Comment by VKondakoff** [comment]
Let's see after the devs investigate the LSP further...

**Comment by nixsee** [comment]
Indeed - I'm looking forward to the upcoming RFCs on all the big topics. I'm certainly satisfied with my setup for now, so I think I'll take this as a cue to check out for a few days and get to work actually writing!

**Comment by BenMatheja** [comment]
@nixsee: Can you share the setup you finally ended up with? I'm currently jumping around between beautiful-editing with Typora (WYSIWYM) and creating the necessary foam links afterwards within VSCode.

**Comment by nahuel** [comment]
There is also the MIT Licensed and also WYSIWYM MarkText: https://github.com/marktext/marktext

**Comment by mk0a1a** [comment]
Any updates to this? Obsidian has live preview editing and it makes it a breeze to work with. Just like what @sia1984 mentioned, having just one tab open for editing gives more screen space and just an overall better experience.

**Comment by ryanwwest** [comment]
As cool as this plugin is, unfortunately the lack of WYSIWYG is a dealbreaker for me. Hopefully foam or another plugin will at some point reconsider so some of us can use VS Code exclusively instead of Obsidian!
