### ISSUE TITLE
Graph Issues with Titles and [[wiki-links]]

### ISSUE THREAD

**Issue by Ham5andw1ch** [foambubble/foam#17]
I have been using Obsidian for almost 2 months and decided to give Foam a try. When I opened up my existing repo, I noticed two major things with the graph-view.

1. Markdown files do not appear in the graph unless they have a # Title
2. Even though I am in version 0.6.0 of Markdown Links, [[wiki-links]] do not show up.

As a result, the graph that looks like this in Obsidian
![image](https://user-images.githubusercontent.com/7903566/85957109-3f600100-b950-11ea-84ea-c8f5c7ca7a70.png)

looks like this in Foam
![image](https://user-images.githubusercontent.com/7903566/85957113-45ee7880-b950-11ea-81d6-517dfb6e23c3.png)

The VSCode Markdown Notes extension handles my knowledge-base just fine, it is only the Markdown Links extension that seems to be not working. If needed, I can post the issue there as well.

**Comment by jevakallio** [comment]
Thanks for the issue report! 

> Markdown files do not appear in the graph unless they have a # Title

This is known, and I was planning on keeping this a fixed constraint for now, as having some sort of common contract helps write tools on top of text files. How does Obsidian handle file titles?

> Even though I am in version 0.6.0 of Markdown Links, [[wiki-links]] do not show up.

Odd, they do for me. I wonder if this is because of the missing file titles as well? AFAIK Markdown Links wants those to even index the files, but I can't remember for sure.

What do your file names look like? Do the link references get generated at the end of the file?

> It is only the Markdown Links extension that seems to be not working. If needed, I can post the issue there as well.

I recommend opening an issue over at [Markdown Links repo](https://github.com/tchayen/markdown-links) as well to see what @tchayen thinks about these constraints. I'm sure he would be happy to improve his package, and even happier to accept it if the contributions came in form of PRs 😉 

Let's keep this open at Foam as well, the issue might be on our end, or we might solve it outside of Markdown Links.

**Comment by Ham5andw1ch** [comment]
That happened to be the case. After updating the references, it updated the graph. Happened to be user error on my end. As to how Obsidian handles it, as opposed to linking to headings, you link to the actual .md file. So if my file was `Notes.md`, I would link to it with `[[Notes]]`. It will handle the rest, and on name clash, full path is used to show which file in particular is being linked to. The VS Code Markdown Notes plugin handles this fine, but I think the Markdown Links plugin does not at the moment support this functionality, requiring wiki-links to be accounted for on Foam's side with links at the bottom.

I don't think this is a super big deal unless interoperability is something you care about later down the road, but seeing as one plugin in the lineup already handles this functionality, I think it is just down to Markdown Links or an alternative handling it similarly.

**Comment by jevakallio** [comment]
> An alternative could also be making a command that recursively digs through the folder structure and updates the references (unless of course, I am blind and it already has this functionality).

@Ham5andw1ch this is definitely on the roadmap as part of migration tooling. It doesn't exist yet, but definitely should, probably in [foam-workspace-manager](https://github.com/foambubble/foam-workspace-manager). If you're interested in collaborating on it, I can write up more thoughts on Foam-specific constraints

**Comment by tchayen** [comment]
Hi! I started the Markdown Links project with focus on the file explorer aspect but requirement of the title is purely artificial and I think it might be removed.

When it comes to discovering links, there are several standards for doing that in community and IIRC Markdown Links doesn't support this one at the moment, but I am planning to improve it.

**Comment by Ham5andw1ch** [comment]
@tchayen thanks for the reply, and I appreciate the work! That is something I was noticing as well. Markdown is not really a standard in of itself, so the features people choose to support and the implementations they go with all differ in subtle ways. I assume as the whole Markdown linked-notes concept takes off, several programs will eventually come out on top and provide some kind of standard for other apps to support (should cross-compatibility be wanted feature later on).

**Comment by riccardoferretti** [comment]
This has been fixed as part of #290
