### ISSUE TITLE
Two 'Backlinks' panes right after install

### ISSUE THREAD

**Issue by VKondakoff** [foambubble/foam#171]
Hello!

There is two 'Backlinks' panes right after initial Foam install. Why is this?

<img width="599" alt="Снимок экрана 2020-07-27 в 13 31 10" src="https://user-images.githubusercontent.com/230824/88532725-c23ab100-d00d-11ea-96f8-8ff4fb94eeeb.png">

macOS Big Sur
VSCode: 1.47.2
Foam: 0.3.1

**Comment by VKondakoff** [comment]
Looks like these are from two different plugins:

<img width="533" alt="Снимок экрана 2020-07-27 в 22 34 36" src="https://user-images.githubusercontent.com/230824/88583839-76155e00-d059-11ea-929b-45fc42e5a1f2.png">

'Markdown Memo' is not included in the Foam, right?

**Comment by jevakallio** [comment]
@VKondakoff nope, that's not a Foam-installed extension, sounds like it's part of [vscode-memo](https://github.com/svsool/vscode-memo).

Markdown Notes is what we use, but you're free to use either that works for you -- just be aware that the interaction between vscode-memo and Foam is not tested, and some things might conflict!

**Comment by vepain** [comment]
Hello all,

I discovered this closed issue and now things have changed:
![Capture d’écran de 2022-02-11 14-08-31](https://user-images.githubusercontent.com/32708963/153597628-65b4b890-d25c-4b0b-9d88-06ed8e2e2605.png)

Foam is using Markdown Notes extension, and both propose Backlinks left panel explorer

**Comment by riccardoferretti** [comment]
Foam no longer uses the markdown notes extension
