### ISSUE TITLE
foam-vscode: Janitor command adds the heading above the frontmatter

### ISSUE THREAD

**Issue by anku255** [foambubble/foam#174]
**Actual:**  The `Run: Janitor (Experimental)` command adds the heading above the frontmatter.

**Expected:** The generated headings should be below the frontmatter.

**Demo GIF:**

![](https://i.imgur.com/9kLGE0X.gif)

**Comment by jevakallio** [comment]
Foam should support all three styles of Headings

Regular Markdown H1
```
# Heading
```

Alternate Markdown H1
```
Heading
=========
```

YAML Frontmatter
```
---
title: Heading
---
```

Right now we don't support Frontmatter, but I'm happy to add it -- should be very easy. We'll just need to add it to Markdown Links (and Markdown Notes?) as well.

If someone wants to pick this up, as an implementation note, I'd like to have the entire frontmatter metadata added to the NoteGraph node, and the "title" attribute extracted to the Note.title field. Ff the document title is provided in multiple formats, we should choose the Frontmatter over the display heading.

**Comment by jasonwilliams** [comment]
It’s worth thinking about what happens if you have both the h1 and the title attribute (I’ve seen this arise in some cases). We had a discussion on GitJournal that the h1 should have priority

**Comment by jevakallio** [comment]
@jasonwilliams I just mentioned the same issue above, but my choice would be to prefer the frontmatter title. My rationale is that you may want to have a different display title in the page itself, while keeping the "metadata title" stable for all other documents that refer to it.

**Comment by anku255** [comment]
@jevakallio I have self-assigned this. The expected behaviour now becomes:

The Janitor should not generate heading if any one of (frontmatter, #, and ===) heading exist.

Also, it seems like Markdown Notes works without the heading. We just need to make changes to `Markdown Links` extension.


The deliverables for this PR becomes:

- [ ] Add frontmatter metadata to the NoteGraph node.
- [ ] Parse heading from the frontmatter and give it preference over the `#` or `=` heading. 
- [ ] If the frontmatter exist but the title doesn't then generate the heading below the frontmatter.

**Comment by jevakallio** [comment]
@anku255 LGTM!
