### ISSUE TITLE
Support for Query? 

### ISSUE THREAD

**Issue by Awannaphasch2016** [foambubble/foam#175]
This is a feature request. 
I really want to migrate my data from roam research to foam, but query features is the big part of my note taking style.
I refer to Query feature from roam research. (I believe that Query is under used. )

I attached link that query can be used for
1. https://www.youtube.com/watch?v=LJZBGJOzhUY&t=494s ( basic usecase of query)
2.  https://www.youtube.com/watch?v=D8lGWF1N0PU&t=66s (How to create an Asana-style 'My Tasks' view in Roam Research)
3. https://www.youtube.com/watch?v=bfNdCWs3eGg&t=191s ( using query to filter content base on context)

I have shown a quick demonstration of the use case below that I personally use for my notes below.  I use this note taking system with every thing that I read, but it is the most useful when using taking notes from research paper.

https://drive.google.com/file/d/1z62KIEWUHgJ7k0suJGU1q-ODmElyIORT/view?usp=sharing

**Comment by ScientificX** [comment]
The google drive file linked seems to be non publicly shared ? 
@Awannaphasch2016

**Comment by Awannaphasch2016** [comment]
I have shared it publicly now. Thank you for pointing that out. Whenver there is an update on this, I am willing to help contribute to the codebase as well.

**Comment by riccardoferretti** [comment]
Thanks for sharing this back in the days, as you can imagine from the lack of progress this has not been a priority for Foam (it's a bit of an advanced feature, possibly beyond Foam's scope), so I am closing the issue

**Comment by charudatta10** [comment]
Can we port logseq query features to foam
