### ISSUE TITLE
Prioritizing Unlinked References

### ISSUE THREAD

**Issue by kkukshtel** [foambubble/foam#18]
I was trying to find a place to properly do this, but just wanted to say that [supporting unlinked references ](https://foambubble.github.io/foam/unlinked-references)is an essential feature. This is largely the benefit of something like Roam, where I can reference an idea, reference it again on the same page and get autocomplete for that page, without having to stop my flow by navigating into the linked page and out so that a page for it is created.

**Comment by jevakallio** [comment]
Thanks for the feedback! I definitely want to improve this.

There's a bit more to unlinked references than just the use case you've described above, but as an imperfect workaround you can do this now:

1. Type `[[foo]]`
2. Cmd+Click the `[[foo]]` link to create the document as a stub to fill out later
3. Ctrl+Tab back to the file you were working on
4. When you now type `[[f...`, it should auto complete

Hope this helps!

**Comment by jevakallio** [comment]
This issue is tracked on the [roadmap](https://foambubble.github.io/foam/roadmap) but requires further research. Expect to get to this soon-ish.

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
