### ISSUE TITLE
Add standards/conventions for spelling in Contribution Guide

### ISSUE THREAD

**Issue by jsjoeio** [foambubble/foam#183]
@ShaunaGordon brought up a great question:
Do we have any standards/conventions on British vs American English? That's the only other thing I see.

From @jevakallio in same discussion
> We absolutely do not have a formal guidance on US/UK English. The documentation, as written by me, is mainly British English, but I feel the internet and programming communities in particular are more accustomed to American English, so at some point we might elect to do a big refactor.

> Let me noodle on this. For now, I'll keep this as UK English to conform to existing standards

For now, we may want to add a short line to the [Contribution Guide](https://foambubble.github.io/foam/contribution-guide) explaining that we should stick to UK English. 

Related: 
- #179

**Comment by Barabazs** [comment]
This could be "enforced" with the help of github actions. Here is an example using cspell: https://seankilleen.com/2021/01/adding-spell-checking-to-my-blogs-build-process-with-github-actions-and-cspell/

**Comment by daniel-vera-g** [comment]
> This could be "enforced" with the help of github actions. Here is an example using cspell: https://seankilleen.com/2021/01/adding-spell-checking-to-my-blogs-build-process-with-github-actions-and-cspell/

Yeah, I've got nearly the same working on a private project.

After fixing some markdown errors in the docs recently I wanted to make a PR to lint the docs using gh actions and markdownlint. Will keep this in mind and also add it to the pipeline 👍
