### ISSUE TITLE
Create Zettelkasten-style filenames

### ISSUE THREAD

**Issue by ituri** [foambubble/foam#184]
Hi! 

I'm a avid user of [The Archive](https://zettelkasten.de/the-archive/) but foam seems to be such an intruiging app that I'm currently thinking about switching to foam. There's one thing I'd like to keep: The way that The Archive creates new notes. All new notes have timestamp IDs so a note created on `2014-02-26 9:39a.m.` is saved as 201402260939.md. This way, the links between the notes don't break when I change the title. 
Is there already such a feature for roam? Or are there plans to include this in future version of foam?

Thanks for this awesome piece of software!

**Comment by dshemetov** [comment]
The file format is pretty specific, but subject to change according to [this document](https://foambubble.github.io/foam/foam-file-format). To me, this seems like a downstream concern of [design specs](https://github.com/foambubble/rfcs/pull/3) that are still being drafted for a much broader picture of the software.

**Comment by ingalless** [comment]
You may also try taking a look at daily note settings to see if it fits your needs?

Check it out here! https://foambubble.github.io/foam/daily-notes#configuration

**Comment by ituri** [comment]
You're right. I've just gotten into Roam and realized that I don't really need the unique IDs since I rarely change titles of a note. Thanks for your help!
