### ISSUE TITLE
Feature request: Paste images from clipboard to markdown

### ISSUE THREAD

**Issue by zomars** [foambubble/foam#185]
Is it possible? I think this would be greatly enhance de note-taking ability of foam.

**Comment by Klaudioz** [comment]
You can use the extension [Paste Image](https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image)

**Comment by jevakallio** [comment]
Yup, it's already in Recipes
https://foambubble.github.io/foam/recipes#write

**Comment by zomars** [comment]
Thank you! 🙏
