### ISSUE TITLE
Chinese Foam Document

### ISSUE THREAD

**Issue by xiaoland** [foambubble/foam#188]
Hello, I am currently Chineseizing the Foam document.
But there are too few people who know this document, so may I have a request here: Can you add a link to the Chinese document in your GitHub pages, thank you.
 I hope that more Chinese users can participate in the development of Foam.
**The link to the Foam Chinese Doucment: https://xiaoland.github.io/Foam-Chinese-Document/**

**Comment by Jackiexiao** [comment]
Foam的中文交流QQ群：610013037，欢迎加入

**Comment by riccardoferretti** [comment]
Closing for lack of interest in helping so far, my inability to either do it nor support it on ongoing basis
