### ISSUE TITLE
Idea: I like Foam so far, but I find the current documentation a bit confusing

### ISSUE THREAD

**Issue by WizardOfAus** [foambubble/foam#19]
I like Foam so far, but I find the current documentation on how to contribute a bit confusing to follow structurally. But I haven't used Roam yet so maybe I am not sure (https://foambubble.github.io/foam/recipes) if these can be simplifed to get started quicker?

**Comment by jevakallio** [comment]
@WizardOfAus thanks for feedback! I agree that the starter experience is a bit rough around the edges right now. This project is less than a week old and until yesterday I've been the only developer on it, so it's no wonder we're discovering all kinds of edge cases left and right!

My idea to scale this process as per the [Contribution Guide](https://foambubble.github.io/foam/contribution-guide) was to encourage users to improve upon the few stub [Recipes](https://foambubble.github.io/foam/recipes) in there.

Maybe we first need a "how to write a recipe" recipe :)

I'd be happy to take advice and feedback around what in particular can be improved!

**Comment by jevakallio** [comment]
Docs have been improved a lot since launch, so given no more specific feedback, will close now. If you have more specific requests, feel free to open new issues.
