### ISSUE TITLE
Support Weekly Notes Natively

### ISSUE THREAD

**Issue by kneely** [foambubble/foam#196]
First of all thank you for your hard work. This package is just what I was looking for to capture my notes.

This is a feature request. I would like to see a shortcut for creating a weekly note just like the daily note. In my workflow and a lot of other workflows as well supporting a weekly review note would be extremely beneficial. 

I plan to look into this as well. Hopefully if I get some time this weekend I will code it out and submit a pull request. 

Just wanted to plug this in here for visibility. If anyone would like to see this feature please reply and let me know.

**Comment by vitaly-pevgonen** [comment]
If you only need weekly notes and not daily notes, with following parameters:

```json
  "foam.openDailyNote.filenameFormat": "'week-'W",
  "foam.openDailyNote.titleFormat": "'Week 'W"
```

in workspace's .vscode/settings.json, it works right now. Feature name in menu is still "Open Daily note", but it would create file with name "week-<ISO week number>.md" with heading "Week <ISO week number>".

**Comment by jevakallio** [comment]
@kneely I'm not wild about adding a "weekly note", as it begs the question: what about "monthly note", "quarterly note", etc. If this issue gets more votes, I'm happy to consider it.

Could you explain to me how do you use a weekly review note?
- What goes into it?
- How frequently do you access it?
- Do you look back at old weeks or are they scrapped?

@vitaly-pevgonen great tip!

Others, if you'd like to see this feature implemented, please hit 👍 on the original issue to vote for it!

**Comment by kneely** [comment]
Thank you both for your replies. 

@vitaly-pevgonen are you using this in conjunction with Daily Notes as well. If that's the case a little renaming of Daily Notes and changing of some logic would work well. 

@jevakallio I am thinking about the whole package. ("monthly note", "quarterly note", etc)

- I work in IT and support many customers. So logs of what has happened that day. Backlinks to different issues. It's basically a way for me to keep track of what I have done, how much time I have spent doing those things, fixes for issues that have come up, and tasks that are in the future.

- After I create the weekly note I access it maybe once or twice in the following weeks. Then I create a Monthly but since that happens once a month it does not slow down my workflow. 

- Old weeks are kept and archived every 6 months

So far I am thinking just a weekly review at first. I would like to see it become a type of boilerplate. Basically keep the daily out of the box but have a custom one that can be renamed to anything and live concurrently with Daily, Weekly, Quarterly. This would give users the freedom to create them as they see fit without having to add more work to the devs.

I am happy to take on the work myself and bring this feature to this product. Let me know what you think.

**Comment by vitaly-pevgonen** [comment]
> are you using this in conjunction with Daily Notes as well

Currently I'm using it for daily notes only, but will check in couple weeks if it would make sense for me to switch to weekly notes only. So settings cover my current and possible future use cases.

Your workflow looks different from my. What is purpose of concurrent daily and weekly notes? How do you decide what goes to daily and what goes to weekly note?

**Comment by kneely** [comment]
Weekly notes are a review of highlights that happened during the week. I set aside 30-60 minutes every Friday to review the daily notes and pick out parts for the weekly. Then I do the same thing with monthly notes except I review the weekly.

**Comment by thomaskoppelaar** [comment]
@kneely I've quickly put together an [extension](https://marketplace.visualstudio.com/items?itemName=thomaskoppelaar.repeating-notes) that would allow you to take daily/weekly/monthly notes - its quite rough around the edges, but you could decide to try this out.

**Comment by kneely** [comment]
@thomaskoppelaar  Thank you for your suggestion. My vision was a little more interchangeable. Please take a look at the extension I have put together. [note-macros](https://github.com/kneely/note-macros)

@jevakallio This issue is now void.
