### ISSUE TITLE
Azure DevOps wiki recipe

### ISSUE THREAD

**Issue by Klaudioz** [foambubble/foam#197]
I pushed some changes to my GitHub repository and I'd like to update the wiki. How can I do that?
I checked the entire Azure DevOps UI and I couldn't find it.

**Comment by vitaly-pevgonen** [comment]
Hello,

When the repository is published as wiki, wiki is updated automatically when you push changes to the repo.

**Comment by Klaudioz** [comment]
@vitaly-pevgonen Thanks for your answer. I followed all the steps of the recipe and the wiki is having a very un-updated version of my repository.

**Comment by vitaly-pevgonen** [comment]
So we've have discussion in Discord, and problem was with remote not pointing to Azure DevOps repo but to github.

**Comment by Klaudioz** [comment]
I've created a PR to add this information. Thanks for your help @vitaly-pevgonen
