### ISSUE TITLE
Can we organize our files in folder ?

### ISSUE THREAD

**Issue by Dasein-Yang** [foambubble/foam#198]
Now we add markdown by [[todo]] and todo.md will be created in the current directory. But a number of files will be listed in the main folder and not organized enough. So can we category the  items in folder like when we type [[read:todo]] and todo.md will be created under read subfolder?

**Comment by jevakallio** [comment]
@Dasein-Yang creating a file in a different directory is not supported yet, but you can either:

1. Type [[todo]], click through to it to create todo.md in the root, and then move the file to read/todo.md. When you save the file that contains the [[todo]] link, it will update the definition at the bottom of the file to automatically point to read/todo.md.
2. Manually create a file in read/todo.md, and link to it using just [[todo]].

In both cases, you can only have one file called todo.md anywhere in the repository, so you can't have read/todo.md and watch/todo.md.

We will be eventually supporting a [[read/todo]] and [[watch/todo]] syntax. Working on it here:
https://github.com/foambubble/rfcs/pull/3
