### ISSUE TITLE
Ability to Create Custom Actions similar to openDailyNote

### ISSUE THREAD

**Issue by PhilFuster** [foambubble/foam#199]
This is a feature request for something along the lines of openDailyNote, but custom.

It would have the following abilities:
1. Designate the directory to place these newly created notes in
2. Designate the format of the file name
3. Designate a template/snippet to use
4. Be able to designate the configuration from settings.json 

This thought came to me when trying to create a time sheet for work so I can track what I did during the day, the time I spent on it, and link to the md file for that specific task. I figured I would be doing this every day and wanted to see if there was a way to create a shortcut to create a new file, insert a template and put it in a directory. openDailyNotes is very very close to that.

I have not looked at the source code for FOAM, nor have I contributed to VS Code so as to how it would be implemented I am unsure at the moment.

Thank you very much to all contributors of FOAM. FOAM is an amazing tool with a very bright future. I hope to one day contribute more than just a feature request.

Thank you for your time,

Philip Fuster

**Comment by jevakallio** [comment]
Hi @PhilFuster! User @kneely has implemented this in a third-party extension over here: https://github.com/kneely/note-macros -- check it out!

At the time, I think this feature is best implemented in a third-party extension rather than in Foam core, so closing this as wontfix for now!
