### ISSUE TITLE
"link reference" section gets more lines down the page on every save, and can overwrite last line of content

### ISSUE THREAD

**Issue by eloff** [foambubble/foam#20]
There seem to be 3 separate issues here:

1. Every time the file saves, another line break get added between the end of the content and the "Link references" section. I have auto-save enabled in vs-code, so this is particularly obvious to me.
2. If I delete all of these empty lines, Link references can be saved over the last line of content, deleting it. If i put the cursor on the last line and backspace until I reach the last line of content (i.e. no trailing line-break) then this happens.
3. Using undo also seems to race with auto-save and adding the link references section in such a way that you have to undo faster than link references is being added and the file is getting auto-saved, otherwise you just loop forever without actually undoing the  "real" edits.

I'm using Ubuntu 20.04. These are hopefully trivially reproducible, but if not I'll help you figure out how to reproduce them.

**Comment by itisbean** [comment]
met the save problem

**Comment by jevakallio** [comment]
Thanks! I'm aware of this issue, tracking it at foam-vscode here:
https://github.com/foambubble/foam-vscode/issues/10

I originally broke this fixing another bug for Windows users. Aiming to fix this today as soon as I get a Windows VM running and can make sure I don't break other platforms :)

**Comment by jevakallio** [comment]
@eloff @itisbean this is now fixed in [foam-vscode@0..1.5](https://github.com/foambubble/foam-vscode/releases/tag/v0.1.5) and released to the Marketplace:

https://marketplace.visualstudio.com/items?itemName=foam.foam-vscode

Remember to reload VS Code after upgrading the extension.

Closing issue as solved, please let me know if it's not fixed.
