### ISSUE TITLE
New file is created by hoovering over wiki link

### ISSUE THREAD

**Issue by VKondakoff** [foambubble/foam#211]
New file is created by *Cmd+hoovering* over wiki link.
Here is [a video](https://www.dropbox.com/s/arzvjilpyi8lgvx/%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D1%8C%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202020-08-05%20%D0%B2%2015.25.15.mov?dl=0):
- created new note
- added a wiki link to a non-existing file 'something'
- Cmd-hovering over wiki link: new note 'something.md' was created and the links were added to the bottom of the note

I'm pretty sure this is wrong: new notes should be created only on *clicking* on a wiki link. There should be some kind of general pop-up `This file is not created yet. Click the link to create <filename.md>` when *hovering* wiki link to a non-existing files.

MacOS Big Sur
VScode Version: 1.47.3
Foam 0.3.1

**Comment by thomaskoppelaar** [comment]
@VKondakoff its best to open an issue on this in the [markdown-notes repository](https://github.com/kortina/vscode-markdown-notes/issues), or check if it exists already

**Comment by VKondakoff** [comment]
@thomaskoppelaar: thanks for a suggestion!

**Comment by kthy** [comment]
I actually quite like the create-by-hover functionality.

([Obligatory XKCD](https://xkcd.com/1172/))

**Comment by jevakallio** [comment]
@kthy 😆  I also quite like this feature. 

@VKondakoff thank you for reporting. Like you've identified in #213, the line of support for different extensions is a little unclear at the moment, and we'd benefit from making it clearer.

For now, there's nothing for Foam to do to fix this issue, so closing it for housekeeping.
