### ISSUE TITLE
Markdown links: (almost) empty graph view after loading files

### ISSUE THREAD

**Issue by VKondakoff** [foambubble/foam#212]
Hello!

I just copied my Obsidian notes to a fresh Foam folder (workspace), restarted VSCode and loaded Foam workspace. And here is what I see after issuing a command `Markdown Links: Show Graph`:

<img width="709" alt="Снимок экрана 2020-08-05 в 15 39 36" src="https://user-images.githubusercontent.com/230824/89414033-6b7e5700-d732-11ea-95e0-faa90a3977e0.png">

So, the graph is empty, and the only node I see refers to this (it is not a wiki link, but Markdown links thinks this is a title):

<img width="917" alt="Снимок экрана 2020-08-05 в 15 45 31" src="https://user-images.githubusercontent.com/230824/89414214-b7c99700-d732-11ea-9016-4e037c90d5ee.png">

The notes are full of wiki links. Here is how they looks in Obsidian Graph view:

<img width="1193" alt="Снимок экрана 2020-08-05 в 15 40 16" src="https://user-images.githubusercontent.com/230824/89414268-cd3ec100-d732-11ea-8ab4-b0bc5fa4231a.png">

Bug? Feature? 
How should I refresh the Markdown Links Graph?

MacOS Big Sur
VScode Version: 1.47.3
Foam 0.3.1

**Comment by jevakallio** [comment]
Every note needs a title to work in Markdown Notes. See https://foambubble.github.io/foam/link-formatting-and-autocompletion

You can try running Foam Janitor for this (but please backup your notes first just in case)
https://foambubble.github.io/foam/workspace-janitor

(Excuse brevity, on mobile)

**Comment by VKondakoff** [comment]
Got it, thanks!
