### ISSUE TITLE
Foam support issues/suggestions/discussion

### ISSUE THREAD

**Issue by VKondakoff** [foambubble/foam#213]
I noticed this issue after reading [this suggestion](https://github.com/foambubble/foam/issues/211#issuecomment-669993474). Where should users post their Foam-related issues: on the main Foam support board or on the specific plugins boards? Let's discuss this!

I'm pretty sure most of the Foam users are thinking of Foam as a full-fledged solid product and want support from the developers of Foam, and not separately from every developer of every plugin (of which Foam consists). 

So, as far as I can see there are several options for providing support:

1. @jevakallio may have some kind of an agreement with plugin developers to check this board periodically and provide support for the issues they associate with they own plugins. This already happens in Discord group. Let do the same here, please!
2. There should be a quite detailed documentation describing which functionality provides every plugin that is included in Foam with an easy accessible links to their support boards. And there should be an unambiguous message from Foam devs pointing to the right support boards. Maybe there should be some king of pinned message with such a links?
3. Any other options?..

What do you think? As far as I see this topic may be quite important for the future of Foam...

**Comment by nixsee** [comment]
Seems like a useful discussion to have, in order to both lighten the load on our fearless leaders as well as get support from where it actually needs to come from. 

#2 is a very good idea.

**Comment by thomaskoppelaar** [comment]
I think that # 2 is a good suggestion - Documenting what extension does what is a great option + pinning an issue stating "where should I post issues" ensures that the relevant people get the relevant information.

As issues tend to be related to certain extension behavior, I think its best to disclose those to the relevant extension. 

As for enhancements: those are more context dependent, and can probably best be discussed here, and (perhaps) be redirected to an extension later.

**Comment by jevakallio** [comment]
@VKondakoff thank you for raising this discussion, and apologies for delayed response -- very ironic given the topic of the issue :)

Approach #2 is definitely the direction I want to go to. I believe this should consist of, at least

1. A documentation page that shows how to get support
2. GitHub issue template
3. Pinned message on Discord #start-here channel

I'm happy to receive contributions to making this experience better! Earliest I'll be able to focus on the Foam "meta experience" -- support, docs, and other non-core issues -- is in September. Quite slammed til then, personally.
