### ISSUE TITLE
"Use this template" link is 404 if you're not logged into Github

### ISSUE THREAD

**Issue by coffenbacher** [foambubble/foam#22]
I don't know how the Github 'Use this template' feature works, but I thought links were broken when I went here and it was a 404. Maybe a note that you have to be logged in first would help.

https://github.com/foambubble/foam-template/generate

**Comment by jevakallio** [comment]
Thanks for the feedback, didn't know this! Fixed now:

![image](https://user-images.githubusercontent.com/1203949/86011954-400e9b00-ba15-11ea-9142-ffeffcf1a478.png)
