### ISSUE TITLE
First Daily note fails after changing `foam.openDailyNote.directory` 

### ISSUE THREAD

**Issue by tristansokol** [foambubble/foam#229]
Hi, I'm new. Thank you for all your work so far, foam has been interesting to check out! 

I noticed that immediately after setting `foam.openDailyNote.directory` running the **Open Daily Note** command results in a little error pop-up: 
![image](https://user-images.githubusercontent.com/867661/90979921-badbca00-e51d-11ea-8477-4975185e1639.png)
```
Command 'Foam: Open Daily Note' resulted in an error (ENOENT: no such file or directory, open '.../foam/[new directory]/2020-08-23.md')
```

Running the command again works fine as the first invocation created the directory. Looking through the code it seems like the issue might be fixed by adding an `await` here:  
https://github.com/foambubble/foam/blob/d8512db7aa5c8f98e002d0744e54c3312bf50dc1/packages/foam-vscode/src/features/open-daily-note.ts#L66

I am happy to open a pull request if this fix is wanted and if it at least seems like I'm in the right spot to start debugging. 

Thank you!

**Comment by jevakallio** [comment]
Fixed via https://github.com/foambubble/foam/pull/232. Thanks @sksmith! 🙌
