### ISSUE TITLE
Idea: keyboard shortcut as Cmd+Click alternative

### ISSUE THREAD

**Issue by coffenbacher** [foambubble/foam#23]
I think it would be really cool to have a keyboard shortcut to open links instead of Cmd+Click. Like many VSCode users, I don't leave my keyboard that much (vim compatibility) so the 'click' interaction in the middle of typing is awkward. 

For now I can use the normal file jump commands but if I have many files named similarly, a keyboard shortcut would be slicker.

**Comment by Georift** [comment]
I had a similar thought when first using foam. After some digging I found this [blog post by the creator](https://kortina.nyc/essays/suping-up-vs-code-as-a-markdown-notebook/#vscode-vim-extension) discussing how they had setup their VSCode.

VSCodeVim users can use `gf` to navigate to the link under the cursor.

**Comment by jevakallio** [comment]
@coffenbacher yup! This is definitely a high priority improvement. Like @Georift discovered, this is not implemented in [Markdown Notes](https://marketplace.visualstudio.com/items?itemName=kortina.vscode-markdown-notes) yet and is not a priority for the author since they're using vim mode. 

If anyone wants to contribute this either to Markdown Notes, or finds a way to include it in foam-vscode, I'd love to have this!

**Comment by Georift** [comment]
@coffenbacher @jevakallio so it looks like this already exists for us today! 😄 Try pressing `F12` when your cursor is on the link.

Markdown Notes is providing [definition support](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition) for this wiki link syntax to VSCode so you want you can remap the command: `editor.action.revealDefinition` if F12 doesn't suit.

Should we document this anywhere before closing this issue?

**Comment by jevakallio** [comment]
@Georift wow, cool! If you could add the hotkey (and the steps to customise `revealDefinition` since F-keys are a little inaccesible for touch bar mac users) to https://github.com/foambubble/foam/blob/master/wiki-links.md, that would be amazing! 🤩

**Comment by coffenbacher** [comment]
Btw for future reference, `gf` doesn't work with pages that don't exist yet, but Go To Definition does :heavy_check_mark: Loving Foam now!
