### ISSUE TITLE
How to load GUI graph window in a workspace.

### ISSUE THREAD

**Issue by midopooler** [foambubble/foam#233]
![b2380cf8-eed5-44ca-9186-aa898c4fd1cf](https://user-images.githubusercontent.com/43686606/91358920-4c468700-e811-11ea-80c8-80e9f7da0611.jpg)

**Comment by juanfrank77** [comment]
If you are referring to how to open the graph in your Foam workspace, do `Cmd` + `Shift` + `P` (or use `Ctrl` if you're not on a Mac) and then run the `Show graph` command.

**Comment by jevakallio** [comment]
Yup, this is documented in https://foambubble.github.io/foam/graph-visualisation.

We'll need to improve our onboarding documentation and these basic commands should be part of it, but in the current documentation structure there's no more prominent place for it, so closing this as resolved

**Comment by midopooler** [comment]
Ohkay thanks a lot. @jevakallio @juanfrank77  I should have looked at docs first. my bad.
