### ISSUE TITLE
Opening Obsidian directory and updating reference list gives error

### ISSUE THREAD

**Issue by alper** [foambubble/foam#235]
I'm trying to not migrate my Obsidian setup but just open that folder with Foam and see if I can use it as a transitional editor.

Updating the reference list gives me this error:
```
Command 'Foam: Update Markdown Reference List' resulted in an error (command 'foam-vscode.update-wikilinks' not found)
```

**Comment by Jackiexiao** [comment]
I have the same error, and sometimes part of link generated, but for the rest of it, it didn't generate link reference. 
![image](https://user-images.githubusercontent.com/18050469/91710557-098d0200-ebb7-11ea-9791-f197de753905.png)

![image](https://user-images.githubusercontent.com/18050469/91710643-30e3cf00-ebb7-11ea-9fd8-25c426c4ab25.png)

**Comment by chirag-singhal** [comment]
@alper You need to use [foam-template](https://github.com/foambubble/foam-template) to get started with using foam. For step by step procedure check out https://foambubble.github.io/foam/#getting-started

**Comment by scott-joe** [comment]
For what it's worth, I had some issues yesterday getting/keeping my links updated. If the extension had indexed one location of a file and I'd moved it since, it kept using that old location's relative path no matter how many times I attempted to change it. I actually had to delete the line, close the file, open it again, and try to recreate the link.

**Comment by dremofly** [comment]
There may be some format error in your files. When I moved from obsidian, I faced this problem, too. 
And yesterday, I face this problem again. 
I don't know how to find out the error file.

**Comment by scott-joe** [comment]
Hm... Yeah, looks like this is still [uncharted territory](https://github.com/foambubble/foam/blob/master/docs/migrating-from-obsidian.md). If you learn anything worth sharing in migrating, please fork and document :)

**Comment by jsjoeio** [comment]
I did migrate from Obsidian to Foam and left some notes here in case it helps: https://github.com/foambubble/foam/issues/46

**Comment by riccardoferretti** [comment]
Given how long ago this was I am going to close it for now due to inactivity, if the proble is still present please open a new issue.
