### ISSUE TITLE
Feature request: Backlinks in markdown preview

### ISSUE THREAD

**Issue by sudeepdino008** [foambubble/foam#237]
The backlinks today are visible only in markdown source mode, and not in markdown preview. I wonder if this intentional.
When exploring my knowledge archive, I would exclusively like to navigate in markdown preview mode (since it's rendered and neater), and backlinks are important for navigation.

**Comment by alan-prudom** [comment]
I believe the (as yet) unimplemented [Roadmap item](https://foambubble.github.io/foam/materialized-backlinks) would satisfy this feature request.

**Comment by khimaros** [comment]
the roadmap item was moved to here: https://foambubble.github.io/foam/dev/materialized-backlinks

**Comment by khimaros** [comment]
i  believe this was fixed by https://github.com/foambubble/foam/pull/830/

**Comment by are** [comment]
Has this been resolved (or maybe reintroduced)? I cannot see any backlinks when displaying a document in preview mode.

I have a setting enabled to open the preview by default and backlinks are not working until I double click the document and go to edit mode.

```
"workbench.editorAssociations": {
  "*.md": "vscode.markdown.preview.editor"
},
```
