### ISSUE TITLE
README links 404ing isn't obvious if you're skimming the docs

### ISSUE THREAD

**Issue by obra** [foambubble/foam#24]
I 100% understand -why- you'd rather users browse the Foam workspace, but on first read, I missed the friendly note at the top of the README.

Since GitHub renders the README.md on the project's homepage, maybe it makes sense to cut down the README and move most of the linked content onto another page.

The user experience of getting 404s from the README isn't a good representation of why Foam is awesome.

**Comment by daniel2231** [comment]
I agree with this. How about emphasizing the note using bold instead of quote?

**Comment by jevakallio** [comment]
Thanks, these are both good ideas. 

@obra I need to test how GitHub pages works on this, but I think I may be able to move the GH Pages home to render from index.md and link it from readme.md

If that doesn't work, will highlight the warning more visually like @daniel2231 suggested!

**Comment by jevakallio** [comment]
Thanks @obra @daniel2231, took both of your suggestions and moved the documentation to website-only, leaving an introductory teaser stub on the GitHub readme with a (hopefully) more visible info heading!

Continuing to track the root cause in #17
