### ISSUE TITLE
If the title contains special characters, link references do not work as expected

### ISSUE THREAD

**Issue by hezhizhen** [foambubble/foam#240]
I use `[[]]` to wrap something like `O'Reilly` or `Whitesides' Group: Writing a Paper` and use `Cmd+Click` to create notes for them, there is nothing wrong about the created notes, but the link references do not contain them or use another name.

Below is an example:

<img width="280" alt="截屏2020-09-01 14 57 40" src="https://user-images.githubusercontent.com/7611700/91812423-ad33ec00-ec63-11ea-8744-a8adec196ced.png">
<img width="234" alt="截屏2020-09-01 14 57 51" src="https://user-images.githubusercontent.com/7611700/91812458-b91fae00-ec63-11ea-9280-ed92d65f1192.png">

**Comment by riccardoferretti** [comment]
IIUC you have created the `o-reilly.md` file, and expect the `O'Reilly` string to be sluggified to `o-reilly`; but instead you are getting `oreilly`. I believe this has to do with your "sluggification" logic being different from foam's.

We use github-slugger to generate the slug from the string, which converts `O'Reilly` to `oreilly`. I also tested online at https://slugify.online/ and I get the same result, so I guess (I am no sluggification expert! :) ) that in that process the `'` char is removed, not replaced by `-`.

**Comment by hezhizhen** [comment]
As far as I observe, foam replaces all special characters with `-`.

**Comment by riccardoferretti** [comment]
gotcha, so you are not creating the file but you are clicking through the link to create it. I just tested it and was able to reproduce.

This must be related to markdown-notes, which probably uses a different sluggification logic from foam. Let me look into it, thanks for reporting the issue!

**Comment by hezhizhen** [comment]
> gotcha, so you are not creating the file but you are clicking through the link to create it. I just tested it and was able to reproduce.
> 
> This must be related to markdown-notes, which probably uses a different sluggification logic from foam. Let me look into it, thanks for reporting the issue!

Thank you for your time, and look forward to your solution.

**Comment by chirag-singhal** [comment]
Correct @riccardoferretti markdown-notes doesn't use the github slugger instead it replaces special characters with '-'.

**Comment by nixsee** [comment]
I also create my files via inline [[wiki-links]], so would love a solution to using special characters (at the very "normal" punctuation like -,?!) in file names. Currently, I am just removing all punctuation other than hyphens from titles/filenames when I create them. 

I don't know how this affects markdown/html though...

**Comment by kortina** [comment]
I started looking into updating to use `github-slugger` in Markdown Notes, and I was originally thinking that I might make it the new default, but given how much breaks, I think it probably does not make sense to default to it:

https://github.com/kortina/vscode-markdown-notes/pull/85/files

**Comment by riccardoferretti** [comment]
Added to default template in https://github.com/foambubble/foam-template/commit/b6ec501cf1cf11e193e66a733ff8e75ceda7e7a4
