### ISSUE TITLE
Use .bib files for citation and links

### ISSUE THREAD

**Issue by argrento** [foambubble/foam#241]
Hi!

While studying a new topic, I try to find papers and store them in jabRef and I would like to link a paper from this library in a markdown file with something like this:
`More at [@BibTexKey]`.

Currently I solve it with a set of .md files in a _papers_ folder inside my Foam workspace. Each file represents one paper. 
BibTexKey.md:

```
key: _BibTexKey_
author: _authors_
title: _title_
abstract: _long abstract_
```

Is it possible to do this in more elegant way?

**Comment by mitchellmcm27** [comment]
I also use bibtex heavily and can share my solution. 

I put my .bib file in the root folder. For VS Code, I use the plugin [Pandoc Citer](https://marketplace.visualstudio.com/items?itemName=notZaki.pandocciter), which gives autocomplete for the references from the .bib file. As an aside, I use [Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) to get a formatted view of my markdown files that renders using pandoc in VS Code (I'm a longtime pandoc user).

For the rendered website, I added a script that runs each markdown file through pandoc. I'm using eleventy to generate my website, so I use `node-pandoc` in a javascript file that is called during the build step. The pandoc args that I find work well are `_metadata.yml -t gfm -F pandoc-citeproc -s -o ${file}` where `_metadata.yml` contains the headers that apply to each markdown document - this is where I define my bibliography file, but there are other ways to do that. The `-t gfm` outputs GitHub flavored markdown, which I find works the best as an input to eleventy. the `pandoc-citeproc` filter converts all the @BibtexKey strings into actual citations. I could probably just use pandoc to generate the final html files, but this is my current solution and it works.

**Comment by yaxu** [comment]
@mitchellmcm27 I'm looking for a way to pass 11ty markdown files through pandoc to resolve citations/make bibliographies, and stumbled across your comment describing exactly what I want to do.. However I'm not sure how to replicate this. If you have a moment, could you say a bit more about how you get 11ty to run each file through pandoc please, or even point to an example if you have one?

**Comment by mitchellmcm27** [comment]
Sure thing @yaxu. this is the javascript script that I wrote to run each markdown file through pandoc. Note that the pandoc command just outputs github flavored markdown, but the pandoc-citeproc filter makes sure that all `@references` to the .bib file are replaced with the formatted citation. Like I said before, the location of the .bib file is inside the header of `_metadata.yml`, which gets appended to each markdown file. I think you could alternatively pass the .bib file path as an additional argument to pandoc.

```
// do-pandoc.js

const nodePandoc = require('node-pandoc');
const path = require("path");
const fs = require("fs");

fs.readdirSync("./").forEach(file => {

    // you may need logic here to determine which files to run through pandoc
    // for me, all .md files were relevant
    if(path.extname(file) === '.md'){

      // this command will overwrite the original md file with the pandoc'd version
      const args = `_metadata.yml -t gfm -F pandoc-citeproc -s -o ${file}`;

      nodePandoc(file, args, (err, result) => {
        if (err) {
         console.error(err);
        } else {
          console.log("successfully pandoc'd", file);
        }
      });
    }
 });

```

I added this as a script in my package.json

```
  "scripts": {
    "do-pandoc": "node ./scripts/do-pandoc.js"
  }
```

I'm using netlify to deploy my site, so I edited the build command in my `netlify.toml` as the following. This uses npm to run the script before building the site using 11ty.

```
[build]
  functions = "./build-netlify-functions"
  publish = "_site"
  command = "npm run do-pandoc && npx eleventy"
```

Hope this helps!

**Comment by yaxu** [comment]
@mitchellmcm27 great, thanks very much for sharing that!
