### ISSUE TITLE
Render workspace using VuePress with built-in media-wiki links rendering, backlinks and more...

### ISSUE THREAD

**Issue by spencerwooo** [foambubble/foam#259]
I spent the past 3 days or so tinkering with Foam and what-not, **and I'd like to share my current progress: <https://wiki.spencerwoo.com/>.**

Some of the features that may interest you:

- Built with VuePress and **rendered into a lightweight, ultra-fast, SPA website.** I like this solution far more than Jekyll for what it's worth. Most of my own project's documentation website is powered by VuePress.
- **Built-in [[media-wiki]] style link rendering** (into Vue Router links), which is supported by a separate plugin I customised: [spencerwooo/vuepress-markdown-it-wikilink](https://github.com/spencerwooo/vuepress-markdown-it-wikilink). This means that **VuePress can render [[media-wiki]] links regardless of Foam's hacky workaround** by using Markdown link references (but these two play well together still). This also **provides a way to render Obsidian workspaces** (considering they don't auto-generate link references like Foam).
- Makes `foam-cli` and `note-link-janitor` play well together. Because Foam auto-generates link references at the end of the document, so I modified [andymatuschak/note-link-janitor](https://github.com/andymatuschak/note-link-janitor) a little bit (~~no, like a lot actually~~) and made it so that `note-link-janitor` renders the backlinks section in between the end of the article and the start of Foam's link references. **This generates a nice little section of backlink references at the bottom of each page:**

  ![image](https://user-images.githubusercontent.com/32114380/92625722-9d6b7600-f2fb-11ea-8835-9c03259b862b.png)

- **And of course there's LaTeX rendering support!!!** (which is also made possible with a custom version of [vuepress/vuepress-plugin-mathjax](https://github.com/vuepress/vuepress-plugin-mathjax) because their current version breaks on rendering `aligned` environments.)
- Finally, I also wrote a new custom VuePress theme to render my Foam workspace in a style quite similiar to the default Jekyll theme.

There's definitely room for improvements:

- `foam-cli` and `note-link-janitor` needs to be run manually on each redeployment. We can absolutely use pre-commit hooks to automate this, but in the mean time, VuePress is capable of generating both the backlinks section that `note-link-janitor` renders and the [[media-wiki]] style links `foam-cli` renders, so this is definitely a thing I could work on in the future.
- VuePress is also definitely capable of generating a graph of local links all on its own, so this is another feature I'm trying to implement.
- Getting rid of the default VuePress search bar may not be the best idea. (But it's easily re-implementable. ㄟ( ▔, ▔ )ㄏ) I saw some folks wishing for a simple search functionality and to be fair any static site generator should already have such plugins.
- This certainly goes against Foam's as little code as possible concept, but hey, I heard Foam is trying to migrate to Gatsby as well. 😏
- ...

Phew, that's a lot of things to cover. I really like to create something like a VuePress Foam template and in the meantime contribute another recipe(s), but I'm not going to have time to work on this for the next couple of days or weeks 😥. Anyway, I thought people might be interested in what I have done so far, **so here's my repo for the code I used to implement this: [spencerwooo/foam-wiki](https://github.com/spencerwooo/foam-wiki).**

(PS: I didn't republish my custom version of the plugins `mathjax-plugin`, `note-link-janitor` and the custom VuePress theme, because they are quite task-specific and also quite unpolished.)

**Comment by riccardoferretti** [comment]
In one word: impressive!

Please keep us posted

p.s. love the final quote from your repo, and I totally agree 😁

**Comment by Jackiexiao** [comment]
great work! FYI, I create a similar [foam-mkdocs-template](https://github.com/Jackiexiao/foam-mkdocs-template)  with media-wiki links rendering (also support obsidian workspace), it looks like this:

https://jackiexiao.github.io/foam/
![image](https://user-images.githubusercontent.com/18050469/93550955-399e1880-f99f-11ea-89ed-4026c84eb772.png)

**Comment by riccardoferretti** [comment]
hi @spencerwooo - curious to know how things have been evolving around this, would you like to share?

**Comment by spencerwooo** [comment]
i'm afraid i'm not working on this anymore sorry :(

it's not because i ditched foam, it's just because i have not been working on this particular research area for almost a year and i'm not scheduled to continue working on this until i start with my phd, which won't begin until next year, so at the moment i don't have a lot to work with in terms of building a personal knowledge base or just using foam-like software for digital gardening.

if you are just scanning through issues for closing, please do, but i should be getting back to using foam when i have more on my hands. cheers 🍻

**Comment by riccardoferretti** [comment]
Thanks for the update, yup I will close the issue in the meantime, but if you come back to the project definitely let us know!
