### ISSUE TITLE
auto complete or vscode intellisense for Chinese?

### ISSUE THREAD

**Issue by Jackiexiao** [foambubble/foam#264]
I want a feature like this 
![image](https://user-images.githubusercontent.com/18050469/93551344-30fa1200-f9a0-11ea-8d3f-ab4b30e13387.png)

but currently foam won't pop up candidate for Chinese
![image](https://user-images.githubusercontent.com/18050469/93551461-80d8d900-f9a0-11ea-84db-61738dec419f.png)

same for `[](#..)`  `[[#title anchor]]`

**Comment by hikerpig** [comment]
Things work smoothly on my side, so I don't think this is foam+Chinese issue. At least not in a clean VS code setup.
But I do find that code-intellisense may have troubles in foam notes project in my regular extensions-heavy VSCode, so it might be a mixed problem of multiple extensions you are using and the specific VSCode config.

**Comment by Jackiexiao** [comment]
yes.... I try it in a clean vscode insider, it works fine... let me find out which extension cause this problem..

**Comment by Jackiexiao** [comment]
I believe it is a bug from `markdown note`, when I disable this extension, autocomplete for Chinese works well 

related issue

https://github.com/kortina/vscode-markdown-notes/issues/97
