### ISSUE TITLE
Update document

### ISSUE THREAD

**Issue by qiwang97** [foambubble/foam#268]
I see `"watch:core": "yarn workspace foam-core start"` in `package.json` but no `start` in `/packages/foam-core/package.json` in `master` branch.  
Something has changed and I find no docs to work with `foam-core`. Please update the README.

**Comment by scott-joe** [comment]
If you're talking about the `foam-core` package, it doesn't have a local server, so there wouldn't be a `start` command. I would guess as this is the shared code for the other packages, it probably doesn't "do" much on it's own. You could try [running the vs-code extension locally](https://code.visualstudio.com/api/get-started/your-first-extension) or the CLI, make changes to the core code and watch for changes in the CLI/VSCode extension projects.

**Comment by scott-joe** [comment]
Oh I see what you mean. That might be left over from when they moved to a monorepo...

**Comment by riccardoferretti** [comment]
@qiwang97 we have consolidated the commands available across all packages, you can find them in the top level `package.json`, and are `clean`, `build`, `test`, `watch`, `lint`.

There are still a couple of extra commands, but the ones above are a sort of "public api" for managing all packages - is this addressing your question?

**Comment by scott-joe** [comment]
@riccardoferretti They mean that [this line](https://github.com/foambubble/foam/blob/master/packages/foam-core/README.md#npm-start-or-yarn-start) is misleading and would like it removed.

**Comment by riccardoferretti** [comment]
Great point @scott-joe , I totally missed it. Start might actually be a better name, although for vscode package I would expect that to start an instance of vscode with the extension in "dev" mode (which I am not sure it's possible).
Do you have any suggestion? 
Will give it some thought too and update the issue

**Comment by scott-joe** [comment]
I agree, since it's all being aliased from the mono-repo, you might as well call it "start" and leave the mono-repo passthru as having the namespace alias

**Comment by riccardoferretti** [comment]
Sorry @scott-joe I didn't quite catch what you meant, can you elaborate?

**Comment by scott-joe** [comment]
@riccardoferretti so, the monorepo has in it's package.json, a set of scripts that point to the scripts in the various package's own package.json scripts.

Monorepo's package.json

```json
  "scripts": {
    "start:vscode": "yarn workspace foam-vscode vscode:start-debugging",
    "build:core": "yarn workspace foam-core build",
    "watch:core": "yarn workspace foam-core start",
    "test:core": "yarn workspace foam-core test",
    "clean": "lerna run clean",
    "build": "lerna run build",
    "test": "lerna run test",
    "lint": "lerna run lint",
    "watch": "lerna run watch --concurrency 20 --stream"
  },
```

`start:vscode` is easy to understand and realistically, nothing more is needed from the user if you're working in the monorepo. However, in the `foam-vscode` package under `packages/foam-vscode/package.json`, the script section looks like:

```json
"scripts": {
    "build": "tsc -p ./",
    "test": "jest",
    "lint": "eslint src --ext ts",
    "clean": "tsc --build ./tsconfig.json ../foam-core/tsconfig.json --clean",
    "watch": "tsc --build ./tsconfig.json ../foam-core/tsconfig.json --watch",
    "vscode:start-debugging": "yarn clean && yarn watch",
    "vscode:prepublish": "yarn npm-install && yarn run build",
    "npm-install": "rimraf node_modules && npm i",
    "npm-cleanup": "rimraf package-lock.json node_modules && yarn",
    "package-extension": "npx vsce package && yarn npm-cleanup",
    "publish-extension": "npx vsce publish && yarn npm-cleanup"
  },
```
There we can see `vscode:start-debugging`, which could be better stated as `start` which would make the `readme.md` accurate as it still shows a `yarn start` command that's no longer present.

I'll just make a PR with a change. The Workflow configs don't appear to depend on these specifically, so it shouldn't be a problem.

**Comment by scott-joe** [comment]
https://github.com/foambubble/foam/pull/277

**Comment by riccardoferretti** [comment]
Build has changed considerably since this issue was open, so closing now
