### ISSUE TITLE
Workspace & Note Organization Model

### ISSUE THREAD

**Issue by scott-joe** [foambubble/foam#269]
Like @spencerwooo, I've been kicking around Foam for a little while and was mostly concerned with how I was going to organize all this information, selectively publish, and secure private scopes. This is what I came up with.

[foam--workspace](https://github.com/scott-joe/foam--workspace) & [foam--bottle--*](https://github.com/scott-joe/foam--bottle--personal) to be made into Templates soon.

To pull from the readme:
>My setup is best summaried as: I have a Foam Workspace that contains Bottles (repos) that contain Bubbles (notes)
> 
> > Bottles of bubbles makes Foam
> 
> My Foam workspace keeps all the workspace settings, extensions, and snippets that make my setup my own. It's like the stickers and modifications I've made to my laptop. It's what makes it custom tailored to me and my brain.
> 
> I have a directory that holds what you could call "notebooks" but for the sake of staying in the naming scheme, I've called them "bottles." Each bottle is a collection of markdown files that are related in some way. I keep one for each work project, personal notes I'd like to publish, and private ones I would like to keep that way. Using git to keep track and github to sync my files, each bottle is a git repo that focuses on the configurations that make sense for that set of notes.
> 
> For my Personal notes that second as a blog, I have configuration files that Netlify picks up on when I push my repo back up to Github. I have local scripts that build Gopher and Gemini files as well. Everything publishes from the same source and are distributed as necessary. I can make changes to my editor config from there as well. If I had a bottle that contained mathematical formulas, I could enable or disable extensions to help Markdown handle those. If I had a bottle that contained a book I was writing, I could format the editor to look like a typewriter and the publish scripts to spit out a PDF. A bottle that included references to code could have syntax highlighting to help with that.

![Screen Shot 2020-09-23 at 2 49 01 PM](https://user-images.githubusercontent.com/2026866/94057088-25965480-fdad-11ea-9f88-9eca04b5b354.png)

Of course, it's just a start, but this model really helped me organize my notes in a way that worked well with the assembled technologies that make up Foam. If you have thoughts or feedback, I'd greatly appreciate it.

**Comment by riccardoferretti** [comment]
We now have a discussion thread for these, would love to hear how this model has been working out for you there!

https://github.com/foambubble/foam/discussions/1081
