### ISSUE TITLE
Improve Default Workspace Settings

### ISSUE THREAD

**Issue by scott-joe** [foambubble/foam#270]
Pulled from Roadmap item: [Improve Default Workspace Settings (stub)](https://foambubble.github.io/foam/improve-default-workspace-settings)

### Required
- Are there goals that these settings should meet?

### Conversation Starters
- Is the assumed workspace configuration the most basic one? Notes in the top level?
- How opinionated are these?
- Do they include configs for the required plugins?
- Do we have multiple sets/levels that can be chosen from with a simple filename change?
  - E.g.: `basic.settings.json`, `blogger.settings.json`, `aggressive.settings.json` etc. renamed to `.settings.json` would "choose" that set.
- Are these a part of Recipes?
- Can this be part of an initialization script?

**Comment by riccardoferretti** [comment]
I didn't create that page so don't have much context on it, but let me share my thoughts.

- Is the assumed workspace configuration the most basic one? Notes in the top level?

My guess is to be unopinionated where possible, and make it easy (docs, cli commands, ...) to change 

- How opinionated are these?

Little where possible :)

- Do they include configs for the required plugins?

Yes

- Do we have multiple sets/levels that can be chosen from with a simple filename change?

That could be an interesting approach

- Are these a part of Recipes?

Definitely settings should be documented, yes

- Can this be part of an initialization script?

Yes
