### ISSUE TITLE
Empty Title/Line 1 H1 breaks VS Code extension

### ISSUE THREAD

**Issue by scott-joe** [foambubble/foam#276]
## Expected Behavior

- Running `Foam: Update Markdown Reference List` in VS Code within a Foam workspace should add Markdown reference links to the bottom of pages containing wikilinks.

## Actual Behavior

- Running `Foam: Update Markdown Reference List` in VS Code within a Foam workspace yields the following error:

> Command 'Foam: Update Markdown Reference List' resulted in an error (command 'foam-vscode.update-wikilinks' not found)

## Steps to Reproduce

1. Create a new markdown file in a Foam workspace
1. Add `# ` to the beginning of the file and leave the rest of the title blank
1. Save the file
1. Close VS Code
1. Open workspace in VS Code
1. `CMD+SHIFT+P` > `Foam: Update Markdown Reference List`

## Notes

Bear automatically starts every note with an H1/single hash mark and if you just skip past that to writing the rest of your note without giving the note a title, when you export, it'll still give you an H1, even if it's empty.

**Comment by Spectrem12** [comment]
This recently happened to me.
One of my files had an empty heading
EX: 
my-file.md
#

vs. what it should be
my-file.md
# my file

This caused the same error you are seeing to occur.
I fixed the header for my one file that had the issue and it did not resolve the problem.
I reinstalled Foam and restarted VS.
Then everything worked after that.

**Comment by riccardoferretti** [comment]
@scott-joe @Spectrem12 this should fix it https://github.com/foambubble/foam/pull/284
