### ISSUE TITLE
Bug: backlinks not working, "No refs in empty workspace"

### ISSUE THREAD

**Issue by coffenbacher** [foambubble/foam#28]
I'm not sure what's going on here, but Backlinks don't work for me (panel renders but is blank), and I get these messages: 

![image](https://user-images.githubusercontent.com/245867/86029052-83eaab80-b9e7-11ea-92fc-af7cb3a59cdf.png)

Any ideas on where to start with that? I didn't see any errors when I tried to check in the Log (Extension Host) logs.

**Comment by jevakallio** [comment]
@coffenbacher I haven't seen that issue, but it's coming from the [Markdown Notes](https://github.com/kortina/vscode-markdown-notes) extension.

I'd be happy to investigate and help fix this is in Markdown Notes as it affects Foam users, but the issue should probably be created there. Ideally, could you:

1. Create an issue in their repo
2. Include platform version info (Operating system, Markdown Notes extension version. VS Code version)
3. With a minimal reproducible example (e.g. by forking a new project from foam-template, and creating a set of linked documents that cause this error)

And then link that issue to this one?

**Comment by coffenbacher** [comment]
https://github.com/kortina/vscode-markdown-notes/issues/43

**Comment by jevakallio** [comment]
@coffenbacher thanks for letting me know!
