### ISSUE TITLE
Blank area in explorer view

### ISSUE THREAD

**Issue by treisinger** [foambubble/foam#280]
Hello,

I have newly installed foam and it shows a big blank area in the explorer view of VSCode.

![image](https://user-images.githubusercontent.com/9279781/95310609-e5df6a80-088c-11eb-8c97-c818e7e0707f.png)

Could you please check. It looks not correct to me.

Best regards,
Tapio Reisinger

**Comment by riccardoferretti** [comment]
hi @treisinger, I think the reason for the blank area is that your panels are all collapsed.
Try expanding either other panels (e.g. outline, while a markdown file is open), or one of the directories in the foam-workspace section.
Let us know how it goes

**Comment by treisinger** [comment]
Hi,

there are still some blank areas. It is not a big thing. Just want to scheck if it's done by purpose, as it looks not correct to me.

![image](https://user-images.githubusercontent.com/9279781/95314031-16c19e80-0891-11eb-9cdc-75483f5f5f55.png)

Thank you and kind regards, Tapio

**Comment by ingalless** [comment]
@treisinger The panels are resizable, could that be the issue? I've been using VS Code pre-Foam with some custom panels, and I get the same experience. See below (it's not a foam repo, but should illustrate the point):

![panels](https://user-images.githubusercontent.com/22981941/95319235-88005200-088f-11eb-8b46-992ca73d8523.gif)

**Comment by riccardoferretti** [comment]
thanks for the thorough explanation @ingalless!
@treisinger also what I see in your image looks fine so I will close the issue

**Comment by treisinger** [comment]
Yes it's fine. Sorry didn't noticed that.

Best regards, Tapio
