### ISSUE TITLE
Focus on the autogenerate graph when clicking on a link

### ISSUE THREAD

**Issue by TommasoBendinelli** [foambubble/foam#285]
Hello, 
I have a graph with many different bubbles. It would be possible, when clicking on a bubble to have the graph to autofocus on the selected bubble?

Best,
Tommaso

**Comment by ingalless** [comment]
@TommasoBendinelli this looks like a fix for the tchayen/markdown-links repository if I understand correctly. 

heres a link: https://github.com/tchayen/markdown-links

Looks a good suggestion!

**Comment by TommasoBendinelli** [comment]
I have open an issue there as well

**Comment by riccardoferretti** [comment]
For reference, here is the link @TommasoBendinelli created in Markdown Links: https://github.com/tchayen/markdown-links/issues/65
