### ISSUE TITLE
Add wikilink support to md preview (was: Use vscode-memo for bidirectional linking)

### ISSUE THREAD

**Issue by mrusso99** [foambubble/foam#286]
Using vscode-memo fixes the uppercase linking issue present in foam

https://github.com/svsool/vscode-memo

**Comment by riccardoferretti** [comment]
hi @mrusso99, can you please describe the bug or include a link to the relevant issue?

**Comment by mrusso99** [comment]
Using the vscode extension vscode-memo allows me to define markdown links in any way that i like, as you can see from the image, fix the case sensitive issue previously present in Foam

![Screenshot_20201012_131353](https://user-images.githubusercontent.com/28223818/95740537-3e8f7880-0c7c-11eb-99c8-e55ff677dc21.png)

**Comment by mrusso99** [comment]
Without the extension enabled as you can see from the [docs](https://github.com/foambubble/foam/blob/master/docs/link-formatting-and-autocompletion.md) i cannot define links with Uppercase names nor with a space.

![Screenshot_20201012_134759](https://user-images.githubusercontent.com/28223818/95743167-d0998000-0c80-11eb-93c2-90986c0089cc.png)

As you can see from the screenshot, disabling this extension breaks my link definition, so i think forking this project and using some of the code for fixing the wikilinks issue is advised.

If not then requiring the extension as part of the workspace could fix this issue

**Comment by mrusso99** [comment]
A way to replicate this bug is by creating a `.md` file like this `Example.md`.\
If i create on another file a wiki link backtracing to `Example.md`, the markdown preview does not show the link, instead, just shows what i wrote in the `.md` like in the screenshot.\
For reference here's is a foam workspace that replicates the issue.

[Issue#286.zip](https://github.com/foambubble/foam/files/5364987/Issue.286.zip)

![Screenshot_20201012_140456](https://user-images.githubusercontent.com/28223818/95744674-3850ca80-0c83-11eb-8c38-d88bce71f8ae.png)

![Screenshot_20201012_140505](https://user-images.githubusercontent.com/28223818/95744687-40106f00-0c83-11eb-98c9-12282d17772f.png)

**Comment by riccardoferretti** [comment]
thanks @mrusso99, I was able to reproduce it.

Looks like vscode-memo addresses it by [extending markdown-it](https://code.visualstudio.com/api/extension-guides/markdown-extension) in [the code](https://github.com/svsool/vscode-memo/blob/master/src/features/extendMarkdownIt.ts)

Thanks for reporting the issue, would you be interested in looking into it?

**Comment by mrusso99** [comment]
Unfortunately i don't nave any competence in neither CSS nor typescript,
sorry.

Il mer 28 ott 2020, 17:00 Riccardo <notifications@github.com> ha scritto:

**Comment by riccardoferretti** [comment]
@mrusso99 thanks anyways for spotting the issue and the path to the solution, we'll sort it out :)

**Comment by mrusso99** [comment]
Good luck and keep up the great work!

Il mer 28 ott 2020, 17:32 Riccardo <notifications@github.com> ha scritto:

**Comment by firerflystar** [comment]
so i think it can't allow us to use two extension together eventually.
