### ISSUE TITLE
Add to docs migration from MS Word to docs

### ISSUE THREAD

**Issue by riccardoferretti** [foambubble/foam#295]
Inspired by https://forum.obsidian.md/t/simple-powershell-for-now-script-to-convert-microsoft-word-files-into-markdown-with-pandoc/7121

**Comment by tlylt** [comment]
Hello, may I know where would be a suitable place to insert this note on migration from MS Word to markdown?
- [Recipes - "Workflows"](https://foambubble.github.io/foam/user/recipes/recipes#workflow) ok?

**Comment by riccardoferretti** [comment]
Yes, that sounds like a good place for it, thanks!
