### ISSUE TITLE
Foam Graph should take into account direct MD links

### ISSUE THREAD

**Issue by jmg-duarte** [foambubble/foam#299]
This issue is related to this comment https://github.com/foambubble/foam/pull/290#issuecomment-713870715.

As stated in the comment and in this issue's title: Foam should be able to parse links of the form `[[title](link)]`.

I am not familiarized with the parsing process for the Foam, however, the strategy can be to first include all double braced links (both `[[]]` and `[[]()]`) and then validate the second ones, separating file links from http ones.

EDIT: The bug link is a mistake.

**Comment by riccardoferretti** [comment]
@jmg-duarte thanks for reporting this. As a reference, the place where this would need to be addressed is during the creation of the foam model:

https://github.com/foambubble/foam/blob/a34842b95722cdbaa86ce07a5549bbf3947208a9/packages/foam-core/src/markdown-provider.ts#L48

Either as part of this function, or by adding a similar one, we would also capture internal links that are not defined using the wikilink syntax.
This requires also augmenting the link model, something I have been meaning to look into for a while.
