### ISSUE TITLE
Idea: use built-in Git extension for now

### ISSUE THREAD

**Issue by coffenbacher** [foambubble/foam#30]
This still isn't ideal [1], but IMO a slightly slicker default than requiring the Git Automator extension at the moment is:

.vscode/settings.json
```
  "git.enableSmartCommit": true,
  "git.postCommitCommand": "sync",
```

To save & sync to Github or any remote, it's just `Git: Commit All`. This doesn't require the additional extension and automatically does the sync.

[1] (I think it would be a cooler default and more like Roam to do this automatically when saving files, but I didn't immediately see how to do that...)

**Comment by jevakallio** [comment]
@coffenbacher that's a great idea! I was looking for commands like these in the default integration and couldn't find them, so I went with Git Automator.

I'll take this to use in my local workspace, test it out for a day or so, and if it works implement it into the template!

**Comment by jevakallio** [comment]
Update: Tested this locally, and it's nice. 

The downside of this approach is that it's not possible to automatically set up a keybinding for `Git: Commit All`, so there's one more setup step for the users. But, still worth it IMO.

One way around this would be to add the key bindings to foam-vscode...

**Comment by coffenbacher** [comment]
Great! Nice turnaround time on testing :rocket: 

> One way around this would be to add the key bindings to foam-vscode

That seems like a good approach from a user's perspective. I don't think the average user needs to know how nless they want to move away from the default.

I think I am becoming a big enough Foam fan that I'll try to get my feet wet with PRs here in a bit, thanks!

**Comment by coffenbacher** [comment]
https://github.com/foambubble/foam/pull/32
https://github.com/foambubble/foam-template/pull/6

**Comment by jevakallio** [comment]
Thank you very much @coffenbacher! Merged both 🥳
