### ISSUE TITLE
Following daily note wiki link does not create file correctly

### ISSUE THREAD

**Issue by ingalless** [foambubble/foam#303]
Following a wiki-link generated by a daily note snippet doesn't apply the daily note settings

**Affected package**
`foam-vscode`

**To Reproduce**
1. Set `foam.snippets.navigateOnSelect` to false
2. Generate a wiki link using the snippet **to a day where a note does not yet exist**
3. Ctrl click or f2 into the note
4. Page won't generate following daily note settings

**Expected behavior**
Wiki links matching daily note format should use daily note command

**Comment by riccardoferretti** [comment]
hi @ingalless, a few questions to better understand:
- do you know why this happens? 
- when you say "generate following daily note settings", what do you mean exactly?
- I believe there is also an issue around navigating to files in other directories, wondering if what you are seeing is somewhat due to that as well?

**Comment by ingalless** [comment]
It happens because the default behaviour only expands the snippet out as a wiki link. It doesn't go and create the file

Thus, to create the file you're relying on the default "ctrl+click" behaviour, which may come from markdown links?

Perhaps if "navigateOnSelect" is false then the file should still be created?
---
Let's say I expand the snippet now for tomorrow. That would put in (based on my settings) `[[2020-10-29]]`. No file is created. When I click it I expect the title "Thursday, October 29 2020" but instead get "2020 10 29"
---
It doesn't seem related to me. It's an oversight on the date snippets feature it seems...

**Comment by riccardoferretti** [comment]
yeah that makes sense.

what's your take on how to best approach it?

yes we could create the file, it would solve the problem of the initial content (as well as the custom directory I guess?). I don't love having those empty files around but maybe it's the lesser evil?

**Comment by ingalless** [comment]
@riccardoferretti I wonder if for now creating the file in the background is the simplest way to handle it.
If the ctrl+click behaviour is coming from ~~markdown links~~ markdown notes then we would be battling its behaviour to get our own behaviour I suspect? I doubt we can both register ctrl+click functionality on the same matches!

Happy to sort it if you like 👍🏻

**Comment by riccardoferretti** [comment]
how do you feel about introducing a property `foam.dateSnippets.afterCompletion`, with values:
- `noop`: nothing happens (the user manually manages the note creation)
- `createNote`: creates the note if it doesn't exist, but won't navigate to it (useful to make sure the daily note settings are followed)
- `navigateToNote`: navigates to the note, and of course creates it if it doesn't exist

Probably for conveniency, `createNote` would become the default.

Thoughts?

**Comment by ingalless** [comment]
@riccardoferretti This sounds great to me! Well thought out.
