### ISSUE TITLE
Decouple from VSCode

### ISSUE THREAD

**Issue by duane** [foambubble/foam#313]
What are the plans to decouple dependencies from VSCode, specifically, as an editor?

**Comment by riccardoferretti** [comment]
Hi @duane , we are considering building an LSP for foam, which would enable support in other editors, there are other items on the roadmap with higher priority, so there is no ETA with regards to when this would be implemented.
To better understand the question, what problem are you trying to solve?

**Comment by duane** [comment]
@riccardoferretti I don't have any specific needs but I do tend to use lighter weight computers that might struggle a bit more with VSCode's memory requirements; specifically I'd be interested in Sublime Text integration. I think there are already comparable projects for vim/emacs so I'm less bothered about that.

I fully understand the work that goes into these integrations so it's hardly something I'd expect! I appreciate the work y'all have done.

**Comment by jerabaul29** [comment]
I know this is closed and stalled for a long time, but for my part, the motivation would be to be able to use this with Onivim2 instead of VSC, which I like much better :) (like in, my computer does not feel like sirup when using Onivim2 :) https://github.com/onivim/oni2 ) .

**Comment by martin-braun** [comment]
@duane 

> I think there are already comparable projects for vim/emacs so I'm less bothered about that.

Could you please name a few?

**Comment by jerabaul29** [comment]
Just curious: are there any plans / further work on implementing all of this as a LSP or similar? That would be awesome for functionality.
