### ISSUE TITLE
Automate adding contributors via GitHub Action

### ISSUE THREAD

**Issue by jsjoeio** [foambubble/foam#315]
It would be great if we had a GitHub Action which ran on "merge pull request" and then opened a new pull request to add a person to the all-contributors table in the `README`. It wouldn't solve all the use cases for adding contributors to the table, but a majority of them.

Happy to help guide/mentor someone if they want to pick this up.

**Comment by riccardoferretti** [comment]
hi @jsjoeio - happy to prioritize this myself as it feels important to me. I have no idea where to start, so any help would be greatly appreciated ;)

**Comment by jsjoeio** [comment]
> hi @jsjoeio - happy to prioritize this myself as it feels important to me. I have no idea where to start, so any help would be greatly appreciated ;)

woo! you're the man! :D 

here's how I was thinking of approaching it:
- look at this [GitHub action](https://github.com/marketplace/actions/contribute-list)
- or [this one](https://github.com/sinchang/all-contributors-action)

If one of these doesn't work, then we can look into building our own using something like [this](https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/6) and the [All-Contributors CLI](https://allcontributors.org/docs/en/cli/usage)

Does that help? Happy to continue brainstorming/collabing asynchronously over this issue thread. Just @ me!

**Comment by riccardoferretti** [comment]
@all-contributors add @ingalless for code

**Comment by ingalless** [comment]
Sweet! Thanks @riccardoferretti. I've also contributed some docs too 👀

**Comment by riccardoferretti** [comment]
@jsjoeio ok I think I found a way :) it's not fully automated, but very easy. And I like that it's not fully automated as it requires a bit of work as token of appreciation, so will stick with this for now :) thanks for bringing up this issue!

**Comment by riccardoferretti** [comment]
@allcontributors add @ingalless for docs

**Comment by riccardoferretti** [comment]
@allcontributors add @jmg-duarte for code

**Comment by riccardoferretti** [comment]
@allcontributors add @yenly for docs

**Comment by riccardoferretti** [comment]
@allcontributors add @hikerpig for code

**Comment by riccardoferretti** [comment]
@allcontributors add @Sigfried for docs

**Comment by riccardoferretti** [comment]
@allcontributors add @scott-joe for docs

**Comment by riccardoferretti** [comment]
@allcontributors add @Jackiexiao for docs

**Comment by riccardoferretti** [comment]
@allcontributors add @jbn for docs

**Comment by riccardoferretti** [comment]
@allcontributors add @asifm for docs

**Comment by riccardoferretti** [comment]
@allcontributors add @ariefrahmansyah for docs

**Comment by riccardoferretti** [comment]
ok, I think I have caught up, closing the issue

**Comment by jsjoeio** [comment]
Woooo! Nice work @riccardoferretti :D
