### ISSUE TITLE
["BUG"] Wiklinks not being generated with v0.4 "command 'foam-vscode.update-wikilinks' not found"

### ISSUE THREAD

**Issue by fmagin** [foambubble/foam#316]
**Describe the bug**

No wikilinks are being generated on file save.

Specifically, when manually running the command `Foam: Update Markdown Reference List` I get the error message:

`Command 'Foam: Update Markdown Reference List' resulted in an error (command 'foam-vscode.update-wikilinks' not found)
`

**Affected package**
Probably mainly `foam-vscode` due to the above error

**To Reproduce**

Not fully clear, but I can reproduce this on two different installs and was most likely caused by the update to the v0.4 version

**Expected behavior**
Generate the links like it used to happen

**Comment by fmagin** [comment]
The error message seems to disappear if I strip all frontmatter metadata like in #301 but the links still aren't generated

**Comment by riccardoferretti** [comment]
hi @fmagin, regarding the frontmatter, we are adding better error handling around it.
Regarding the fact that they are still not generated, can you check in your settings the value of `Link Reference Definitions`? if it's `off` the references won't be generated

**Comment by fmagin** [comment]
That is set to `withExtensions`.

**Comment by fmagin** [comment]
I think this specific bug is fixed with v0.5, and I found out more about second bug:

The name of the link, i.e. the text between `[[` and `]]` has to match the target file name (without the `.md`). So I guess the links are not normalized by applying the appropriate slugger before checking if the appropriate file exists?

**Comment by riccardoferretti** [comment]
at the moment we rely on markdown-notes to connect the wikilinks to the notes. on our immediate roadmap we have to support links based on the foam model

**Comment by fmagin** [comment]
But this used to work before, and seems like a major regression to me. Are you sure we are talking about the same issue? The behavior I am encountering breaks the links in the preview pane, and the ones links detected by the Markdown Links Addon. Those links would then also not appear on the Foam graph either.

**Comment by riccardoferretti** [comment]
> So I guess the links are not normalized by applying the appropriate slugger before checking if the appropriate file exists?

Maybe it is something related to this, although I don't believe this has been changed (I might be wrong).

Do you have an example to reproduce the issue?

**Comment by riccardoferretti** [comment]
does it sound like #323 ?

**Comment by fmagin** [comment]
Yes, that is the same issue I am encountering. Closing this issue then, because it wasn't primarily about this problem.

**Comment by riccardoferretti** [comment]
sounds good, let's track it there
