### ISSUE TITLE
["BUG"] Foam: Show graph' fails with "All collection items must start at the same column"

### ISSUE THREAD

**Issue by fmagin** [foambubble/foam#317]
**Describe the bug**

The new graph does not work or it is unclear what is required to make it work.

**Affected package**
unclear

**To Reproduce**
Upgrade to v0.4

Run command `Foam: Show Graph`

`Command 'Foam: Show graph' resulted in an error (All collection items must start at the same column)`

**Expected behavior**
Whatever that command is actually supposed to do.

**Additional context**
https://github.com/foambubble/foam/issues/301 brings up yaml (i.e. frontmatter) as a possible cause for a different error. I also have that in some files and might investigate this. Still I do not think that this feature should break simply because I am using YAML, without ever being told how YAML interacts with it.

**Comment by fmagin** [comment]
Running the command from the other issue and restarting does seem to fix it. Still I consider this a bug, because this forces me to conform to some unknown frontmatter spec (which I'd like to use for other purposes or extensions).

**Comment by riccardoferretti** [comment]
@fmagin sounds like there is a syntax problem in your YAML metadata. I agree that shouldn't cause the whole thing to break, we need to push some error handling in the document parsing.

**Comment by riccardoferretti** [comment]
this has now been fixed by #320
