### ISSUE TITLE
Center markdown link graph on current note

### ISSUE THREAD

**Issue by jessebett** [foambubble/foam#319]
Is there a setting or shortcut or command for centering the Markdown Links graph on the node for the current note? I regularly lose my position and the graph is to visually noisy to locate my current note with just the colour change.

**Comment by jessebett** [comment]
Hm, actually I was still using Markdown Links and not the new Foam Graph.

**Comment by jessebett** [comment]
I realized that I was still using the Markdown Links graph view instead of the new Foam Graph.

**Comment by riccardoferretti** [comment]
this behavior is actually also present in foam, and I agree we should have an option to navigate to the active note - will reopen to track it

**Comment by riccardoferretti** [comment]
addressed in #352
