### ISSUE TITLE
Instead of file names, show titles in the panel

### ISSUE THREAD

**Issue by canpolat** [foambubble/foam#321]
I have a workflow where file names are auto-generated (datetime) and carry no information about the contents of a file. Instead, I use YAML frontmatter (`title` variable/label). I think it would be good to have an option to show the title (and fall back to file names if they don't exist) instead of the file name.

Hopefully this is a feature request that is in alignment with your future plans.

**Comment by riccardoferretti** [comment]
IIUC this is now the case
