### ISSUE TITLE
Hi,how to show markdown-links?

### ISSUE THREAD

**Issue by xieyezi** [foambubble/foam#33]
👋，Thank you for creating this great project!!!!

when I generate repositories by your template,then git clone to local,open it with vscode,and install all recomend  extensions,but I can't preview markdown link?  how can i resolve this ? hope get you reply😊

![image](https://user-images.githubusercontent.com/16821989/86078253-47d74980-bac0-11ea-84ba-26b03ef4925b.png)

**Comment by KJTang** [comment]
show graph ：）
![image](https://user-images.githubusercontent.com/9363734/86079609-760a5880-bac3-11ea-8a48-8c2e8faeeec1.png)

**Comment by xieyezi** [comment]
@KJTang why I  have nothing still ?

![image](https://user-images.githubusercontent.com/16821989/86084278-026e4880-bacf-11ea-82a8-81fbd467d829.png)

**Comment by kawnnor** [comment]
Cmd + Shift + P 「show graph」

**Comment by xieyezi** [comment]
@kawnnor  thanks! I got this😄

**Comment by subhinay** [comment]
> ![image](https://user-images.githubusercontent.com/16821989/86084278-026e4880-bacf-11ea-82a8-81fbd467d829.png)

@xieyezi, may I enquire about the theme you are using?

**Comment by kawnnor** [comment]
May be 「One Dark Pro」

**Comment by subhinay** [comment]
> May be 「One Dark Pro」

I saw it on my phone and somehow missed that. Thank you and my apologies for the redundant question.
