### ISSUE TITLE
Support Prettier

### ISSUE THREAD

**Issue by martonlanga** [foambubble/foam#357]
Formatting with Prettier breaks the autogenerated footer.

On each save, the footer will be inserted once again:
```
[//begin]: # 'Autogenerated link references for markdown compatibility'
[structured-stdio]: structured-stdio 'Structured Stdio'
[easter-eggs]: easter-eggs 'Easter eggs'
[autocomplete]: autocomplete 'Autocomplete'
[cla]: cla 'CLA'
[//end]: # 'Autogenerated link references'
[//begin]: # 'Autogenerated link references for markdown compatibility'
[structured-stdio]: structured-stdio 'Structured Stdio'
[easter-eggs]: easter-eggs 'Easter eggs'
[autocomplete]: autocomplete 'Autocomplete'
[cla]: cla 'CLA'
[//end]: # 'Autogenerated link references'

[//begin]: # "Autogenerated link references for markdown compatibility"
[structured-stdio]: structured-stdio "Structured Stdio"
[easter-eggs]: easter-eggs "Easter eggs"
[autocomplete]: autocomplete "Autocomplete"
[cla]: cla "CLA"
[//end]: # "Autogenerated link references"
```

Disabling prettier works, but I like to have `.md` formatted. Any way to go around this?

**Comment by jmg-duarte** [comment]
You can use the Foam default `"yzhang.markdown-all-in-one"` for the time being

**Comment by SanketDG** [comment]
@martonlanga Do you have a `.prettierrc`? Would be helpful to post the config here.

**Comment by martonlanga** [comment]
Sure, I usually just do something like:
```json
"prettier.semi": false,
"prettier.trailingComma": "all",
"prettier.singleQuote": true,
"prettier.arrowParens": "avoid",
```
Can you reproduce the problem btw?

Thanks guys for working on this!

**Comment by SanketDG** [comment]
Looks like `prettier.singleQuote: true` is the faulty option. Since it convert's Foam's wikilinks from double quote to single quote, Foam regenerates them again at the end of the file.

This seems like most people would be okay with removing that option, is that a viable option for you? :slightly_smiling_face: 
 @martonlanga

**Comment by martonlanga** [comment]
Totally a viable option, thanks for looking into this @SanketDG
