### ISSUE TITLE
["BUG"] Command 'Foam: Open Daily Note' resulted in an error

### ISSUE THREAD

**Issue by keremkayabay** [foambubble/foam#362]
**Describe the bug**
Commands `Foam: Open Daily Note` and `Foam: Create New Note From Template` both results in an error.

- OS: Windows 10
- VSCode version 1.51.1
- Foam for VSCode version 0.6.0

**To Reproduce**
1. Open VSCode workspace with Foam extension (Windows 10)
2. Run either `Foam: Open Daily Note` or `Foam: Create New Note From Template` commands (or press Alt+D)

**Expected behavior**
Daily note opens with today's date.

**Screenshots**
![image](https://user-images.githubusercontent.com/42340157/99937772-88897500-2d77-11eb-9692-6c43db824b24.png)

![image](https://user-images.githubusercontent.com/42340157/99937802-94753700-2d77-11eb-9bbd-4ed2167b3b66.png)

**Additional context**
I was able to use `Foam: Open Daily Note` command until recently. I believe this is due to the Foam for VSCode 0.6.0 update.

**Comment by riccardoferretti** [comment]
hi @keremkayabay, to see if this is the same problem as #363, can you check whether other things (e.g. the graph) work?

**Comment by keremkayabay** [comment]
Just checked, they do not work. It is the same problem with #363.
