### ISSUE TITLE
GitLab Support

### ISSUE THREAD

**Issue by SaundersB** [foambubble/foam#365]
Would it be possible to support GitLab for markdown render?

**Comment by riccardoferretti** [comment]
That's a really good idea.
Unfortunately atm I don't use GitLab (so I can't even estimate the effort on this task) and am focused on a couple of high priority items on our roadmap - but I would love for someone to contribute it.

**Comment by jmg-duarte** [comment]
@SaundersB what do you mean supporting GitLab for MD rendering? 
Could you elaborate?

**Comment by SaundersB** [comment]
@jmg-duarte I'm able to create a foam project, host it in GitLab and standard markdown will render. However, [[wiki-links]] don't seem to work on GitLab. Is it possible to render to something GitLab would be able to display this and other foambubble specific markdown?

**Comment by jmg-duarte** [comment]
Wiki-links are usually rendered in the bottom of the file.
If you're using the default style they will not end in `.md` and thus not work in plain Git sites (GitHub included)

`"vscodeMarkdownNotes.noteCompletionConvention": "noExtension"` should be what you're looking for.
You can change it to include an extension (VSCode will autocomplete with options)

If that still does not work, I ask you to link me to the repository or the a simple minimal example of the problem.

**Comment by jmg-duarte** [comment]
@SaundersB did it work?

**Comment by SaundersB** [comment]
@jmg-duarte Working on it now. I'll respond here

**Comment by SaundersB** [comment]
So I was able to make the change to the extensions settings and I do see the wiki-links render in GitLab markdown rendering.

However, when I click the [[to-do]] I see:  "to-do" did not exist on "master" which means it thinks I'm trying to look at the branch instead of another markdown file.

Do you think this has to do with this: 

```
{
...
 "vscodeMarkdownNotes.noteCompletionConvention": "noExtension",
 "vscodeMarkdownNotes.slugifyMethod": "github-slugger"
}
```

Can I change the slugifyMethod to something like "gitlab-slugger"?

**Comment by SaundersB** [comment]
I'm getting this URL:

`< gitlab_repo_url >/-/blob/master/day-to-day/pending-code`

When I need:

`< gitlab_repo_url >/-/blob/master/day-to-day/pending-code.md`

My vsconfig is: 

```
{
  "editor.minimap.enabled": false,
  "editor.wrappingIndent": "indent",
  "editor.overviewRulerBorder": false,
  "editor.lineHeight": 24,
  "[markdown]": {
    "editor.quickSuggestions": true
  },
  "git.enableSmartCommit": true,
  "git.postCommitCommand": "sync",
  "files.exclude": {
    "**/node_modules": true
  },
  "files.watcherExclude": {
    "**/node_modules": true
  },
  "vscodeMarkdownNotes.workspaceFilenameConvention": "relativePaths",
  "vscodeMarkdownNotes.noteCompletionConvention": "noExtension"
}
```

**Comment by jmg-duarte** [comment]
What would a Gitlab slugger be? I'll be glad to work with you to implement your feature!

**Comment by SaundersB** [comment]
@jmg-duarte Do you know how to get the markdown generated wiki-links path to include the .md?

**Comment by jmg-duarte** [comment]
This should be in your settings: `"foam.edit.linkReferenceDefinitions": "withExtensions",`

**Comment by SaundersB** [comment]
Perfect! Thank you so much that worked!
