### ISSUE TITLE
["BUG"] New link/document created from within a daily note in a daily-note subfolder is *also* put into the daily-note subfolder

### ISSUE THREAD

**Issue by gammak** [foambubble/foam#366]
**Describe the bug**
I have set the daily notes for Foam to be created in a `daily` subdirectory, but adding the following setting to `settings.json`: `    "foam.openDailyNote.directory": "./daily"`.

All the new daily notes are properly added there, and if I create a new link from a *non* daily file, it creates it in the top-level directory appropriately. 

However, if I create a new link from within one of my daily notes by creating a non-existent tag `[[someTag]]` and Ctrl+Clicking it, `someTag.md` will be create under my `daily` folder, rather than in the top-level non-daily folder.

**Affected package**
I would guess that the affected package here is `foam-vscode` due to the fact that `"foam.openDailyNote.directory": "./daily"` seems to be misbehaving or ignored, but I could be dead wrong here.

**To Reproduce**
1. Open `settings.json`
2. Set your daily note directory to `daily`, adding `"foam.openDailyNote.directory": "./daily"`
3. Reload VSCode (not sure if needed, but I did this to test)
4. Create a new daily note
5. Navigate to your new daily note
6. Within that daily note, type `[[someNonExistentTag]]`, and Ctrl+Click the link.
7. Note that `someNonExistentTag.md` exists under your `daily` folder, rather than the top-level directory.

**Expected behavior**
During step 7, I expect `someNonExistentTag.md` to be created under the top-level directory

**Comment by riccardoferretti** [comment]
@gammak is it possible it's just creating the new files in the same directory as where the source note lives?

Can you check the vscode setting `Markdown-note-factory: New Note Directory`?

**Comment by keremkayabay** [comment]
@gammak I also use a folder to store daily notes, and it is working properly. But I am running Foam extension in a workspace. What worked for me is I've added `"foam.openDailyNote.directory": "daily"` to settings in `[workspace-name].code-workspace` file.

**Comment by MCluck90** [comment]
I came here thinking this was a bug but @riccardoferretti was right. My `New Note Directory` was set to `SAME_AS_ACTIVE_NOTE` and can be "fixed" by changing it to `WORKSPACE_ROOT`
