### ISSUE TITLE
Feature Request: List all docs and images which are unlinked by others

### ISSUE THREAD

**Issue by ysl2** [foambubble/foam#367]
Sometimes there are so many files that I can't find out if there are some docs or images in my repository that aren't referenced by other files.

So I was wondering if it could create a file from command palette in a specified path which listed all the unlinked files and images by wiki-link or markdown-link to let me know all the files that are not linked, so that I can  link them or delete them.

**Comment by riccardoferretti** [comment]
I like this idea, I wrote something similar for the graph export (which has not been released yet), but that could be a template for the first iteration on this task - adding it here for reference if someone wants to help out with implementing this.

```
    vscode.commands.registerCommand(
      "foam-vscode.export-graph-data",
      async () => {
        const data = generateGraphData(await foamPromise);
        const doc = await vscode.workspace.openTextDocument(
          vscode.Uri.parse("untitled:data.js")
        );
        await vscode.window.showTextDocument(doc);
        vscode.window.activeTextEditor.edit(editBuilder =>
          editBuilder.insert(
            new vscode.Position(0, 0),
            JSON.stringify(data, null, 2)
          )
        );
      }
    );
```

**Comment by leonhfr** [comment]
I like this idea too and I find myself missing not having it, so I might take a shot at it when time allows. 

What I would include in this feature is also the ability to exclude files from some directories from being listed. For example in my repository there are many unlinked entries in `/journal`, but while I like having them for archiving/references purposes, I wouldn't want them listed.

So a proposal:

- Implement a new `Generate unlinked references file` command
- It would create/update a `unlinked-references.md` file in the root directory
- a `foam.unlinkedReferences.exclude` field in `settings.json` would receive an array of strings and exclude files from those directories being included in the generated file

Example `unlinked-references.md`:

```md
# Unlinked References

## `/journal`

- [[daily-note-2021-01-01]]
- [[daily-note-2021-01-02]]

## `.`

- [[entries-are-sorted-alphabetically]]
- [[they-only-contain-notes-which-are-not-linked-to]]
```

`settings.json`:

```json
{
  // existing properties
  "foam.unlinkedReferences.exclude": ["journal", "archives"],
}
```

We could group the entries by directories, and skip the `## '.'` part when there are none.

@riccardoferretti does this sounds like a good goal for a first iteration?

**Comment by riccardoferretti** [comment]
I like the idea, maybe I would adjust the terminology.
We are talking about notes that have no inbound nor outbound connections to other notes (or placeholders).
Some apps call such note is called orphan. The term is a bit strong, but it can work. I am also curious to explore alternatives.
Unlinked note feels a bit "convoluted", maybe something like "isolated note", but ideally we should use a simple noun.
As an example "placeholder" was originally called "non-existing note" 😅  - I'd say placeholder is better hehe

Once that is sorted, this will be used for everything else. For the sake of example, let's say we go with "orphan".

The command can be "Generate orphans report", or something like that.

In terms of behavior:
- by default I wouldn't save it to a file, but simply create a new panel with the list
- settings with defaults:
  - `foam.orphansReport.path: undefined` if provided, write/update the buffer to the file path
  - `foam.orphansReport.exclude: undefined` will provide a list of globs for notes to be excluded by the report
  - `foam.orphansReport.groupBy: "folder"` property (e.g. `off`, `folder`, ...) will define how the notes are organized in the report (it's fine to start without this property, even though I don't think the effort to support it would be high, and just default to grouping by folder)

The path can simply be relative to the repo root, as you suggested, with the exception of root being `/`. (let's just use posix separator and not go crazy about `/` vs `\`)

**Comment by leonhfr** [comment]
I like those ideas, it feels like a more complete feature.

For the terminology, in graph theory we'd talk about `isolated vertex`, so maybe `isolated note`? Or maybe `singles`? Otherwise I'd say `orphan` sounds good.

Good point about the placeholders too, they indeed shouldn't be in the list.

Also liking the settings and their defaults, more flexible for sure

**Comment by riccardoferretti** [comment]
ok, confirmed for "orphans"

**Comment by leonhfr** [comment]
Sounds good, I'm happy to look at this in the coming days!
