### ISSUE TITLE
Feature Request: Mouse hover preview

### ISSUE THREAD

**Issue by ysl2** [foambubble/foam#370]
Move mouse to a wiki-link or a markdown link, and the file content will be visualized.

**Comment by jmg-duarte** [comment]
If this is to be implemented, it should be optional and the default should be off.
There are people with huge graphs having performance problems so I can't imagine how it would be if we add a preview on top of the graph pane.

**Comment by riccardoferretti** [comment]
The way I read it, this is about links in the text editor (not in the graph panel), is that correct?

**Comment by ysl2** [comment]
> The way I read it, this is about links in the text editor (not in the graph panel), is that correct?

@riccardoferretti Yes, it is in the text editor :-)

**Comment by ysl2** [comment]
I once mentioned that there were a solution for vim user in [this issue](https://github.com/foambubble/foam/issues/369#issuecomment-734636799), but just now I found it also provided a solution for current issue, by using “peekDefinition”.

`{
      // peek definition inline with gD
      "before": ["g", "D"],
      "commands": ["editor.action.peekDefinition"]
    }, `

**Comment by Barabazs** [comment]
Isn't this already implemented? (maybe in vscode)
When I hover over a wiki-link and click `ctrl` I can see a pop-up with the content of the file:

Hover over wiki-link:
![image](https://user-images.githubusercontent.com/31799121/115949993-d8ac6500-a4d8-11eb-9893-d39ac3cbca91.png)

Click on `ctrl`:
![image](https://user-images.githubusercontent.com/31799121/115950004-e6fa8100-a4d8-11eb-84d6-ec95a98ed358.png)

**Comment by SR--** [comment]
I think this will be a very useful feature so here is my vote. This is how it looks like in Markdown Memo.

https://github.com/svsool/vscode-memo/raw/master/help/Attachments/Notes%20and%20images%20preview.gif

**Comment by DawnPaladin** [comment]
Looks like this has been implemented here: https://github.com/svsool/vscode-memo. Maybe that's what @Barabazs is seeing? It's a good feature.

**Comment by Barabazs** [comment]
> Looks like this has been implemented here: https://github.com/svsool/vscode-memo. Maybe that's what @Barabazs is seeing? It's a good feature.

You're right. Very handy feature btw.

**Comment by DawnPaladin** [comment]
It is! Sadly it only works for `[[this]]` link style, not `[this](one)`. So there's still room for Foam to improve on its competitors. 😄

**Comment by riccardoferretti** [comment]
I don't expect this to be a lot of work to implement. The pieces are already there (hover on links in text editor, and markdwon preview which we use in our panels). Anyone wanna take this on? ;)

**Comment by JonasSprenger** [comment]
@riccardoferretti I have created a duplicate with https://github.com/foambubble/foam/issues/727, this issue can also be closed because the over feature was implemented in https://github.com/foambubble/foam/pull/728

**Comment by riccardoferretti** [comment]
Yup good point, thx!
