### ISSUE TITLE
["BUG"] Link References are not generated in a way that allows the default preview to recognize them

### ISSUE THREAD

**Issue by fmagin** [foambubble/foam#374]
**Describe the bug**

Autogenerated link references are using the sluggified link text instead of the original one, leading to links inside the preview being broken.

This definitely worked at some point before I still have old notes with this format.

**To Reproduce**

See screenshots, happens on version 0.7.0, potentially already in 0.6.0 or even earlier versions. 

**Expected behavior**

The Markdown References links can be generated in the format that allows the links in the preview to work. This might be the generally better option and could be non configurable default behavior, but in case other setups require the format that does not allow the preview link to works this could be made configurable.

**Screenshots**

Link text is already sluggified: Preview Link works
![image](https://user-images.githubusercontent.com/8415354/100262763-e7541780-2f4c-11eb-82a0-a6873ffaf255.png)

Link is changed during slugging: Preview Link does not work
![image](https://user-images.githubusercontent.com/8415354/100263056-4c0f7200-2f4d-11eb-8934-4ef9b449c2b8.png)

Reference is manually edited to contain the non sluggified link text: Preview Link works
![image](https://user-images.githubusercontent.com/8415354/100263143-68abaa00-2f4d-11eb-871e-4815851d99a1.png)

**Comment by SanketDG** [comment]
I can't seem to replicate this, what preview is this?

**Comment by fmagin** [comment]
Should be the completely normal markdown preview. What part of this can't you replicate, e.g. do all of the links work in your case?

**Comment by jmg-duarte** [comment]
Quick aside since GitHub has no DM's, what are the fonts you're using @fmagin?

**Comment by fmagin** [comment]
[Jetbrains Mono](https://www.jetbrains.com/lp/mono/) primarily, exact fontconfig in VSCode is `'JetBrains Mono', 'monospace', monospace, 'Droid Sans Fallback'` Can highly recommend the Jetbrains font, I use it in every editor.

**Comment by jmg-duarte** [comment]
What about the interface/system font?

**Comment by fmagin** [comment]
Those are just the defaults, found nothing in my VS Code settings that sets them specifically. If you have further questions you can just DM me on twitter, they should be open.

**Comment by riccardoferretti** [comment]
@SanketDG could this be related to the change in the slugification?

**Comment by SanketDG** [comment]
> could this be related to the change in the slugification?

It is, it's silly of me to not test my changes on Github and the normal markdown preview in VSCode.

I was just so focused on making my graph work and look all pretty.

Turns out the real reason for #323 not working is because the internal "Note Graph" uses slugs but not names, and not the other way around.

I have an one-liner fix, but let me try and understand how the internal graph implementation and the wikilinks all come together so that I do not miss edge cases like this.

**Comment by riccardoferretti** [comment]
@SanketDG re the new generic implementation, I can spec it out and share for comments. But that plus the work could take a few days to get done, and I'd rather not wait that long to fix this issue.

Happy to guide you through the internals of the graph if you need it to get confidence on the fix.

**Comment by fmagin** [comment]
This seems to be fixed with 0.7.3, so I'm closing this
