### ISSUE TITLE
["BUG"] Graph does not use the full size of its pane after the pane is resized

### ISSUE THREAD

**Issue by fmagin** [foambubble/foam#375]
**Describe the bug**
Graph does not use the full size of its pane after the pane is resized, see screenshot

**To Reproduce**

1. Open the Foam Graph
2. Change the size of the resulting window by dragging the edge and make it larger
3. Observe that the graph view is cut off at the right and/or bottom end despite the pane still having space left

**Expected behavior**

That the graph view detects changes to its pane size and uses this window size. This should affect the actual layout, so this should be possible to do without any performance penalty

**Screenshots**

![image](https://user-images.githubusercontent.com/8415354/100263947-6f86ec80-2f4e-11eb-940b-a1aa53daba7f.png)

**Additional context**

It seems like the issue is in the view on the graph that which size is calculated once when the graph is generated and will stay this size no matter the size of the pane. If the pane is dragged smaller and then larger it will still be the size of the original pane when the graph was first opened.

**Comment by ingalless** [comment]
Just flying by to add that I noticed this the other day!

**Comment by riccardoferretti** [comment]
yup, on my plate - let's make this official :)

**Comment by jmg-duarte** [comment]
Quick comment, I would not put this as a good first issue, this comes from personal experience.

**Comment by riccardoferretti** [comment]
haha ok :)

**Comment by riccardoferretti** [comment]
I think it's one of those things that it's easy if one knows where to look, but gets quickly very complicated otherwise
