### ISSUE TITLE
Publish to Netlify

### ISSUE THREAD

**Issue by SanketDG** [foambubble/foam#38]

**Comment by jevakallio** [comment]
This could be added to Recipes. Help wanted.

**Comment by Trimankaur** [comment]
Hi , I would like to work on this issue. I am a first timer so can you please suggest me steps for getting started ?

**Comment by bclinkinbeard** [comment]
[Netlify's docs](https://docs.netlify.com/configure-builds/get-started/#basic-build-settings) show the steps to follow for connecting a repo. Once connected I guess you'd need a build step to go from Markdown to HTML.

**Comment by Trimankaur** [comment]
Thank you @bclinkinbeard for the information. 
I would like to be assigned this issue so that I can start working on it at the earliest.

**Comment by jevakallio** [comment]
@Trimankaur thanks for your interest! I'm not on my computer until tomorrow but will write out any "requirements" / expectations from Foam PoV tomorrow at my earliest convenience.

Feel free to start looking at this. Foam Gatsby Template might be a good starting point for static site generation

**Comment by synesthesia** [comment]
A subtlety might be to look at how often a build is started, so far have thought of two scenarios where building on Netlify on every push might be wasteful of build minutes (£):

* if using GistPad or other v tight sync where every file save is a push
* when running post-push GH actions e.g. Foam Janitor, which potentially generate changes and a new commit / push 

[This Netlify forum post](https://community.netlify.com/t/build-deploy-via-webhook-only/2516) May be useful.

**Comment by martinlaws** [comment]
In my opinion, a big part of the benefit of deploying to Netlify is the ability to quickly configure their [Identity service](https://docs.netlify.com/visitor-access/identity/#enable-identity-in-the-ui) for easy + secure user authentication. I'm going to tinker with setting that up for my own instance of `foam-gatsby-template`, and would be happy to contribute my learnings back as a recipe, would that be valuable?

**Comment by martinlaws** [comment]
Update - I also found a super simple way to run a built `foam-gatsby-template` project's `index.html` through [StatiCrypt](https://robinmoisson.github.io/staticrypt/) during Netlify's build for a super simple way to password protect a deployed Gatsby Foam instance. You're welcome to try to break into mine at https://mlawsbrain.netlify.app/

**Comment by martinlaws** [comment]
> In my opinion, a big part of the benefit of deploying to Netlify is the ability to quickly configure their [Identity service](https://docs.netlify.com/visitor-access/identity/#enable-identity-in-the-ui) for easy + secure user authentication. I'm going to tinker with setting that up for my own instance of `foam-gatsby-template`, and would be happy to contribute my learnings back as a recipe, would that be valuable?

Actually, I take this back (lol don't mind me conversing with myself here). I think I've found a simpler way to password-protect a deployed Foam instance (in my case, using `foam-gatsby-template`).

I've just run the built project's `index.html` through [StatiCrypt](https://robinmoisson.github.io/staticrypt/) during Netlify's build for a super simple way to password protect a deployed Gatsby Foam instance. You're welcome to try to break into mine [here](https://mlawsbrain.netlify.app/). I'll open a separate PR to add that as a recipe if anyone's into it and it isn't too technically complex for folks?

**Comment by riccardoferretti** [comment]
That's a really good idea! I didn't know about StatiCrypt and it looks pretty cool. 

I have actually found a way to get into your site (won't share how, so that other people can give it a try).
I can say you have listed that you are currently playings 4 games, amongst which Starcraft (by the way, great taste, the most amazing game!) 

Password protecting the site (or parts of it) sounds like an interesting feature!
