### ISSUE TITLE
Create note from template - template name not accepting!

### ISSUE THREAD

**Issue by aldrinjenson** [foambubble/foam#380]
Hi, I started using Foam from yesterday and I really love it so far ❤️  .

I watned to try out the template feature for daily notes, which will include a link to an index file.
I created a .foam/templates directory and inside it, added a daily.md and a code.md file which contains some markdown I plan to use as a template. However, I am confused on how exactly to use this template.

When I try: create new Note from template command,
I am getting an empty prompt in which no matter whatever content I enter, I am not able to go to the next one,
![image](https://user-images.githubusercontent.com/53407417/100371036-36717980-302d-11eb-8c64-8253e9f3dda1.png)

P.S. I tried entering daily.md itself and when enter key is pressed, I am not able to go to the next one.

When escape is pressed, then it asks for the path and file names,
but then it results in the following error in the end once the names are entered:
![image](https://user-images.githubusercontent.com/53407417/100370302-12f9ff00-302c-11eb-9869-53aa99fd87ff.png)

**Affected package**

- [ ] `foam-cli`
- [ ] `foam-core`
- [x] `foam-vscode`
- [ ] `other/meta/???`

**To Reproduce**

**Expected behavior**
When the template name is entered, it should take the user to the next prompt

**Screenshots**

**Additional context**

I am not sure if this is a bug, or if I am missing something here. 🤔  Any advice would be really appreciated. 
Also, great thanks for putting together this wonderful software. 😍

**Comment by ingalless** [comment]
@aldrinjenson Hey! I notice there's a typo in your screenshot. Your folder is `.foam/tempates` (notice, no L), but it should be `.foam/templates`

Let me know if that sorts things!

**Comment by aldrinjenson** [comment]
@ingalless , Yes!!, It just fixed my issue.
It was so silly of me to not notice this this typo!
I'm closing this issue rn. Thank you and sorry for the trouble.
