### ISSUE TITLE
'Command 'Foam: Show graph' resulted in an error (command 'foam-vscode.show-graph' not found)'

### ISSUE THREAD

**Issue by Alekhine51** [foambubble/foam#389]
- Foam version: 0.60

**Summary**

Displaying a graph with Foam returns the error message in the title. I realize the codebase is at 7.2 as of today, so I don't know if this has been fixed or not.
**Steps to reproduce**
1. Install Foam using Foam-template
2. Enter command 'Foam: Show graph'

Does this issue occur on the [foam template](https://github.com/foambubble/foam-template) repo? **Yes**

**Additional information**

*Feel free to attach a screenshot and/or include a zip with a minimal repo to reproduce the issue*
I am using VSCodium v1.51.1

**Comment by riccardoferretti** [comment]
It should have been fixed, can you update and let us know?

**Comment by Alekhine51** [comment]
@riccardoferretti How do I manually install the extension?

**Comment by Alekhine51** [comment]
Updated. It now shows a new window, but no actual graph is displayed.

**Comment by SanketDG** [comment]
So even the nodes with file names don't appear?

Is there a sample repo that I could take a look at?

**Comment by deceptikon** [comment]
![image](https://user-images.githubusercontent.com/10824151/100837649-304f2300-349b-11eb-9fa3-0c5be2d02f9b.png)
Having same error, just installed from a latest foam-template and getting this, while trying to show graph

**Comment by mmoran0032** [comment]
This appears to be broken for *any* `foam-vscode.*` commands:

![image](https://user-images.githubusercontent.com/972164/101094271-5cd96c80-3579-11eb-8d43-9c7595653939.png)

Taken from newly-installed template repo with the following recommended extensions installed:
```
foam.foam-vscode
esbenp.prettier-vscode
yzhang.markdown-all-in-one
kortina.vscode-markdown-notes
tchayen.markdown-links
```
Extension `foam.foam-vscode` is v0.6.0.

**Comment by SanketDG** [comment]
@mmoran0032 Can you try `0.7.2`, just to be safe?

**Comment by Alekhine51** [comment]
@SanketDG I'm on the latest version, downloaded from the marketplace website via a `.vsix` file. `Foam: Open Daily Note` works along with other commands, but the 'show graph' command shows a blank page.

@mmoran0032 For some reason auto-update isn't working. Go to [here](https://marketplace.visualstudio.com/items?itemName=foam.foam-vscode) and click on 'version history' then download and install v0.72. There's an 'install from VSIX' option in the extensions menu in VSCode.

**Comment by riccardoferretti** [comment]
@Alekhine51 was this happening in a Windows environment? we just released a new version that fixes some path related issues for Windows

**Comment by Alekhine51** [comment]
@riccardoferretti Just updated to latest version, it works now!

**Comment by mihaimaruseac** [comment]
Just a note: in 0.26.0, the error shows up again. Switching to the older 0.25.12 works.
