### ISSUE TITLE
Extension not compatible with VS Code 1.45 

### ISSUE THREAD

**Issue by ahoho** [foambubble/foam#39]
I'm encountering the following error when I try to install the Foam extension:

`Unable to install 'foam.foam-vscode' extension because it is not compatible with the current version of VS Code (version 1.45.1)`

Seems minor, but I didn't see this listed in the existing issues so figured I'd mention it.

**Comment by jevakallio** [comment]
@ahoho thanks! Is there a reason you can't update to latest VS Code?

**Comment by ahoho** [comment]
Wow, I'm so embarrassed---I didn't realize there was an update available!

**Comment by jevakallio** [comment]
Ha, that's ok! Thanks for reporting! I think there are some users who are stuck on an older version (I think there's an iPad for or something?), which is why I asked.

Glad you got it sorted!

**Comment by jevakallio** [comment]
@ahoho just an update for you and any future spectators, I've just released [foam-vscode@0.1.6](https://github.com/foambubble/foam-vscode/releases/tag/v0.1.6) with VS Code 1.45.1 support
