### ISSUE TITLE
Feature request: snippet or command to insert link to today's note

### ISSUE THREAD

**Issue by aschampion** [foambubble/foam#395]
As described, should be trivial and can be keybound. This is very convenient for referencing daily notes from topic notes when work is done. I'm creating this issue as a reminder to myself to hack on this if no one else does.

**Comment by SanketDG** [comment]
I might be understanding this wrong, but doesn't typing in `/today` insert the daily note reference?

**Comment by aschampion** [comment]
It does indeed, I had not yet discovered that. Thanks!

**Comment by ingalless** [comment]
> It does indeed, I had not yet discovered that. Thanks!

A few more for you

- `/tomorrow`
- `/yesterday`
- `/dayofweek` (where `dayofweek` is a day of the week (e.g. Monday))
- `+nd` (where n is number of days)
- `+nw` (where n is number of weeks
- `+nm` (where n is number of months)
- `+ny` (where n is number of years)

I should really document these...

**Comment by riccardoferretti** [comment]
yeah @ingalless - now that we have reorganized the docs it would be great if we could add some documentation, maybe in  a `docs/features/dates-snippets.md` or something like that.

For higher level considerations, I will defer to #355
