### ISSUE TITLE
Feature request: command to collapse items in a markdown list with checked checkboxes

### ISSUE THREAD

**Issue by aschampion** [foambubble/foam#396]
This is convenient when editing large TODO lists. VSCode already has appropriate parsing with collapsable regions. Likely should be implemented in one of the markdown plugins rather than foam itself. I'm creating this issue as a reminder to myself to hack on this if no one else does.

**Comment by riccardoferretti** [comment]
This sounds like an interesting addition to markdown editing.
As it is not strictly related to Foam, I will close it.
