### ISSUE TITLE
Graph "freezes" when deleting node that links to file that doesn't exist

### ISSUE THREAD

**Issue by AndrewNatoli** [foambubble/foam#397]
- Foam version: 0.7.2
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
Scenario that can cause the graph will "freeze" (does not update, can not click / drag, etc)

**Steps to reproduce**
1. Create a new note
2. Add some `[[link]]`s to notes that exist.
3. Add a link to `[[file-that-does-not-exist]]`
4. Save. File that does not exist should not appear in the footer links (as it does not exist)
5. Delete your note.
6. Graph may update but should now be frozen

**Comment by hikchoi** [comment]
I just found this also happens when renaming. I guess it's the same thing as deleting (and then making a new note with a new name).

The graph will freeze before it gets a chance to update with the newly renamed note.
