### ISSUE TITLE
Foam template includes dead link to Foam Tips

### ISSUE THREAD

**Issue by TheLonelyGhost** [foambubble/foam#402]
- Foam version: v0.7.2
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
Foam template repository includes link to Foam Tips on the official website, but the link ends up in a 404 error.

**Steps to reproduce**
1. Clone foambubble/foam-template@b6ec501cf1cf11e193e66a733ff8e75ceda7e7a4
2. Open `foam-tips.md`
3. Follow link to https://foambubble.github.io/foam/recipes
4. See 404 error

**Additional information**

N/a.

**Comment by riccardoferretti** [comment]
thanks for reporting this issue @TheLonelyGhost - the template has been fixed
https://github.com/foambubble/foam-template/commit/6d46be1fded17601e082a8bec69d485fb49355b3
