### ISSUE TITLE
ENOENT: mkdir on Windows

### ISSUE THREAD

**Issue by plttn** [foambubble/foam#405]
The "Open Daily Note" command seems to be trying to run mkdir on Windows.

**Comment by riccardoferretti** [comment]
@plttn thanks for reporting this issue, can you share the problem you are experiencing and how to reproduce it?

I saw this note on the function we use:
https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback
That sounds like the source of the problem.

I suggest using https://github.com/jprichardson/node-fs-extra as a solution, given I already wanted to introduce it for other reasons and it supports this use case.

**Comment by MCluck90** [comment]
I'm running in to this when running "Open Daily Note". I don't see any error messages or stack traces in the developer console

**Comment by plttn** [comment]
Hmm, interesting. This works on my work laptop, but on my personal laptop it errors out.

**Comment by riccardoferretti** [comment]
I have published 0.7.5 - https://github.com/foambubble/foam/releases/tag/v0.7.5
