### ISSUE TITLE
Foam Graph fonts are blurred 

### ISSUE THREAD

**Issue by jmg-duarte** [foambubble/foam#409]
I'm currently running Foam 0.7.5 on VSCode 1.52.1 (Ubuntu 20.04)

The Foam graph is somewhat blurred, while the effect is small, it is noticeable.
![image](https://user-images.githubusercontent.com/15343819/102609253-15c7ab80-4123-11eb-8e50-69c34d14b34b.png)

I think this is due to the fonts being incredibly small.
This should definitely be a setting.

![image](https://user-images.githubusercontent.com/15343819/102609287-1fe9aa00-4123-11eb-9d4f-ec0b100ba3ba.png)

Furthermore, the font should scale (even if just a bit) as the user zooms in and out.
Additionally, having the labels disabled (not reducing opacity, really disabled) past a certain threshold should yield better performance as well as a better UX as there is not a cluster of information in the screen which isn't really usable.
![image](https://user-images.githubusercontent.com/15343819/102609628-b918c080-4123-11eb-93d3-96d2d9b6b21d.png)

**Comment by riccardoferretti** [comment]
I agree with all of the above. I think the graph can have one more major improvement.
Will write some specs around the graph behavior these days and create an issue for review

**Comment by jmg-duarte** [comment]
I'll be closing this issue in favor of #436 which is more broad while still relating to the graph
