### ISSUE TITLE
Foam Janitor ENOENT error

### ISSUE THREAD

**Issue by doodlewhale** [foambubble/foam#410]
- Foam version: 0.7.5
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
Error when trying to run Foam Janitor:

`Foam Janitor attempted to clean your workspace but ran into an error. Please check that we didn't break anything before committing any changes to version control, and pass the following error message to the Foam team on GitHub issues: ENOENT: no such file or directory, open 'C:\c:\Users\xxx\xxx\xxx.md' Error: ENOENT: no such file or directory, open 'C:\c:\Users\xxx\xxx\xxx.md'`

Note: file path changed to \xxx to obfuscate my real folders. The `C:\c:\` is in the error though.

**Steps to reproduce**
1. Run Foam Janitor

**Comment by riccardoferretti** [comment]
Related to #407 and #405

**Comment by targodan** [comment]
Same thing here. It also happens when the actual directory is not on `C:\`, my directory is on `D:\` and I get the same error with `C:\d:\...`

**Comment by riccardoferretti** [comment]
I juste released 0.7.6, which fixes this issue. let me know if the problem persists

**Comment by doodlewhale** [comment]
Yes, all good now. Janitor ran successfully and graph now looks good too! Thank you @riccardoferretti
