### ISSUE TITLE
Code Server compatibility

### ISSUE THREAD

**Issue by RustyWraith** [foambubble/foam#414]
I'm not able to make Foam work as intended on self-hosted [code-server](https://github.com/cdr/code-server).
Links seem broken while graph animations and move/select interactions are not working at all.
**code-server**
![image](https://user-images.githubusercontent.com/11280514/103173622-2ee00300-486d-11eb-88f5-7c825b10f462.png)
**VScode**
![image](https://user-images.githubusercontent.com/11280514/103173757-3653dc00-486e-11eb-9298-6f6e059ab311.png)

**Comment by riccardoferretti** [comment]
thanks for reporting this @RustyWraith, unfortunately code-server is not officially supported, so it's not high priority for us to fix this issue, but if you are happy to look into it we could assist

**Comment by RustyWraith** [comment]
Thank you for your answer!
I believe, I'm not competent enough to dig into this problem myself.
However, I was able to somewhat reproduce the bug in VScode.
Steps: Open foam folder -> Run Foam:Show Graph -> Save Workspace -> Close window, open workspace
Reopened graph window is now static lacking any interactivity. You can run another Foam:Show Graph to open working one.
![image](https://user-images.githubusercontent.com/11280514/103179059-52b93e00-4899-11eb-80fd-d20ebca0647d.png)

**Comment by RustyWraith** [comment]
Ok. If one looks closer on the last screenshot, he will figure out the source of the problem.
Don't confuse Foam:Show Graph with Markdown Links:Show Graph.
So code server works as intended in this case.

**Comment by riccardoferretti** [comment]
Great, thanks for clarifying this. Will close the issue then!
