### ISSUE TITLE
Support for Codium?

### ISSUE THREAD

**Issue by pkoch** [foambubble/foam#42]
There are some people in this world that would rather use OSS. Code is not OSS, but [Codium](https://vscodium.com/) is.

However, when using the template, I get a bunch of weird behavior. Namely:
- It installs a bunch of extensions I never heard of
- It tells me there's problems with the suggested extensions

![Screenshot from 2020-07-01 13-04-08](https://user-images.githubusercontent.com/9627/86242215-3e231400-bb9c-11ea-86c2-8ef9eda7dcc3.png)

They did get installed, but this message is there on every boot.

Perhaps there's something we can do to make life easier for folks who use Codium?

PS: I could also just have messed something up. It's super weird that Codium installed stuff like [WakaTime](https://wakatime.com/)'s extension.

**Comment by jevakallio** [comment]
Thanks for reporting! This is already being tracked at https://github.com/foambubble/foam/issues/26zinsya

The third party extensions are how this version of Foam works. Down the line I want bring more functionality in-house, but for now that's what it is.

No idea about WakaTime tho, that's not us.

**Comment by pkoch** [comment]
Thank you for shepherding me! :two_hearts:
