### ISSUE TITLE
Support spaces in wikilnks

### ISSUE THREAD

**Issue by riccardoferretti** [foambubble/foam#423]
This feature is about enabling wikilinks using the file name without slugification.

Currently wikilinks are slugified e.g.: 
- in markdown notes, when cmd+click on wikilink, the generated file name is slugified
- foam itself slugifies graph connections

**Comment by joaosa** [comment]
Any news on this? I would say this is essential for my workflow 😃

**Comment by riccardoferretti** [comment]
#467 addressed a good chunk of this issue, will be merged today or tomorrow. 
That will address the graph and the anything that comes from the Foam extension itself.

Markdown notes doesn't support this yet, which means link navigation / note creation won't work yet. 
The best workaround atm is to replace markdown notes with vscode-memo.

Let me know how it goes

**Comment by joaosa** [comment]
@riccardoferretti sorry for delay! Thank you! I can confirm wikilinks navigation works with either https://github.com/svsool/vscode-memo or https://github.com/kortina/vscode-markdown-notes 🎉 

I somehow assumed this would also solve regular markdown links with spaces but that doesn't seem to be the case. Any ideas?
