### ISSUE TITLE
Full support for markdown links

### ISSUE THREAD

**Issue by edrex** [foambubble/foam#427]
Meta issue for rough edges using markdown-style links with Foam

To check for support for both markdown-style relative links with extension (`[foo](./foo.md)` or `[foo](foo.md)`) and without.

 * [ ] Foam link graph
   * *Test result: Doesn't pick up links either with or without extension.*
 * [ ] Markdown link graph
 * [ ] What other features am I missing?

**Person msg:** I just installed foam and I'm using it with my existing markdown note repository, which uses markdown-style relative links *without* extension, like `[foo](./foo)`. The other tooling I use (vscode link follow, vimwiki, lervag/wiki.vim, ikiwiki) supports these links, and according to https://github.com/foambubble/foam/issues/16#issuecomment-652525890 Foam should support, but I'm seeing some problems so I'm creating this meta-issue to track rough edges.

**Comment by riccardoferretti** [comment]
Thanks for this @edrex, it's going to help consolidating the various issues that surround links in one place.
Here are some related issues: #299, #306, $424, #426.
