### ISSUE TITLE
unlink and delete the file

### ISSUE THREAD

**Issue by itisbean** [foambubble/foam#43]
I deleted one markdown file, and remove the `[[FILENAME]]` in other linked files, then `Ctrl`+`s` to save.But the deleted filename automatically appears again.Does it have caches in vscode or ohther reason?

**Comment by jevakallio** [comment]
Thanks for reporting @itisbean! This is a [known issue](http://foambubble.github.io/foam/known-issues), 
 simply haven't had the time to implement the note removal yet. 

I've created a documented tracking issue for this in foam-vscode: https://github.com/foambubble/foam-vscode/issues/15, happy to continue discussing there!
