### ISSUE TITLE
Date wikilink shortcuts expand incorrectly

### ISSUE THREAD

**Issue by riccardoferretti** [foambubble/foam#432]
- Foam version: 0.7.7
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
The date wikilink shortcuts (e.g. `/today`) expand incorrectly (e.g. `/[[2021-01-05]]` instead of `[[2021-01-05]]`)

**Steps to reproduce**
1. open a document
2. type `/today` and press enter
3. you will get `/[[2021-01-05]]` instead of `[[2021-01-05]]`

**Comment by alainrk** [comment]
I get the same issue but with backslash instead:

`/[[2021-05-02]]`

**Comment by riccardoferretti** [comment]
@alainrk interesting, and let me guess, are you on a Win machine?

**Comment by alainrk** [comment]
@riccardoferretti sorry, didn't mention it, it happens on MacOS big sur

**Comment by riccardoferretti** [comment]
mmmm.. actually I was wrong in the original description. I put `\` instead of `/`. makes sense now
