### ISSUE TITLE
Wrong URL in the documentation

### ISSUE THREAD

**Issue by zkarampa** [foambubble/foam#437]
- Foam version:  v0.7.7 
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No

**Summary**
URL in the documentation points to unknown page.

**Steps to reproduce**
1. Go to https://foambubble.github.io/foam/features/link-reference-definitions
2. Click on the link in the Example: "You can open the raw markdown to see them at the bottom of this file"
3. Should not get page not found.

**Comment by riccardoferretti** [comment]
thanks! this has now been fixed
