### ISSUE TITLE
Idea: web clipper

### ISSUE THREAD

**Issue by plainspace** [foambubble/foam#44]
Evernote, Notion, TiddlyWiki, Joplin all have web clippers. Foam would be even more awesome if it had one.

**Comment by subhinay** [comment]
There is one for VS Code: [Web Clipper - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=jsartelle.web-clipper) - Clip the contents of a web page into a Markdown document using the Web Clipper: Clip Web Page command.

**Comment by jevakallio** [comment]
@plainspace can you check if that one works for your needs? If it does, I'd love to see a PR that adds a new recipe to the Recipes section on the Foam website

**Comment by plainspace** [comment]
The VS Code extension works really well. I think the issue is that it references images on the website instead of creating a local version. The problem is that if the image is deleted on the web, you lose it. Any thoughts on making it work for Foam such that the image would actually be downloaded and stored with the markdown file?

**Comment by riccardoferretti** [comment]
I wonder if that is better addressed on the VS Code extension itself, maybe even put forward a PR for it (glancing at the code it looks reasonably easy to implement).

Alternatively, as the extension is a thin wrapper around [Mercury](https://github.com/postlight/mercury-parser), it could also just be built into Foam with a tailored integration (e.g. convention for file path).

**Comment by jevakallio** [comment]
@plainspace, as @riccardoferretti said, this is better solved in the extension itself, feel free to open a PR (or issue) there.

I'd still be keen to have a [recipe](https://foambubble.github.io/foam/recipes) for it on Foam!

**Comment by steveklabnik** [comment]
The extension is good, but has a few flaws. There's the above image one, but also:

* The workflow I want from a web clipper is to be in the browser, and click a button. This makes you paste a URL into Code.

* The extension provides a URL to do something like this, but because it's `vscode://`, if you put this into a bookmarklet, for example, chrome will ask you if you want to open Code, which is also less than ideal. 

* Beyond these issues, it also can't deal with logged in content at all, which is a bummer.

Still very cool, but not quite there yet.

**Comment by plainspace** [comment]
@steveklabnik agreed that a browser extension would be ideal. Should be pretty easy once the core features are there. Joplin has a web clipper extension that is solid. FYI: https://github.com/jsartelle/vscode-web-clipper/issues/3

**Comment by I4son** [comment]
hi all, reposting here for easier tracking. I've come across this while looking for web clipper extension. 

[markdown-clipper](https://github.com/deathau/markdown-clipper) is a chrome extension that use Readability.js and Turndown behind the scene and able to save content fo file.

**Comment by VPetukhov** [comment]
On the topic of clippers, there is a beta open-source tool https://getmemex.com/, which provides annotation functionality for web pages and it is roam-friendly. I don't mean that it can replace a web-clipper now, but they develop fast, and probably in a half of a year it will be a good addition for the Foam.

**Comment by riccardoferretti** [comment]
@VPetukhov I have used memex for a bit, really like the project, but I haven't figured out how to properly export/integrate it with other tools. They recently released https://worldbrain.github.io/storex-docs/#/storex-hub/ but haven't had a change to look deeply into it.
What do you mean by the are roam-friendly?

**Comment by VPetukhov** [comment]
@riccardoferretti , I mainly meant the [Text Export Template](https://www.notion.so/Text-Export-Templates-bb1794c15dea4e588a59b52d37ca0070) feature, which allows to copy-paste individual annotations with references to an external knowledge base. And generally, they reference Roam and Obsidian in several places across the web-site, which makes me think that they will be mindful about integrations.
