### ISSUE TITLE
A comparison to other personal knowledge management systems

### ISSUE THREAD

**Issue by ingalless** [foambubble/foam#446]
From the hackernews comments today:

> My 2 cents: I'd have liked to find a "Why this is better than for instance Notion" somewhere in the Readme

I thought this sounded like a good idea. "Why this is better than x" is probably not the route to take, but perhaps "why you may enjoy this over x".

**Comment by riccardoferretti** [comment]
this seems related to https://discord.com/channels/729975036148056075/729976652448137269/800425283978526731

I would prefer to offload this to a third party we can point to. I believe it's the best way to avoid keeping the doc constantly up to date and maintain it.

Maybe though there are other benefits in having it in house? thoughts?
