### ISSUE TITLE
Numeric tags not being recognized in tag explorer

### ISSUE THREAD

**Issue by bserrao** [foambubble/foam#451]
- Foam version: 0.7.7
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
When using full numeric tags (#2021), those get correctly highlighted in VSCode but don't get listed on tag explorer

**Steps to reproduce**
1. Edit any markdown document inside Foam with a numeric tag (#2021)
2. Save file, and check tag explorer

**Additional information**
This only happens when using a fully numeric tag like #2021. If i include letters in any position of the tag, it works as expected.
For instance: #2021y , #20y21 are correctly picked up by tag explorer

Also look at #382 where changes where made related to tag parsing.

Thanks

**Comment by mngad** [comment]
So I thought I'd approach this as a `good first issue`. Turns out this can be added by extending the regex from [a-zA-Z] to [a-zA-Z0-9]. 

However, there's a test that checks that tags with only numbers in them are ignored:

      it('ignores tags that only have numbers in text', () => {
        expect(
          extractHashtags('this #123 tag should be ignore, but not #123four')
        ).toEqual(new Set(['123four']));
      });

So this is obviously a desired feature and more of a discussion point than a `good first issue`.

**Comment by pderaaij** [comment]
@riccardoferretti I've had the same thing as @mngad ran into. I was looking into solving this issue, but it looks the behaviour is intentional. Any thoughts how you'd like to see this continued?

**Comment by riccardoferretti** [comment]
yup, numeric tags will not be supported for the time being
