### ISSUE TITLE
Feat: (local) Image pasting

### ISSUE THREAD

**Issue by cmcconomy-element** [foambubble/foam#454]
Consider adding this capability:
https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image

perhaps as a sane default create a default image path - I found the following to be useful:
"pasteImage.path": "${currentFileDir}/images/${currentFileNameWithoutExt}"

This way the attached images are filed in an images folder, under the topic, and by default with a timestamp.

**Comment by riccardoferretti** [comment]
This is a very good idea, can you create a PR for it in https://github.com/foambubble/foam-template?

**Comment by cmcconomy-element** [comment]
Ready for review/merge.

**Comment by SanketDG** [comment]
https://foambubble.github.io/foam/recipes/add-images-to-notes

It's already there, although could use some brushing up with the recommended setting!

> Also - if you want to advertise openness to PRs, you could embed the following in the foam readme:

Wait, did you create this? I remember playing with this yesterday and got pretty cool insights on mega projects.

**Comment by cmcconomy-element** [comment]
> https://foambubble.github.io/foam/recipes/add-images-to-notes
> It's already there, although could use some brushing up with the recommended setting!

My bad - I guess I duplicated someone else's research and ended up choosing one of those as default?? :p 
I suppose the page would have to change to reflect that these particular batteries are included in by default now.

> Wait, did you create this? I remember playing with this yesterday and got pretty cool insights on mega projects.
Nope, not mine, we both probably saw it on HN or something - but I like the idea!

**Comment by riccardoferretti** [comment]
I merged the PR because this feels like a core, unintrusive, good functionality to have, that I agree it should be in the template. 

Thinking of it, one thing we could have done is add some instructions about it in the `getting-started.md` file, I found a bit confusing that the command is invoked by `cmd+alt+v` as opposed to simply `cmd+v` (which would fall back to regular pasting if the clipboard doesn't contain an image). 
Maybe there is a good reason for that, I asked on the repo: https://github.com/mushanshitiancai/vscode-paste-image/issues/87

I will add that reference in the meantime in foam-template and update the docs here.

**Comment by riccardoferretti** [comment]
done: https://github.com/foambubble/foam/commit/8bd3109325552bd28d3f528e09642ccf8e5197c7
and done: https://github.com/foambubble/foam-template/commit/c29ca1f6457e25fb71a173513fb3826a1dd18a7f

**Comment by cmcconomy-element** [comment]
> I merged the PR because this feels like a core, unintrusive, good functionality to have, that I agree it should be in the template.
> 
> Thinking of it, one thing we could have done is add some instructions about it in the `getting-started.md` file, I found a bit confusing that the command is invoked by `cmd+alt+v` as opposed to simply `cmd+v` (which would fall back to regular pasting if the clipboard doesn't contain an image).
> Maybe there is a good reason for that, I asked on the repo: [mushanshitiancai/vscode-paste-image#87](https://github.com/mushanshitiancai/vscode-paste-image/issues/87)
> 
> I will add that reference in the meantime in foam-template and update the docs here.

So, I found a tool to inspect forks for activity:
https://techgaun.github.io/active-forks/index.html#https://github.com/mushanshitiancai/vscode-paste-image

which led me to:
https://github.com/telesoho/vscode-markdown-paste-image

And I think it's just a better plugin.

I'm going to look at doing another PR to replace the plugin as this has more comprehensive pasting capabilities for markdown.

Cheers

**Comment by riccardoferretti** [comment]
This second extension feels a bit "heavier", both in a good and bad way, so I prefer to try it out myself for some time before making it part of the default template.
In the meantime I am happy to have it added to the list of recommended extensions

**Comment by riccardoferretti** [comment]
(of course please feel free to try it out and report as well)

**Comment by SanketDG** [comment]
> This second extension feels a bit "heavier", both in a good and bad way, so I prefer to try it out myself for some time before making it part of the default template.

I feel the same, let's add it to the recipes! It definitely has a lot of features.
