### ISSUE TITLE
Orphan list doesn't update on file deletion

### ISSUE THREAD

**Issue by ingalless** [foambubble/foam#463]
Just want to start off with a huge thank you to @leonhfr for this feature - it's great!
- Foam version: 0.9.0
- Platform: Windows (But probably all)
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Probably, untested

**Summary**
When a file is deleted (which has been tested), and perhaps when any update is made, the Orphans list is not updated accordingly.

**Steps to reproduce**
1. Create an orphaned note which you're happy to delete
2. Pop open the orphans panel
3. Delete the file
4. Note that there's no update to the list

**Additional information**
Here's a GIF:
![templates](https://user-images.githubusercontent.com/22981941/106123533-f1171880-6151-11eb-83c6-c19c5097668b.gif)

**Comment by riccardoferretti** [comment]
cc @leonhfr 
I saw that the panel is listening for `onDidUpdateNote`, but also needs to listen for `onDidAddNote` and `onDidDeleteNote` (maybe there should be a generic `onWorkspaceChange` event to make this easier?)

**Comment by leonhfr** [comment]
> cc @leonhfr
> I saw that the panel is listening for `onDidUpdateNote`, but also needs to listen for `onDidAddNote` and `onDidDeleteNote` (maybe there should be a generic `onWorkspaceChange` event to make this easier?)

@riccardoferretti  Yep, I checked those and saw the same, I'll make a PR for this
