### ISSUE TITLE
Stuck for a long time

### ISSUE THREAD

**Issue by jqknono0** [foambubble/foam#466]
- Foam version: 0.9.1
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo:  No

**Summary**

Stuck for a long time.

**Steps to reproduce**
1. Every time the workbench open up.

**Additional information**

Feel free to attach any of the following that might help with debugging the issue:
- screenshots
- a zip with a minimal repo to reproduce the issue
- Foam Logging: info

the file **exthost-f1ec43.cpuprofile** summary, I cannot offer more infomation due to the company's polices.

Filter functions or files, or start a query()

Self Time
Total Time
File
1,874.55ms
11,126.27ms
tokenize
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/remark-parse/lib/tokenizer.js:9
0.00ms
5,563.14ms
parse
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/remark-parse/lib/parse.js:11
0.00ms
5,563.14ms
parse
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/unified/index.js:271
0.00ms
5,563.14ms
parse
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/foam-core/dist/foam-core.cjs.development.js:2974
0.00ms
5,563.14ms
(anonymous)
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/foam-core/dist/foam-core.cjs.development.js:3402
1,874.55ms
5,563.14ms
paragraph
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/remark-parse/lib/tokenize/paragraph.js:15
0.00ms
5,575.42ms
(root)
0.00ms
5,563.14ms
(anonymous)
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/foam-core/dist/foam-core.cjs.development.js:3402
0.00ms
5,563.14ms
parse
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/foam-core/dist/foam-core.cjs.development.js:2974
0.00ms
5,563.14ms
parse
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/unified/index.js:271
0.00ms
5,563.14ms
parse
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/remark-parse/lib/parse.js:11
0.00ms
5,563.14ms
paragraph
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/remark-parse/lib/tokenize/paragraph.js:15
4.23ms
3,688.37ms
emphasis
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/remark-parse/lib/tokenize/emphasis.js:14
3,683.12ms
3,683.12ms
trim
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/trim/index.js:3
11.91ms
11.91ms
(garbage collector)
1.02ms
1.02ms
wordCharacter
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/is-word-character/index.js:9
0.37ms
0.37ms
(program)
0.00ms
0.22ms
text
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/remark-parse/lib/tokenize/text.js:4
0.11ms
0.11ms
locate
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/remark-parse/lib/locate/strong.js:4
0.11ms
0.11ms
locate
c:/Users/nononono/.vscode/extensions/foam.foam-vscode-0.9.1/node_modules/remark-parse/lib/locate/url.js:6

**Comment by riccardoferretti** [comment]
that sounds really strange, it's not been processing that many files.. do you have a repo where we can reproduce the issue?

**Comment by jqknono0** [comment]
> that sounds really strange, it's not been processing that many files.. do you have a repo where we can reproduce the issue?

repo kept in secret, it's inside the company. I wonder if my notes are too much.

Adding some paths to the `foam.files.ignore` reduced the startup time.

**Comment by riccardoferretti** [comment]
how many files are in the repo?

**Comment by jqknono0** [comment]
> how many files are in the repo?
> […](#)
> On 29 Jan 2021, 10:36 +0100, jqknono0 ***@***.***>, wrote: > that sounds really strange, it's not been processing that many files.. do you have a repo where we can reproduce the issue? repo kept in secret, it's inside the company. I wonder if my notes are too much. Adding some paths to the foam.files.ignore reduced the startup time. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

about 60 mds, some reaches 2MB, ignoring them solved the issue.

**Comment by jmg-duarte** [comment]
@jqknono0 do you have/know of some _non-secret_ repo with heavy files?

**Comment by jqknono0** [comment]
> @jqknono0 do you have/know of some _non-secret_ repo with heavy files?

you don't need any repo, with the next line copied for 2000 times to one md file, then the file could stuck the extension.

> APS_AGE_ADD_013 [4029ms] [SUCCESS] [nobody] [11:48:45.210] [11:48:49.239]

**Comment by riccardoferretti** [comment]
the js/ts extension in VS Code will skip tokenization when a file is very big.
Maybe Foam can do the same and "ignore" files that are too big (providing a warning), until we have better metrics around performance. 

The best approach would actually be to parse the files as a cancellable task, to which we can provide a time limit, so that i.e. if a file has not been parsed in some ms we skip it.

All of these still require some sort of performance testing though, even just to define the baselines or "sensible defaults" around size/time limits.

**Comment by jmg-duarte** [comment]
From the example, I think this might have to do with the fact that there are tons of square brackets.

José Duarte
https://jmg-duarte.github.io/
