### ISSUE TITLE
Adding context to the note preview in the tag explorer

### ISSUE THREAD

**Issue by leonhfr** [foambubble/foam#471]
@riccardoferretti had this [idea](https://github.com/foambubble/foam/pull/468#discussion_r567422947) I'm linking a lot about improving the note preview in the tag explorer. It was a bit outside the scope of the original PR so I'm putting it here to get to it at some point.

> Ok, I thought of this crazy idea, I can't not share it :)
> 
> Here are a couple of considerations for tags, which might be interesting to think about. When I look at a tag probably I want to know where it shows up in the target note, in what context. What if we showed in the description the list of lines where the tag shows up in the file. e.g.
> 
> ```
> 12: - I need to check whether this would work #follow-up
> 25: - Check-in with Max #follow-up
> ```
> 
> where `12` and `25` are the line numbers.
> 
> Might be out of scope for this PR, but thought it'd be good to share.
> 
> This wouldn't change anything in the way we deal with the preview for orphans.

**Comment by riccardoferretti** [comment]
Fixed in 0.22.0
