### ISSUE TITLE
Add performance testing

### ISSUE THREAD

**Issue by riccardoferretti** [foambubble/foam#472]
We need to have some performance tests for Foam.

Approaches and notes:
- generate a directory with various files connected based on some patterns (random, with some sort of linear progression, ...).
- use existing digital gardens (see https://github.com/KasperZutterman/Second-Brain and https://github.com/foambubble/foam/pull/467#discussion_r568144587)
- test also performance with large md files (see https://github.com/foambubble/foam/issues/466#issuecomment-771589901)

Anything else?

**Comment by leonhfr** [comment]
Batch operations:
- renaming a directory
- N files deleted at once
- N files added at once (moved from outside foam)
