### ISSUE TITLE
Dots break wiki links

### ISSUE THREAD

**Issue by Panke** [foambubble/foam#475]
- Foam version: 0.9.1
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes | No

**Summary**
If Wiki links include dots like [[ASP.NET Core]] than it will not be included in the generated link references, instead 'points to a non-existing note' turns up in the output. Without the dot everything works, e.g. [[ASPNET Core]] works like a charm. 

**Steps to reproduce**
1. Use a dot in a wikilink
2. Create the file by double clicking the link
3. observe no reference will be created

**Comment by SanketDG** [comment]
I cannot seem to replicate this.

> 2\. Create the file by double clicking the link

Confused, how does double clicking the link create the file? Is "Reveal Definition" mapped to double click?

**Comment by ingalless** [comment]
I can get this issue. Here's a reproduction repository. Notice the files `namespace1.a.md` and `namespace2.a.md`

https://github.com/ingalless/foam-dot-issue-reproduction
