### ISSUE TITLE
Orphans Not Exluding

### ISSUE THREAD

**Issue by njnygaard** [foambubble/foam#476]
- Foam version: v0.9.1
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes (if you add an orphaned document see image directly below)

![image](https://user-images.githubusercontent.com/4606342/106920263-2975a400-66c8-11eb-85c8-db67a6e1d376.png)

**Summary**

![image](https://user-images.githubusercontent.com/4606342/106919508-71e09200-66c7-11eb-9717-706fd296c8e4.png)

**Steps to reproduce**

With Foam configuration:

```json
  "foam.dateSnippets.afterCompletion": "createNote",
  "foam.graph.style": {
    "background": "#202020",
    "fontSize": 12,
    "highlightedForeground": "#f9c74f",
    "node": {
      "feature": "green",
      "note": "#277da1",
      "placeholder": "#545454"
    }
  },
  "foam.graph.titleMaxLength": 0,
  "foam.openDailyNote.directory": "journal",
  "foam.openDailyNote.filenameFormat": "isoUtcDateTime",
  "foam.openDailyNote.titleFormat": null,
  "foam.orphans.exclude": ["journal"],
```
Orphans in `[foam-workspace]/journal` are not excluded from the Orphans panel.

**Additional information**

I thought I followed the [documentation](https://foambubble.github.io/foam/features/orphans) correctly.
I can't seem to get the Orphan panel to exclude things.

**Comment by leonhfr** [comment]
My bad, seems the documentation is slightly outdated. Can you try to use globs instead?

```json
"foam.orphans.exclude": ["journal/**/*"],
```

**Comment by njnygaard** [comment]
Killer @leonhfr, `"foam.orphans.exclude": ["journal/**/*"],` works well after window reload.
Should I close this or make a PR for the docs?

**Comment by njnygaard** [comment]
#477 I figured out how to do it. Thanks @leonhfr

**Comment by julianprester** [comment]
I seem to have a similar issue. I can't get the orphans (or placeholders) panel to exclude files. I have a folder `daily` for my daily notes and would like to exclude it from orphans using the suggested setting: `"foam.orphans.exclude": ["daily/**/*"]` However, daily notes are still shown. If I try the same folder exclusion setting for `foam.files.ignore`, it works by excluding it from all foam related panels. I would like to only exclude the folder from orphans though. Any idea what I'm doing wrong?
