### ISSUE TITLE
Support for accentuation?

### ISSUE THREAD

**Issue by zomars** [foambubble/foam#48]
When using accents like this:

```
- [[Seríes matemáticas]]
```

It replaces the letter with a dash:

![image](https://user-images.githubusercontent.com/3504472/86479297-1a311100-bd09-11ea-9b03-47ea9f36ba0b.png)

**Comment by jevakallio** [comment]
@zomars thanks for letting me know! As someone with äccentuäted name myself, this would be good to get fixed. 

The file name generated is implemented in [VSCode Markdown Notes](https://github.com/kortina/vscode-markdown-notes) -- would you mind opening the issue there and linking it to this issue so we can track it?
