### ISSUE TITLE
Feature Request: Node colors based on note age in the Foam Graph

### ISSUE THREAD

**Issue by flatplate** [foambubble/foam#485]
I have been using foam for a while now and I find the graph view especially useful. For someone who is so bad at organizing notes, it is very helpful to see the graph when I am trying to look at a particular note. With the note type coloring it has gotten much better.

It is hard to see what I have been doing lately in the graph though. I would find it very helpful to be able to visually see the note freshness (not creation but last edit) on the foam graph. So it would be easier to see what I have been working on recently, and how I have shifted my focus. 

I am thinking it could be done by changing node brightness, or maybe defining a gradient in the custom styles.

**Comment by riccardoferretti** [comment]
Thanks for the input, @jmg-duarte has been collecting reqs on the graph and we are plotting a roadmap for it.
I don't know whether this will make it in core graph, or whether it would required an extension, but just wanted to keep you posted

**Comment by jmg-duarte** [comment]
I don't think this should make it into the core. 

As an extension? Sure, I'll even throw in the idea that you can use git to track graph evolution over time.

However, I see this feature as bringing more complexity than benefits.
I am open to be proven wrong though.

**Comment by riccardoferretti** [comment]
I am going to close this as it will be captured/triaged in the dataviz roadmap
