### ISSUE TITLE
Add template examples in foam-template onboarding

### ISSUE THREAD

**Issue by riccardoferretti** [foambubble/foam#486]
(originally created by @alongwill at https://github.com/foambubble/foam-template/issues/29)

The introduction to note templates could be improved if one or more example templates were included to:

a) Demonstrate how to use VS code variables
b) Give an example of what a useful template could be. The following examples have been given:

a template for book reviews
a template for daily notes
a template for meetings
Then this page could be improved: https://github.com/foambubble/foam-template/blob/master/docs/features/note-templates.md

Many Thanks 👍

**Comment by alongwill** [comment]
@riccardoferretti I could take a look at this (I'm not a JavaScript dev though!). Would the PR be made against this repository or https://github.com/foambubble/foam-template/?

**Comment by riccardoferretti** [comment]
thanks @alongwill! the PR would be against the template repo. 
no need to be a js dev, you won't need to do coding, but add an example of template in the repo and some instructions on how to use it or create new ones.

**Comment by riccardoferretti** [comment]
pinging @ingalless who is just wrapping up improvement work on the template feature in #359

**Comment by riccardoferretti** [comment]
this has now been addressed by #359 and https://github.com/foambubble/foam-template/pull/32 - @alongwill feel free to comment, will close the issue in the meantime
