### ISSUE TITLE
Files auto-created from Cmd-Click on non-existent files should not be created in daily notes folder

### ISSUE THREAD

**Issue by jonasdiemer** [foambubble/foam#490]
I am referring to https://foambubble.github.io/foam/features/daily-notes.html

When Cmd+Click on a wiki-link to a non-existent file inside a daily note, foam creates this file in the current folder, i.e. the daily notes folder. However, I would prefer to have those files in the root folder instead.

**Comment by OlavStornes** [comment]
"Markdown notes" has the option to configure which folder you want for new notes. You should have it if you have downloaded the recommended extensions.

Append this to your `settings.json`:
`"vscodeMarkdownNotes.newNoteDirectory": "WORKSPACE_ROOT"`

**Comment by jonasdiemer** [comment]
Thanks, exactly what I was looking for!
