### ISSUE TITLE
Support for Footnotes

### ISSUE THREAD

**Issue by zomars** [foambubble/foam#492]
According to the [extended markdown guide](https://www.markdownguide.org/extended-syntax#fn:1).

It would be nice if foam could support Footnotes to avoid cluttering some articles with links.

**Comment by jmg-duarte** [comment]
Afaik this is has to do with the MD renderer you are using. Could you elaborate on what exactly you're trying to accomplish (i.e. where should they be supported)

**Comment by AndrewNatoli** [comment]
@jmg-duarte - Are you familiar with a markdown renderer that can render footnotes? Maybe it'd be worth coming up a few we can throw in the recipes section of the documentation.

**Comment by ingalless** [comment]
@AndrewNatoli According to a quick Google search [this](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes) looks to add footnote support to the built-in markdown preview!

**Comment by AndrewNatoli** [comment]
> @AndrewNatoli According to a quick Google search [this](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes) looks to add footnote support to the built-in markdown preview!

Nice! I don't use them personally so I'm not sure if there are a few competing standards for writing and rendering them. Suggesting the _most official_ one to showcase would probably be best for folks who also want to render the footnotes on their foam sites.

**Comment by riccardoferretti** [comment]
we might be able to use https://github.com/markdown-it/markdown-it-footnote

**Comment by riccardoferretti** [comment]
actually, someone might have already solved this problem: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes

I haven't tested it yet, @zomars can you give it a try and let us know if it works? (I don't see why it shouldn't)

**Comment by riccardoferretti** [comment]
we should add this to our list of recommended extensions, @zomars is this something you can do?

**Comment by zomars** [comment]
@riccardoferretti sure! I'll take a look.
