### ISSUE TITLE
Foam Graph is blank

### ISSUE THREAD

**Issue by pyreton** [foambubble/foam#499]
`Open Foam Graph` opens the panel, but it is blank. My best guess is this is because I am on the VSCode for Insiders build in order to get native M1 Apple Silicon support. (Foam Graph worked fine on previous Intel laptop using standard VSCode)

**Comment by ValentinTrinque** [comment]
Not on M1, but graph is also blank.

```
  macOS :                Big Sur 11.2.1
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,1
  Processor Name:	Dual-Core Intel Core i5
```

VS Code
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

Foam 0.10.2

**Comment by danieljue** [comment]
Same issue here on Windows 10 64bit, was working a couple days ago.

Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by danieljue** [comment]
Also just updated to vscode 1.53.2, same issue.  
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by riccardoferretti** [comment]
Can you see if anything shows up in the Foam log? https://github.com/foambubble/foam/blob/master/docs/features/foam-logging-in-vscode.md

**Comment by ValentinTrinque** [comment]
@riccardoferretti 

```
[error - 10:21:34 AM] An error occurred in the graph view
{
  "message": "Uncaught TypeError: Cannot read property 'id' of undefined",
  "filename": "vscode-webview-resource://5a811484-39da-4d25-9fdb-1bd349196e93/file///Users/val/.vscode/extensions/foam.foam-vscode-0.10.2/static/graphs/default/graph.js",
  "lineno": 233,
  "colno": 24,
  "error": {}
}
```

**Comment by riccardoferretti** [comment]
@ValentinTrinque 
thanks for this, I recognize the error and where it's coming from.
by any chance to do you have a repo I can reproduce it from? I have not been able so far

**Comment by iamtherealgd** [comment]
I'm not getting anything in the Foam logs when the Graph is blank. If I reload the window and then try to view the graph then it becomes visible. 

 **BUT** if I delete a link/node, then the graph isn't refreshing and I'm seeing the below logs:

`[info - 12:02:38 PM] Deleted: /Volumes/Data/1Brain/test-link.md
[error - 12:02:38 PM] An error occurred in the graph view
{
  "message": "Uncaught TypeError: Cannot read property 'id' of undefined",
  "filename": "vscode-webview-resource://a6fd8997-3934-49e1-8935-5e874af931bb/file///Users/<my-username>/.vscode/extensions/foam.foam-vscode-0.10.2/static/graphs/default/graph.js",
  "lineno": 233,
  "colno": 24,
  "error": {}
}
[warn - 12:02:38 PM] Link file:///Volumes/Data/1Brain/test-link.md in file:///Volumes/Data/1Brain/inbox.md is not valid.`


Link to Repo: https://github.com/iamtherealgd/Brain

**Comment by riccardoferretti** [comment]
I found the issue, it was related to how wikilinks were being resolved when in presence of a definition.
This will be fixed by #502

**Comment by riccardoferretti** [comment]
this has now been fixed as of 0.10.3 - can you confirm?

**Comment by pyreton** [comment]
Confirmed - thank you

**Comment by pyreton** [comment]
Unfortunately the foam graph intermittently stops updating again, and when I close it and re-open, it is blank. 

I just upgraded to the latest version of Big Sur. (But it was working sometimes after the upgrade)

**Comment by pyreton** [comment]
Looks like I can repro:
1. Quit VSCode and reopen
2. Open graph to side, see graph
3. Edit text files for a while, notice graph stopped updating
4. Try closing and re-opening graph, see it's blank
5. GOTO 1
