### ISSUE TITLE
Idea: Allow notes in folders or subfolders

### ISSUE THREAD

**Issue by sahil48** [foambubble/foam#5]
The impression I have is that all files created in foam are in a single folder. It would be good if foam could index notes in a folder and its subfolders, or even indexing of external folders. There are a few reasons why:

* vscode file manager is the sidebar is a useful tool and when a note is accessed, related notes show up in the sidebar.
* knowledge graphs could be more powerful by toggling graph of files in all folders or files in a given folder only. If your files are grouped by project, you get project-specific graphs, or domain specific graphs, etc

**Comment by jevakallio** [comment]
Thank you @sahil48! Indeed the original idea when I created this was to avoid categorisation in directories, but I've gotten similar feedback from others. 

In fact, most of the extensions in the workspace already supports this, we just need to add support to the foam-vscode extension that glues all the this functionality together using markdown links.

The works is being tracked in https://github.com/foambubble/foam-vscode/issues/8, and there's a WIP PR https://github.com/foambubble/foam-vscode/pull/9 which I'm hoping to complete early next week.

> knowledge graphs could be more powerful by toggling graph of files in all folders or files in a given folder only. If your files are grouped by project, you get project-specific graphs, or domain specific graphs, etc

This is a fantastic idea! Maybe @tchayen would be open to supporting it in Markdown Links?

**Comment by tchayen** [comment]
@jevakallio I am definitely open to adding something like this, but I would need some further explanation how such feature could exactly look.

@sahil48 Would you mind creating an issue for toggling all/specific folder displaying in https://github.com/tchayen/markdown-links/issues? We can continue there.

**Comment by jevakallio** [comment]
FYI this was shipped in foam-vscode@0.1.7 🎉
