### ISSUE TITLE
foam-template window.autoDetectColorScheme

### ISSUE THREAD

**Issue by faydanube** [foambubble/foam#503]
"window.autoDetectColorScheme": true,
->
"window.autoDetectColorScheme": false,

Automatically change my color theme, this is too abrupt and offensive to me

**Comment by jmg-duarte** [comment]
Please edit the issue to be in English

**Comment by faydanube** [comment]
Automatically change my color theme, this is too abrupt and offensive to me 

> Please edit the issue to be in English

**Comment by faydanube** [comment]
thanks very much.

**Comment by jmg-duarte** [comment]
I'm keeping it up until the PR is merged

**Comment by faydanube** [comment]
> I'm keeping it open until the PR is merged

ok

**Comment by riccardoferretti** [comment]
This setting means that VS Code will match the theme style of the OS (light, dark).
Feels like a sensible default, of course someone can be free to change it if that's not of their liking, but to change it in the template I would like to understand what problem are we trying to solve?

**Comment by jmg-duarte** [comment]
AFAIK if can be daunting to have the OS superimpose over your chosen VSCode theme, so if your OS has light theme set (e.g. Windows) you can get your retinas "burnt"

José Duarte
https://jmg-duarte.github.io/

**Comment by riccardoferretti** [comment]
mmmm... yeah in the end it's just a matter of style preference.
Given that, I agree we shouldn't really suggest anything in that regard, and instead let people do it their way.

PR has been merged - closing
