### ISSUE TITLE
spellright default configuration suggestion

### ISSUE THREAD

**Issue by faydanube** [foambubble/foam#504]
I think it sucks to get this experience in a default configured template, suggest removing the `spellright` extension suggestion or adding the default configuration `"spellright.addToSystemDictionary": true,

![image](https://user-images.githubusercontent.com/8817046/109415163-0ce03980-79f2-11eb-875f-4c8d53272a39.png)

**Comment by faydanube** [comment]
In fact it does very little in markdown notes, such as support for Chinese, Korean, and Japanese, and I personally always just uninstall it.

**Comment by jmg-duarte** [comment]
This traces back to the https://github.com/foambubble/foam-template/issues/1.
The main goal is to provide a starter environment which anyone can use. Personally, I don't use the Spell Right spellchecker either, however I do understand its importance in the base template.

An easy fix is for you to fork it and base your future Foam-spaces from there.

Regardless, if you don't mind linking the documentation to the default setting you suggest so I can review it, I'd be thankful.
