### ISSUE TITLE
When a file is not associated with any other file, it is very difficult to be found in the graph

### ISSUE THREAD

**Issue by faydanube** [foambubble/foam#508]
When a file is not associated with any other file, it is very difficult to be found in the graph, so I hope to improve it for this case
![image](https://user-images.githubusercontent.com/8817046/109585333-4e7dfb00-7b3e-11eb-9adb-98b6359a6102.png)

**Comment by riccardoferretti** [comment]
have you tried using the Orphans panel? its goal is to surface disconnected nodes so that they are easy to review/connect/navigate-to
