### ISSUE TITLE
License page not found in Foam docs

### ISSUE THREAD

**Issue by brendanfattig** [foambubble/foam#510]
- the page you came from: https://foambubble.github.io/foam/
- the link you followed: https://foambubble.github.io/foam/license

**Comment by jmg-duarte** [comment]
It seems to me that the page is out of sync with the README. 
@riccardoferretti do you have any insight on this?

**Comment by riccardoferretti** [comment]
interesting, seems like the LICENSE page is not publishing.
The file name is `LICENSE`, so I thought the link was broken, but actually in the `readme.md` it looks fine.
What's missing is the license page itself, even the link https://foambubble.github.io/foam/LICENSE gives a 404.
Feels like a github-pages/jekyll publishing setting..

**Comment by dheepakg** [comment]
The github-pages is built from foam/docs folder. Under this folder we don't have `LICENSE` file.
So, I'm copying `https://github.com/foambubble/foam/blob/master/LICENSE` to `https://github.com/foambubble/foam/tree/master/docs/LICENSE`.

**Comment by dheepakg** [comment]
Hi @jmg-duarte & @riccardoferretti,

The pre-commit in my local machine was successful. However, the CI check for mac is failing as one of the tarball installations failed (below is the installation log and the **lines in bold** is the error. Could you please help me with this  

Run yarn
  yarn
  shell: /bin/bash -e {0}
  env:
    OS: macos-10.15
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
**error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.6.6.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/runner/work/foam/foam/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.**
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
Error: Process completed with exit code 1.

**Comment by dheepakg** [comment]
Now the license is getting [displayed](https://foambubble.github.io/foam/LICENSE.txt). Can we close this issue?
