### ISSUE TITLE
https://foambubble.github.io/foam/recipes/ is a 404, but /foam/recipes/recipes is not

### ISSUE THREAD

**Issue by jikanter** [foambubble/foam#515]
- Foam version: 0.10.3
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes 

**Summary**

**Steps to reproduce**
1.  navigate to https://foambubble.github.io/foam/recipes/ from a templated workbook
2. Observe error paget

**Additional information**

Feel free to attach any of the following that might help with debugging the issue:
- screenshots
- a zip with a minimal repo to reproduce the issue
- the Foam log in VsCode (see [instructions](https://github.com/foambubble/foam/blob/master/docs/foam-logging-in-vscode.md))

**Comment by riccardoferretti** [comment]
> ...from a templated workbook

what do you mean by templated workbook?

**Comment by jikanter** [comment]
using the template downloaded directly from the site.

**Comment by ingalless** [comment]
@jikanter Did you clone/use the template before [this PR](https://github.com/foambubble/foam-template/pull/23) was merged?

**Comment by jikanter** [comment]
Yes! thanks, that fixes the issue.
