### ISSUE TITLE
All graph nodes look highlighted.

### ISSUE THREAD

**Issue by AliArdaOrhan** [foambubble/foam#516]
- Foam version v0.10.3
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No

**Summary**
All of the graph nodes look highlighted instead of only selected one.

**Additional information**
Below is the screenshot took from v.0.9.3. Everything seems working as only selected node highlighted.
https://user-images.githubusercontent.com/8167817/109507405-c05b3380-7aaf-11eb-8956-664554133d37.png

Below screenshot is took from v0.10.3. As you can see all of the nodes are highlighted which makes it nearly impossible to navigate.
https://user-images.githubusercontent.com/8167817/109507659-02847500-7ab0-11eb-99be-bee41416d783.png

Screenshots are also shared at issue #455 .

**Comment by jmg-duarte** [comment]
Did you select the highlighted nodes previously?

**Comment by AliArdaOrhan** [comment]
No. At the second SS you can see that Portfolio Management node is selected but all grey nodes are visible as well.
