### ISSUE TITLE
Issues with "piped" Wikilinks in tables

### ISSUE THREAD

**Issue by jonasdiemer** [foambubble/foam#519]
- Foam version: 0.10.3
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes (probably)

**Summary**
When using wikilcnks with pipes, e.g. [[long link\|short]] (I use it e.g. for dates in a monthly calendar, eg. [[2020-03-08\|08]]), there a some issues when I use such links in tables (where I have to use a backslash to escape the pipe to avoid it interfering with table pipe)

1. Graph view shows such links as "nonexistant pages" with the full content of the link (incl. the backslash)
2. New pages are created for such links (I might have triggered that from graph view).

**Comment by riccardoferretti** [comment]
can you please provide an example to make it easy to reproduce the issue?

**Comment by jonasdiemer** [comment]
Please find attached a workspace that should hopefully show the issue easily:
[foam_issue#519.zip](https://github.com/foambubble/foam/files/6102974/foam_issue.519.zip)

**Comment by riccardoferretti** [comment]
We don't yet officially support piped links (you can see it by how the graph doesn't correctly connect those), although that's coming soon. This was actually already mentioned in #223, which we put on hold but we are reviving soon.

Also there, you can see how there is a rendering issue for tables. I couldn't find a definitive answer online, but I think this is an issue with the github md parser/rendering, the pipe inside a wikilink shouldn't need to be escaped. We need to check from the parser's perspective how this is evaluated.

**Comment by riccardoferretti** [comment]
related to #695

**Comment by riccardoferretti** [comment]
We now support piped links
