### ISSUE TITLE
Wiki links don't work in the editor (Linux, neovim)

### ISSUE THREAD

**Issue by tlc** [foambubble/foam#520]
- Foam version: v0.10.3  (download zip, not clone)
- Platform: Linux (Ubuntu 20.04)
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes (download zip version)

**Summary**
Wikilinks don't work in the editor on Ubuntu 20.04.  They do work in a preview window.
I'm using neovim, if it matters.  But this same setup works on Mac.

**Steps to reproduce**
1.  Download the zip [as instructed](https://github.com/foambubble/foam/blob/master/docs/index.md#getting-started), unzip
2.  Open the folder
3.  Select getting-started.md
4. Try to use wiki links.  I've tried ctrl+click and many meta key combinations.  ctrl+click works for non-wiki links.

**Comment by tlc** [comment]
I was thinking this might be about key bindings, with vim making heavy use of ctrl and Mac being OK because FOAM wiki links cmd+click on Mac.

But again, the regular links `Look at the [Foam Recipes](https://foambubble.github.io/foam/recipes/recipes) for ideas!` work fine.  As soon as I hover over one I get `Follow link (ctrl+click)` and the ctrl+click works.

**Comment by riccardoferretti** [comment]
this should be addressed by #524 as we are bringing link navigation in the document within Foam (currently it's managed by markdown-notes, another extension), can you try once 0.12.0 is released?

**Comment by tlc** [comment]
> Foam is a plugin for VSCode, not vi/vim/neovim

Sorry, neovim keymap extension.  https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim

**Comment by tlc** [comment]
This resolved after some update.
