### ISSUE TITLE
Template the filepath in `openDailyNote`

### ISSUE THREAD

**Issue by movermeyer** [foambubble/foam#523]
After working on #482 , I realize there are further steps that could be done to improve this feature.

## Limitations of the current solution

In the current setup, there are two settings that govern the filepath used in the `openDailyNote` command:

* `foam.openDailyNote.directory`: Which directory to use
* `foam.openDailyNote.filenameFormat`: Which "format" to use when making the filename. It can accept any format understood by [`dateformat`](https://www.npmjs.com/package/dateformat)
* `foam.openDailyNote.fileExtension`: Which extension to append to the filename.

The full filepath is calculated by appending all of these together. Effectively:

`${directory}/${dateFormat(filenameFormat)}/${fileExtension}`

However, under this system, you cannot do useful things like:

* Include the date in the directory path. You might want to store your daily notes in a subdirectory that contains the date. For example, I'm considering using a browser extension (like [Markdown Clipper](https://github.com/deathau/markdownload)) to download the text of the sites I visit, then store them in daily directories. Alongside those files, you may want to store your daily notes.
* Add other characters to your filename besides the timestamp. For example, perhaps you want to add a prefix to each filename `daily_note_2021-03-11`. There is no way to specify that in the current setup. (You **can** add extra characters to `filenameFormat`, but only if they don't collide with the characters already used by dateFormat (now, or anytime in the future))

## A potential new solution

I posit that there is no reason to treat these as separate segments of the filepath and indeed that the feature can be simpler, while also more powerful by allowing a single format string for the whole path.

Perhaps instead of `directory`, `filenameFormat`, and `fileExtension`, you could have a pair of settings.

1. `foam.openDailyNote.filepathFormat` would be a format string that can be an absolute or relative filepath to use. Relative paths would be relative to the current workspace (as it is today) and absolute paths would be absolute (as they are in #482). The path would be templated though, allowing a `${date}` parameter to be inserted to indicate where a data should go in the path. It would default to `${date}.md` (to maintain the same default behaviour as today)
2. `foam.openDailyNote.dateFormat` would be the date format to use when replacing the `${date}` parameter. It would default to `isoDate` (as `filenameFormat` does today)

```jsonc
// Daily note is found at ${workspace}/my/subdir/daily_note_2021-03-11.md
"foam.openDailyNote.filepathFormat": "my/subdir/daily_note_${date}.md",

// Daily note is found at /absolute/path/2021-03-11.md
"foam.openDailyNote.filepathFormat": "/absolute/path/${date}.md",

// File extension is configurable without a special key.
"foam.openDailyNote.filepathFormat": "/absolute/path/${date}.mdx",

// Of course it also works on other platforms (ex. Windows)
"foam.openDailyNote.filepathFormat": "C:\\absolute\\path\\${date}.md",
```

### Benefits

* **Simpler:** less config settings. Easier to reason about since the `filepathFormat` shows you visually exactly what you'll get.
* **More powerful:** You can add the date anywhere in the path. You can add arbitrary characters to the filename.

#### Default behaviour

The default behaviour for someone who hasn't set any of `directory`/`filenameFormat`/`fileExtension` would be the same as it is today.

#### Customized behaviour

I expect that `directory`/`filenameFormat`/`fileExtension` would be deprecated in favour of `filepathFormat` usage.

A section would be added to the documentation to explain the simple migration path. (Depending on permissions, it might even be possible for an extension to auto-migrate users 🤞).

After deprecation, but before removal of `directory`/`filenameFormat`/`fileExtension`, both systems would be supported.

However, usage of `filepathFormat` would be mutually exclude usage of `directory`/`filenameFormat`/`fileExtension`. ie. You can either use the old way until the settings are removed, or use the new way without using the old. I've toyed around with it, and while it is technically possible to define behaviours for all combinations of old and new settings, some of the edges are non-intuitive and encourage the wrong behaviour. Ultimately, allowing usage of both has the effect of users migrating twice (once when they half-adopt the new system, and another when the old system is removed). Simpler and better if we force a one-time break from the old.

### Template syntax

While simpler and more powerful, the templating format shown in the above example doesn't allow you use different `dateFormat`s in the same filepath. Perhaps instead of having a separate `foam.openDailyNote.dateFormat` setting at all, the templating could be made more complicated (to read and to implement) and the date format could be included in the `filepathFormat`. Something like:

```jsonc
// A relative path containing multiple, different date format templates
"${dateFormat('isoDate')}/${dateFormat('isoDate')}.md",
```

Depending on aesthetics, we could make the templating format whatever we want, so please don't get hung up on that. (It could be something less verbose `{d('isoDate')}.md`) **We can use whatever templating syntax looks good, is simple to implement, and allows for extension in the future.**

### Future extension (thought experiment)

If there turns out that there are other things that would make sense to also template in filenames, it would fit naturally into this scheme.

```jsonc
// `foo` is some other attribute that people in the future care about:
"foam.openDailyNote.filepathFormat": "${date}_${foo}.md",
```

In the present system, anything other than `date` cannot be added to the filename (without more settings being added). Making the filepath templated allows for easy extension in this direction.

**Comment by riccardoferretti** [comment]
this is a very good write-up and I agree 100% with the idea, we need to consolidate the path to the daily note.

So for me there are a few points here:
- consolidation of the path for daily notes: 100% agreed we should do it
- variable substitution in path: we should do it, and I would use some sort of "standard" (e.g. momentjs, but maybe vscode snippet variables could also be good)
- backwards compatibility: i would just add a new property: if it exists it wins over everything else, if it doesn't we fallback to current behavior
- migration: show a warning to users when they are still using the old settings (and migrate foam-template to use the new one)


We were thinking of making the daily note driven by templates, and to allow templates to define the (default) pattern for the path of notes created from there, e.g. via a `_defaultPath` yaml property.
This would allow to also include custom content in your daily note (and crucially, it could be used by other templates, e.g. a `meeting` template).
In that case the setting coming from the template would have the highest priority (if we also find another setting, we should report it as a warning).

Thoughts?

**Comment by riccardoferretti** [comment]
cc @ingalless who has worked on templating

**Comment by ingalless** [comment]
Hey @riccardoferretti @movermeyer. Really nice write up! I've enjoyed thinking about it over the last few days.

I agree with all the points already made. I just want to chime in on variable substitution

> and I would use some sort of "standard" (e.g. momentjs, but maybe vscode snippet variables could also be good)

VSCode snippet variables + yaml props (for custom variable substitution) sounds a cool idea. I like that VS Code snippet variables give us free documentation. Increased consistency is a win in my books too!

---
> In that case the setting coming from the template would have the highest priority **(if we also find another setting, we should report it as a warning).**

I think this warning should be suppressible if I understand there to be a "order of precedence" in the settings. An expert user may deliberately have a "catch all" in his workspace settings, but have certain templates override that setting.

---

A kind of related thought:

It's also got me thinking whether we could have a "default daily note template" config, but then also a "Create new daily note from template" command and "Create new blank daily note" 🤯
An example: On the weekend I'm not likely to be working, thus no need for a meeting template, but just a blank spread to help me with whatever I'm doing.
Apologies if I'm moving this off topic, but all feels related to Templates `V2` to me!

**Comment by movermeyer** [comment]
> Apologies if I'm moving this off topic, but all feels related to Templates V2 to me!

Yeah, it seems like all this might just fit nicely into templates, which would allow us to remove all of the `openDailyNote` settings 🎉

**Comment by hukacode** [comment]
Hi all,

Please let me know if I share my think in the wrong place.

I use notes with file name format `yyyyMMddhhmmss.md` and this header:
```
---
title: ""
tags: ""
---
```

To achieve that, I have to use one of these approaches:
A. Use template
1. Create a template with that header.
2. Create a new note with `Foam: Create New Note From Template`
pros: This approach matches my requirements.
cons: I have to copy the file name from the new note to link with an existed note.

B. Use Ctrl + Left Click
1. I generate a text `[[yyyyMMddhhmmss]]` in my existed note.
2. Then use Ctrl + Left Click to create a note.
pros: I don't have to copy the filename to fill it into the existed note.
cons: I have to edit the header manually.

Could you please consider adding a property to config header when creating a note with Ctrl + Click?

**Comment by movermeyer** [comment]
@riccardoferretti @ingalless is there a design document / proposal for "Templates V2" that I could look at (and contribute to)? 

Otherwise, I might try drafting one.

**Comment by riccardoferretti** [comment]
happy for you to get started on one. 
I would like to try a PR based approach, can you create a PR for a `docs/specs/templates-v2.md` file?
We'll use the PR for the discussion and summarize in the document.

**Comment by movermeyer** [comment]
Closing this since it has been superseded by [Templates v2](https://github.com/foambubble/foam/pull/534)
