### ISSUE TITLE
Broken links in readme.md on master branch

### ISSUE THREAD

**Issue by derrickqin** [foambubble/foam#526]
**Summary**

I am a new user of Foam and found there are two broken links in readme.md file. They are related to a change which moved a few files under `docs/features` folder.

**Steps to reproduce**
1. Visit https://github.com/foambubble/foam
2. Click `Graph Visualisation` or `Backlinking` under `How do I use Foam` section

**Additional information**
Screenshots:
![image](https://user-images.githubusercontent.com/3038111/111086457-4f685100-8570-11eb-8906-eabee551757f.png)

![image](https://user-images.githubusercontent.com/3038111/111086478-61e28a80-8570-11eb-967c-49af72801670.png)

**Comment by movermeyer** [comment]
@derrickqin Can this be closed now?
