### ISSUE TITLE
Add support for other metadata in the markdown

### ISSUE THREAD

**Issue by shelper** [foambubble/foam#531]
right now, foam supports only tags in the metadata at the start of markdown file
if we can add extra properties in addition to tags, that would be very useful for organizing and navigating the notes.
e.g.:, 
```
---
tags: tag1, tag2
status: todo, started, wait, ...
date: 2021-03-14 
...
---
```
it would be even greater if we can make this list configurable, so that users can define his/her own metadata/properties for customized use case.

**Comment by riccardoferretti** [comment]
In what way were you thinking this metadata could be exposed to organize and navigate notes?

**Comment by shelper** [comment]
the first thing i can think of is to make it like tags, but just a different class, and can be used for filtering docs
the second is we can rank the docs, e.g, by date or by status

**Comment by riccardoferretti** [comment]
Sorry, I am not sure I am following.
You can have properties in your YAML file, which get attached to the notes. That's already possible.
What I think you are describing are other ways to "surface" those properties, the same way e.g. tags are surfaced via the Tag Explorer.
Can you share some example of ways in which these properties can be surfaced and for what use cases? 
(could be panel, graph, search, .. not sure..)

**Comment by shelper** [comment]
i was thinking of something like the software [notion](https://www.notion.so)
say we added a property called status. the simplest way is to surface it as tag but can be sorted 
one more step further, we can surface the property in a panel like below and then under each status is the list of notes with that property value.
![image](https://user-images.githubusercontent.com/546163/111651568-b8ec9780-87dc-11eb-9d83-33407aa251e1.png)

To make it more generalized, maybe we can have a dedicated panel for all properties, then we can add or remove properties as columns, and sort, filter by each column as needed, e.g, something like below, which is the file explorer in detailed view on windows
![image](https://user-images.githubusercontent.com/546163/111652539-855e3d00-87dd-11eb-81ec-fccb21d7619d.png)
