### ISSUE TITLE
Follow link preview is not rendered correctly if path has spaces

### ISSUE THREAD

**Issue by maciejmatczak** [foambubble/foam#542]
- Foam version: 0.12.0
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No

**Summary**
With update from: https://github.com/foambubble/foam/pull/524: when foam repository is opened from a path with spaces, a preview of ctrl-click action is rendered incorrectly.

No spaces in a path:
![image](https://user-images.githubusercontent.com/1786383/112031078-385ecb80-8b3b-11eb-92fd-e6edb53f678e.png)

Spaces in path:
![image](https://user-images.githubusercontent.com/1786383/112031167-50364f80-8b3b-11eb-97db-a0cf9dd1fc52.png)

Additionally:
- on Windows I am able to create and follow the link correctly
- on WSL I am able to create a link but not to follow

**Comment by hyrathon** [comment]
Yes, this is critical, half of my existing links are broken
