### ISSUE TITLE
Foam interfering/disabling/removing correct tokenization/semantic highlighting

### ISSUE THREAD

**Issue by GBrachetta** [foambubble/foam#547]
- Foam version: **0.12**
- Platform: **Mac**
- Issue occurs on the [foam template](https://github.com/foambubble/foam-template) repo: **No, it happens on all .md files, regardless of being in a foam environment.**

**Summary**

Since v0.12, Foam changed the Syntax Highlighting off .md files, making them very difficult for me to read.

Before Foam 0.12:

![Screenshot 2021-03-24 at 18 47 33](https://user-images.githubusercontent.com/57924268/112690540-3fa81100-8e7c-11eb-8725-74a2045e958a.png)

With Foam 0.12:

![Screenshot 2021-03-24 at 18 47 03](https://user-images.githubusercontent.com/57924268/112690584-5189b400-8e7c-11eb-9ba7-f8706a10c824.png)

Disabling/uninstalling Foam brings correct tokenization back to normal

**Also reverting back to Foam 0.11 fixes the issue.**

I disabled **all** extensions but **Foam** to isolate the issue and it's clear Foam is causing it, at least in my current setup.

I also cleared completely all settings in my settings.json file, so default everything, including theme.

This is a short clip of the process, to see how syntax highlighting gets impacted by Foam:

https://user-images.githubusercontent.com/57924268/112690858-c3fa9400-8e7c-11eb-858d-b95692944334.mov

**Comment by riccardoferretti** [comment]
Yes the decorations have been problematic for several users, in the next version we will:
- make them optional 
- keep them off by default
