### ISSUE TITLE
v0.12.0 has a file creating bug

### ISSUE THREAD

**Issue by adamliuio** [foambubble/foam#548]
- Foam version: **v0.12.0**
- Platform: **Mac**
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Donno, didn't check the code, the issue just occurs after a auto-update without me noticing

**Summary**
Basically it was working fine, I use "[[]]" every time I wanted to create a new page to link, and it works fine, a new file with lowercase letters & hyphen (i.e. [[Good Day]] creates "good-day.md") is created in the dir, and using cmd + click will go to the file.

in **v0.12.0** however, when you try to link to a new page, it creates a file with the same sentense ("Good Day.md") as name in the root dir, and creates a file with lowercase letters & hyphen in the current dir, and links to the root dir file.

**Steps to reproduce**
1. update to **v0.12.0**
2. cmd + click on a [[link]]
3. use mac

**Additional information**

Any change that it allows users to configure creating a new file with title format as something like:

```
---
title: Good Day
---
```

I'm using jekyll to generate a static site, **Foam** creates a file with title using **"# "**, so every time I need to update the title manually.

Besides above, thanks for creating this guys, it's amazing!

Adam

**Comment by RVirmoors** [comment]
i get the same thing on Windows 10

**Comment by moorebi** [comment]
# Issue:
I am getting a similar issue when I try to link other files using the following syntax:

`[filename](file-name.pdf)`

The outcome of this link is that a file names "file-name.pdf.md" is created.

# Resolution:
I have resolved this issue by using the following syntax:

`[filename](file:///../file-name.pdf)`

**Comment by ingalless** [comment]
@adamleo Do you have both Markdown Notes and Foam installed in your environment?

**Comment by ChanceNCounter** [comment]
I'm getting what I assume is the same as @moorebi's issue, but it might offer some more clarity. Prepare for a whole bunch of takes on the same input and weird output. Try not to glaze over like I did while re-reading it 😉 

`[label](folder/filename)` and `[label](folder/filename.md)` both work when `folder/filename.md` already exists.

However, when it *doesn't* exist, the relative path is resolved into an absolute path which is then interpreted literally:

`[label](folder/filename)` --> file exists --> mouseover --> `Go to /abspath/to/folder/filename.md`  
`[label](folder/filename)` --> FNF --> mouseover --> `Create note for 'abspath/to/folder/filename.md'`

it then creates `./abspath/to/folder/filename.md`

Put differently, it then creates, `/abspath/to/foam/project/abspath/to/foam/project/folder/filename.md`

---

If I feed it a *relative* path:

`[label](./folder/filename)`

then it creates the file in the right directory, but it doubles the extension, even though there's *no* extension in the link:

`/abspath/to/foam/project/folder/filename.md.md`

Finally, *adding* the extension to the link:

`[label](./folder/filename.md)`

does *not*, as the above might suggest, result in a *third* `.md`; it still makes `folder/filename.md.md`

**Comment by riccardoferretti** [comment]
Closing as there have been a lot of changes in the way URIs are handled, as well as improved wikilink support.
If the problem persists with the latest release please open a new issue
