### ISSUE TITLE
Roam Import

### ISSUE THREAD

**Issue by phxtho** [foambubble/foam#55]
First of all great work!

I've been working on importing my roam knowledge graph into foam. There's a couple of features/issues which I was wondering about.

1. Roam's export doesn't generate `# Headings` which are required for  the [markdown links](https://github.com/tchayen/markdown-links) graph, this seems relatively easy to resolve by simply making the file name the heading.
2. Roam notes feature backlinks showing which notes reference the note you're on, something like this was implemented by [andy matuschak](https://github.com/andymatuschak/note-link-janitor)
3. Resolving block embeds and block references implemented by [roam export](https://github.com/houshuang/roam-export)

I was wondering what the best way to integrate all of this into something Roam users can get up and running quickly in — wether as part of foam, an extension or just simply shipping a js script users can run on import?

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
