### ISSUE TITLE
Wikilinks colors changed & darkened to be very hard to read in some themes

### ISSUE THREAD

**Issue by felixweinberger** [foambubble/foam#553]
- Foam version: 0.12.0
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
Colors have changed on the wikilinks, with potentially adverse interactions with other themes or settings.

On a standard install of the native template:

Before (v0.11):
![Screenshot 2021-03-31 at 09 37 57](https://user-images.githubusercontent.com/3823880/113116107-6dd77900-920d-11eb-9ae7-441c5cb91754.png)

After (v0.12):
![Screenshot 2021-03-31 at 09 37 26](https://user-images.githubusercontent.com/3823880/113116153-76c84a80-920d-11eb-8670-7cf02994a520.png)

The color change itself is not the main problem (though I personally significantly prefer the previous design), but it seems to generate weird interactions with other themes / extensions? On my standard install the effect is this (for reference the theme is Monokai Pro - Spectrum)

Before (v0.11):
![Screenshot 2021-03-31 at 09 42 29](https://user-images.githubusercontent.com/3823880/113116716-ff46eb00-920d-11eb-9d01-4abf545cc052.png)

After (v0.12):
![Screenshot 2021-03-31 at 09 43 41](https://user-images.githubusercontent.com/3823880/113116692-f7874680-920d-11eb-9595-75ff60e49b61.png)

**Steps to reproduce**
1. Clone the template repo on a clean VSCode install (I used insiders to clear all extension from my standard install)
2. Open template in VSCode and install the recommended extensions (Foam at 0.12.0)
3. Observe the links as in "after" above
4. Install a different version of Foam on the extension's page (Foam at 0.11.0)
5. Observe the links looking correct as in "before" above

Note this might affect display on different themes differently - on my standard install the change looks like this:

**Comment by ingalless** [comment]
Hey @felixweinberger! Mind checking if this seems related to #547?

**Comment by felixweinberger** [comment]
> Hey @felixweinberger! Mind checking if this seems related to #547?

Hi, didn't see this notification apologies - I see it's been fixed, thanks for checking in!
