### ISSUE TITLE
I created some tags with Chinese characters , but I can't find them in "TAG EXPLORER"。

### ISSUE THREAD

**Issue by rockbmw** [foambubble/foam#567]
- Foam version: v0.12.0
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo:  No

**Summary**

Thanks for the great extension , and I don't sure if it's a bug . when I created some tags with Chinese characters , such as "#标签1" or "#标签2", I can't find them in "TAG EXPLORER".  That's OK when I created tags with English character.
**Steps to reproduce**
1. Open a note, add a tag "#标签1"；
2. Save the note and look for it in "TAG EXPLORER".

**Additional information**

Feel free to attach any of the following that might help with debugging the issue:
- screenshots
- a zip with a minimal repo to reproduce the issue
- the Foam log in VsCode (see [instructions](https://github.com/foambubble/foam/blob/master/docs/foam-logging-in-vscode.md))

**Comment by riccardoferretti** [comment]
good point, the current regex only includes latin characters

**Comment by RobinKing** [comment]
> good point, the current regex only includes latin characters

Maybe I fixed this in [pull request #568 ](https://github.com/foambubble/foam/pull/568) by using Unicode property escapes in Regular expressions. 

Before:
![Before](https://cdn.jsdelivr.net/gh/RobinKingPubForToken/I/img/20210330232913.png)

After:
![After](https://cdn.jsdelivr.net/gh/RobinKingPubForToken/I/img/20210404213111.png)

**Comment by riccardoferretti** [comment]
fixed by #568
