### ISSUE TITLE
Improve monorepo setup

### ISSUE THREAD

**Issue by jevakallio** [foambubble/foam#57]
Last night I migrated all the foam packages (save for foam-template) to a monorepo structure. There are a couple of issues that need to be resolved:

- [x] Workspace tasks for running common development workflows
- [x] `foam-vscode` and `foam-cli` should use local `foam-workspace-manager` in development
- [ ] `vsce package` does not know how to pick up packages from hoisted yarn workspaces
  - Currently worked around by running vsce package with npm install. See https://github.com/foambubble/foam/commit/d6d31faf2fab86fb8bc5a810112a232ac5a46cb6
- [x] Migrate all packages to test with jest
  - Highest priority is running `foam-vscode` tests with Jest. See: https://medium.com/@soloydenko/end-to-end-testing-vs-code-extensions-via-jest-828e5edfeb75

**Help wanted with remaining issues!**

## Materials

https://medium.com/@rossbulat/typescript-working-with-paths-packages-and-yarn-workspaces-6fbc7087b325

**Comment by riccardoferretti** [comment]
per my conversation with @jevakallio, this is currently blocked by  https://github.com/microsoft/vscode-vsce/pull/493 - and will be tracked in https://github.com/foambubble/foam/issues/314 - so closing this issue
