### ISSUE TITLE
WikiLinks suddenly have the same color

### ISSUE THREAD

**Issue by vojavocni** [foambubble/foam#572]
- Foam version: v0.12.1
- Platform:  Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
The wiki-links in VS code had different color based on whether the note they refer to is created or not. If it is created, they used to be blue, if not, they used to be dark yellow. Right now, all link are yellow, and this started, at least for me, this morning.

**Steps to reproduce**
1. Not completely sure as I don't know the root cause, but updating to 0.12.1 could be relevant.

**Additional information**
Reverting to v0.12.0 fixes the issue, so the new versions seems to be the cause.

**Comment by riccardoferretti** [comment]
in 0.12.1 this feature is off by default and can be enabled by setting the property `foam.decorations.links.enable` to `true`
