### ISSUE TITLE
Autosave causing non-existant placeholders

### ISSUE THREAD

**Issue by KO4JZT** [foambubble/foam#573]
- Foam version: v0.12.1
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
When adding new URL links to a project and saving mid-way, new placeholders are added for variations of "https" removing letters. Only resolved by reloading the window.

**Steps to reproduce**
1. Open a note and make sure autosave is enabled.
2. Begin typing a link beginning with https in format `[link](url)`
3. Open placeholders tab to see https

**Additional information**
![Screen Shot 2021-04-09 at 1 30 39 PM](https://user-images.githubusercontent.com/16247799/114225664-37e67300-9938-11eb-9a78-da522688b44d.png)

**Comment by DrSLDR** [comment]
I am able to reproduce this without auto-save being on.

- Foam version: v0.12.1
- Platform: Linux (Ubuntu-family)
- Issue occurs on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
When writing a wiki-link, placeholders are generated for a seemingly random set of stems for the link. As noted by @KO4JZT, the placeholders are only cleared by reloading the window.

**Steps to reproduce**
1. Open a note (auto-save not necessary)
2. Bracket a wiki-link by typing `[[]]`
3. Write the link inside the brackets
4. Save
5. Check Placeholders

This bug does NOT occur if you write the link first, then wrap it in `[[ ]]`.

**Additional information**
The below image shows the slew of placeholders generated by me writing `[[fake-placeholder-name]]`.

![image](https://user-images.githubusercontent.com/949651/114367243-8c7a3000-9b7c-11eb-857e-099de218d085.png)

**Comment by DrSLDR** [comment]
As of updating to 0.13.0, I am no longer seeing this behavior. @KO4JZT, are you seeing the same?

**Comment by KO4JZT** [comment]
@DrSLDR I am not having the issue anymore as well! 👍
