### ISSUE TITLE
How can I change the prefix "/"(slash)

### ISSUE THREAD

**Issue by Stivenke** [foambubble/foam#587]
Suggestion: Allow users to customize the leading character to avoid conflicts with other plug-ins, such as: "path intellisense".

**Comment by riccardoferretti** [comment]
I am not sure I understand, are you referring to date snippets?

**Comment by Stivenke** [comment]
If I want to add a file link `[file name](../path)`, when I type `/` now, the prompt it appears must be "/ today ... / friday ...". Therefore, I hope users can specify a prefix, such as `/` (default), `\`, `:`,`@`....

**Comment by riccardoferretti** [comment]
Thanks @Stivenke I understand now.
There is no plan to change the prefix "/", I will leave this issue open for a bit to see if there is wide interest, but I wouldn't consider it a priority for Foam atm.

**Comment by Stivenke** [comment]
Thank you for your reply, of course this is just my personal suggestion.
