### ISSUE TITLE
Korean tags not recognized in tag explorer.

### ISSUE THREAD

**Issue by mytory** [foambubble/foam#589]
- Foam version: v0.12.1
- Platform: Mac, Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
I tagged Korean words to my document. I used both two methods. Sharp(#) prefix and note property. Tag Explorer doesn't recognize my tags. It's below.

```
#자동화 #인력감축 #주식매매트레이더 #골드만삭스
```

```
---
tags: 자동화 인력감축 주식매매트레이더 골드만삭스
---
```

**Steps to reproduce**
1. Type Korean tags to your document. Like below:

```
#자동화 #인력감축 #주식매매트레이더 #골드만삭스
```

```
---
tags: 자동화 인력감축 주식매매트레이더 골드만삭스
---
```

2. And see tag explorer.

**Additional information**

![image](https://user-images.githubusercontent.com/1888222/115205164-39801a00-a134-11eb-8c71-07d8b83b367b.png)

The screenshot is on Ubuntu Linux. But I tested on my Macbook Pro and got the same result, too.

And I think that tags regex does not wide. Maybe for only alphabets like characters. For example, a regex for all Korean characters is `/[가-힣ㄱ-ㅎㅏ-ㅣ]/`. But I think the same problem may be on other non-Latin characters like Japanese, Chinese, Arabic...

Thank you.

**Comment by riccardoferretti** [comment]
I thought #568 addressed non-latin characters for tags, maybe something is missing.
CC @RobinKing, what do you think the problem is?

**Comment by RobinKing** [comment]
> I thought #568 addressed non-latin characters for tags, maybe something is missing.
> CC @RobinKing, what do you think the problem is?

v0.12.1 does have this problem because it is a little bit older now. 
And the latest version v0.13.0 has solved this problem.

**Comment by mytory** [comment]
Thank you. I updated the Foam. It works very well.
