### ISSUE TITLE
Linking between published workspaces

### ISSUE THREAD

**Issue by mathieudutour** [foambubble/foam#59]
Opening this issue to discuss what linking between published workspaces could look like.

I believe there are (at least) 3 very separate aspects of this feature:

1. what the format should look like to link to another workspace? Is it just a normal markdown link? Do we have a shortcut that the extension handle (similar to wiki links)? If we have a shortcut, how to we get the title of the foreign bubble (and update it if/when it changes)?
1. Shall we notify the linked workspace that it is being linked to (for backlinks)? If so how?
1. Do we (and if so, how) display backlinks from foreign workspace?

I don't have many opinion on `1.` but I thought about `2.` and `3.` a bit. IMO this is the perfect use case for [webmentions](https://www.w3.org/TR/webmention/).

Using [webmention.io](https://webmention.io), it is possible to have a JAMstack website display its mentions dynamically (eg. its backlinks). The only requirement is to open an account on webmention.io and add some metadata in the head of your pages. Those metadata specify the server to ping when another website mentions yours.

You then have an API to query the mentions. It does require a bit of code but there are some gatsby plugins to make it easier for example.

The second part is notifying the websites (workspaces) you mention when you deploy it. I built a small webservice that does the following when you ping it with your url:
- fetch your sitemap.xml expecting a sitemap with an extension to specify external links for each pages
- for each external link, look if there is a metadata specifying a webmention server
- if so, ping it with the source page and the target page
- stores the sitemap to compare it next time (and only ping the new links)

**Comment by jevakallio** [comment]
Still keen to explore this but haven't gotten around to doing so yet.

Not sure if useful for us, but the MediaWiki interwiki links are related to this:
https://www.mediawiki.org/wiki/Help:Links#Interwiki_links

**Comment by mathieudutour** [comment]
One of the downsides of webmentions is that it's a bit hard to control what you receive. You have to "trust" the senders.

A potential solution would be mimic web-rings (and call them bathtub? 😄):
- a repo listing the origins mutually trusted
- if you want to be part of the webring, open a pull request and add yourself
- any webmentions from those origins is approved and showed as a backlink

Down the line we could implement a theme gallery or recipe list as webrings (which foambubble/foam would be part of): any theme would link to the theme gallery page and be shown as a backlink (which we can style however we want)

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
