### ISSUE TITLE
Note autocomplete suggestions outside wiki-link brackets `[[` `]]` in v0.13.

### ISSUE THREAD

**Issue by vojavocni** [foambubble/foam#592]
- Foam version: v0.13
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
When typing in the same line where another wiki-link exists, every keystroke produces note suggestions, even after the wiki-link is closed.

**Steps to reproduce**
1. Update to v0.13
2. Make a line with a wiki-link
3. Continue typing in the line

**Additional information**
![image](https://user-images.githubusercontent.com/40206443/115292488-b6c08480-a15e-11eb-9e46-4c594bcaf36e.png)

I can confirm that reverting back to 0.12.1 removes the issue.

**Comment by RobinKing** [comment]
I can replicate on Windows.

After wiki-link brackets `]]` and some blank characters (space or tab , etc), autocomplete suggestions still shows the hint.

May have something to do with `packages\foam-vscode\src\features\link-completion.ts`

**Comment by riccardoferretti** [comment]
I can replicate on Mac too. Yes, the issue seems to be with the regex in `link-completion.ts`.

also cc @jmg-duarte, my trusted regex advisor ;)

**Comment by RobinKing** [comment]
@riccardoferretti  I have made a fix and tested locally .
And now I'm working on wrighting some tests for this....

**Comment by jmg-duarte** [comment]
@RobinKing I was looking at the latest commit. First of all, nice catch on the bracket. Second, why the negative lookahead for `.*`?

**Comment by RobinKing** [comment]
@jmg-duarte 
With `.*` like `(?!.*\]\]) ` means should not have `]]` after any characters (`.*`)
And without `.*` in `(?!\]\])` caused that if cursorPrefix has ended with `]]`, if we seperate the cursorPrefix(like `[[note]]`) before last charater ahead of `]]` (means seperate it before `e`), first part (`[[not`) also match the RegExp.

Tests like this:
---
![TestPic](https://cdn.jsdelivr.net/gh/RobinKingPubForToken/I/img/20210423221531.png)

**Comment by jmg-duarte** [comment]
I've just tested and it seems to work
https://regex101.com/r/wRXsXO/2

**Comment by pderaaij** [comment]
@riccardoferretti This one can be closed it seems?
