### ISSUE TITLE
Some difficulties working with PDF attachments/links

### ISSUE THREAD

**Issue by ddbrierton** [foambubble/foam#597]
- Foam version: 0.13.1
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No

**Summary**
A markdown link to a local PDF file in a Foam Bubble makes Foam think there is a missing MD document. An HTML link to a local PDF file creates a link but clicking it in the preview pane fails to open it in a PDF viewer.

**Steps to reproduce**
1. Copy a PDF file to your Foam workspace, e.g. `_attachments/test.pdf`.
2. Create a markdown link to it in a Foam Bubble, e.g. `[Test](_attachments/test.pdf)`
2. Notice that in the Placeholders view Foam now believes there is a missing markdown document, `_attachments/test.pdf`, and hovering over the link in the document prompts you to cmd-click to create the file.
3. Try using HTML instead: `<a href="_attachments/test.pdf”>Test</a>`.
4. Foam no longer thinks there is a missing markdown document, but the link in the preview pane just opens the binary file inside VS Code, instead of in a suitable PDF viewer.
5. Try refining HTML link like so: `<a href="_attachments/test.pdf” type=“application/pdf">Test</a>`.
6. No improvement.

**Comment by wcerfgba** [comment]
I am also having this problem. Ideally I would like to use Markdown links to point to arbitrary files s.t. this is compatible with VSCode, Github Markdown preview, and published Foam workspaces.

**Comment by duskmoon314** [comment]
I'm working on M1 MacOS, and facing the similar issue.

> Foam no longer thinks there is a missing markdown document, but the link in the preview pane just opens the binary file inside VS Code, instead of in a suitable PDF viewer.

I have LaTeX Workshop installed in VSCode, so I can view PDF in VSCode when clicking the markdown link. But when I use html link, it tries to open in Chrome with a wrong link.

I hope that foam can recognize different file in markdown link, and maybe don't show in graph?

**Comment by tlc** [comment]
I would love pdf and arbitrary file support.  The only working method I found was hosting a PDF on a web server and putting the URL in the text,  not a `[]()` link.  Everything else I tried -- file:///, file paths, etc. - did not work inside or outside of `[]()` or `[[]]` links.

**Comment by marcoscannabrava** [comment]
The following works for me: `file://full_path_to_file`
e.g.
```sh
file:///home/user/folder/notes/attachments/some_file.pdf
```
_It has to be used by itself i.e. outside parentheses_

**Comment by riccardoferretti** [comment]
there are two issues that combined will sort this out:
1. attachments need to be treated as such instead of placeholders
2. filter nodes in the graph by type

n. 2 is already on master and will be available with the next release

so that leaves us just with n. 1, which I don't expect to be a massive amount of work, but needs better definition of various edge cases

**Comment by riccardoferretti** [comment]
This has been fixed some time back, in 0.19.0

**Comment by tlc** [comment]
Which part was fixed?  I'm trying to open [foo](file:///some/path/foo.pdf) and I'm looking at binary in the foam editor.
