### ISSUE TITLE
Idea: View similar to Story River in Tiddlywiki

### ISSUE THREAD

**Issue by sahil48** [foambubble/foam#6]
While I edit notes one file at a time, I would like to see a Story-River like view of Notes in Tiddlywiki (https://tiddlywiki.com/), where multiple related notes are tied to one or more keywords selected in the Knowledge Graph to get a bigger picture of a node and quickly navigate to and find files of interest without having to open them one at a time.

**Comment by sahil48** [comment]
In this scheme, referring to https://github.com/foambubble/foam/issues/7, you could even have a node in the knowledge graph present more than one document in a story-river-like view.

**Comment by jevakallio** [comment]
@sahil48 see my response at the other tiddlywiki issue here:
https://github.com/foambubble/foam/issues/10#issuecomment-650814714

I'm keen to learn more about this, but it's not the highest priority right now. If it's important to you, I would love to accept code or documentation contributions to help others!
