### ISSUE TITLE
Notes navigation using orphan panel

### ISSUE THREAD

**Issue by Kcalb35** [foambubble/foam#600]
I've observed that I can navigate through my notes from "BACKLINKS" and "TAG EXPLORER" panels within simply left click, but failed from "ORPHANS" panel.
I don't know whether it's a bug for me. Or I'm looking forward to that feature that I can go through my "orphan" notes from "ORPHANS" panel in order to link them to other notes and make them connected easily and conveniently.

**Comment by riccardoferretti** [comment]
thanks for reporting this, it's now been fixed and will be pushed out with 0.14
