### ISSUE TITLE
Ignoring files requires a restart of VS Code for the setting to be applied

### ISSUE THREAD

**Issue by Barabazs** [foambubble/foam#605]
- Foam version: 0.13.1
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes 

**Summary**
Ignoring files requires a restart of VS Code for the setting to be applied.

**Steps to reproduce**
1. Add a folder to the foam.files.ignore setting. E.g.   `"foam.files.ignore": ["/docs/**/*"]`
2. Look at graph with "Show Graph" and see that the nodes representing the files in /docs/ are still visualised
3. Restart VS Code
4. Look at graph again and now the nodes are correctly ignored and not visible on the graph

**Comment by riccardoferretti** [comment]
yes that's a great point, we should monitor the configuration for that

**Comment by Barabazs** [comment]
According to this part, we can monitor a configuration change that affects a specific key:
https://github.com/foambubble/foam/blob/7412d518d7aeb00976bfbf7b517db62d78f692f7/packages/foam-vscode/src/features/dataviz.ts#L13-L19
Adding the below code after L19 is triggered correctly when I update a line in foam.files.ignore
```javascript
 else if(event.affectsConfiguration('foam.files.ignore')){
    // do something
}
```
But now I'm not sure how to update/regenerate the graph correctly.

**Comment by riccardoferretti** [comment]
this configuration requires the whole `FoamWorkspace`/`FoamGraph` to be recomputed, it would likely live in `extension.ts`, so that not only the dataviz, but all features (e.g. tags, placeholders, ..) are affected by the change

**Comment by riccardoferretti** [comment]
I am thinking this is not very high priority (how often would it happen?) and could probably be closed.
If we decide to go for it, probably the simplest approach would be something like this: https://github.com/microsoft/vscode/issues/45774#issuecomment-373423895
