### ISSUE TITLE
Command 'Foam: Create New Note From Template' Error. 

### ISSUE THREAD

**Issue by vegfos** [foambubble/foam#606]
- Foam version: 0.13.1
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
Forked the [foam template](https://github.com/foambubble/foam-template) and started using foam for note taking a week ago. Great stuff! Everything worked fine (including the command "Create New Note From Template". Then yesterday I tried to run the "Create New Note From Template" and the command results in an error (see screenshot). I've made sure the github fork is up to date as well as the VSCode extension. 

I also get the error on version 0.13.0 and 0.12.1. 

Other commands like 'Show Graph' works perfectly. 

**Steps to reproduce**
1. Execute command Foam: Create New Note From Template
2. Choose the 'your-first-template.md' (Note: the error occurs for all other templates also, in my case). 

**Additional information**
![Error Message](https://user-images.githubusercontent.com/72223445/116506189-0a4c7400-a8bd-11eb-8dad-eaf13b36ed89.png)

**Comment by riccardoferretti** [comment]
can you check if there is any info in the output logs? https://github.com/foambubble/foam/blob/master/docs/features/foam-logging-in-vscode.md

**Comment by vegfos** [comment]
Not sure what to tell you, but it now works. I disabled/enabled the Foam extension this morning, which seems to do the trick (even though i'm pretty sure I tried this yesterday...)

By the way the link to output logs instructions in the issues bug template is dead, and should perhaps be updated from:
- the Foam log in VsCode (see [instructions](https://github.com/foambubble/foam/blob/master/docs/foam-logging-in-vscode.md))

To:
- the Foam log in VsCode (see [instructions](https://github.com/foambubble/foam/blob/master/docs/features/foam-logging-in-vscode.md))

**Comment by riccardoferretti** [comment]
Thanks for that, will fix it
