### ISSUE TITLE
Redirection notes

### ISSUE THREAD

**Issue by wcerfgba** [foambubble/foam#608]
Hi Foamers :wave: 

I am wondering if having notes which can redirect you to other notes would be a useful feature and I wanted to float that with the community.

My use case is as follows: I am building an encyclopedia of economic terminology [1] and it is nice to be able to use wikilinks in a conversational manner, but this is subject to the title (or rather, filename) of the page being linked to. For example, I have sentences like:

> If a variable in an econometric model (see [[econometrics]]) is endogeneous (see [[endogeneity]])

where instead I would prefer to write:

> If a variable in an [[econometric-model]] is [[endogeneous]]

This could be solved by some form of aliasing or titling:

> If a variable in an [[econometric-model|econometrics]] is [[endogeneous|endogeneity]]

but I think redirects would be more suitable because:

* it preserves grep-ability of wikilinks (i.e. they are always of the form `[[<filename>]]`), which permits searching and refactoring;
* reduces complexity of parsing code;
* it allows for incremental refactoring of the page graph.

For example, let's say I have pages `cheese` and `blue-cheese` and I link to both of these from elsewhere. One day I decide I want to move `blue-cheese` into `cheese` as a subheading. Maybe I am lazy and don't want to find-and-replace all of my `[[blue-cheese]]`, but if I can change the `blue-cheese.md` file to redirect to `cheese#blue-cheese` then I do not need to do a find-and-replace, I can just change the content of one page in the graph.

This has the added advantage that we are able to represent concepts like `blue-cheese` as first class nodes in the graph view, even if they are not actually 'pages', and so it decouples the graph from the filesystem. Some may view this as a _disadvantage_ though, it depends on your use case.

I haven't worked with front matter in Foam (yet :wink: ) but I presume standard YAML front matter should work fine? In that case, we could support redirects through a special `redirect` key (or equivalent namespaced/prefixed key) whose value is a wikilink (supporting anchor), for example I could then make my `blue-cheese.md` file the following:

```
---
redirect: 'cheese#blue-cheese'
---
``` 

[1] https://github.com/wcerfgba/studying_economics/tree/master/encyclopedia

Thanks! :pray:

**Comment by riccardoferretti** [comment]
Related to https://github.com/foambubble/foam/issues/461

**Comment by riccardoferretti** [comment]
I would actually consider both of them solutions to the same problem, so unless I am mistaking I would close this issue and move the conversation there
