### ISSUE TITLE
Strange-labelled node appears in the graph linked to existing nodes

### ISSUE THREAD

**Issue by alainrk** [foambubble/foam#611]
- Foam version: v0.13.1
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No

**Summary**
Nodes with strange label (actually they are placeholders sometimes) neither existing in tree folder nor they are wikilinks in any file, appears in the graph (see attached).
Eg. "${1:$TM_FILENAME_BASE}" or "link.md"

**Steps to reproduce**
1. I haven't found a way to reproduce it in a clean repo. I haven't created neither a file nor a wikilink with any of the node label i see.

<img width="248" alt="bug" src="https://user-images.githubusercontent.com/1529268/116921411-3fa5e880-ac54-11eb-943a-6aa45ac9bdc8.png">

**Comment by revett** [comment]
I've had this happen when using `.vscode` snippets, do you use that?

**Comment by alainrk** [comment]
@revett you're right, but I can't explain the "link.md" that doesn't exist as a file nor as a title

**Comment by revett** [comment]
Is it within `.foam/templates`?

**Comment by alainrk** [comment]
No, I have 3 templates in it, but with no such file or link to it inside them.

**Comment by alainrk** [comment]
Pretty strange, always on Mac, but another one (BigSur this time).
I cannot replicate the bug anymore, so no relevant log, no strange-labeled nodes in the graph.
I'm going to update as soon as I'll try with the same configuration as before.

**Comment by alainrk** [comment]
@revett After vscode reboot, I cannot replicate anymore (same configuration of initial bug reporting). I assume this could be closed, I keep monitored anyway.
