### ISSUE TITLE
Add support for nested tags

### ISSUE THREAD

**Issue by huy-vuong** [foambubble/foam#614]
### Context

Other note-taking setups like with [Bear](https://bear.app/) and [Notable](https://notable.app/) have the ability to nest tags such as `#ideas/foam` to indicate "ideas specifically for Foam".

The nesting is denoted by the `/` character, like a directory, so this should be able to work in either `#hashtag` form or in the YAML frontmatter.

This way, it'd be easier to group similar ideas together and instead of just searching for "ideas", you could search for "ideas specifically for Foam" for instance.

The **Tag Explorer** might look something like this:

- #️⃣ ideas
    - #️⃣ foam
        - 📝 Add support for nested tags

### Current Behaviour

- In the **Tag Explorer**:
    - `#ideas/foam` gets treated as just having the tag `#ideas`.
    - Adding the tag `ideas/foam` to the frontmatter gets treated as just having the tag `#ideas`.

### Desired Behaviour

- In the **Tag Explorer**:
    - `#ideas/foam` gets treated as having the tag `#ideas`.
    - `#ideas/foam` also gets treated as having the tag `#ideas/foam`, which is nested inside `#ideas`.
    - Adding the tag `ideas/foam` to the frontmatter gets treated as just having the tag `#ideas`.
    - Adding the tag `ideas/foam` to the frontmatter also gets treated as just having the tag `#ideas/foam`, which is nested inside `#ideas`.

**Comment by riccardoferretti** [comment]
I like the idea, happy to provide guidance if someone wants to take it on

**Comment by pderaaij** [comment]
Part of release 0.13.4. Please try it out and leave feedback, if any.

**Comment by riccardoferretti** [comment]
this is now in 0.13.4, so I am closing the ticket. If anything is amiss, feel free to further comment
