### ISSUE TITLE
In Preview on Windows, local file links go to external

### ISSUE THREAD

**Issue by nduc** [foambubble/foam#616]
- Foam version: 0.13.2
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
In the markdown view the links reference the correct file (c:\foam\todo.md) but in the preview it is different (/c:/foam/todo.md).  See inbox.md as an example.

**Steps to reproduce**
1. Open inbox.md
2. Hover over [[todo]] and notice link.  Ctrl-click and it goes to todo.md
3. Hover over [[todo]] in preview and notice link.  Ctrl-click and it asks to open external website.

**Comment by riccardoferretti** [comment]
I am unable to reproduce in 0.13.3 - can you check whether it has been fixed?

**Comment by riccardoferretti** [comment]
in my testing hovering on the link in the preview will show the title of the note.
inspecting the link will give the relative path to the file.
navigation works well for me in 0.13.3 on both document and preview.

**Comment by nduc** [comment]
Sorry for the late reply.  Yes, it's working in version 0.13.3.
Thanks for the fix!
