### ISSUE TITLE
Possible v0.13.2 Regression - Backlinks & Placeholders

### ISSUE THREAD

**Issue by revett** [foambubble/foam#617]
- Foam version: `v0.13.2`
- Platform: `Mac`
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: `No`

## Summary

- Update to `v0.13.2` today
- Went from no placeholders to over 30
- Backlinks are no longer displaying within the panel
- Some labels on the graph no longer show the correct title
- Reverting to `v0.13.1` manually fixes the issue

Unrelated but this error also starting occuring after the update, even though `/Users/revett/Projects/github.com/revett/pkb/cmd/**/*` is ignored:

```
[error - 12:52:02 PM] FileDataStore: error while reading uri: /Users/revett/Projects/github.com/revett/pkb/cmd - Error: EISDIR: illegal operation on a directory, read
```

## Steps to Reproduce

Unsure currently, am trying to replicate in a [foam template](https://github.com/foambubble/foam-template) workspace.

## Additional information

Example of a placeholder but the file actually exists:

```
[info - 12:58:55 PM] Found: file:///Users/revett/Projects/github.com/revett/pkb/content/code/language/language.md
[debug - 12:58:55 PM] Parsing:
{
  "scheme": "file",
  "authority": "",
  "path": "/Users/revett/Projects/github.com/revett/pkb/content/code/language/language.md",
  "query": "",
  "fragment": ""
}
[debug - 12:58:55 PM] Result:
{
  "uri": {
    "scheme": "file",
    "authority": "",
    "path": "/Users/revett/Projects/github.com/revett/pkb/content/code/language/language.md",
    "query": "",
    "fragment": ""
  },
  "type": "note",
  "properties": {
    "title": "Language",
    "type": "section",
    "draft": true
  },
  "title": "Language",
  "tags": {},
  "links": [
    {
      "type": "wikilink",
      "slug": "code",
      "target": "code",
      "range": {
        "start": {
          "line": 14,
          "character": 2
        },
        "end": {
          "line": 14,
          "character": 10
        }
      }
    }
  ],
  "definitions": [
    {
      "label": "//begin",
      "url": "#",
      "title": "Autogenerated link references for markdown compatibility",
      "range": {
        "start": {
          "line": 16,
          "character": 0
        },
        "end": {
          "line": 16,
          "character": 71
        }
      }
    },
    {
      "label": "code",
      "url": "../code",
      "title": "Code",
      "range": {
        "start": {
          "line": 17,
          "character": 0
        },
        "end": {
          "line": 17,
          "character": 22
        }
      }
    },
    {
      "label": "//end",
      "url": "#",
      "title": "Autogenerated link references",
      "range": {
        "start": {
          "line": 18,
          "character": 0
        },
        "end": {
          "line": 18,
          "character": 42
        }
      }
    }
  ],
  "source": {
    "text": "---\ntitle: Language\ntype: section\ndraft: true\n---\n\n## Graph\n\n### Backlinks\n\n...\n\n### MoCs\n\n- [[code]]\n\n[//begin]: # \"Autogenerated link references for markdown compatibility\"\n[code]: ../code \"Code\"\n[//end]: # \"Autogenerated link references\"\n",
    "contentStart": {
      "line": 7,
      "character": 0
    },
    "end": {
      "line": 19,
      "character": 0
    },
    "eol": "\n"
  }
}
```

The file shows up as a placeholder in the panel:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/2796074/117446891-a9fca880-af34-11eb-8fa2-9c32a1863398.png">

And is not rendered correctly in the graph:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/2796074/117446993-d284a280-af34-11eb-9320-b938ae678a8c.png">

The file exists:

<img width="997" alt="image" src="https://user-images.githubusercontent.com/2796074/117447388-576fbc00-af35-11eb-881f-5c4f9b70e15f.png">

**Comment by revett** [comment]
I believe it is linked to https://github.com/foambubble/foam/pull/593, as the other four PRs included within [v0.13.2](https://github.com/foambubble/foam/releases/tag/v0.13.2) do not touch placeholder code.

**Comment by riccardoferretti** [comment]
can you please share a reproducible set up? I am not sure what's happening here

**Comment by revett** [comment]
@riccardoferretti I've managed to recreate the issue within new a `foam-template` repo.

You should have an invite to: https://github.com/revett/foam-issue-617

I imported one sub-directory of notes from my main workspace, and that recreated the issue. 

Each time I reload the workspace, the incorrect placeholders change, this time there were more: 

<img width="311" alt="image" src="https://user-images.githubusercontent.com/2796074/117554305-b9701480-b04e-11eb-8bd9-ba93cce94300.png">
