### ISSUE TITLE
Question: too much frequent git commit message

### ISSUE THREAD

**Issue by linonetwo** [foambubble/foam#62]
When using GitHub as the backend storage, we will generate lots of commits.

This will impact our contribution heatmap.

And will 20 a day, 7k a year of commits impact git performance?

**Comment by jevakallio** [comment]
> When using GitHub as the backend storage, we will generate lots of commits.

You can choose how often to commit. You can do once a day, or you can do once a minute. You can also rewrite history and squash all your daily commits and force push at the end of the day if you want.

> This will impact our contribution heatmap.

I guess it will 🤷 

> And will 20 a day, 7k a year of commits impact git performance?

Let me know if it becomes a problem!
