### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by DaniAkash** [foambubble/foam#63]
A mobile/tablet app will make foam so much easier to use. Based on my daily usage, I'd prefer a mobile app similar to [GitJournal](https://gitjournal.io/) but focused on quickly creating notes and accessing them using links. 

I'd be more than happy to help build a mobile app once we establish a clear list of features 😁

Previously discussed on this [tweet thread](https://twitter.com/dani_akash_/status/1279813848447324161?s=20)

**Comment by nicholasnadel** [comment]
I'd love this too

**Comment by Koleok** [comment]
In keeping with the way foam wholly delegates it's main _"editor"_ to vscode, I have found that using any one of many mobile markdown/git editors is great solution.

Personally I have been using [gitjournal](https://play.google.com/store/apps/details?id=io.gitjournal.gitjournal) which is literally exactly what I would build if I was making a foam mobile app, sure it'd be nice to have a viewer, tag explorer, a search and all that, but really what your need on mobile is just a way to easily write and read notes. 

If you need the full experience, it's easy to build a static site from your foam project and package it as a pwa. 

Just to clarify, I'd totally install and use a dedicated app, I even thought of building one, but with such elegant and lightweight solutions available I just couldn't justify it.

**Comment by chrisUsick** [comment]
I’m interested in a slightly more refined mobile experience (honestly haven’t got into mobile editing yet). I’d be willing and able to contribute to an implementation too. Here is a link to stimulate some ideas on an open source mobile app: 
https://standardnotes.org/longevity
StandardNotes, another note taking app (my current preference, for its useful extensions and quality cross platform experience) has shipped an open source mobile app successfully their longevity principles are a contributing factor to their success.

**Comment by riccardoferretti** [comment]
@chrisUsick this is a good idea, my first thought would be to properly explore (and document) leveraging compatible applications (e.g. git journal, obsidian mobile, ...) and see what's the delta between that and what we want.

In terms of goals, I reckon the MVP is basically populating an inbox, no need for things like graph, tag explorer, ... which can be added later on.

thoughts?

**Comment by chrisUsick** [comment]
I’m on board with that direction. I’ve been using foam heavily since I
commented here last and my workflow has changed lots. I see one of the
differentiators of Foam being the unique balance of tooling and simplicity.
For documenting compatible applications, where would the right spot be for
that? A PR to the docs, a discord discussion?

**Comment by riccardoferretti** [comment]
a PR for the docs would be the best place to do it.
If you want to do me a favor and go the extra mile, I'd be happy for you to take a general look at the docs and as you have been using it heavily see how they can be improved (e.g. a useful feature that is documented but not easily discoverable and you didn't know about) or integrated (based on your workflow) - I'd really appreciate it!

**Comment by chrisUsick** [comment]
I’d love to contribute as foam is making a real difference to my
productivity! Unfortunately I’m not productive enough to commit to a speedy
PR!
I’ll start organizing my thoughts. I appreciate the direction on how to
contribute.

I’ll open a pr and link to this issue for context.

**Comment by riccardoferretti** [comment]
Closing this for now, as no active dev effort is going on, and workarounds have already been listed in documentation
