### ISSUE TITLE
Links containing '/' delete files

### ISSUE THREAD

**Issue by eBerdnA** [foambubble/foam#64]
Just noticed that there seems to be an issue when having links which contain '/'.

Files:
- Demo1.md
- Link-Topic.md

When `Demo1.md` does contain a link `[[Link/Topic]]` it creates a new file `link-topic.md` even though the file `Link-Topic.md` already exists. Unfortunately this does overwrite everything which has already been written in `Link-Topic.md`.

Environment information:
Visual Studio Code 1.46.1
OS: WSL running Ubuntu 20.04 on Windows 10

If you need any further information just let me know.

**Comment by jevakallio** [comment]
@eBerdnA thanks, this seems unfortunate! The file creation is implemented in [VS Code Markdown Notes](https://github.com/kortina/vscode-markdown-notes) -- could you please open an issue over there and link it here?

**Comment by eBerdnA** [comment]
Thanks for your quick response.

I opened an issue in [VS Code Markdown Notes](https://github.com/kortina/vscode-markdown-notes).

https://github.com/kortina/vscode-markdown-notes/issues/50

**Comment by jevakallio** [comment]
Fixed by Markdown Notes v0.0.11! Thanks for reporting @eBerdnA!

https://github.com/kortina/vscode-markdown-notes/releases/tag/v0.0.11
