### ISSUE TITLE
Create Note deletes previous content if wikilink has different capitalization than Markdown file

### ISSUE THREAD

**Issue by lautjy** [foambubble/foam#641]
- Foam version: v0.13.3
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
Mismatching wikilink vs filename capitalization causes file contents to be cleared.

If [[WIKI-links]] has capitalized letters (like that one), then CTRL+click will **clear existing content** of file `wiki-links.md` if it exists. If filename is `WIKI-links.md` CTRL+click works ok - opens file.
Or if [[wiki-links]] has no caps, but the filename is for example `wiki-LINKs.md`, then CTRL+click will clear file contents.

I just lost all my TODO notes. I'm using [[TODO-project]] to link different TODO's in a project, but I don't like
caps in filenames. Hence the file was `todo-project.md`.

I don't think this has happened from the beginning (used this for 1 month'ish), because I'm sure CTRL+click just worked at some point.

Point of NOTE: I don't have Markdown All-in-one installed, because it has a bug where **it disables the Enter and Backspace keys in .md files**. I have never had an issue with that extension before, but.. for some reason it started misbehaving.

Markdown All-in-one issues:

* This issue: https://github.com/yzhang-gh/vscode-markdown/issues/335
* Issue with more discussion: https://github.com/yzhang-gh/vscode-markdown/issues/95

OSX: I have also OSX laptop where I have NOT encountered this issue. Also.. I have used Foam for month+ on this Win10 machine, and.. all of a sudden this bug appears. Maybe some update, maybe disabling an extension, maybe some setting changed?
_[ EDIT: Issue reproes on OSX with a slight twist. See my next comment below. ]_

NOTE 2: Funnily when CTRL+hovering over the [[WIKI-links]] it shows the actual contents from [[wiki-links.md]], but clicking will still override the contents.

**Steps to reproduce**
1. Clone foam-template repo
2. (have what I have on my machine now -  I might try to repro this from fresh install, but can't right now)
3. Edit `inbox.md` to have 2 wikilinks: [[DOG-cat]]
4. CTRL+click this wikilink
5. Foam creates file `dog-cat.md`
6. CTRL+click the wikilink again
7. Foam clears file contents, and.. actually keeps adding the Title again and again.

**Additional information**
* Attached DEBUG logs from Starting in foam-templates dir, and Clicking on "Smurfs" to override `smurfs.md` contents.
  - [foam_debug.log](https://github.com/foambubble/foam/files/6499335/foam_debug.log)

VSCode info:

* Version: 1.56.2 (system setup)
* Commit: 054a9295330880ed74ceaedda236253b4f39a335
* Date: 2021-05-12T17:13:13.157Z
* Electron: 12.0.4
* Chrome: 89.0.4389.114
* Node.js: 14.16.0
* V8: 8.9.255.24-electron.0
* OS: Windows_NT x64 10.0.21376

VSCode extensions:

```
code --list-extensions
ban.spellright (disabled due to it being annoying)
DavidAnson.vscode-markdownlint
eamodio.gitlens
evilz.vscode-reveal
foam.foam-vscode
goessner.mdmath
hediet.vscode-drawio
kortina.vscode-markdown-notes
ms-azuretools.vscode-docker
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
mushan.vscode-paste-image
PKief.markdown-checkbox
stuart.unique-window-colors
tomoki1207.pdf
```

**Comment by riccardoferretti** [comment]
I wonder if this is more related to `kortina.vscode-markdown-notes` than Foam, can you try disabling that extension?

> Point of NOTE: I don't have Markdown All-in-one installed, because it has a bug where it disables the Enter and Backspace keys in .md files. I have never had an issue with that extension before, but.. for some reason it started misbehaving.

Thanks for this, I have seen that happen to me too and I always wondered what was the cause

---

At the same time, I do believe we need better support for wikilink casing, probably we should be case insensitive, we need to think about possible side effects, but I agree that `[[hello world]]` and `[[Hello World]]` should point to the same resource.

**Comment by lautjy** [comment]
Thanks for the idea @riccardoferretti .  Why do I even have kortina.vscode-markdown-notes installed I wonder.
(Edit: Ah, it was just removed from recommended extensions list)
Anyway, disabled that extension, and even uninstalled it.
Bad destructive behavior remains.

Here are overlaid screenshots of the mouse-over tooltips one gets.

* File `sausage.md` exists.
* The `[[sausage]]` will take me to said file.
* The `[[Sausage]]` will clear the contents of that file, opens it in vscode, and offer the default title "# Sausage + empty file" which I can save. If I don't save, the file is 100% empty.

## Update on OSX:

Just tried on OSX, and the behavior is quite similar. (also removed extension vscode-markdown-notes)

This is the behavior:
* The `[[Sausage]]` will clear the contents of that file, opens it in vscode, and offer the default title "# Sausage" **appended to the existing text**, which I can save. If I don't save, the file is 100% empty.
So on OSX the behavior is bit better. It doesn't completely nuke user's previous content.


I think `touch` is the command one should be using. Touch the file, and if it exists, don't just nuke it :D
I wish I had time and knowledge to look into the code behind this more deeply.


May I ask that, is it so that you cannot reproduce this on your machine?
Write `[[sausage]]` in a .md file. CMD/CTRL+click it to create it. Go to previous md file and write `[[Sausage]]` and CMD/CTRL+click it.  What happens?

**Comment by riccardoferretti** [comment]
I am actually getting a slightly different behavior, where the existing content of the file is not removed, but the `# Sausage` heading is added at the end of the file... definitely a bug in either case :)

**Comment by lautjy** [comment]
> I am actually getting a slightly different behavior, where the existing content of the file is not removed, but the `# Sausage` heading is added at the end of the file... definitely a bug in either case :)

That is how things work on OSX for me. On windows everything is cleared: file contents and vscode text too.

Which operating system were you using if I may ask?

And do note: If you **do not save** the document once `# Sausage` appears at end of file, the file underneath has been wiped empty.  Could you also confirm this behavior?
This is what makes the bug quite severe even on OSX.

**Comment by riccardoferretti** [comment]
yup I am on OSX
and yes, I can confirm that behavior

Without digging into the code I can't tell whether it will be a quick hit, or whether it affects deeper parts of the model.
would love for someone to look into this issue
