### ISSUE TITLE
Insert other md file in preview

### ISSUE THREAD

**Issue by kv-gits** [foambubble/foam#652]
In obsidian you can do ![[file.md]] and its content will be inserted in current one during preview. Would like such feature in foam.

**Comment by SanketDG** [comment]
This might be helpful here https://www.npmjs.com/package/markdown-it-include

**Comment by SanketDG** [comment]
@kv-gits Can you re-open this? I was the one who asked you on discord to open this issue. The package mentioned above allows us to support this in markdown, a certain amount of development still needs to be done :)

**Comment by SR--** [comment]
Just posting to up-vote this.

**Comment by riccardoferretti** [comment]
yes I agree this is a must have, it's also supported by https://github.com/svsool/vscode-memo

**Comment by pderaaij** [comment]
Did an initial look at `markdown-it-include`. Offers the ability to include notes, but all is relative from a root folder. It's not possible to manipulate the behaviour of the inclusion that would allow for a syntax like `![[WikiLink]]`. The only thing that could work is to work with relative links to an MD file, like `![[relative/note.md]]`. Personally, I would feel this does not match the user experience desired by Foam users. 

`vscode-memo` solved this by creating a custom MarkdownIt extensions. Initial research led me to not find a suitable alternative to `markdown-it-include`. Looks like we need to dive into the custom route as well, or other ideas might pop up?

**Comment by riccardoferretti** [comment]
I agree the custom route is probably the best one, just like vscode-memo. 
I reckon there is more complexity in integrating with a third party library than roll out our own solution.
I think their approach is pretty solid, rendering the markdown seems trivial, the only other aspect worth making sure we also support is the cycle detection.

**Comment by riccardoferretti** [comment]
this has been done by @pderaaij 🙌
