### ISSUE TITLE
A way to move selected text into a newly created note

### ISSUE THREAD

**Issue by winni2k** [foambubble/foam#653]
# Feature request

I find myself writing some text in a note and then deciding that that text should live in a new note (a .md file with a random string as name). Currently I perform the following steps to do this. I:

1. generate a short random string
2. run Foam: create new note with the random string as file name and title
3. create a backlink to the note that I want to move the text from
4. navigate the backlink to the note that I want to move the text from
5. highlight and cut the text
6. navigate back to the new note
7. insert the cut text in the new note

I would like to have a shortcut that will perform steps 1.-7. on a highlighted piece of text.

**Comment by riccardoferretti** [comment]
We could add a `Create note from selection` command, which would:
1. ask for the name of the note
2. create a new note with that filename and title
3. take the current selection as content of the new note
4. replace the selection in the original text with a wikilink to the new note

thoughts?

**Comment by pderaaij** [comment]
I would welcome this feature very much. Can imagine using this a lot myself. I'll have a stab at implementing it later this week.

**Comment by winni2k** [comment]
> We could add a `Create note from selection` command, which would:
> 
>     1. ask for the name of the note
> 
>     2. create a new note with that filename and title
> 
>     3. take the current selection as content of the new note
> 
>     4. replace the selection in the original text with a wikilink to the new note
> 
> 
> thoughts?

This sounds really nice. 

After replacing the text with a wikilink to the new note, would the `Create note from selection` command stay "focused" on the original note, or switch focus to the new note? I think I would prefer the former, as the wikilink would be right there to use if needed.

**Comment by riccardoferretti** [comment]
that's an interesting idea. Maybe it could even show in a panel on the side of the original note, so that both are easily accessible (and the new note can easily be closed to get back to the original one)
