### ISSUE TITLE
"Open Daily Note: On Startup" triggering for any directory which contains markdown files

### ISSUE THREAD

**Issue by ChrisJefferson** [foambubble/foam#664]
- Foam version: 
- Platform: Windows (in WSL)
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**

I have enabled "Open Daily Notes: On Startup". This works fine on my roam repository, but also some other repositories seem to trigger creating a daily note.

**Steps to reproduce**
1. Enable "Open Daily Note: On Startup`
1. Create a directory with a file called `README.md`
2. In that directory, run `code .`
3. See that a new markdown file called (for example) `2021-06-03.md` is automatically created.

**Comment by riccardoferretti** [comment]
you can fix this by setting the "Open Daily Notes: On Startup" to False at a user level, and on True in the workspace settings
