### ISSUE TITLE
No templates available if `.foam/templates` is excluded from workspace

### ISSUE THREAD

**Issue by Wieke** [foambubble/foam#665]
- Foam version: 0.13.4
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
No templates available if `.foam/templates` is excluded from workspace.

**Steps to reproduce**
1. Exclude `.foam/templates` from workspace. Either specifically or through a general hidden folder exclusion  rule (e.g. `.*/**`).
2. Try to create a note from a template using the `Foam: Create New Note From Template` command.
3. Command will claim no templates are available even though there are `*.md` files in `.foam/templates`.

**Additional information**
So I did some digging. [According to the api](https://code.visualstudio.com/api/references/vscode-api#workspace.findFiles) the `workspace.findFiles` function will apply default excludes if the exclude parameter is undefined. And in the [getTemplates](https://github.com/foambubble/foam/blob/1cb8174a9f57740ea7419c40647b69f4ff67cfbc/packages/foam-vscode/src/features/create-from-template.ts#L55) function this parameter isn't set. So it the behavior is entirely expected given how things are set up.

The api also mentions that if `null` is passed as the exclude parameter the findFiles function will not apply any exclusion rules (including the default ones). So that would probably be a way of having foam find templates even if the `.foam/templates` folder is excluded from the workspace. The one drawback being that if people were deliberately excluding `*.md` files in the template folder those rules wouldn't be applied anymore.

Of course this is arguably a feature and not a bug. Personally I think it makes sense to exclude hidden folders from a workspace in general. I also would like to exclude everything that isn't a note from my foam workspace, keep it clutter free, but at the moment I can't if I also want to use templates.

**Comment by riccardoferretti** [comment]
Thanks for reporting this.

This looks like a bug to me, the call in `getTemplates` should not honor the exclude list from the workspace as it has a special meaning and is used for configuration only.

Sounds like the solution is to pass `null` as you suggested. I will include this fix in today's release.
