### ISSUE TITLE
Auto-complete/intellisense for tags

### ISSUE THREAD

**Issue by SR--** [foambubble/foam#669]
Some ideas to support easier and more controllable tag management:

- auto-complete/intellisense for tags. if we consider that they are to be in some way controlled or loosely controlled it would be helpful.
- an ability to dump all tags in the alphabetical order into an auto-updated md file for easy viewing, exporting, visualization, etc...

**Comment by riccardoferretti** [comment]
Thanks @SR-- for opening the issue 🚀 

I would prioritize the autocomplete on tags, which would add a missing editing feature in Foam.
As a guide for someone who'd like to take this on, from Discord:

> this is a good idea and unfortunately so far we haven 't given tags lots of love. the implementation should be pretty straightforward because all the data (all tags in the repo) is available, and for the rest it will look very similar to the wikilink autocompletion provider - wanna open an issue for this?

(no pressure ;) )

Regarding the export ability, I am not against it, but I would separate it from the autocompletion.

Will rename the task to reflect the above.
