### ISSUE TITLE
Create a wiki file in the current folder, instead of the root folder

### ISSUE THREAD

**Issue by shuang-yi** [foambubble/foam#680]
When I pressure cmd and click a new `[[wiki-file]]`, the file is always created in the root folder, even if I am in a subfolder. Is there a way to create it in the current folder?

**Comment by t2hv33** [comment]
@shuang-yi I have the same issue
Cmd+Click 1st on a new [[wiki-file]], the new file with the name `wiki-file.md` have created at the root folder.
If a file created in the root folder, just delete it, and do it again.
Cmd+Click on [[wiki-file]] at 2nd time, it's will create at current folder.

**Comment by riccardoferretti** [comment]
this will be addressed by https://github.com/foambubble/foam/issues/566

**Comment by trungtin** [comment]
I don't find this resolved by https://github.com/foambubble/foam/pull/712
My extension is v0.14.2

**Comment by t2hv33** [comment]
@riccardoferretti 
My issue on https://github.com/foambubble/foam/issues/680#issuecomment-863975873 has not been resolved
Foam version`v0.14.2`
Mac OS
VS Code `August 2021 (version 1.60)`
