### ISSUE TITLE
Ignore tags in code blocks

### ISSUE THREAD

**Issue by tzeumer** [foambubble/foam#682]
Notes with CSS id's in code blocks gets the id's parsed as tags. For example `div#myId {color: red}` or

```css
div#myId {color: red}
```

would extract the tag #myId. I think it would be ok to always ignore tags in code blocks. If tags in code blocks are considered useful, maybe the parsing could at least be made an option?

**Comment by riccardoferretti** [comment]
this seems wrong for 2 reasons:
1. tags should start with `#`, not simply contain it
2. tags in code blocks/inlines should be ignored

I was aware of n. 2, I am really surprised by n. 1.

**Comment by tzeumer** [comment]
Sorry, you are right concerning (1). I've chosen the wrong example (`div#myId` is no problem). 

It really should have been more like `#MyId {color: #colorCode}`. Sorry again!
