### ISSUE TITLE
Foam ignores     "foam.openDailyNote.titleFormat": "yyyy-mm-dd"

### ISSUE THREAD

**Issue by jonasdiemer** [foambubble/foam#687]
- Foam version: 0.13.7
- Platform: Mac 
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
Changes in "foam.openDailyNote.titleFormat" are ignored, Daily notes title is always shown as "dddd, mmmm dS, yyyy".

**Steps to reproduce**
1. Open Preferences, Foam > Open Daily Note: Title Format; Click "Edit in settings.json" 
2. Change format to e.g. "yyyy-mm-dd"
3. Open new daily note (via keyboard shortcut)
4. Observe that title format is still like # Monday, June 21, 2021

**Comment by movermeyer** [comment]
Interestingly, I was able to reproduce this, but only in some scenarios...

My config:

```json
  "foam.openDailyNote.directory": "/Users/michael.overmeyer/src/github.com/movermeyer/foam-data/journal",
  "foam.openDailyNote.titleFormat": "yyyy-mm-dd",
```

When I have `/Users/michael.overmeyer/src/github.com/movermeyer/foam-data` opened as a workspace, and run `Foam: Open Daily Note`, then it opens a new note with the title `# Monday, June 21, 2021`, as described in the bug report.

If however, I have a different workspace open, the correct title is used: `# 2021-06-21`

Seems there is something going on with Foam's ability to find the VSCode settings???

**Comment by jmg-duarte** [comment]
I was unable to reproduce, could you provide more information?

**Comment by RobinKing** [comment]
I think this may have something todo with different config files in vscode.

There are 3 config files in the user directory, workspace directory, and current directory.

See if the workspace settings file `workspace.code-workspace` also has a config item for `foam.openDailyNote.titleFormat`.

I can reproduce this by changing `workspace.code-workspace` .

@jonasdiemer @movermeyer

**Comment by jonasdiemer** [comment]
Thanks, @RobinKing - I indeed overlooked the setting in the workspace config.
