### ISSUE TITLE
ignore folders at the root of workspace not properly ignored

### ISSUE THREAD

**Issue by adrien-perello** [foambubble/foam#704]
This is linked to [#304](https://github.com/foambubble/foam/issues/304)

Let's assume that the structure of my workspace in vscode is as follow:
```
workspace
  ├ foam directory
  | ├ _layout/
  | ├ notes/
  | ├ A/
  | └ index.md
  |
  ├ folder1 (with many other files)
  └ folder2 (with many other files)
  ```
  From [#304](https://github.com/foambubble/foam/issues/304), we know how to ignore **`A/`**. But I don't manage to ignore all the other files (in folders at the root of the workspace: **`folder1/`**, **`folder2/`**) from showing up in the graph view.
    
![Screenshot from 2021-07-06 13-24-38](https://user-images.githubusercontent.com/76055749/124592660-fa718300-de5d-11eb-8f65-82a7c34f1099.png)

I added ```"foam.files.ignore": []``` in 'settings.json' in both the workspace and the user (I also tried adding ../ in front of the paths), but it does not ignore the folders. Only the folders that are inside my 'foam directory' seems to be ignorable.

And I much rather avoid having several vscode windows opened :sweat_smile:  Any clue how we could go about it? :smiley:

**Comment by pderaaij** [comment]
Just wondering, given it's a glob I would wonder if `*/folder1` would work or perhaps `**/folder1` could work? Might be interesting to give a try and see if that solves it?

**Comment by riccardoferretti** [comment]
My guess (without having looked closely at the implementation) is that the glob use the workspace folder as root (/), so it won't filter by that.
In a way it's as if the workspace folders namespace is unified before the globbing takes place.
This needs to be validated, it's just my hunch atm

**Comment by pderaaij** [comment]
I would expect that when #730 is merged, you can ignore the folders successfully by using a glob as `/folder1` of `/**/folder1`

**Comment by riccardoferretti** [comment]
Closing as I believe it's been fixed and has been inactive for a long time
