### ISSUE TITLE
Add collapsible markdown 

### ISSUE THREAD

**Issue by asbjornb** [foambubble/foam#71]
I'm just getting started and this might be something I just haven't found or that my work flow could be optimized. But in multiple of my notes I'd like the option to collapse regions of the note. Like in my inbox and todo notes I like to have a section in the top on usage and have that collapsible so it's not visible generally (like for code in visual studio) but that you can expand. Also in goals/todos I generally section in *today, *this week, *long term and it would make sense to only view *today most of the time and then only once a day open the other sections.

I can easily generate collapsible text in the preview pane with `<detail>` and `<summary>` but when working in the markdown document I can't collapse it.

I'm not sure if this is easy to implement or if others have other extensions that can solve this or good ways to work around it. I guess I could link to a usage document for each and that each time I want something to be collapsible it might be that I should actually create a new linked note?

**Comment by jevakallio** [comment]
As of today, you can already collapse markdown header sections, as well as lists and sub-lists. I'm not sure if this is default VS Code behaviour or part of Markdown All In One that's one the automatically installed Recommended Extensions:

![collapse](https://user-images.githubusercontent.com/1203949/86759324-5b446080-c03c-11ea-9c7a-70b63c848387.gif)

Do you need more granular control than this?

**Comment by asbjornb** [comment]
Thanks. That is perfect and just what I needed. I was apparently just blind.

Thanks again for the work you put into this!

Btw. I added a spellchecker extension to my own visual studio code for notetaking - I'm not sure if it's common enough to use with notes that it might make it to recommended extensions for the template.
