### ISSUE TITLE
Wikilink notes created on Cmd+<Hover>?

### ISSUE THREAD

**Issue by movermeyer** [foambubble/foam#715]
- Foam version: v0.13.8
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**

* When I Cmd+<Hover> over a placeholder Wikilink, it produces a new file as a sibling of the file that contains the wikilink.
    * The filename is slugified (lowercase + escaped)
* When I Cmd+Click a placeholder Wikilink, it produces a new file in the root of the workspace
    * The filename is **not** slugified, as expected
    * Depending on timing, the Cmd+<Hover> may also occur.

I do not expect any notes to be created until I Cmd+Click, at which point I expect the note name to not be slugified.

**Steps to reproduce**

![weirdness](https://user-images.githubusercontent.com/1459385/125353156-2f834700-e330-11eb-95c4-c482627e0078.gif)

#### Scenario 1

1. Create a new note `<WORKSPACE>/weirdness/link_to_weirdness.md`

```markdown
[[Weirdness]]
```

2. Cmd+<Hover> over the `[[Weirdness]]` wikilink with the mouse

`<WORKSPACE>/weirdness/weirdness.md` is created (with the contents `# Weirdness`) and link reference definitions are generated and added to `<WORKSPACE>/weirdness/link_to_weirdness.md`

#### Scenario 2

1. Create a new note `<WORKSPACE>/weirdness/link_to_weirdness.md`

```markdown
[[Weirdness]]
```

2. Cmd+Click over the `[[Weirdness]]` wikilink with the mouse

`<WORKSPACE>/Weirdness.md` is created (with the contents [`# $\{1:Weirdness}\n\n$0`](https://github.com/foambubble/foam/blob/1ab9cc5f4a3cc89fa6fb9751fc5f9d07e48ccb8b/packages/foam-vscode/src/features/utility-commands.ts#L24))

Depending on timing, the behaviour of Scenario 1 may also occur.

**Comment by riccardoferretti** [comment]
do you also have Markdown Notes installed?

**Comment by movermeyer** [comment]
I did. 🤦 

Uninstalling `Markdown Notes` fixes the problem.
