### ISSUE TITLE
Creating a wikilink with a `/` starting the path creates multiple files

### ISSUE THREAD

**Issue by dkowis** [foambubble/foam#720]
- Foam version: v0.14.0
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes 

**Summary**
If you create a Daily Note, and create a wiki link in it, it will create it in the Journal folder. That's not always desireable, so I tried to create a link in a specific location using `[[/root-note]]` which, via assumption, would put it in the root, not in the current path.
Instead, it created *two* files, one in the journal folder, and one in the root.

Even more fun, when you click on that file to navigate to it, it overwrites the content of the file, *always*

**Steps to reproduce**
1. Get the template repo
2. Open a daily note
3. create a wikilink `[[/root-note]]`
4. See that there are *two* notes created, one in `journal` and one at the root
5. Edit content in the root note and the `journal/root-note.md` just to compare things
    * Something like "in the journal" and "in the root"
    * ![image](https://user-images.githubusercontent.com/28048/125661086-bbbb27a8-31d8-4746-89db-79241d85ed64.png)
6. ctrl-click on the `[[/root-note]]` in the daily note
    * ![image](https://user-images.githubusercontent.com/28048/125661171-15e7d77f-a842-4ee4-88bb-49567caf7d9e.png)
7. you get taken to the root note, but it overwrites all the content, and breaks things.
    * ![image](https://user-images.githubusercontent.com/28048/125661300-6562ced5-5111-4d36-9a8a-17cec3c9d0be.png)

**Comment by pderaaij** [comment]
Hi, same request as in the other issues. Could you provide a list of extensions? Quick try-out gives me a different behaviour, so want to rule some things out. Thanks in advance!

**Comment by dkowis** [comment]
Just for completions sake: 

```
❯ code --list-extensions
aprilandjan.ascii-tree-generator
asciidoctor.asciidoctor-vscode
ban.spellright
eamodio.gitlens
esbenp.prettier-vscode
foam.foam-vscode
hashicorp.terraform
jebbs.plantuml
kortina.vscode-markdown-notes
lunaryorn.fish-ide
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
mushan.vscode-paste-image
naumovs.color-highlight
philipbe.theme-gray-matter
puppet.puppet-vscode
rebornix.ruby
skn0tt.markdown-link-expander
skyapps.fish-vscode
systemticks.c4-dsl-extension
t-nano.markdown-to-confluence-vscode
tchayen.markdown-links
wingrunr21.vscode-ruby
yzhang.markdown-all-in-one
```

**Comment by pderaaij** [comment]
Ah, I see `kortina.vscode-markdown-notes` is enabled. That's one I have disabled and when I enable it, it does replicate the behaviour that you are seeing. It was a recommended extension, but I am not certain if it still is or should be. It's actually removed from the template (https://github.com/foambubble/foam-template/commit/ca8ee63cea4a846b3ce0606ff2252c64825ba89f). 

I'd suggest trying things with this extension disabled. If you're happy with how it works, that solves the problem. If you need markdown notes for certain reasons, we'd like to know!

cc @riccardoferretti

**Comment by dkowis** [comment]
Yep, that did it. Probably an artifact of having it installed when it used to be a recommended extension, and I didn't ever go back to clean it up. I'm satisfied with this solution. and it resolves https://github.com/foambubble/foam/issues/719 as well.

I don't know if ya'll want to close it, or if there's some action that needs to be done, maybe a `conflicts` so it doesn't remain installed, since it does break things if both are enabled at the same time.

**Comment by riccardoferretti** [comment]
> I don't know if ya'll want to close it, or if there's some action that needs to be done, maybe a conflicts so it doesn't remain installed, since it does break things if both are enabled at the same time.

I was looking in the VS Code documentation for this `conflicts` you mentioned, but couldn't find it, can you point me in the right direction? thanks!

**Comment by dkowis** [comment]
> > I don't know if ya'll want to close it, or if there's some action that needs to be done, maybe a conflicts so it doesn't remain installed, since it does break things if both are enabled at the same time.
> 
> I was looking in the VS Code documentation for this `conflicts` you mentioned, but couldn't find it, can you point me in the right direction? thanks!

To be honest, I was using that as a hypothetical, I assumed there was a way to mark an extension as being conflicty with another. Google searching has led me to believe that isn't possible. So I guess there's not really anything that can be done, other than a manual list, or going through this process with ya'll again :(

**Comment by pderaaij** [comment]
Perhaps we should open a changelog file after an update of the extension? Much like the behaviour of `vscode` itself? Could be a way to communicate updates and recommendations.

**Comment by riccardoferretti** [comment]
yup, I would like to integrate this, which I really like: https://github.com/alefragnani/vscode-whats-new

Haven't had the chance yet, but I think it would address some of these issues.

**Comment by riccardoferretti** [comment]
I have created an issue to track this: https://github.com/foambubble/foam/issues/721

I think therefore this issue can be closed (feel free to comment if you feel otherwise)
