### ISSUE TITLE
New Files Oddity With Placeholder links

### ISSUE THREAD

**Issue by everythingability** [foambubble/foam#726]
Am I not understanding how this should work?

I am writing a Markdown/Foam file which is the root of my **art-foam** project.  _(btw my "art-foam" project folder is in my Mac's WebServer Documents folder)_

Expecting to create a placeholder link, I create a link like this... 

```* [Ganesh](works/ganesh/Ganesh.md)```

... and command-click it. And although it suggests that it *should* make it in the right place. That is to say, it should create a folder in the subfolder works called "ganesh" and then in there a file called Ganesh.md. 

<img width="676" alt="Screenshot 2021-07-18 at 10 51 42" src="https://user-images.githubusercontent.com/96276/126062885-51db00a3-f001-4132-8169-cc755702dafa.png">

... It actually creates a folder in my root called "Library" WebServer/Documents/art-foam/ganesh/Ganesh.md.md 

Now, I know I'm expecting a lot for it to create a folder called "ganesh", when I create a link to a folder and file in the "works" folder, but when I create a link to a file THAT DOES ALREADY EXIST, it doesn't put ".md" in the link.... and doesn't have the weird glitch of replicating the whole path in folder form into my project.

My guess is that although I might be able to create placeholders that create files, they have to be in the same folder right? And/or when using other folders or paths, those folders need to exist already (which is a shame).

Lastly, in theory should link placeholders contain .md on the end or not?

Thanks

**Comment by Hocnonsense** [comment]
I meet the same error

Meanwhile, another bug occurs when there are two files with same name but in different subdir:
![image](https://user-images.githubusercontent.com/48747984/127596967-bf9d23ab-6d9c-454b-8f56-63861fa83a89.png)

I'm at `Bioinformation\MetabolicModels\s41396-020-0710-7\README.md`, I'm expected to `Bioinformation\MetabolicModels\s41396-020-0710-7\Introduction.md`, but I went to `Bioinformation\MetabolicModels\PSAMM\Introduction.md`

Thanks

**Comment by riccardoferretti** [comment]
@Hocnonsense can you please create a separate issue for the name conflict bug?

**Comment by memeplex** [comment]
I think this is a special case of my report https://github.com/foambubble/foam/issues/864 and may be closed as such.

I'm going to implement the following logic as soon as I find the time:

- Absolute link (starts with `/`): create in the workspace root
- Relative link (starts with `./` or `../`): create relative to current note folder
- Other (identifier): show a dropdown with all workspace folders
