### ISSUE TITLE
store and fetch gists as bubbles

### ISSUE THREAD

**Issue by perXautomatik** [foambubble/foam#731]
i have a vast amount of notes taken as gists.
would be very usefull to be able to push and pull notes and vizualise and organize them in foam
currently they don't have the right formating so some sort of pull, editing and then push when correctly formated.

gistpad is a nice vscode extension, maybe possible to integrate with foam?

i'll gladly help develop such feature and would love to hear any feadback from senior foam developers why they'd think this is a good/bad idea and and what would be needed to be done to get it implemented.

**Comment by miseenplace** [comment]
Not sure if you've seen this:

[https://jackiexiao.github.io/foam/recipes/gistpad/](https://jackiexiao.github.io/foam/recipes/gistpad/)

Seems like you can use foam templates with gistpad, though this is not exactly what you were looking for regarding an already established pile of gists. Perhaps you could write a script to pull the contents down, reformat/update them to foam's spec, then push them to a foam-template configured in gistpad as outlined in the above source?

Hope this helps.
