### ISSUE TITLE
Command to enter current time

### ISSUE THREAD

**Issue by vamsiyerramilli** [foambubble/foam#735]
A feature similar to Roam's /current time, this would allow to quickly enter the time right now, which helps maintaining a log of tasks or any other form of journaling much easier - this would be particularly useful in the daily note page.

**Comment by riccardoferretti** [comment]
we have `/now` which gives you the current date in wikilink format (so you can connect it to your daily note).
What does `/current` give you exactly? if it's just "text replacement" then probably a VS Code native snippet would do?

**Comment by adamist521** [comment]
I don't have `/now` command either. Is this due to version or something?

<img width="534" alt="image" src="https://user-images.githubusercontent.com/2974951/201448831-69db1759-3d90-47bd-be9d-e23daeaf5848.png">

**Comment by riccardoferretti** [comment]
it's `/today` 😅

**Comment by riccardoferretti** [comment]
But to my previous point, the goal of these snippets is to create wikilinks to day notes, not to timestamp things.
You don't need Foam to create a timestamp snippet, there is nothing "Foam specific" in it, I believe a simple VS Code snippet should do

**Comment by adamist521** [comment]
> You don't need Foam to create a timestamp snippet, there is nothing "Foam specific" in it, I believe a simple VS Code snippet should do

I got your point! Thanks ❤️
