### ISSUE TITLE
filename confusion

### ISSUE THREAD

**Issue by Hocnonsense** [foambubble/foam#736]
- Foam version: v0.14.2
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No

**Summary**
when there are two files with same name but in different subdir:
![image](https://user-images.githubusercontent.com/48747984/127596967-bf9d23ab-6d9c-454b-8f56-63861fa83a89.png)

**Steps to reproduce**
I'm at `Bioinformation\MetabolicModels\s41396-020-0710-7\README.md`, I'm expected to `Bioinformation\MetabolicModels\s41396-020-0710-7\Introduction.md`, but I went to `Bioinformation\MetabolicModels\PSAMM\Introduction.md`

This bug may related to #726 ?

Thanks!

**Comment by memeplex** [comment]
Does this still happen in the latest version? There were many changes related to how relative filenames are treated.

**Comment by riccardoferretti** [comment]
Closing as this should be fixed as of 0.16.0, feel free to let us know if that is not the case
