### ISSUE TITLE
Creating new files using [[markdown-links]] doesn't actually create files until I click through.

### ISSUE THREAD

**Issue by ztratar** [foambubble/foam#74]
As mentioned in the title, creating new files using [[markdown-links]] doesn't actually create files until I click through.

I am not entirely sure how to reproduce yet, but this compounds with another issue: if I create a file with [[markdown-links]], then it doesn't show up in "Link references" as well. Getting it to show up is also quite unreliable, so I'm having trouble creating connections.

**Comment by jevakallio** [comment]
> creating new files using [[markdown-links]] doesn't actually create files
until I click through

This is the behaviour of vscode markdown links extension. We might want to
improve on it in the future, but it does open other questions, such as,
when should a file be created? If we create it as soon as you stop typing,
we could accidentally create useless files with typos in their names

>  if I create a file with [[markdown-links]], then it doesn't show up in
"Link references" as well. Getting it to show up is also quite unreliable,
so I'm having trouble creating connections.

Yes, this is something we're looking to fix. Right now the process you'd
have to follow to get it to be reliable is:

1. Click through to new file
2. Cmd+S to save
3. Ctrl+Tab to navigate back to file
4. Cmd+S to generate link references

This is clearly not ideal and is the highest priority TODO right now. It'll
be shipped as part of
https://foambubble.github.io/foam/workspace-janitor#notes

**Comment by ztratar** [comment]
Good points!

I would think:

- Create the file immediately.
- As references are removed, to a file, check if that file is empty and no other backlinks exist. If so, delete the file.

Only edge case is that I create an empty file on purpose and have no backlinks there, then attempt to backlink and don't want it anymore, thus deleting the file accidentally. Might require meta-data to remove that edge.

Excited for the next ship! 👍

**Comment by steveklabnik** [comment]
I don't know the exact behavior Roam has here, but it will create the pages immediately, but also seems to clean up after typos somehow.

**Comment by ividic** [comment]
Obsidian creates the file once the user opens the link for the first time

**Comment by ztratar** [comment]
Correct @ividic, but Obsidian is IMO not the ideal state. If I create a [[topic]], I then want it to autocomplete and create a file for me automatically so I can just go to it.

Worrying about creating the file is just an extra step that removes from the user experience. If there's a trade-off to be gained where having the manual creation step helps, I don't see it, but am interested to hear about i!

**Comment by amatsukawa** [comment]
I like the way Obsidian does it, which is any [[links]] show up for autocomplete on links, but a file is not created until you click through.

**Comment by jivthesh** [comment]
@ztratar can I work on this

**Comment by riccardoferretti** [comment]
Probably the approach we will take will be along the lines of Obisdian - good mix of UX and avoiding managing empty files
