### ISSUE TITLE
Recommended Extension: TODO Tree

### ISSUE THREAD

**Issue by TheOneValen** [foambubble/foam#740]
I would like to suggest another recommended extension:

[TODO Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) pairs wonderfully with foam.

You'll get an overview of all the stuff you want(ed) to do sometime in your workflow.

Works very well for me and I thought I share.

Have a good day!

**Comment by riccardoferretti** [comment]
Added to documentation, this issue can be closed
