### ISSUE TITLE
slash (/) commands disappeard (eg /yesterday)

### ISSUE THREAD

**Issue by wafe** [foambubble/foam#743]
- Foam version: v0.14.2
- Platform: Windows 
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo:  No

**Summary**
slash commands like /yesterday, /today are not working.

**Additional information**

Feel free to attach any of the following that might help with debugging the issue:
- screenshots
![image](https://user-images.githubusercontent.com/1501557/129353693-87a1a3b7-f902-439c-9ade-29111fac6ce2.png)

**Comment by benrobertsonio** [comment]
I have also noticed this, starting yesterday.

**Comment by riccardoferretti** [comment]
This was reported on discord:

https://discord.com/channels/729975036148056075/729975036664086560/874633965699485786

Can you check if you have markdown notes enabled?

**Comment by benrobertsonio** [comment]
I do have markdown notes enabled, and disabling markdown notes does bring back the `/` commands.

**Comment by wafe** [comment]
Oh, me too.
After I did disable Markdown Notes, slash commands are back.

**Comment by riccardoferretti** [comment]
> Is Markdown-notes not necessary to use FOAM now ?

That's correct
