### ISSUE TITLE
Creating new note manually creates 3 nodes on the graph

### ISSUE THREAD

**Issue by dannysemi** [foambubble/foam#745]
- Foam version: 0.14.2
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
Manually creating a new note by pressing ctrl+N and then saving the file as markdown in the workspace causes three nodes to be added to the graph. It creates one with the id "Untitled-1" and the path as the first heading I created in the file. It creates two others with the correct path as the id, but one of them the *C* in the pathname is uppercase and the other is lowercase:

/C:/path/to/file
/c:/path/to/file

**Steps to reproduce**
1. Open graph
2. ctrl+N to create a new file.
3. Give the note a heading, e.g., `# test-1` (not sure if this is necessary to reproduce, but it's a step I took)
4. Save the file as .md, e.g., test-1.md
5. Observe console output. There should be the three nodes mentioned in the summary in the object accompanying `didUpdateGraphData`.

**Additional information**
The bug persists when closing the webview and reopening. Completely reloading the extension loads the expected one node with the id as the lowercase path.

**Comment by dannysemi** [comment]
I'm pretty sure this causes the `document not found` errors I get in the console sometimes too. Selecting a node with the improper id would probably result in this error, right?

**Comment by riccardoferretti** [comment]
I can't reproduce this anymore, I believe it was solved by the refactoring around `URI` and more changes to make Foam happy in Windows. can you please validate? will close in the meantime
