### ISSUE TITLE
Optionally include deadlines for TODO items.

### ISSUE THREAD

**Issue by arnarthor** [foambubble/foam#75]
It would be a neat feature to have the ability to add an optional `deadline` tag to `todo` items. 
It would open up the ability to create an automated agenda view where you have all your todos with deadlines viewable across all files.

Link to Discord discussion on this topic: https://discordapp.com/channels/729975036148056075/729978910363746315/730192312856084562

Screenshot from org-agenda which is the inspiration for this feature request
![image](https://user-images.githubusercontent.com/4514159/86853361-dee66780-c0a5-11ea-9bd2-39d71fe77e69.png)

TODOs in this picture come from multiple files and are gathered in a single view to keep track of progress.

**Comment by sauravkhdoolia** [comment]
@jevakallio If you want to use a lib for this then take a look at [this](https://github.com/pgilad/leasot).

**Comment by yufanlu** [comment]
It would be awesome if this is supported! Could fully migrate to foam with this feature

**Comment by ingalless** [comment]
@yufanlu @arnarthor Although it doesn't support deadlines, [this extension](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) may be useful.

@sauravkhdoolia Looks a good lib! I wonder if this would be better developed as an extension that could be curated into Foam rather than baked into Foam. @riccardoferretti any thoughts? Could this be a good candidate for a plugin too?

**Comment by riccardoferretti** [comment]
Yeah it's definitely something people are interested in managing via foam. 
My take is that it's good to get started with a recipe, using a third party extension (like the ones that have been mentioned) to gather some experience and data on the use cases.
A template-level plugin sounds like a good option for someone that needs deeper integration as well.
Eventually it might be built into foam core, probably down the line, there are a few other priorities we are focusing on atm.

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
