### ISSUE TITLE
Add more meaningful error message to replace "ByName[name].push is not a function at Foam Workspace.set"

### ISSUE THREAD

**Issue by iam-yan** [foambubble/foam#760]
## Problem

Because of invalid naming, broken links or some other issues, sometimes foam could fail to get reloaded. However the error message is just a JS Uncaught TypeError, which is not helpful.

## Solution

Catch the error and print the name and path of the problematic file.

**Comment by riccardoferretti** [comment]
can you provide an example step by step to reproduce the issue?

this might have already been addressed by #729

**Comment by iam-yan** [comment]
Sure.

1. Create a note named `constructor.md`.
2. Reload VS code.
3. See the error:
![image](https://user-images.githubusercontent.com/48427014/132154229-149f007e-b5e2-4ae7-aac8-ec29a7634aaa.png)

It would be better if this error could point out where it has failed.

**Comment by pderaaij** [comment]
This one will be fixed in #729, duplicate of #705. Thanks for reporting!

**Comment by iam-yan** [comment]
@pderaaij 

Cool! Thank : )
