### ISSUE TITLE
Wikilink in markdown preview mode not working 

### ISSUE THREAD

**Issue by jamestansx** [foambubble/foam#765]
- Foam version: 0.14.2
- Platform: Windows 10
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**

tl;dr: _Opening `wikilink` in preview mode doesn't work_ 

With built-in preview mode & enabled `markdown notes`, `vscode` will treat the links as url. However, if disabled `markdown notes`, nothing will happen when clicking on the link in preview.

With `markdown preview enhanced` preview mode (although this is not supported by `foam`), the link appears to be working with or without `markdown notes`, but with a catch that the link can only be opened if the note lives at the root of the workspace. `vscode` will try to open the notes(that is inside subdir) in the root folder which doesn't exist. 

**Steps to reproduce**
1. clone the foam template repo
2. open `getting started.md` in preview (built-in/`markdown enhanced`)
3. click on the wikilink --> `get-started-with-vscode` (or any other link except for `inbox)
4. Errors occur (either link not functioned, trying to open in browser, or note doesn't exists as described in *summary*
5. click on `inbox` wikilink in `enhanced preview`
6. note successfully open

**Additional information**

Feel free to attach any of the following that might help with debugging the issue:
- screenshots
- a zip with a minimal repo to reproduce the issue
- the Foam log in VsCode (see [instructions](https://github.com/foambubble/foam/blob/master/docs/features/foam-logging-in-vscode.md))

**Comment by riccardoferretti** [comment]
I have just tested this and I can't reproduce it.
Try updating to the latest Foam, there was an issue at some point with VS Code changing the way links in the preview were being opened, which was fixed in Foam (although I believe 0.14.2 already had it).
We don't provide support for `markdown preview enhanced`.

**Comment by jamestansx** [comment]
Closing this as I have made it work by enabling `foam.edit.linkReferenceDefinitions`.

**Comment by tobiasriemenschneider** [comment]
Hi both (@riccardoferretti / @jamestansx)!

I'm happy that it works for you. However for me it's not scrolling down to the linked section/headline in Preview Mode.
I made a screen-capture: https://www.youtube.com/watch?v=U49jtI9bBuo

Am I doing somthing wrong?

**Comment by riccardoferretti** [comment]
Hi @tobiasriemenschneider, thanks for reporting the issue.
The bug you reported is related to the 0.17.0 release with support for sections, not to the original issue discussed here.
My guess is that you are having the problem only when linking to sections, not to simple wikilinks, right?

Can you please file a new bug for this?

**Comment by tobiasriemenschneider** [comment]
@riccardoferretti, thanks for the fast reply. 👍

Yes, only when linking to sections, normal Wikilinks do work.

Here the seperate bug, as requested: https://github.com/foambubble/foam/issues/863

**Comment by jankap** [comment]
I do have the same issue unfortunately:

![image](https://user-images.githubusercontent.com/12893844/185367120-17317947-1686-4274-b75d-0bf8fa3f56a1.png)

Wiki links are not interactive in preview mode.
