### ISSUE TITLE
Has anyone considered using gollum?

### ISSUE THREAD

**Issue by craig-silva** [foambubble/foam#766]
Its possible that Gollum could be used to publish foam - and run locally to avoid github and/or/gitlab to publish to - and as a local viewer.

Apologies for not doing the work - bandwidth - as is the case for all of us I suppose - maybe in time - but perhaps someone might have more time.

**Comment by riccardoferretti** [comment]
Thanks for suggesting this @craig-silva - will leave it open for now in case there is interest.
I will close it in some time if no one steps up to dig deeper into this issue.
