### ISSUE TITLE
New graph command seems to be losing some nodes

### ISSUE THREAD

**Issue by DrakeWhu** [foambubble/foam#777]
- Foam version: 0.15.0 
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No

**Summary**

Graph command seems to be losing nodes when changing between tags and default visualization

**Steps to reproduce**

1. Run the command `Foam: Show Graph`
2. Select the `tags` option and wait for the visualization to change
3. Select the `default` option and wait for the visualization to change

**Additional information**

Screenshots of my graph visualization:

- First `default` viz
<img width="620" alt="red1" src="https://user-images.githubusercontent.com/68055182/135923428-4c871494-8e8a-4232-9a8c-1430e154674f.png">
- First `tags` viz
<img width="573" alt="red2" src="https://user-images.githubusercontent.com/68055182/135923484-8a3ed758-f963-4dab-bf1b-6aacc41aefbc.png">
- Second `default` viz
<img width="552" alt="red3" src="https://user-images.githubusercontent.com/68055182/135923523-1644a277-a05a-4bd0-930c-96922d5fc8e7.png">

**Comment by riccardoferretti** [comment]
p.s. your graph looks pretty cool!

**Comment by riccardoferretti** [comment]
I haven't released the new version of the extension yet ;)
