### ISSUE TITLE
LaTeX formatting in hover link preview

### ISSUE THREAD

**Issue by Dominic-DallOsto** [foambubble/foam#788]
Since #728 there is now a nice markdown-rendered preview of a page if I hover over a wikilink to it.

But LaTeX-formatted maths equations do not display nicely in this markdown rendering, as shown below.

![image](https://user-images.githubusercontent.com/26859884/137808827-a9bc3a13-73fb-4521-957a-2b663fc6f0fb.png)

Is a different renderer being used for the hover compared to the normal markdown preview view?

While not a huge issue, how feasible would it be to nicely render LaTeX equations in the hover preview?

**Comment by jsamr** [comment]
@riccardoferretti This PR https://github.com/microsoft/vscode/pull/132182 which has been merged into insider preview, enables support for HTML given the `supportsHtml` option, so that should be feasible :-).
