### ISSUE TITLE
Support for embedded markdown

### ISSUE THREAD

**Issue by SvanteRichter** [foambubble/foam#790]
Would it be possible to get foam working with embedded markdown? My usecase is to use https://marketplace.visualstudio.com/items?itemName=jeoht.es6-string-markdown to be able to link & graph between foam markdown docs and a js codebase.

The markdown blocks in the js files look like this
```js
md`
# Hello
[[foo]]
`
```
or

```js
/* md */`
# Test
[[bar]]
`
```

If anyone has pointers on where to start to implement such a feature I'll give it a try!

**Comment by SahAssar** [comment]
The extension works the same way as https://marketplace.visualstudio.com/items?itemName=bashmish.es6-string-css does for css (but for markdown), essentially providing syntax highlighting for blocks of non-js code within js. It does this via https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals, either by using a tag function called md or by prefixing the template with a comment (`/* md */`).

Some other extensions, like for example stylelint support these kinds of embed code blocks for css. Essentially I just want to be able to leverage foams backlinking, graphing and similar for code comments, sortof like normal docblocks but with foam.

An example would be something like:

```js
/* md */`
# isNaN

A [[polyfill]] for isNaN using [[strict equality comparison]].
Works because NaN is the only thing that is not equal to itself.
`

const isNaN = function(value) {
    const n = Number(value);
    return n !== n;
};
```
