### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lregaladohdez** [foambubble/foam#793]
- Issue Type: `Performance`
- Extension Name: `foam-vscode`
- Extension Version: `0.15.0`
- OS Version: `Darwin x64 19.6.0`
- VS Code version: `1.61.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/xr/lxzkfq693fv4xhvwb741sn340000gp/T/foam.foam-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by riccardoferretti** [comment]
keeping this closed as duplicate of #739
