### ISSUE TITLE
Long delay in link highlighting

### ISSUE THREAD

**Issue by memeplex** [foambubble/foam#805]
- Foam version: v0.15.2
- Platform: macOS Big Sur
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**

Colorization of wikilinks occurs after a perceptible delay even in very small pages that are already loaded. This produces a noticeable and ugly visual artifact.

**Steps to reproduce**
1. Create a page a.md with content `[[b]]`
2. Create a page b.md with content `[[a]]`
3. Repeatedly switch between them.

https://user-images.githubusercontent.com/2845433/139409175-d4d1e9fa-fc1d-4160-8f34-b92c65835ddf.mov

**Comment by pderaaij** [comment]
Looked briefly into in, but seems to be a bit intentional. If I understand the `debounce` function correctly, we basically tell the editor to decorate the links 500 ms after activation. I don't know the reasons why and if we should optimise this. @riccardoferretti do you have any background information on this?

**Comment by memeplex** [comment]
FWIW from my perspective as user, having those flashy color changes each time a document is shown (not only the first time but every time) is distracting as well as unpleasant. I thought you were bumping into some vscode constraint.

**Comment by memeplex** [comment]
I think the problem you have here is that both `onDidChangeActiveTextEditor` and `onDidChangeTextDocument` throttle decoration updates. It's sensible to throttle on text document changes but you want to update ASAP on active text editor changes.

```ts
      vscode.window.onDidChangeActiveTextEditor(editor => {
        activeEditor = editor;
        debouncedUpdateDecorations(activeEditor);
      }),
      vscode.workspace.onDidChangeTextDocument(event => {
        if (activeEditor && event.document === activeEditor.document) {
          debouncedUpdateDecorations(activeEditor);
        }
      })
```

 I've checked the implementation of vscode-memo and indeed it only delays on document changes:

```ts
    window.onDidChangeActiveTextEditor(updateDecorations),
    workspace.onDidChangeTextDocument((event) => {
      const editor = window.activeTextEditor;
      let timeout: NodeJS.Timeout | null = null;
      const triggerUpdateDecorations = (editor: TextEditor) => {
        if (timeout) {
          clearTimeout(timeout);
        }
        timeout = setTimeout(() => updateDecorations(editor), 200);
      };

      if (editor !== undefined && event.document === editor.document) {
        triggerUpdateDecorations(editor);
      }
    }),
```

**Comment by riccardoferretti** [comment]
Looks like you found the culprit, wanna make a PR for it? :)

**Comment by memeplex** [comment]
Sure, it may take me a couple of days though.

**Comment by memeplex** [comment]
I've reported the issue upstream because after setting the delay to 0 and also precomputing decoration ranges in order to avoid expensive parsing on editor switch the visual artifact persists to some extent. I believe this is unavoidable because of the way decorations work, which may be difficult to change. Of course going down to 0 from 500ms will be an improvement, but besides that I would like to know what they have to say about this.

**Comment by memeplex** [comment]
I've created the PR. Interestingly enough, the repaint effect in foam is almost unnoticeable, much subtler than for example in vscode-memo with the same delay (0). I would like to understand why, I don't think it's due to a more efficient parser because I had cached the decoration ranges so it was as fast as it gets in that regard.

**Comment by memeplex** [comment]
@riccardoferretti @pderaaij  my report upstream https://github.com/microsoft/vscode/issues/136241 was ackowledged and it's candidate to backlog but it needs some upvotes, so if you want decorations not to be recomputed each time editors are switched this is your chance :).

**Comment by riccardoferretti** [comment]
Thanks for the amazing research and work @memeplex!
I have upvoted it and encouraged others to do the same, 🤞 will make it through ;)
