### ISSUE TITLE
Add support for note renaming

### ISSUE THREAD

**Issue by AndreiD049** [foambubble/foam#809]
- Foam version: v0.15.2 
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes 

**Summary**

My file structure has some folders in it, just to avoid having big amount of files in the root folder. When i create a new note, i would just type it's name `[[example-new-note]]` and `Ctrl+click` it to be created. This creates the note in the root folder, then i move the file in the folder i want it to be. When i do this, i can still click the `[[example-new-note]]` and it will get me to the correct file. But i cannot see the backlinks, and on the graph, there are duplicated nodes, one linked, and another one orphan. See print screens in repro steps:

**Steps to reproduce**
1. I create the `[[items]]` note, and `ctrl+click` it to be created
![image](https://user-images.githubusercontent.com/52671223/139723342-a6838685-60e6-487a-8c87-d327f649f537.png)
2. Then i move this file to another folder, for example to `/docs`:
![image](https://user-images.githubusercontent.com/52671223/139723418-bd7e5ac9-cc7c-41c2-b597-e79226c95ecb.png)
3. I can navigate to `[[items]]` by clicking on the link from Inbox, but when i get there, there are no backlinks:
![image](https://user-images.githubusercontent.com/52671223/139723524-4a1af815-0e6e-4667-b8b6-78559c3f720f.png)

What i see on the graph (duplicated nodes, 1 linked with the graph, other one orphan):
![image](https://user-images.githubusercontent.com/52671223/139723610-abb9d5bf-869b-4588-8010-433baf14ee48.png)

**Additional information**
I reproduced this on a clean copy of [foam template](https://github.com/foambubble/foam-template)
In case additional info needed, please let me know

**Comment by dmurph** [comment]
I also have this issue. A restart usually solves it. There are also issues in the "orphans" section. It seems like the foam graph doesn't get updated on file moves, and I'm not sure if there is a command or something we can execute to do a rescan?

**Comment by riccardoferretti** [comment]
yes, this is the same as #810 - we need to add support for note moving/renaming

**Comment by riccardoferretti** [comment]
related #305

**Comment by riccardoferretti** [comment]
Note renaming supported in 0.18.0
