### ISSUE TITLE
Janitor adds duplicate link references

### ISSUE THREAD

**Issue by michael-guimet** [foambubble/foam#833]
- Foam version: **v0.15.6**
- VS Code version: **1.62.3**
- Platform: **Windows 11** 
- Issue occurs on the [foam template](https://github.com/foambubble/foam-template) repo: **Yes**

**Summary**
Janitor adds duplicate link references when run

**Steps to reproduce**
1. Download  [foam template](https://github.com/foambubble/foam-template) and extract
2. Look at docs/principles.md
3. Check foam link references at end of file. [recipes] is defined once (line 52)
4. Run Janitor
5. Look at docs/principles.md
6. Check foam link references at end of file. [recipes] is defined **twice** (line 52 and line 55)
7. Bug: link reference for [recipes] should only be defined once

**Additional information**
I use a heavily configures vscode with many extensions installed. These may impact behavious. Happy to provide more information if needed.

**Comment by stefanfritsch** [comment]
That issue affects me as well

**Comment by riccardoferretti** [comment]
This might have been fixed by #1228 - keep an eye on the next release

**Comment by riccardoferretti** [comment]
This should be now fixed
