### ISSUE TITLE
editor.action.openLink keyboard shortcut does not work on foam links

### ISSUE THREAD

**Issue by felixaumer** [foambubble/foam#836]
- Foam version: 0.15.5
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No

**Summary**
Since upgrading to v0.15.5 the keyboard shortcut `editor.action.openLink` does not work anymore for opening foam links.
When I downgrade to v.0.15.4 everything works as expected again.
Personally I prefer navigating the files with the keyboard only and want to avoid CTRL + Mouse Click to resolve linked files.

I would expect for Foam Links to open with `editor.action.openLink`.

**Steps to reproduce**
1. Insert foam link to file.
2. Place cursor on link.
3. Press keyboard shortcut for `editor.action.openLink` -> file does not open

**Comment by riccardoferretti** [comment]
This issue is related to https://github.com/foambubble/foam/pull/724 and https://github.com/foambubble/foam/pull/821

With #821 placeholders are links whereas wikilinks are navigated via definitions, but I reckon there is no reason to not also make them links (I need to check)
