### ISSUE TITLE
Convert to PDF or other mobile friendly format

### ISSUE THREAD

**Issue by dakenblack** [foambubble/foam#839]
Hi,

I love this project and have been using it a lot. I am now in a situation where I would like to access my foam notes (on a github repo for now) on my android tablet. I don't need to edit the notes on the tablet, but just view it. is there a way to export all the foam files into a PDF with links and maybe bookmarks/table of contents to represent directory structure?

Happy to hear any other ideas re: accessing the notes from a tablet too.

I've also noticed that there is a thread on a mobile app (https://github.com/foambubble/foam/issues/63), but looks like there is nothing there yet?

Thanks,
Jabez

**Comment by lazyoracle** [comment]
If you have access to internet on the tablet, does the github.dev web-based editor help access your Foam workspace in a tablet-friendly manner? I have not tried it myself but just something that struck me as a possible solution.

**Comment by dakenblack** [comment]
Oh I hadn't heard about this, will check it out when I get a chance and update this post.

**Comment by riccardoferretti** [comment]
If you also have your notes in something like Dropbox you can access them directly from there (it's just a text file in the end)

**Comment by dakenblack** [comment]
Hi Riccardo, Thanks for that but I was hoping to also use all the links (i.e. go from one file to another via links instead of browsing for that file) and formatting in the files.

**Comment by riccardoferretti** [comment]
Have you considered publishing the repo? Maybe take a look at `docs/publishing` as a starting point

**Comment by ttpro1995** [comment]
> Have you considered publishing the repo? Maybe take a look at `docs/publishing` as a starting point


Not `docs/publishing`, but `docs/user/publishing`

Full url:
https://github.com/foambubble/foam/tree/master/docs/user/publishing
