### ISSUE TITLE
如果使用中文创建没有文件名

### ISSUE THREAD

**Issue by gaoyunyun** [foambubble/foam#84]
我再使用 [[]] 创建中输入中文的时候,生成的 .md 文件没有文件名~

**Comment by jevakallio** [comment]
Hi @gaoyunyun,

I don't speak Chinese, so I'll have to respond to you in English. This is same issue for other non-western character sets (https://github.com/foambubble/foam/issues/73).

I think it should be fixed now in Markdown Notes v0.0.11?
https://github.com/kortina/vscode-markdown-notes/releases/tag/v0.0.11

Please update markdown-notes and let me know if it's not fixed, and I'll reopen!

Thanks!

**Comment by gaoyunyun** [comment]
我再多试了几下又行了...应该是我之前错误的操作导致的.很喜欢你的插件,3q!
