### ISSUE TITLE
Link notes from various points within the Directory Structure including Folder Hierarchy

### ISSUE THREAD

**Issue by JamesLarkinWhite** [foambubble/foam#847]
# Understand the OS Directory Structure 
Dear all, i recently came accross this tool and would like to use it. IT seems to me like i have not fully understood the concept tho.
I tend to have multiple different places (nested strcture) were i store my notes. They are on various different places within my dir strcuture. Everything is stored as markdown.
This is a mpockup of a possible strucutre

```
Home
│
└───PATH/TO/WORK-Folder                                                   <- All work related stuff is inside here
│   │
│   └───Notes
│   │   └───DailyNotes                                                              <- Daily Todolists etc ...
│   │   └───OtherNotes                                                            <- Specific Stuff that does not bekong to a Project 
│   └───+relPATH/TO/ProjectXY                                            
│   │   │  │
│   │   │  └───Code                                      
│   │   │   │
│   │   │   └─── ...                                  
│   │   │   │
│   │   │   └───notes                                                                <- This folder contains all my notes i take that belong to this project including metadata /pictiures....
│
└───PATH/TO/EDU                                                                     <- All my "Education"/ general knowlege gathering goes in here... there are subfolders with books i link to in the notes for example...
│   │
│   └───Notes
│   │   └───KnowledgeCards                                                       <- Main folder for stuff i want to learn about
│   │    │        └───Topic1                                                            <- For example all about DevOps is in one folder
│   │    └───Papers                                                                       <- Notes on all peer reviewd Publication i have read
```

- So i have special places where i store my daily todos.md 
- I have a very nested structure
The reasion i do this, is that notes are where they belong. For example if a specific Project is done, i can archive it and all notes related to this Project are also inside. Is there a way to do this in Foamr? Would i have to use multiple workspaces? Wouldn´t this defy the idea of Foam?

Thank you in advance....

I am also open to suggestions what would be a good tool for me.

**Comment by riccardoferretti** [comment]
This should just work in Foam, check this doc for more info:

https://github.com/foambubble/foam/blob/master/docs/proposals/wikilinks-in-foam.md

**Comment by JamesLarkinWhite** [comment]
So i can simply add another folder to the "foam workspace"? Do the wiki style links also work?

**Comment by riccardoferretti** [comment]
yes
