### ISSUE TITLE
pasteImage.path in settings.json is ignored

### ISSUE THREAD

**Issue by JamesLarkinWhite** [foambubble/foam#849]
Dear all i have just started using Foam. I have added multiple folders to the Foam workspace which containt my notes.
Each of these folders has its own attachments folder where i want my images to be saved, instad of the root/attchement folder
Hower this setting:

"pasteImage.path": "${currentFileDir}/attachments",

seems to be ignored. Do i have to do anything besides saving the json file and restarting vscode?

Thank you in advance

**Comment by riccardoferretti** [comment]
This is probably a better question for the Paste Image extension repo: https://github.com/mushanshitiancai/vscode-paste-image
