### ISSUE TITLE
Wikilinks to different files with same suffix are considered ambiguous

### ISSUE THREAD

**Issue by zharkovstas** [foambubble/foam#851]
- Foam version: v0.16.0
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
When I have two files with different names, say `todo.md` and `another-todo.md` (the name of one file ends with the name of another), then Foam mixes them up and considers links to the file with shorter name ambiguous.

**Steps to reproduce**
1. Go to foam-template
2. Create a file `another-todo.md`
3. Go to `inbox.md`

Link to `[[todo]]` is considered ambiguous. It leads to the `another-todo.md` file now instead of `todo.md`.

![screenshot](https://user-images.githubusercontent.com/1273305/144081985-61a88dae-ea37-4c68-b420-9bdebb2f8c05.png)

**Additional information**

Is probably linked to #841

**Comment by riccardoferretti** [comment]
Fixed in 0.16.1

**Comment by riccardoferretti** [comment]
Thanks for reporting it @zharkovstas  ;)
