### ISSUE TITLE
Wikilink-style syntax highlighting on all files

### ISSUE THREAD

**Issue by paw-lu** [foambubble/foam#857]
- Foam version: v0.16.1
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No

**Summary**

New to foam. But when the extension is installed it seems almost all uses of double brackets get unique syntax highlighting. For example a screen shot of a python file is shown. It would be preferred if this only occured for markdown files, or could be configured per project.

**Steps to reproduce**
1. Install foam extension.
2. Use double bracket on any file.

**Additional information**

<img width="566" alt="Screen Shot 2021-12-03 at 1 24 29 PM" src="https://user-images.githubusercontent.com/30049606/144674721-3691218e-a598-40b1-980f-6db8ec2a8dc3.png">

**Comment by riccardoferretti** [comment]
thanks for reporting this, it will be fixed in 0.16.2

**Comment by paw-lu** [comment]
thank _you_ for sharing the project!
