### ISSUE TITLE
Tabstop Placeholders not working in `daily-note.md`

### ISSUE THREAD

**Issue by tobiasriemenschneider** [foambubble/foam#859]
- Foam version: **v0.16.1**
- Platform: **Mac**
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: **Yes**

**Summary**
If I go via **Foam: Open daily note**, then `daily-note.md` is used as a template.
```md
<!-- .foam/templates/daily-note.md -->

# ${CURRENT_DAY_NAME}, ${CURRENT_DATE}. ${CURRENT_MONTH_NAME} ${CURRENT_YEAR}

## What is your mood today?
${1:great}

## To-Dos
${2:save the world}
```
However the cursor is at the very bottom, not at the first tabstop `${1:great}`, as expected.

**Steps to reproduce**
1. put `daily-note.md` into template folder
2. put Tabstop Placeholders into `daily-note.md`
3. do **Foam: Open daily note**

**Additional information**
If I'm going via **Foam: Create Note from Template** and then select `daily-note.md` the Tabstop Placeholders are working. However in this case the `foam.openDailyNote.directory` in my `settings.json` is not respected.

**Comment by riccardoferretti** [comment]
This will be released in 0.16.2
