### ISSUE TITLE
Feature Request: optional YAML front matter

### ISSUE THREAD

**Issue by TianyiShi2001** [foambubble/foam#86]
Further to issue #34 which requests for tagging, I would like an optional feature that allows parsing YAML frontmatter (which can include tags, date of creation and last modification, etc). 

YAML header is a common practice to store per-file metadata for markdown files in many markdown-oriented high-level applications, such as [Pandoc](pandoc.org), [RMarkdown](http://rmarkdown.rstudio.com), and [Hugo](https://gohugo.io). Personally, I also use custom metadata fields to facilitate my workflow.

Some potential benefits of, and possible applications based on YAML front matter, in the context of Foam::

- Easier to re-organize in a traditional, structured manner based on tags/categories/date
- Easier migration to other note-taking tools, many of which use tags and some of which use dates
- Filter nodes in the graph by conditions
- Color nodes in the graph by parameters (date of last view, or other custom parameters such as 'difficulty', for example)

**Comment by mathieudutour** [comment]
I believe #34 is about tags in the content, like `#thistag`. But is there anything stopping you from adding a frontmatter section above your content? The markdown preview seems to work fine and I believe Jekyll understands it as well.

What would Foam do with your frontmatter (which is super specific to your data, even tho it's structured)?

**Comment by SanketDG** [comment]
For me, it has been largely been the idea of being able to keeping a main index of tags, something like https://notes.zander.wtf/

Obviously this can be done with how `#tags` is supported with gatsby, where we basically search and fetch the tags and then create a index page containing all the tags. I am not sure whether it's possible with `jekyll` or `11ty`.

I think the question here is how we want to support #tags in foam. I would also like to know how others go about maintaining tags or categories in their Foam workspace.

**Comment by mathieudutour** [comment]
Let’s keep the conversation about tags in #34 ?

**Comment by nixsee** [comment]
I would also like to see YAML front matter supported, which, it seems to me, goes well beyond the tags that are discussed in #34

**Comment by fi0** [comment]
Apart from tags, the date of creation and last modification mentioned in the original post can be very useful.

**Comment by riccardoferretti** [comment]
YAML support has been added in https://github.com/foambubble/foam/pull/191
