### ISSUE TITLE
Text file names with a point 3 or fewer char before the end break links

### ISSUE THREAD

**Issue by MalcolmMielle** [foambubble/foam#861]
- Foam version: v0.17.0
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
Links with a point at the end of the file name with three character, or fewer, breaks unless the extension is in the link.

**Steps to reproduce**
1. Create a file name "test.yo.md"
2. Create a file name "test.md"
3. In "test.md" add `[[test.yo]]`

The link won't work and if right-clicking the user is prompted to create the file. If the user presses "yes", they are told that the file already exists.

**Comment by riccardoferretti** [comment]
Thanks for reporting the issue @MalcolmMielle, this will be fixed by #858

**Comment by MalcolmMielle** [comment]
Super !!
Thanks for the answer

**Comment by memeplex** [comment]
A heads up: the way this is going to be fixed is that everything after a dot is going to be considered an extension, so @MalcolmMielle you will still have the issue you have now. I recommend you to explicitly add `.md` to the reference if your filename has dots on it. There is an inherent ambiguity here, foam can't tell if `.yo` is an extension or part of the filename, except that we make the reference resolution more heuristic and sophisticated (in a way that is not yet clear), which was informally decided against for now. @riccardoferretti what do you think? Would you like to revisit that?

**Comment by MalcolmMielle** [comment]
@memeplex thanks for the heads-up. There is definitely an ambiguity there, and I understand the limitation with having to put the `.md` extension in that case. Does the fix mean that it won't be limited to files with less than three characters after the `.` but it will be necessary to put `.md` for any file with a point in its name anywhere?

**Comment by memeplex** [comment]
For the time being the rule will be simple: "everything after a dot is an extension, it there's no extension .md will be tried". This forces to add the .md extension to dendron-like references, yes. Any other rule will have to take into account something outside the path itself, for example "can `test.yo` be resolved as `test.yo.md`?". But it's not clear yet what has to be done here, if anything. I will think about it.

**Comment by MalcolmMielle** [comment]
I don't mind having to had `.md` to dendron style file name in the [[wikilinks]]. A simple fix is to use `-` instead of `.` or to put the `.md` extension in the name. It would be great if it was documented somewhere after the modification, though, just for reference :). Especially if some users migrate from Dendron.

This is all a very personal note-taking strategy, so I don't think it should impact the implementation, especially if there is a simple workaround. Simply put, I find folder harder to use than (re)naming files. Some (but as few as possible) notes only make sense in a given context. E.g. I have a note about a person I work with, and a sub-project I do with them. The project as a very common name sadly (think "cv") and I don't want it confused with other things. So I call the file `person.CV.md`. Section could work, but I'm trying to have my note as atomic as possible :).

I am not good enough at typescript to understand #858 and it seems like solid work. However, I don't know if a lot of user migrate away from Dendron but it will make the migration harder. Might be an irrelevant problem though, if few people migrate away from it to Foam.

**Comment by memeplex** [comment]
Ok, but don't jump into rename everything yet, maybe I could still address this in #858.

**Comment by memeplex** [comment]
@riccardoferretti what do you think about doing this modification:

1. If `path` extension is not `.md`, try to resolve `path + '.md'`
2. If the previous resolution returned no match, try to resolve `path`

?

This has to be implemented both in `listByIdentifier` and `find`, but it's a small change.

The potential double lookup should add little overhead because most lookups are of Foam links which either have `.md` extension or have no extension, so they require just one lookup.

Examples:

* `test.md`: has `.md` extension, go to step 2, lookup `test.md` -> found.
* `test.yo`: doesn't have `.md` extension, convert to `test.yo.md`, lookup -> found.
* `test`: doesn't have `.md` extension, convert to `test.md`, lookup -> found.
* `test.jpg`:  doesn't have `.md` extension, convert to `test.jpg.md`, lookup -> no result, go to step 2, lookup `test.jpg` -> found.

**Comment by memeplex** [comment]
An additional benefit it that it will be able to resolve legit links with no extension to resources other than Foam notes.

**Comment by memeplex** [comment]
https://github.com/foambubble/foam/pull/870 implements the algorith described above.

**Comment by memeplex** [comment]
> Didn't change anything yet. Keep me updated :)

@MalcolmMielle #870 was merged (yet not still released).

**Comment by MalcolmMielle** [comment]
Excellent! And i see the dendron link still work. Thanks for the fantastic work :)!
