### ISSUE TITLE
Automatic link creation

### ISSUE THREAD

**Issue by MalcolmMielle** [foambubble/foam#862]
Hear me out, I'm not sure that it's a great idea, but I thought I'd pitch it!

I think it would be interesting to have a feature to create automatic link/tags in files. That could be done by scanning the content of a subset of notes and counting the number of time each word appears. After removing the most common words (like "the", "a", and so on), one would be left with a set of commonly used words that could correspond to interesting links between notes. 

By selecting such key word that are of interest, users could find new connections between notes and concepts that they would not have "manually" found otherwise.

**Comment by riccardoferretti** [comment]
Thanks for the idea @MalcolmMielle - this is a bit of an advanced feature that is slightly outside of Foam's core responsibility, but that we hope other devs might be able to build on top of once we release the API.

**Comment by memeplex** [comment]
TFIDF is probably a better metric. Or some NMF, LDA algorithm for topic analysis. You might be better by writing a simple python parser for your workspace, text mining it and presenting the output in a way that can be consumed by a vscode problem matcher. Then you can create a vscode task for you analyzer and run it from time to time in order to get insights.

**Comment by MalcolmMielle** [comment]
Tfidf would be great, i don't know the two others :). Will look it up if i ever have time!

Yeah I think everyone agrees that it makes more sense outside of foam in the end :).

**Comment by memeplex** [comment]
That's one of the great things of having everything in the filesystem as markdown, parsers are a dime a dozen and for trivial things you may be ok with just a couple of regexs. It's like the json of knowledge management.
