### ISSUE TITLE
Wikilinks to Sections not working in VS Code Preview

### ISSUE THREAD

**Issue by tobiasriemenschneider** [foambubble/foam#863]
- Foam version:  **0.17.0**
- Platform: **Mac**
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: **Yes**

**Summary**
Wikilinks like `[[otherPage]]` are working well in Preview Mode of VS Code.

However Wikilinks to Sections or (Sub-)Headlines like `[[otherPage#subheadline42]]` are not working. Clicking on such a link within the Markdown Preview I'm navigated to the top of the other page, not to the subheadline the link is pointing to.

**Steps to reproduce**
1. Create one looong Note with a subheadline.
2. Create another Note with a Wikilink pointing to the subheadline of the first page.
3. Click on this Wikilink within the Markdown Preview.

**Additional information**
- I created a Screencast: https://www.youtube.com/watch?v=U49jtI9bBuo

**Comment by clux** [comment]
I had this issue myself and found it was resolved by uninstalling the old [markdown-notes](https://marketplace.visualstudio.com/items?itemName=kortina.vscode-markdown-notes) extension that was still enabled from older times (even though it was removed from my repo-level `extensions.json`). This extension also seemed to cause other issues related to subsection links (where `[[file#section]]` links would also create `filesection.md` in the current dir).

**Comment by riccardoferretti** [comment]
Fixed in 0.20.6
