### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by HomereAMK** [foambubble/foam#874]
- Issue Type: `Performance`
- Extension Name: `foam-vscode`
- Extension Version: `0.17.0`
- OS Version: `Darwin arm64 21.1.0`
- VS Code version: `1.63.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/hn/gtjgrbhx5b180373dbc4jx4r0000gn/T/foam.foam-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by riccardoferretti** [comment]
can you please attach the profile file? 
(`/var/folders/hn/gtjgrbhx5b180373dbc4jx4r0000gn/T/foam.foam-vscode-unresponsive.cpuprofile.txt`)

**Comment by HomereAMK** [comment]
[foam.log](https://github.com/foambubble/foam/files/7713970/foam.log)

**Comment by jonasdiemer** [comment]
I am having the same issue - VSCode is hardly usable atm with foam running (typing is significantly delayed). Any chance to see a fix?

**Comment by riccardoferretti** [comment]
@jonasdiemer can you describe the issue? does it happen on any repo? do you have the graph view open? do you have very long markdown files? do you have a log we can look at?

**Comment by jonasdiemer** [comment]
@riccardoferretti - thanks for getting back. Issue disappeared after restart of vscode, so I can't report much atm. Will come back if it reappears.
