### ISSUE TITLE
Allow tags to be listed using YAML arrays

### ISSUE THREAD

**Issue by brendanzab** [foambubble/foam#877]
Currently multiple tags can be listed, separated by spaces:

```md
---
tags: tag1 tag2
---
```

However in other note taking tools, tags can be listed using YAML arrays, for example:

```md
---
tags:
  - tag1
  - tag2
---
```

At the moment Foam does not seem to recognise the latter, as far as I can tell (the listed tags do not show up in the tags sidebar).

**Comment by riccardoferretti** [comment]
mmmmm... works for me, will close for now, feel free to further comment if there is something I am missing.

![image](https://user-images.githubusercontent.com/457005/146201990-8a24cc14-34b9-412e-bdb7-f5aba8b2ec55.png)

**Comment by brendanzab** [comment]
Oh! I was doing:
```md
---
- tags:
  - tag1
  - tag2
---
```
My bad, it works without the additional dash 🤦‍♂️

**Comment by brendanzab** [comment]
Hmm, though it doesn't seems to load the tags unless I open each markdown file individually, and save the file. Is it meant to search my workspace, or does it only detect tags in files I'm currently working on?

**Comment by brendanzab** [comment]
Hmm, for some reason it is working now! Not sure what was broken.
