### ISSUE TITLE
Autocomplete stops working when there's a # symbol in the same line

### ISSUE THREAD

**Issue by luisherranz** [foambubble/foam#884]
- Foam version: v0.17.1
- Platform: Mac (macOS Big Sur)
- Issue occurs on the [foam template](https://github.com/foambubble/foam-template) repo: Yes!

**Summary**

When there's a #tag in the same line, the autocomplete stops working. I think this started happening just a few weeks ago.

**Steps to reproduce**

1. Add a #tag to the line
2. Keep writing and try to autocomplete a [[wikilink]]

I was able to reproduce it using the [foam template](https://github.com/foambubble/foam-template).

**Additional information**

The only VSCode extensions I run are Vim, Prettier, and GitGraph.

![Screen Capture on 2021-12-22 at 10-48-59](https://user-images.githubusercontent.com/3305402/147073327-1270304a-6bbf-476d-b90a-c98753332c5b.gif)

**Comment by xs30snw** [comment]
Reproduced this bug as well:

- Windows 10;
- VSCodium;
- Foam v0.17.1, recommended extensions and the recent default foam template.

Basically, autocompletion for links works between the beginning of a line and the first tag in this line:

```
- Some text [[works]] #tag1 [[doesn't work]] #tag2 [[doesn't work]]
```

**Comment by riccardoferretti** [comment]
Thanks for reporting this. 
I did some quick testing and I think the issue is related to the `#` char in general, and my guess is that it is messing with the regex (which includes that character to see whether the wikilink has a section in it)

**Comment by luisherranz** [comment]
> the issue is related to the # char in general

Confirmed. It also happens with a markdown link that contains a hash: `[Link](https://site.com/#hash)`

**Comment by memeplex** [comment]
I've created a couple of alternative PRs that fix this.

**Comment by luisherranz** [comment]
Any chance to get a new release containing this fix soon? 🙂

**Comment by riccardoferretti** [comment]
> Any chance to get a new release containing this fix soon? 🙂

oops, totally thought I had released the fixes. Done now.

**Comment by luisherranz** [comment]
Awesome. Thank you Riccardo 👏🙂
