### ISSUE TITLE
Allow using emoji in tags

### ISSUE THREAD

**Issue by ricekot** [foambubble/foam#903]
Examples:
- Purely Emoji:
  - `#📥/🟩`, `#📥/🟧`, `#📥/🟥`
  - `#⭐`, `#⭐⭐`, `#⭐⭐⭐`
  - `#🐞`
- Text and Emoji:
  - `#example1️⃣`
  - `#example/1️⃣`

**Comment by riccardoferretti** [comment]
Happy to receive a contribution to support this

**Comment by badsketch** [comment]
The above PR admitted that it didn't cover all the cases for this issue, but I'm curious why it ended up being closed? I'd like to take a stab at this 🙂
