### ISSUE TITLE
Allow user to create a node containing slashes?

### ISSUE THREAD

**Issue by searene** [foambubble/foam#904]
I'm trying to create a node with the name "Liability/Asset Ratio", but it seems that I cannot create it. Foam always tried to create a node called "Asset Ratio" under the directory "Liability". But they are not the same thing. Is there any way to allow users to create that node?

**Comment by riccardoferretti** [comment]
Hi @searene that is not possible in Foam. You can follow the Dendron naming convention of using dots (Liability.Asset Ratio), or personally I use "-" (Liability - Asset Ratio)

**Comment by searene** [comment]
Hi @riccardoferretti,

Thanks for the suggestions. I got it.
