### ISSUE TITLE
Wikilinking becomes very slow in larger gardens

### ISSUE THREAD

**Issue by flancian** [foambubble/foam#906]
- Foam version: 0.17.2
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No

**Summary**
Wikilinking anything in my digital garden takes ~5-10s, apparently due to autocomplete delays. 

What's worse, if I keep typing while vscode is hanging (in the case in which I know in advance which node I want / I do not really need autocomplete), my input gets garbled when it eventually shows up on screen -- square brackets are often added in the wrong positions in the string I just wrote.

I can reproduce in both an i7-8565U and a Ryzen 5900, not state of the art but not exactly old machines either.

**Steps to reproduce**
1. Grow a garden with  more than 4k nodes, like e.g. anagora.org/go/flancian/garden
2. Try to wikilink anything :)

**Additional information**
- the Foam log in VsCode (see [instructions](https://github.com/foambubble/foam/blob/master/docs/features/foam-logging-in-vscode.md))
  - just learnt about this and changed the level to debug, will attach in an update.

Thank you!

**Comment by DrakeWhu** [comment]
Hey, I've been having some performance issues with my graph specially, not with linking yet. My garden is over 1k notes so I'd like to know if we can solve this so we won't have any problem with large gardens. I don't have much time now but I'd like to help with this, I think the support of big gardens should be a priority.

**Comment by HaloWang** [comment]
Also find the latency of typing in vscode is increased after I show my project's graph. Actually I want a [d3.js-like](https://vasturiano.github.io/react-force-graph/example/text-nodes/index-3d.html) graph which might be hard to be integrated into VSCode.

**Comment by riccardoferretti** [comment]
Yeah I think we need to take a look at performance optimization, @DrakeWhu if you are interested in taking a stab, I would be happy to support as best as I can

**Comment by riccardoferretti** [comment]
Closed for inactivity
