### ISSUE TITLE
Support shortcut for opening link in a new split panel

### ISSUE THREAD

**Issue by flancian** [foambubble/foam#907]
As discussed over Discord, it's be nice to have a shortcut to follow a link (opening or creating a note) in a new editor panel.

This is what [[riccardo]] said over Discord: "@Flancian  @=Ingalless= cmd+option+click should open in a new split panel, that's the normal behavior in VS Code on a e.g. javascript file.
In Foam that behavior is actually not there because of the way we route the navigation (via our custom command), but it would be pretty easy to restore this behavior by passing the Uri instead of the command in navigator-provider:165. We would need to properly handle the placeholder case though... might be worth opening an issue for that"

Having a keyboard-only shortcut in addition to a keyboard+mouse combo would be ideal, but the keyboard+mouse combo sounds great already :)

Thank you!

**Comment by riccardoferretti** [comment]
This should be fixed in 0.20.3
