### ISSUE TITLE
Add all-contributors

### ISSUE THREAD

**Issue by jevakallio** [foambubble/foam#91]
Here's an opportunity for the most meta contribution I can think of:

Get yourself to the contributor list by integrating [all-contributors](https://github.com/all-contributors/all-contributors) that adds the contributor list to the project documentation.

Ideally, adds contributors to both `readme.md` and `docs/readme.md`, but if we only get to pick one, it should be in `docs/readme.md`, so we'll get these on the project home page.

**Comment by msaglietto** [comment]
Maybe you can use something like https://allcontributors.org/ ?

**Comment by jevakallio** [comment]
@msaglietto ah, that makes sense! I didn't realise it was that easy to integrate these days, I thought it still involved doing code changes in the project. Lemme give that a shot!

**Comment by jevakallio** [comment]
Added all-contributors list to project home page and readme, and configured `@all-contributors` bot

https://foambubble.github.io/foam/#thanks-and-attribution
