### ISSUE TITLE
Janitor should use provided name to replace wikilinks in LinkReferences

### ISSUE THREAD

**Issue by DhruvaSambrani** [foambubble/foam#916]
Right now, `[[filename#sectionname|linkname]]` is meant to be rendered as `[filename]` in a website and ignores `linkname`. This should not happen.

**Comment by riccardoferretti** [comment]
> is meant to be rendered as [filename] in a website 

What do you mean by "in a website"?

**Comment by DhruvaSambrani** [comment]
Oh my bad. I am using foam to then deploy to GHPages. However, I now understand that this has nothing to do with GHPages.

For referenced links, the text it is meant to display on render should be as above.

**Comment by riccardoferretti** [comment]
This is managed by the website template, not Foam, so I will close the issue
