### ISSUE TITLE
Feature request: Support for `asciidoc`

### ISSUE THREAD

**Issue by hacker-DOM** [foambubble/foam#917]
Hi there! Any plans to support [asciidoc](https://docs.asciidoctor.org/asciidoc/latest/). I for one find that the table syntax is better; great for creating large tables. Lots of other advantages over md imho. (Alternatively, recommending a tool that supports `asciidoc` would also solve my [xy problem](https://en.wikipedia.org/wiki/XY_problem) :).)Thanks a lot!

**Comment by riccardoferretti** [comment]
Hi @hacker-DOM, there is no plan to implement that in Foam core, as its goal is to be purely focused on the "bare" set of features to help with md note taking, but this could be implemented as an extension on top of Foam once the API is released

**Comment by jmanthony3** [comment]
Would it not be possible to incorporate [asciidoctor.js](https://github.com/asciidoctor/asciidoctor.js) natively as an alternate parser for the Foam database? This could be an option in the Foam configuration for which language to prioritize when linking and graphing notes (some notes might be written or shared in either language). The [AsciiDoc Extension for VS Code](https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode) does not allow for backlinks like Markdown does. I cannot yet find a VS Code extension that implements backlinking in AsciiDoc notes. Certainly, AsciiDoc can make links between external documents and sections within that document, but no extension exists (as best I can find) to browse or graph those references like is supported for Markdown.

**Comment by aisbergde** [comment]
AsciiDoc support would be great. A few years ago I migrated my Notes system from Markdown to AsciiDoc. Unfortunately there is nothing like this application for AsciiDoc.

> but this could be implemented as an extension on top of Foam once the API is released

When can this be expected? So is there a chance? Could this issue then perhaps be reopened, even if it cannot currently be realized?

**Comment by riccardoferretti** [comment]
When we release the API others would be able to build on top of them to achieve AsciiDoc support, this however would not be in scope for Foam core itself, that's why I closed the task.
In terms of release of the API, it's unfortunately terribly behind, but it's my intention to get to it by the end of the year, possibly sooner

**Comment by pariah-kite** [comment]
> When we release the API others would be able to build on top of them to achieve AsciiDoc support, this however would not be in scope for Foam core itself, that's why I closed the task. In terms of release of the API, it's unfortunately terribly behind, but it's my intention to get to it by the end of the year, possibly sooner

Is there a GitHub issue for the API, that one can follow?

**Comment by riccardoferretti** [comment]
Good point, I created one: https://github.com/foambubble/foam/issues/1291

**Comment by Aitanuqui** [comment]
I see that issue now closed and no more news here. Is there still no `asciidoc` support?

**Comment by riccardoferretti** [comment]
Foam doesn't support `asciidoc`, I consider it to be out of scope for the extension, not sure if there are extensions in the marketplace for that
