### ISSUE TITLE
`${FOAM_DATE_*}` variable expansion is dependent on system locale.

### ISSUE THREAD

**Issue by korrat** [foambubble/foam#919]
- Foam version: 0.17.3
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**

`${FOAM_DATE_*}` variable expansion is dependent on system locale, which is inconsistent with the behaviour of VS Code snippet variables.

**Steps to reproduce** (on a system with German locale)
1. Create a note template with `filepath: ${FOAM_DATE_HOUR}.md`
2. Create a note from the template.

The filename is "11 Uhr.md", while I expected it to be `11.md`. For comparison, I created a user snippet with the `${CURRENT_HOUR}` snippet variable, which only expands to `11`.

**Comment by riccardoferretti** [comment]
Good catch, this should be pretty simple to address (although let's wait for #882 is merged to avoid conflicts)

**Comment by riccardoferretti** [comment]
Fix is on master, will be released with 0.17.8
