### ISSUE TITLE
Support for math formulas on rendered pages

### ISSUE THREAD

**Issue by TaiChi-IO** [foambubble/foam#92]
I have some math formulas in my notes that can be rendered properly with All-in-One markdown in VS Code but they are not rendered on the published pages. Could you please support for rendering math formulas on published pages?

**Comment by digiguru** [comment]
As @TaiChi-IO observed there is a workaround for this, as found in the Math recipe.

#109 

Perhaps adding this out of the box is overkill, but I wanted to ensure that future people who encounter this issue please read the notes on [Math Support](https://foambubble.github.io/foam/math-support)
