### ISSUE TITLE
Discord invite link is invalid

### ISSUE THREAD

**Issue by develmusa** [foambubble/foam#927]
**Summary**
The discord invite link is invalid

**Steps to reproduce**
1. Click on ["Discord Chat" badge](https://github.com/foambubble/foam/blame/master/readme.md#L11)

<img width="488" alt="invalid_invite" src="https://user-images.githubusercontent.com/9266221/153706615-a7ecffea-d26e-4e81-9afc-b9bb53091190.PNG">

**Comment by develmusa** [comment]
It's on top of the README.md.
https://github.com/foambubble/foam/blame/master/readme.md#L11

**Comment by riccardoferretti** [comment]
This invite link is working for me

**Comment by riccardoferretti** [comment]
Can someone else test this please?

**Comment by develmusa** [comment]
I tested the link on my phone and it works. Seems to be a problem with my browser. Sorry for the trouble.
