### ISSUE TITLE
/previous shortcut for Daily Notes

### ISSUE THREAD

**Issue by ayberk** [foambubble/foam#930]
My usual workflow is like this:

1. Open the daily note in the morning
2. Use `/yesterday` to go to the previous note
3. Copy paste the `Tasks` section into today's note

One small thing that breaks this flow is Mondays. On Mondays `/yesterday` obviously goes to Sunday, which is not I want. It'd be nice to have something like `/previous` to get a link to the _last_ note based on the date.

**Comment by riccardoferretti** [comment]
This to me feels outside of the boundaries of Foam Core at this stage, but @MCluck90 has done some amazing work that overlaps with this request, you can see more info here: https://discord.com/channels/729975036148056075/771033587293618176/920373078922526802

**Comment by riccardoferretti** [comment]
This was just released: https://marketplace.visualstudio.com/items?itemName=MikeCluck.kaleidofoam
