### ISSUE TITLE
Relative Daily Note templates

### ISSUE THREAD

**Issue by ayberk** [foambubble/foam#931]
My usual workflow is like this:

1. Open the daily note in the morning
2. Use /yesterday to go to the previous note
3. Copy paste the Tasks section into today's note

It'd be really nice if I could create a daily note template where I can refer to previous note[1]. Even a simple complete copy of previous note would be enough for my case, but ideally it'd be nicer if I can just grab certain content (based on headers maybe?)

[1]: Also see #930 which would play well with this request.

**Comment by riccardoferretti** [comment]
This to me feels outside of the boundaries of Foam Core at this stage, but @MCluck90 has done some amazing work that overlaps with this request, you can see more info here: https://discord.com/channels/729975036148056075/771033587293618176/920373078922526802

**Comment by riccardoferretti** [comment]
This was just released: https://marketplace.visualstudio.com/items?itemName=MikeCluck.kaleidofoam
