### ISSUE TITLE
FOAM_TITLE not working right in 0.17.4 and 0.17.5

### ISSUE THREAD

**Issue by poblabs** [foambubble/foam#940]
- Foam version: 0.17.5 (also present in 0.17.4)
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
I created a `.foam/template/new-note.md` template with the below data. When I press F1 in vscode, select "Foam: Create new note" and just give it a title of "test", the file name and first header say `$FOAM_TITLE`. However the frontmatter section is fine.

Downgrading to 0.17.3 fixes the issue with filename and first header.

---

Foam template: `D:\documents\notes\.foam\templates\new-note.md`

```
---
foam_template:
  filepath: 'D:\documents\notes\$FOAM_TITLE.md'
title: $FOAM_TITLE
date: $FOAM_DATE_YEAR-$FOAM_DATE_MONTH-$FOAM_DATE_DATE $FOAM_DATE_HOUR:$FOAM_DATE_MINUTE:$FOAM_DATE_SECOND
lastmod: 
source: 
tags: 
---

# ${1:$TM_FILENAME_BASE}

```

---

Results in `d:\documents\notes\$FOAM_TITLE.md` (literal file name with the $)

```
---
title: test
date: 2022-02-24 08:22:05
lastmod: 2022-02-24 08:22:07
source: 
tags: 
---

# $FOAM_TITLE

```

**Comment by riccardoferretti** [comment]
I can't reproduce this. I tried with a slightly different template because I think using the filename as title was confusing:

```
---
foam_template:
  filepath: '$FOAM_TITLE.md'
title: $FOAM_TITLE
date: $FOAM_DATE_YEAR-$FOAM_DATE_MONTH-$FOAM_DATE_DATE $FOAM_DATE_HOUR:$FOAM_DATE_MINUTE:$FOAM_DATE_SECOND
lastmod: 
source: 
tags: 
---

# ${1:$FOAM_TITLE}
```

And it worked fine.

I tried with also an absolute path:

```
  filepath: '/path/to/note/$FOAM_TITLE.md'
```

And it worked fine.

Will leave this open for now to see if other people are having the same issue

**Comment by poblabs** [comment]
I'm able to replicate this problem on 2 different computers. I'll try with your template to see if it helps.

**Comment by poblabs** [comment]
Using your template worked until I added the absolute path, then it broke.  Screenshot below of the explorer file it created. 

I'm on Windows. 

On my 2nd computer, VS Code is running in portable mode on Windows, and there I have the same behavior. Using absolute path breaks it. I also have a new problem on portable mode - it does not remove the `foam_template:` `file_path` from the front matter. 

```
---
foam_template:
  filepath: 'd:\documents\notes\$FOAM_TITLE.md'
title: $FOAM_TITLE
date: $FOAM_DATE_YEAR-$FOAM_DATE_MONTH-$FOAM_DATE_DATE $FOAM_DATE_HOUR:$FOAM_DATE_MINUTE:$FOAM_DATE_SECOND
lastmod: 
source: 
tags: 
---

# ${1:$FOAM_TITLE}

```

![image](https://user-images.githubusercontent.com/3484775/155755412-ca89b684-43c8-4dd7-ab0f-a84fb22d9567.png)

**Comment by riccardoferretti** [comment]
I wonder if somehow on Windows the `\` is escaping the `$`

**Comment by poblabs** [comment]
Good catch, this works just fine. Not sure why I didn't need it 2 versions ago, but glad this works. 

```
foam_template:
  filepath: 'd:\documents\notes\\$FOAM_TITLE.md'
```

The weird issue on portable version not removing the foam_template on new note.
