### ISSUE TITLE
date snippets not working

### ISSUE THREAD

**Issue by danyx23** [foambubble/foam#942]
- Foam version: 0.17.5
- Platform: Windows 
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes (but not the first time after cloning!)

**Summary**
When I type `/tomorrow` and press enter I don't get the autolink generation to create a new journal note for tomorrow anymore.

**Steps to reproduce**
1. Type `/tomorrow`
2. Press enter
3. Nothing happens

**Additional information**
When trying to report this I cloned the template repo and tried it there and then **it worked** and I could create new notes and got suggestions for +1d etc. But then after restarting code it was gone again and stays broken now in the foam-template repo. The bizarre thing is that this is repeatable. The first run on an new clone works, afterwards no luck. Do you have *any* idea what this could be? Thanks a lot in advance and for all your work on this cool project!

**Comment by riccardoferretti** [comment]
Thanks for reporting the issue @danyx23 - unfortunately I have not been able to reproduce it and I have no idea why something like that would happen. It feels to me it's a VS Code (configuration?) issue more than Foam.

One thing I would check is whether it also happens when reverting to older versions of Foam? And back to the latest?

I will keep this open anyways for now, in case other users encounter the same issue.

**Comment by carlisia** [comment]
It is not working for me either. The `/today` snipped also doesn't work. But /+1 works (doesn't create the note, but creates the link.

I think it all worked then stopped working. Might be an incompatibility with another extension or configuration. I'm suspecting installing a Gatsby theme on top of Foam might be the culprit. Still trying to find the source.

---
I'm on:
Mac
Foam version v0.18.3.

**Comment by carlisia** [comment]
My embed `![[]]` also stopped working. I'm suspecting it's due to the same issue.

**Comment by carlisia** [comment]
Hey @danyx23, and anyone else who ran into this: for me it was a problem with extension conflict. Specifically, I installed `kortina.vscode-markdown-notes`, which I'm sure works great by itself but it was likely conflicting with the `yzhang.markdown-all-in-one` extension required by foam. What removing this extension did for me:

- embed now works
- typing `/today` or `/tomorrow` now works
- my markdown files are not hanging anymore

Hope this helps someone 🤓
