### ISSUE TITLE
Add navigation location for file create 

### ISSUE THREAD

**Issue by fanlushuai** [foambubble/foam#946]
![image](https://user-images.githubusercontent.com/21078607/155947702-081284d3-0343-4006-ba31-09b15d41e7f0.png)

**Comment by fanlushuai** [comment]
@riccardoferretti  

![动画](https://user-images.githubusercontent.com/21078607/156030362-fa0f030e-fba6-4828-9789-141897558fd5.gif)

When creating a new file, add a create navigation guide instead of creating it in the root path

I'm sorry about my description，I hope I can make it clear about my feature suggestion

**Comment by riccardoferretti** [comment]
This was discussed in #683 by @movermeyer back some time ago, which eventually stalled
There were a few use cases that made it non-trivial, but I believe we are not too far from getting to a resolution there

**Comment by riccardoferretti** [comment]
This is now fixed as of 0.20.6
