### ISSUE TITLE
Add unique ID to file front matter

### ISSUE THREAD

**Issue by fanlushuai** [foambubble/foam#952]
### Is your feature request related to a problem? Please describe.

Renaming the file causes the connection to be lost, so you don't want the association to be through the file name. The same is true of anchors

### Describe the solution you'd like

 Add unique ID to file front matter for file connection

Anchor point still can't think of how to solve

### Describe alternatives you've considered

Plugins support refactoring, synchronizing changes to file names and associations

**Comment by riccardoferretti** [comment]
Thanks for the proposal @fanlushuai, the approach we are taking these days is support for refactoring. We had a WIP PR some time ago that unfortunately didn't get enough traction, and I have some code that I will turn into a PR as soon as I get some deep time on Foam (EoM likely).
Most importantly, and to your open problem about anchor points, the file name/path is the identifier for wikilinks, so we can't just switch to another one (although I totally see the possible benefits of your proposal). In a way we have chosen a certain evil and now we need to work around it, aware that it also gives us lots of benefits.

For those reasons I am going to close the issue right away, but if you have any comment feel free to post here.
