### ISSUE TITLE
ctrl-click standard link wants to create a file 

### ISSUE THREAD

**Issue by gmccullo** [foambubble/foam#955]
Given a valid link like this:

```md
[foobar](foobar.md)
```

When I ctrl-click "foobar.md" in the editor, I expect to navigate to foobar.md. Actual: Foam wants to create a new note.

**Comment by riccardoferretti** [comment]
Can you add a repo to reproduce the issue? I seem to only be able to reproduce it for paths that have a space in them, e.g. `foo bar.md`.

**Comment by gmccullo** [comment]
The next time it happens I will. But what you found already might be all there is to it, yes?

**Comment by riccardoferretti** [comment]
Yup, that needs to be fixed, I was just curious to know if the problem was wider

**Comment by riccardoferretti** [comment]
This should have now been fixed, I will close it - but can you check if that's the case in your set up?
