### ISSUE TITLE
Jump after the closing brackets (`]]`) on autocomplete

### ISSUE THREAD

**Issue by luisherranz** [foambubble/foam#962]
### Is your feature request related to a problem? Please describe.

I'd love Foam to jump ahead the closing brackets `]]` when I use autocomplete.

### Describe the solution you'd like

When using autocomplete (by either clicking or using `Tab/Enter` on a result), Foam moves the cursor to the last word, like this:

- `I am linking to [[some page|]]`

You then have to type `]]` to continue writing.

It'd be great if Foam could jump ahead after the `]]` instead, like this:

- `I am linking to [[some page]]|`

Then you could open double brackets `[[`, partially complete the name of the page (`some p`), use `Tab` to finish the autocomplete, and keep writing the next words.

### Describe alternatives you've considered

Write the `]]` yourself, although I can't imagine a case where you wouldn't want to jump ahead. Similar software, like LogSeq, already works this way.

**Comment by riccardoferretti** [comment]
That's an interesting optimization, I can see it speeding things up when writing notes.
I don't know whether it might interfere with some use cases (e.g. using sections), so this requires a bit of deep dive.
Happy to keep it in the backlog, and if someone wants to work on it I am happy to support, at least until v1 is out, at which point I could take a look myself.

**Comment by Lauviah0622** [comment]
I'm trying to implement this feature but found problem. Like @riccardoferretti  said, it will interfere the section use case. 

Here is the demo, cursor jump after the closing bracket that cannot trigger the section auto completion. 
![movecursor](https://user-images.githubusercontent.com/43416399/169541125-b06630f0-5fa6-484f-a1a3-8499035ed417.gif)

but the cursor move in section auto completion is work fine. 

![movecursor-sec](https://user-images.githubusercontent.com/43416399/169541535-d1622b79-6c8d-4cc9-be5d-c4870ac107f6.gif)

**Comment by luisherranz** [comment]
Maybe leave it optional for people not using sections? (I'm not)

**Comment by riccardoferretti** [comment]
@Lauviah0622 Not sure which char you were using to confirm `test` in your first gif? what happens if you confirm the wikilink with the `#`? that must trigger the section autocomplete.
If instead you press enter and you get out of the wikilink, well, I think that could be fine.

**Comment by Lauviah0622** [comment]
I'm sorry forgot to record my keystroke in demo! Here is the new version. 
![movecursor-withKey](https://user-images.githubusercontent.com/43416399/169636233-ea7a6dd9-dfbd-4aa3-9135-0ea60f026905.gif)

And here is the [file change](https://github.com/Lauviah0622/foam/pull/1/files) on my current branch. 

Because it just added the command after selection of auto complete simply, So It will move cursor with any confirm method - both  press `Enter` and type `#` char. 

I'll trying to use custom command to parse the regex of current line instead of the built in `cursorMove` command to prevent move cursor after `#` .

**Comment by Lauviah0622** [comment]
Here is the demo of completion. Not move cursor completion with `#`. 
![movecursoe-complete](https://user-images.githubusercontent.com/43416399/169683178-0ff63081-2c2e-47e9-96b5-f1a1ac0ff7aa.gif)

And recording the suggest of the @luisherranz.  I also add the setting of the feature that can turn the moving enabled/disabled

**Comment by riccardoferretti** [comment]
@Lauviah0622 this looks pretty sweet. A few comments:
- do we really need a setting? I think the behavior is good and intuitive enough that I would just have it on
- I agree re the `|` commit character, good call

what do you think?

**Comment by Lauviah0622** [comment]
@riccardoferretti Thank for appreciation!!

> do we really need a setting? I think the behavior is good and intuitive enough that I would just have it on

In my opinion, it's the subtle change and like you said its the enhancement with no effort.  If there is any reason that need a setting to disabled, which is the feature maybe will confuse somebody's muscle memory. But I think it's just a matter of getting used to it.

> I agree re the | commit character, good call

I'm agree with that ! Its make the operation so smooth. Here is demo: 

![movecursoe-cmt-cha](https://user-images.githubusercontent.com/43416399/169818515-30c1e26f-9450-4dd3-b0c0-0b33fa9b891b.gif)

**Comment by riccardoferretti** [comment]
I absolutely love it!

**Comment by luisherranz** [comment]
Awesome! 

Will this work with `Tab` as well if that is what people use in VS Code, or is it hardcoded to `Enter`?
