### ISSUE TITLE
Opening wikilinks with editor.action.openLink

### ISSUE THREAD

**Issue by aritmos** [foambubble/foam#963]
### Describe the bug

When I used foam in the past I had a keybind set for "editor.action.openLink", therefore allowing me to quickly navigate my notes via wikilinks without using my mouse.

I havent used foam for a couple weeks, this appears to not be working anymore.
External (url) links are still handled as expected, it is only the wikilinks that fail.

### Steps to Reproduce the Bug or Issue

1. Set a keybind for "editor.action.openLink".
2. Attempt to use it on a wikilink to open an editor with the linked file
3. Urls open correctly, but nothing happens when acting on a wikilink

### Expected behavior

One expects the same functionality as <Alt+Click>: opening a new editor with the linked file. 

### Operating System Version

Windows 

### Visual Studio Code Version

1.64.2

**Comment by aritmos** [comment]
v0.17.7

**Comment by aritmos** [comment]
I have just checked, the desired behaviour occurs in 0.17.6. The latest update is causing the bug.

**Comment by riccardoferretti** [comment]
Thanks, I identified the issue, will be sorted in the next release

**Comment by riccardoferretti** [comment]
Fixed in 0.17.8
