### ISSUE TITLE
Latex : Would it be possible to add a mathematical  formula written in Latex (for writing math or physics papers)

### ISSUE THREAD

**Issue by serge-hulne** [foambubble/foam#964]
### Is your feature request related to a problem? Please describe.

writing math or physics papers or simply a science article containing formulas

### Describe the solution you'd like

Some kind of additional plug-in

### Describe alternatives you've considered

I think Obsidian has a plugin for LaTex.

**Comment by mebu83** [comment]
Take a look at https://github.com/goessner/mdmath

**Comment by serge-hulne** [comment]
Thank you!
