### ISSUE TITLE
First class support for images and pdfs

### ISSUE THREAD

**Issue by alberto-lanfranco** [foambubble/foam#966]
### Is your feature request related to a problem? Please describe.

In my workflow, pdfs and images are first class citizens in my note vault.
In Foam, at the moment, they are not properly supported in this way.

### Describe the solution you'd like

I would like to be able to link to them with wikilinks `[[]]` , and embed them with `![[]]`

### Describe alternatives you've considered

- images
  - linking and embedding are currently supported with `[]()` and `![]()`
- pdfs
  - linking is supported with `[]()` 

problems:
- this type of linking and embedding is not tracked in graph view
- syntax highlight is broken for linking to local files in this way (see attached screenshot)

### Screenshots or Videos

<img width="326" alt="image" src="https://user-images.githubusercontent.com/57365132/161382716-918e9dfd-692c-482d-a1ca-44b63f03381b.png">

**Comment by femto-code** [comment]
+1
I already tried a PDF extension ([link](https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf)) but unfortunately it does not support linking a specific page in a PDF...

**Comment by riccardoferretti** [comment]
I agree that this needs to be implemented for v1, adding to backlog. If someone wants to help please ping me
