### ISSUE TITLE
Error occuring while bootstrapping foam in v 0.18.0

### ISSUE THREAD

**Issue by Saskia-R** [foambubble/foam#975]
### Describe the bug

After updating to version 0.18.0 and reloading, starting the foam workspace results in an error while bootstrapping. Thus, functions like calling the graph or janitor cause the error that the `command resulted in an error (object null is not iterable (cannot read property Symbol(Symbol.iterator)))`, backlinks are not shown despite the panel being present, etc.

Downgrading to version 0.17.8 restores the workspace, everything works fine.

The problem does not arise in the foam template repository.

If I manage to create a minimal example I will provide it.

The problem persists with all other extensions - even recommended ones - disabled and despite restarts.

### Steps to Reproduce the Bug or Issue

Update to version 0.18.0 in existing repository
Workspace loads, but visual studio code provides a message stating an error has occurred during bootstrapping

### Expected behavior

I expected foam to boot up without errors, providing, among others, the graph functionality, backlinks, etc, instead, no foam features are available, foam fails during bootstrapping.

### Operating System Version

Linux x64 (Solus)

### Visual Studio Code Version

1.66.1

### Additional context

[info - 16:54:46] Workspace loaded in 2743ms
[error - 16:54:46] An error occurred while bootstrapping Foam
"TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))\n\tat Function.analyzeLink (/home/user/.vscode/extensions/foam.foam-vscode-0.18.0/out/core/services/markdown-link.js:15:48)\n\tat MarkdownResourceProvider.resolveLink (/home/user/.vscode/extensions/foam.foam-vscode-0.18.0/out/core/services/markdown-provider.js:79:66)\n\tat FoamWorkspace.resolveLink (/home/user/.vscode/extensions/foam.foam-vscode-0.18.0/out/core/model/workspace.js:130:33)\n\tat FoamGraph.update (/home/user/.vscode/extensions/foam.foam-vscode-0.18.0/out/core/model/graph.js:84:50)\n\tat Function.fromWorkspace (/home/user/.vscode/extensions/foam.foam-vscode-0.18.0/out/core/model/graph.js:68:15)\n\tat Object.exports.bootstrap (/home/user/.vscode/extensions/foam.foam-vscode-0.18.0/out/core/model/foam.js:16:37)"

**Comment by Saskia-R** [comment]
Alright, I have found what caused the problem for me: using manual links instead of wikilinks and adding square brackets into the "alias": `[example [xyz]](example.md)`
example repository: https://github.com/Saskia-R/foam-v0.18.0-bootstrapping-error-example
The file causing the error is called bug.md

Removing those square brackets and reloading visual studio code restores functionality!

**Comment by chrisUsick** [comment]
I get the same error on Linux, latest VS Code. 
From my testing, the error occurs from a manual link (`[foo](bar.md)` style) when the text inside the square brackets is empty or contains square brackets, based on my and @Saskia-R's repo.
my reproduction: https://github.com/chrisUsick/foam-v0.18.0-bootstrapping-error-example

**Comment by riccardoferretti** [comment]
Thanks for the reporting the issue, this will be fixed in 0.18.1, to be released between today and tomorrow

**Comment by chrisUsick** [comment]
@riccardoferretti Hi, I'm still seeing this issue with empty direct links; e.x. `[](foo.md)` or `[](https://example.com/foo)`.
I think this line just needs to be modified: https://github.com/foambubble/foam/blob/master/packages/foam-vscode/src/core/services/markdown-link.ts#L8

**Comment by riccardoferretti** [comment]
Out of curiosity, why having empty links?
