### ISSUE TITLE
Intellij/Webstorm integration?

### ISSUE THREAD

**Issue by reidjs** [foambubble/foam#985]
### Is your feature request related to a problem? Please describe.

No, just I recently switched to intellij and would like like to get backlinking to work. 

### Describe the solution you'd like

As a user, I would like to use backlinks to jump between files in intellij/webstorm.

### Describe alternatives you've considered

Go back to VS Code, I don't think this is an option anymore, I am in love with a lot of intellij features.

**Comment by riccardoferretti** [comment]
Thanks for getting in touch! Atm we are purely focused on VS Code, but maybe there are similar extensions in the IntelliJ ecosystem? 🤞
