### ISSUE TITLE
Use different color for non-existence wiki link in the Markdown Preview panel

### ISSUE THREAD

**Issue by ansidev** [foambubble/foam#996]
### Is your feature request related to a problem? Please describe.

Wiki links in the Markdown Preview panel have same style.

### Describe the solution you'd like

As a user, I expect the non-existence wiki links will have a different style, so I can distinguish between existing wiki links and non-existence wiki links.

### Describe alternatives you've considered

N/A.

**Comment by riccardoferretti** [comment]
They use two different settings, so they should be different (unless those settings match)
```
.foam-placeholder-link {
  color: var(--vscode-editorWarning-foreground);
  cursor: default;
}

.foam-note-link,
.foam-attachment-link {
  color: var(--vscode-textLink-foreground);
}
```

<img width="260" alt="image" src="https://user-images.githubusercontent.com/457005/177761185-16cd39d6-0b40-4d65-ba53-48ed18257a43.png">

**Comment by ansidev** [comment]
For this issue, I determined that the style was overridden by another extension [Markdown Preview Github Styling](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles).
